### PR TITLE
DAOS-7153 test: datamover xattr verification

### PR DESCRIPTION
**Pull request by daltonbohning**
Test-tag: pr dm_posix_meta_entry dm_posix_types dm_posix_symlinks

- Add attr to the daos-tests dependencies
- Enabled xattr checking in dm_posix_meta_entry

Signed-off-by: Dalton Bohning <daltonx.bohning@intel.com>

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]

**Review by brianjmurrell — COMMENTED** [review]
Packaging changes LGTM.  I will reserve my review slot for somebody who knows the test code better than I do.

For future reference, rather than `Test-tag: pr other test tags`, you can use `Features: other test tags`.  That way you don't have to worry about what the "default set" (currently `pr`, but if it should change, you shouldn't need to care) of test tags are.

**Comment by daltonbohning** [comment]
> Packaging changes LGTM. I will reserve my review slot for somebody who knows the test code better than I do.
> 
> For future reference, rather than `Test-tag: pr other test tags`, you can use `Features: other test tags`. That way you don't have to worry about what the "default set" (currently `pr`, but if it should change, you shouldn't need to care) of test tags are.

@brianjmurrell Most of the datamover tests are in under `full_regression`, which (last I checked) aren't ran with `Features`. Once full_regression is more stable, and hopefully ran with `Features`, then I definitely plan to use `Features`

**Review by dsikich — APPROVED** [review]

**Review by dsikich — DISMISSED** [review]

**Review by shimizukko — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
PR looks good, waiting for 2 approvals

**Review by dsikich — APPROVED** [review]

**Comment by daltonbohning** [comment]
> PR looks good, waiting for 2 approvals

@sylviachanoiyee Yes, sorry. Had to resolve merge conflict. In the future, should I remove gatekeeper, get approvals again, and then re-add gatekeeper?

**Comment by daltonbohning** [comment]
@shimizukko Could I get your approval again, please? Had to resolve another master conflict

**Review by shimizukko — APPROVED** [review]

**Pull request merged**
