### PR TITLE
DAOS-7111 test: Cleanup python2.7 references (#5206)

### PR DESCRIPTION
**Pull request by mjean308**
Test-tag-vm: pr,-hw daily_regression,-hw
Test-tag-hw-small: pr,hw,small daily_regression,hw,small
Test-tag-hw-medium: pr,hw,medium,ib2 daily_regression,hw,medium,ib2
Test-tag-hw-large: pr,hw,large daily_regression,hw,large soak_smoke

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### CODE REVIEW

**Review by dpquigl — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by mjean308** [comment]
The two failures in this PR are due to
DAOS-7178: pool/rebuild_tests.py failure also occurring on head release/1.2 
DAOS-7175: control/dmg_pool_query.py test is failing due to recent json update to dmg method

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Sorry, merge conflict on the release/1.2 branch

**Comment by mjean308** [comment]
Failures are all related to:
DAOS-7169 - failed to start server after format

**Review by jolivier23 — APPROVED** [review]

**Comment by mjean308** [comment]
Latest test failure was due to:
DAOS-7178 - pool/rebuild_tests.py - pool query data is not matching expected results

**Pull request merged**
