### PR TITLE
DAOS-2433: Change the DD_MASK=daos_default for Functional test.

### PR DESCRIPTION
**Pull request by ravalsam**
This will help reducing the log log size as by default DD_MASK=all and we do not 
need DD_TRACE enabled by default

Signed-off-by: ravalsam <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
@jolivier23 let me update the default file as well

**Comment by brianjmurrell** [comment]
> I was thinking we should modify daos_server.yaml as well. It's just weird that the default isn't actually daos_default

I agree with this.  People shouldn't need to configure a setting to not get (overly, and unnecessarily for the usual case) huge logs.  It's worth leaving the env. variables setting in the file as this patch does as an indication of what the default is, but I think it's important to fix the default (i.e. if no env. variable setting is put into a `.conf` file) value.

**Comment by tanabarr** [comment]
is there a requirement for DD_MASK to be set to a specific value by default? if so should this be done in daos code or do you want me to add it as a server config file parameter and apply a default in the control plane? perhaps someone could raise a ticket if a change is required. thanks.

**Comment by sydneyvanda** [comment]
I'm a little confused by this - currently D_LOG_MASK is set to ERR in all of these configs it seems. DD_MASK is only used when D_LOG_MASK=DEBUG (and by default D_LOG_MASK=INFO if not currently set I believe). The reason that DD_MASK was set by default to "all" (enabling all debug streams) is because it was assumed if you had to set D_LOG_MASK=DEBUG explicitly then you could also set DD_MASK to specify exactly what debug streams you were interested in for specific tests etc. I think DD_MASK could be set to "daos_default" by default if needed.

**Comment by brianjmurrell** [comment]
Given what @sydneyvanda has said, is this change going to have any actual effect on log sizes in the Functional tests or are we barking up the wrong tree?

**Pull request merged**
