### PR TITLE
DAOS-4522 build: add --debug-build option to scons

### PR DESCRIPTION
**Pull request by bfaccini**
Add a way to request for components to be built with
debug options from scons command line.
Also use this for Mercury and ofi/libfabric who need
specific/non-default options/defines at
configure/compile time to enable debug logging.

Change-Id: Ifae2297ac2b9d3b6d9a96e7e9df8e77da6c05b92
Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>

### CODE REVIEW

**Comment by jolivier23** [comment]
If it's not a sticky option, I think what we really want here is to have a release vs debug setup where we replicate the stack (e.g. build/{release|debug}, install/{release|debug}, _build.external/{release|debug}) so we can switch developer builds merely by changing the paths.   I've been thinking about this type of thing for a while because I'd like to be able to build without optimizations for easier debugging at times.   We also might consider different path options for OS, compiler, etc to speed up builds when switching

**Comment by bfaccini** [comment]
@jolivier23 , hmmm I thought my change could be generic enough to allow for a lot of different debug vs regular build needs ... What/how do you think I should change this ?

**Comment by jolivier23** [comment]
fo

> @jolivier23 , hmmm I thought my change could be generic enough to allow for a lot of different debug vs regular build needs ... What/how do you think I should change this ?

I guess what I'm saying is we should take this a step farther.   When debug is enabled, you could

1. checking and build external components from _build.external/debug
2. Change the VariantDir for build to build/debug so it doesn't conflict with release build
3. install debug builds under install/debug

Or perhaps the other way around...anyway, the point is this if we do this, rebuilds will be fast if you switch back and forth between debug and release which is something people will do accidentally because it's not a sticky option (saved in daos.conf).

So maybe instead of --build-debug non-sticky option, we could do something like

VARIANT={default, debug, [new type of build]}

**Comment by jolivier23** [comment]
> fo
> 
> > @jolivier23 , hmmm I thought my change could be generic enough to allow for a lot of different debug vs regular build needs ... What/how do you think I should change this ?
> 
> I guess what I'm saying is we should take this a step farther. When debug is enabled, you could
> 
> 1. checking and build external components from _build.external/debug
> 2. Change the VariantDir for build to build/debug so it doesn't conflict with release build
> 3. install debug builds under install/debug
> 
> Or perhaps the other way around...anyway, the point is this if we do this, rebuilds will be fast if you switch back and forth between debug and release which is something people will do accidentally because it's not a sticky option (saved in daos.conf).
> 
> So maybe instead of --build-debug non-sticky option, we could do something like
> 
> VARIANT={default, debug, [new type of build]}

we would also maybe want a build-vars and daos.conf that is specific to each variant

**Comment by jolivier23** [comment]
The variant dir, install dir, and configs could be based on both the build variant and the compiler

e.g. release/gcc/..., release/clang/..., debug/gcc, debug/clang.   For external components, we only would do debug and release since we don't use compiler option there

I guess daos.conf would stay as is and keep the latest build sticky.   And maybe build-vars doesn't really need to change as both daos.conf and build-vars would be easily regenerated with a new scons command (with the build still being there).

**Comment by bfaccini** [comment]
I guess it needs to be integrated to the new debug build mechanism you have introduced with [PR-2576](https://github.com/daos-stack/daos/pull/2576). Sorry Jeff I am late, but I will push a new patch version in this direction soon.

**Comment by bfaccini** [comment]
According to the logs, the first failed test "Test / Functional_Hardware_Small / 1-./io/hdf5.py:Hdf5.test_hdf5;client_processes-container-hosts-pool-servers-test_repo-1c5a – Hdf5" seems to have triggered DAOS-4522 ...

**Comment by bfaccini** [comment]
After rerun of tests in 5th series, only one test has failed (rebuild 25) and it seems for a similar issue than the one reported in [DAOS-4491](https://jira.hpdd.intel.com/browse/DAOS-4491)

**Comment by jolivier23** [comment]
> After rerun of tests in 5th series, only one test has failed (rebuild 25) and it seems for a similar issue than the one reported in [DAOS-4491](https://jira.hpdd.intel.com/browse/DAOS-4491)

do you want to make it a non-draft PR?

**Comment by bfaccini** [comment]
> do you want to make it a non-draft PR?

@jolivier23 , oops right!

**Pull request merged**
