### PR TITLE
DAOS-10530 agent: Fix NUMA node rotation

### PR DESCRIPTION
**Pull request by kjacque**
The agent was assuming NUMA nodes were sorted by index rather than
ID for load balancing purposes. This broke in cases with network
interfaces on non-sequential NUMA nodes.

Feature: control

Signed-off-by: Kris Jacque <kristin.jacque@intel.com>

### CODE REVIEW

**Review by mjmac — DISMISSED** [review]

**Review by tanabarr — DISMISSED** [review]

**Review by knard-intel — APPROVED** [review]
Ok for me

**Comment by mjmac** [comment]
@kjacque: Looks like this PR conflicts with your other PR that was landed earlier.

**Comment by kjacque** [comment]
> @kjacque: Looks like this PR conflicts with your other PR that was landed earlier.

Oops. I'll merge.

**Review by tanabarr — APPROVED** [review]

**Review by mjmac — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]
OK for me

**Pull request merged**
