### PR TITLE
DAOS-6808 container: Fix cleanuping resources

### PR DESCRIPTION
**Pull request by dmiter**
- Fix reference counting for container
- Free memory in an error path
- Resolve the race in REBUILD code

### CODE REVIEW

**Review by johannlombardi — DISMISSED** [review]

**Comment by johannlombardi** [comment]
@dmiter could you please check the NLT failure?

**Comment by johannlombardi** [comment]
Repushed and added "Allow-unstable-test: true"

**Review by jolivier23 — APPROVED** [review]

**Comment by dmiter** [comment]
NTL fails with "warning in strict mode" in d_hhash_link_lookup() NULL PTR type key.
It looks a bit strange. This is an error reporting. Why I should not report it? What the rule about "warning in strict mode"?

**Comment by jolivier23** [comment]
> NTL fails with "warning in strict mode" in d_hhash_link_lookup() NULL PTR type key.
> It looks a bit strange. This is an error reporting. Why I should not report it? What the rule about "warning in strict mode"?

It's an existing warning but you changed the wording so the NLT couldn't figure that out.   Notice there is "One new warning" and "One fixed warning".  They differ in the line of code and the wording.

**Comment by ashleypittman** [comment]
> > NTL fails with "warning in strict mode" in d_hhash_link_lookup() NULL PTR type key.
> > It looks a bit strange. This is an error reporting. Why I should not report it? What the rule about "warning in strict mode"?
> 
> It's an existing warning but you changed the wording so the NLT couldn't figure that out. Notice there is "One new warning" and "One fixed warning". They differ in the line of code and the wording.

The reason this PR passed on master but not the 1.2 branch is because https://github.com/daos-stack/daos/commit/3784fcd2509eb37d0ac9131b44bf76044bbb7ca3 is present on master but not 1.2, and that silences the warning that the 1.2 build was complaining about.

**Pull request merged**
