### PR TITLE
DAOS-14590 tests: increase test_daos_ec_obj timeout (#13376)

### PR DESCRIPTION
**Pull request by liuxuezhao**
now test_daos_ec_obj with 17 "wait for 30 seconds for EC aggregation", that need 510S, so the original timeout of 600 Seconds possibly hit if the system is busy. Increase to 700 S.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by daltonbohning — APPROVED** [review]

**Review by wangdi1 — APPROVED** [review]

**Comment by liuxuezhao** [comment]
the only test failure is timeout in test_daos_md_replication test which the "querying pool info" does not get response in time, due to https://daosio.atlassian.net/browse/DAOS-13986

**Comment by mchaarawi** [comment]
since this is just 1 test fix, please consider next time to use Test-tag for the affected test only instead of running all stages and consuming CI time for all other unaffected tests.

**Comment by mchaarawi** [comment]
unfortunately we had to revert the merge because rc1 was still being tested. I will recreate the back port for this.

**Comment by liuxuezhao** [comment]
> unfortunately we had to revert the merge because rc1 was still being tested. I will recreate the back port for this.

did you create the PR already? or should i create it? @mchaarawi

**Comment by mchaarawi** [comment]
> > unfortunately we had to revert the merge because rc1 was still being tested. I will recreate the back port for this.
> 
> did you create the PR already? or should i create it? @mchaarawi

i did here: https://github.com/daos-stack/daos/pull/13474
still cannot land though because we are still testing rc1

**Pull request merged**
