### PR TITLE
DAOS-6280 build: Update minimum libfabric version

### PR DESCRIPTION
**Pull request by brianjmurrell**
To 1.11.1 for Ubuntu build.

### CODE REVIEW

**Review by jolivier23 — DISMISSED** [review]
no log update?

**Review by JohnMalmberg — DISMISSED** [review]

**Review by frostedcmos — APPROVED** [review]

**Comment by brianjmurrell** [comment]
> no log update?

Thanks for catching that.  Added.

**Review by JohnMalmberg — DISMISSED** [review]

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Lost a race on debian control log

**Comment by brianjmurrell** [comment]
> Lost a race on debian control log

So do we really need to tie up test resources confirming a changelog entry/race?  I'll of course update, but waiting for the end of 3 hardware test stages, just to see if this wins another race seems silly.

**Review by frostedcmos — APPROVED** [review]

**Comment by brianjmurrell** [comment]
Errors cannot be related.  Previous iteration of this passed fully, and the only thing the most recent commit does is add a `debian/changelog` entry.

**Review by JohnMalmberg — APPROVED** [review]

**Pull request merged**
