### PR TITLE
DAOS-12584 build: fix d_test_program() method's prototype

### PR DESCRIPTION
**Pull request by bfaccini**
Since commit 6711cc9cb15d73447972c0f000c8a0f30bb962db the Env is not passed as the first parameter of
d_test_program() method since it is its "self" now. But this behavioral change had mistakenly not been propagated to the "STACK_MMAP==1" conditional branch.

Required-githooks: true

Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by ashleypittman — APPROVED** [review]
I remember fixing this before, did I make the same mistake twice?

**Review by knard-intel — APPROVED** [review]
LGTM

**Comment by bfaccini** [comment]
Not sure why this has still not landed... may be due to the tests failures ?? which could not be related by the way as the change in this PR is only to allow builds with STACK_MMAP=1 to complete, when this not the case at all in the whole CI builds by default !!!

**Comment by phender** [comment]
> Not sure why this has still not landed... may be due to the tests failures ?? which could not be related by the way as the change in this PR is only to allow builds with STACK_MMAP=1 to complete, when this not the case at all in the whole CI builds by default !!!

@bfaccini something went wrong with the HW Large stage in build 2 and it didn't run any tests.  The only test failures in build 2 were in the HW Medium stage and they look like the known issue https://daosio.atlassian.net/browse/DAOS-11178.

**Comment by ashleypittman** [comment]
> Not sure why this has still not landed... may be due to the tests failures ??

Partly yes, only a small number of gatekeepers are able to force-land so yes, having test failures means that the PR is going to take longer to merge.

**Comment by phender** [comment]
> @bfaccini something went wrong with the HW Large stage

Looks like there was a problem with wolf-111:
```
[2023-02-09T23:23:25.714Z] ---------------
[2023-02-09T23:23:25.714Z] wolf-111
[2023-02-09T23:23:25.714Z] ---------------
[2023-02-09T23:23:25.714Z] + for i in 0 1
[2023-02-09T23:23:25.714Z] + iface=ib0
[2023-02-09T23:23:25.714Z] + '[' -e /sys/class/net/ib0 ']'
[2023-02-09T23:23:25.714Z] + ifconfig ib0
[2023-02-09T23:23:25.714Z] + grep 'inet '
[2023-02-09T23:23:25.714Z] Infiniband hardware address can be incorrect! Please read BUGS section in ifconfig(8).
[2023-02-09T23:23:25.714Z] + mail -s 'Interface ib0 found down after reboot' -r wolf-111.wolf.hpdd.intel.com@intel.com john.e.malmberg@intel.com,brian.murrell@intel.com,phillip.henderson@intel.com,ray.dennis@intel.com
[2023-02-09T23:23:25.714Z] + ifconfig ib0
[2023-02-09T23:23:25.714Z] + grep 'inet '
[2023-02-09T23:23:25.714Z] Infiniband hardware address can be incorrect! Please read BUGS section in ifconfig(8).
[2023-02-09T23:23:25.714Z] Failed to bring up interface ib0 on wolf-111.wolf.hpdd.intel.com.  Please file a CORCI ticket.
[2023-02-09T23:23:25.714Z] + echo 'Failed to bring up interface ib0 on wolf-111.wolf.hpdd.intel.com. ' 'Please file a CORCI ticket.'
[2023-02-09T23:23:25.714Z] + exit 1
```

**Pull request merged**
