### PR TITLE
DAOS-6808 rpc: Fix cleanuping resources (#4807)

### PR DESCRIPTION
**Pull request by dmiter**
- Fix reference counting for rpc
- Free memory in an error path

### CODE REVIEW

**Comment by kprantis** [comment]
Anything preventing this from moving to reviews?

**Comment by dmiter** [comment]
Python Bandit check failed only. I don't know how to fix this.

**Review by Nasf-Fan — DISMISSED** [review]

**Review by frostedcmos — CHANGES_REQUESTED** [review]
As this is a risky change due to changes to rpc ref count, it is needed to run full daily_regression on it.
Please resubmit with Test-tag: pr daily_regression

**Comment by dmiter** [comment]
This patch was just cherry-picked from master. Python Bandit and FTEST_rebuild.PoolDestroyWithIO fails not related to this patch in 1.2 branch. I have the same fails for other patch.

**Pull request merged**
