### PR TITLE
DAOS-3553 bio: SCM RDMA update over DRAM buffer

### PR DESCRIPTION
**Pull request by NiuYawei**
Implement SCM RDMA update over DRAM buffer since the AEP RDMA update
performance isn't good at this moment. This feature can be enabled
by setting env BIO_BUFFERED_SCM_RDMA=1.

Signed-off-by: Niu Yawei <yawei.niu@intel.com>
Change-Id: I2ca05627d6653b4208180a6161a4cd3e74d81001

### CODE REVIEW

**Comment by NiuYawei** [comment]
> can we reuse DAOS_IO_BYPASS=pmem_rdma?

I'm not sure, because it's not actually a debug option like dropping SCM RDMA. BTW, this patch is conflicting with the SPDK upgrade patch, I prefer to land that one first.

**Comment by mchaarawi** [comment]
@NiuYawei , how can we test with this patch?
if there is nothing, can you rebase this PR? thanks.

**Comment by NiuYawei** [comment]
> @NiuYawei , how can we test with this patch?
> if there is nothing, can you rebase this PR? thanks.

I suppose you want to do some evaluation with this patch? I can rebase it, is it urgent?

**Comment by mchaarawi** [comment]
> > @NiuYawei , how can we test with this patch?
> > if there is nothing, can you rebase this PR? thanks.
> 
> I suppose you want to do some evaluation with this patch? I can rebase it, is it urgent?

yes i understand write over pmem will be slow without this. i would like to get some testing for the MS168 demo, so yes somewhat urgent. if this is going to be a significant effort, then we can just highlight the issue in the slides when i present the performance numbers.

**Comment by NiuYawei** [comment]
Replaced by https://github.com/daos-stack/daos/pull/2124

**Pull request closed without merging**
