### PR TITLE
DAOS-7148 Test: enable osa/osa_dmg_negative_test.py

### PR DESCRIPTION
**Pull request by omar-ocampo**
Re-enabled osa/osa_dmg_negative_test.py since ticket
    has been resolved.

Test-tag-hw-medium: pr,hw,medium dmg_negative_test_extend

Signed-off-by: Omar Ocampo <omar.ocampo.coronado@intel.com>

### CODE REVIEW

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Review by shimizukko — APPROVED** [review]

**Comment by omar-ocampo** [comment]
@sylviachanoiyee , could you merge please?

**Review by shimizukko — APPROVED** [review]
Please don't force-push after asking for reviews.

**Review by sylviachanoiyee — CHANGES_REQUESTED** [review]
@omar-ocampo , i think you need to rerun with tag
osa_dmg_negative_test instead of dmg_negative_test_extend
since you made changes to validate_results, which is called by tests with and without extend to make sure both pass.

**Comment by sylviachanoiyee** [comment]
@omar-ocampo , please do not force push as mentioned by Makito after you start review.
Make sure you use merge with master instead of rebase to avoid force pushing

**Review by shimizukko — APPROVED** [review]
As Sylvia mentioned, please run test with tag "osa_dmg_negative_test". I believe now you can put it like this:
Test-tag-hw-medium: pr osa_dmg_negative_test

If you want to run only these two tests, you can do:
Test-tag: osa_dmg_negative_test

If you add the following, it will run even faster:
Quick-build: true
Skip-unit-tests: true

**Comment by omar-ocampo** [comment]
> As Sylvia mentioned, please run test with tag "osa_dmg_negative_test". I believe now you can put it like this:
> Test-tag-hw-medium: pr osa_dmg_negative_test
> 
> If you want to run only these two tests, you can do:
> Test-tag: osa_dmg_negative_test
> 
> If you add the following, it will run even faster:
> Quick-build: true
> Skip-unit-tests: true

Thanks for the tags inputs Makito, however it doesn't really matter, everything must run, per policy.

**Comment by omar-ocampo** [comment]
@sylviachanoiyee , should be ready for merge

**Comment by sylviachanoiyee** [comment]
@omar-ocampo , could you take a look at the pool create test failure in build #8? 
If it is an existing issue, please paste the JIRA ticket here for reference.
If it is a new issue, please file a ticket. If you create a ticket, please leave the ticket unassigned so it can be triaged.
In the meantime, can you retrigger just running the pool create test? Thanks!

**Comment by sylviachanoiyee** [comment]
@rpadma2 , can you review this?

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Comment by omar-ocampo** [comment]
Both osa test passed: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5446/8/testReport/FTEST_osa/OSADmgNegativeTest/

Failure un hw large unrelated to this change

@sylviachanoiyee could you help with a merge?

**Comment by sylviachanoiyee** [comment]
> @omar-ocampo , could you take a look at the pool create test failure in build #8?
> If it is an existing issue, please paste the JIRA ticket here for reference.
> If it is a new issue, please file a ticket. If you create a ticket, please leave the ticket unassigned so it can be triaged.
> In the meantime, can you retrigger just running the pool create test? Thanks!

@omar-ocampo , can you follow up on this real quic? then we can look into landing. Thanks!

**Comment by omar-ocampo** [comment]
> > @omar-ocampo , could you take a look at the pool create test failure in build #8?
> > If it is an existing issue, please paste the JIRA ticket here for reference.
> > If it is a new issue, please file a ticket. If you create a ticket, please leave the ticket unassigned so it can be triaged.
> > In the meantime, can you retrigger just running the pool create test? Thanks!
> 
> @omar-ocampo , can you follow up on this real quic? then we can look into landing. Thanks!

It looks like a test timeout, the test aims to do 100 iterations but time run out at iteration 83, there have been some issues related to the test before: https://jira.hpdd.intel.com/browse/DAOS-6174  but no specific ticket for the timeout, new ticket here:

https://jira.hpdd.intel.com/browse/DAOS-7394

**Pull request merged**
