### PR TITLE
DAOS-13757 test: Update csum_logging.yaml to pass test args.

### PR DESCRIPTION
**Pull request by rpadma2**
Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: test_csum_error_logging always_passes

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by rpadma2** [comment]
Test passed. No skipped tests exectuted as part for the csum_log tests now.

**Comment by daltonbohning** [comment]
It looks like a daily run has 39 passing (not skipped) variants
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-testing/145/testReport/FTEST_checksum/

But this PR only has 2:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14247/2/testReport/FTEST_checksum/

Shouldn't we only be excluding the ones that are skipped?

**Comment by rpadma2** [comment]
> It looks like a daily run has 39 passing (not skipped) variants https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-testing/145/testReport/FTEST_checksum/
> 
> But this PR only has 2: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14247/2/testReport/FTEST_checksum/
> 
> Shouldn't we only be excluding the ones that are skipped?

@daltonbohning  : We are trying to avoid the skipped tests shown here on the daily [https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-testing/145/testReport/FTEST_checksum/CsumErrorLog-DAOS_Checksum/ ]

The csum_log test internally executes daos_test -z presently... The changes in this PR basically runs necessary tests daos_test -x -u 18-19... 

We should run only minimal daos_test checksum tests. Two tests daos_test execution is more than enough for csum_log test case.

**Comment by daltonbohning** [comment]
> > It looks like a daily run has 39 passing (not skipped) variants https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-testing/145/testReport/FTEST_checksum/
> > But this PR only has 2: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14247/2/testReport/FTEST_checksum/
> > Shouldn't we only be excluding the ones that are skipped?
> 
> @daltonbohning : We are trying to avoid the skipped tests shown here on the daily [ https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-testing/145/testReport/FTEST_checksum/CsumErrorLog-DAOS_Checksum/ ]
> 
> The csum_log test internally executes daos_test -z (which runs every single checksum tests). The changes in this PR basically runs necessary tests daos_test -x -u 18-19...
> 
> We should run only minimal daos_test checksum tests. Two tests daos_test execution is more than enough for csum_log test case.

But what about the other 37 tests daily testing is running that DO pass? We're not going to run them at all?

**Comment by rpadma2** [comment]
> > > It looks like a daily run has 39 passing (not skipped) variants https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-testing/145/testReport/FTEST_checksum/
> > > But this PR only has 2: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14247/2/testReport/FTEST_checksum/
> > > Shouldn't we only be excluding the ones that are skipped?
> > 
> > 
> > @daltonbohning : We are trying to avoid the skipped tests shown here on the daily [ https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-testing/145/testReport/FTEST_checksum/CsumErrorLog-DAOS_Checksum/ ]
> > The csum_log test internally executes daos_test -z (which runs every single checksum tests). The changes in this PR basically runs necessary tests daos_test -x -u 18-19...
> > We should run only minimal daos_test checksum tests. Two tests daos_test execution is more than enough for csum_log test case.
> 
> But what about the other 37 tests daily testing is running that DO pass? We're not going to run them at all?

Yes. We don't need to run all 37 tests for csum_log test case. The other checksum tests are run as part of daos_test suite. The reason why we used daos_test method under csum_log is to induce checksum faults. Initially, we ran the entire checksum suite. All we need in 2 test cases within checksum suite.

**Review by daltonbohning — APPROVED** [review]

**Comment by daltonbohning** [comment]
> Yes. We don't need to run all 37 tests for csum_log test case. The other checksum tests are run as part of daos_test suite. The reason why we used daos_test method under csum_log is to induce checksum faults. Initially, we ran the entire checksum suite. All we need in 2 test cases within checksum suite.

Ah! I missed that. Thanks for the explanation :)

**Review by shimizukko — APPROVED** [review]

**Pull request merged**
