### PR TITLE
DAOS-8080 test: re-enable nvme query and health tests

### PR DESCRIPTION
**Pull request by tanabarr**
Remove test skips and address some small feedback issues.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Review by kjacque — DISMISSED** [review]
LGTM

**Comment by tanabarr** [comment]
3 failures in CI:
- https://jira.hpdd.intel.com/browse/DAOS-8229
- Test Hardware / Functional Hardware Large / 1-./io/io_consistency.py:IoConsistency.test_ioconsistency;container-dfuse-hosts-client_processes-FPP-SX-1M-pool-servers-dc7c – FTEST_io.IoConsistency
- Test Hardware / Functional Hardware Large / 1-./ior/ior_small.py:IorSmall.test_ior_small;transport_config-container-dfuse-transport_config-hdf5_vol-hosts-np_16-iorflags-pool-servers-transport_config-ec00 – FTEST_ior.IorSmall

Looks like at least the second one is on master: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/5059/ , this PR in question is only a skip test removal so has no practical chance of adding failures.

**Comment by sylviachanoiyee** [comment]
@tanabarr , looks like the nvme tests are not run in the PR.
Could you repush with the following pragma to check the status of the test?
Test-tag: pr nvme_health nvme_fault

**Comment by tanabarr** [comment]
CI run completed with requested pragma, known failures:

Test Hardware / Functional Hardware Large / 1-./io/io_consistency.py:IoConsistency.test_ioconsistency;container-dfuse-hosts-client_processes-FPP-SX-1M-pool-servers-dc7c – FTEST_io.IoConsistency
Test Hardware / Functional Hardware Large / 1-./ior/ior_small.py:IorSmall.test_ior_small;transport_config-container-dfuse-transport_config-hdf5_vol-hosts-np_16-iorflags-pool-servers-transport_config-ec00 – FTEST_ior.IorSmall
Test Hardware / Functional Hardware Large / 1-./pool/create_capacity_test.py:PoolCreateTests.test_create_pool_quantity;hosts-pool-0-timeouts-da42 – FTEST_pool.PoolCreateTests

**Review by sylviachanoiyee — APPROVED** [review]

**Review by mjmac — APPROVED** [review]

**Review by kjacque — APPROVED** [review]

**Pull request merged**
