### PR TITLE
DAOS-1828 Test: Pool query is not reflecting correct object stats after rebuild more then 1 pool.

### PR DESCRIPTION
**Pull request by ravalsam**
- Used obj_cls=16 DAOS_OC_R1S_SPEC_RANK so that data gets written with specific rank.
- Removing epoch_range from iod, as it was causing the issue for DAOS-2028.
- Some common code moved under setup(). - Code cleanup.

Test-tag: rebuildsimple

Signed-off-by: Samir <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
Need DAOS-2094 (PR-190) to pass Rebuild tests.

**Comment by brianjmurrell** [comment]
This failed all tests.  Is it really ready for review yet?

**Comment by ravalsam** [comment]
Brian,

I mention above this patch need another recent patch which got merged yesterday, I rebase it to master, so Functional tests should work now.

**Comment by ravalsam** [comment]
RebuildTest still fails so trying to get things clean with new PR, Hence closing this one...

**Pull request closed without merging**
