### PR TITLE
DAOS-15773 tests: add "--implicit-deps-unchanged" in scons install command in daos build test

### PR DESCRIPTION
**Pull request by wiliamhuang**
To speedup scons install with "--implicit-deps-unchanged" to save CI resource. It decreases this step a little over 10 minutes in local test when libpil4dfs.so is loaded.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by ashleypittman — CHANGES_REQUESTED** [review]
Looking at the ticket the aim here is to save CI time however the PR that resolved the issue with building in parallel already changed this test to build in parallel so there is no gain to be had.

Running the deps/daos and install steps separately makes the output clearer, it easier to diagnose steps when they do wrong and us to set more appropriate timeout values for the different stages.

Two calls to `daos filesystem query` are not strictly needed but the `evict` call does provide a lot of additional coverage for fduse (it will cause the whole tree to be forgotten and therefore verify the reference counts on all inodes are correct) so I'd rather keep these.  Ideally `daos filesystem evict` would take a `--wait` option which would negate the need for the second `query` but that's a different issue.

**Comment by wiliamhuang** [comment]
> Looking at the ticket the aim here is to save CI time however the PR that resolved the issue with building in parallel already changed this test to build in parallel so there is no gain to be had.
> 
> Running the deps/daos and install steps separately makes the output clearer, it easier to diagnose steps when they do wrong and us to set more appropriate timeout values for the different stages.
> 
> Two calls to `daos filesystem query` are not strictly needed but the `evict` call does provide a lot of additional coverage for fduse (it will cause the whole tree to be forgotten and therefore verify the reference counts on all inodes are correct) so I'd rather keep these. Ideally `daos filesystem evict` would take a `--wait` option which would negate the need for the second `query` but that's a different issue.

Merging scons commands together can decrease the test time from ~2 hours to 1.5 hours. If you do not think the gain is big enough, I will close this PR then. Thank you!

**Comment by ashleypittman** [comment]
> Merging scons commands together can decrease the test time from ~2 hours to 1.5 hours. If you do not think the gain is big enough, I will close this PR then. Thank you!

Can you justify that with data?  In terms of what the build is doing then it's the same, the only difference will be the new scons process doesn't have the directory tree in cache and I can't believe that takes 30 minutes.  I thought you'd said yesterday that this test took between 2-4 hours due to natural variance anyway?

**Comment by wiliamhuang** [comment]
> > Merging scons commands together can decrease the test time from ~2 hours to 1.5 hours. If you do not think the gain is big enough, I will close this PR then. Thank you!
> 
> Can you justify that with data? In terms of what the build is doing then it's the same, the only difference will be the new scons process doesn't have the directory tree in cache and I can't believe that takes 30 minutes. I thought you'd said yesterday that this test took between 2-4 hours due to natural variance anyway?

https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14280/1/testReport/FTEST_dfuse/DaosBuild/
"1 hr 33 min"

The shortest time I previously observed is ~2 hours.
It seems scons repeats some go applications compiling which takes some time.

**Comment by ashleypittman** [comment]
Ok, this completed now.  Comparing build 1 vs 2 of this PR I see:

B1: combined 90:30
B2: deps: 89:55 build: 55:58 install 2:01

There is no reference weekly test yet to compare against, but from one of my PRs I can see

deps: 62:08 build: 34:11 install 26:05 for a total of 2h 5m.

I think from that we can say there is significant variance anyway as you say, but also that the flag is helping.

scons doesn't run the configure checks when doing --build-deps=yes so adding this flag to the build step would likely not help and with this PR the install step taking 2 minutes is not a significant time so I think this PR is good as-is but further work is needed to understand the variance.

**Comment by wiliamhuang** [comment]
> Ok, this completed now. Comparing build 1 vs 2 of this PR I see:
> 
> B1: combined 90:30 B2: deps: 89:55 build: 55:58 install 2:01
> 
> There is no reference weekly test yet to compare against, but from one of my PRs I can see
> 
> deps: 62:08 build: 34:11 install 26:05 for a total of 2h 5m.
> 
> I think from that we can say there is significant variance anyway as you say, but also that the flag is helping.
> 
> scons doesn't run the configure checks when doing --build-deps=yes so adding this flag to the build step would likely not help and with this PR the install step taking 2 minutes is not a significant time so I think this PR is good as-is but further work is needed to understand the variance.

Thank you!
"install 2:01" looks good since it takes ~12 minutes in my local test without "--implicit-deps-unchanged".
Large variance could be caused by the contention of shared resources on the vm host. Do all nodes running functional tests have similar hardware?

**Comment by ashleypittman** [comment]
> Thank you! "install 2:01" looks good since it takes ~12 minutes in my local test without "--implicit-deps-unchanged".

Yes, this is definitely worth having.

> Large variance could be caused by the contention of shared resources on the vm host. Do all nodes running functional tests have similar hardware?

True, and no, I don't think I they do.  I've not observed such a big variance with the other versions of this test but I have not been actively looking for it.  The only way to tell would be to use Test-repeat and get several instances on the same set test node, or as you're doing test locally.

One other change that might be a factor is that we updated libfuse earlier today, that will enable PARALLEL_DIROPS which won't make any difference if dfuse caching were on but for this test where it isn't then it might have a positive impact on performance.

**Review by ashleypittman — APPROVED** [review]

**Review by daltonbohning — APPROVED** [review]

**Pull request merged**
