### PR TITLE
CART-822 test: Simplify whitelisting of alloc/free locations.

### PR DESCRIPTION
**Pull request by ashleypittman**
When checking for known locations where alloc/free happens across
different facilities apply a whitelist to the facility, then a
whistlist of function name.  This cuts down the amount of entires
that have to be whitelisted, and reflects areas of code where
there is a lot of overlap.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by mjmac** [comment]
Why are there so many copyright updates on files that weren't changed by this PR?

**Comment by ashleypittman** [comment]
> Why are there so many copyright updates on files that weren't changed by this PR?

I blame @jolivier23 for that one.  There was a merge-conflict and the script added the copyright change for every file in hte merge.  As this PR was started this year they're all changes that have happened this year, so they are correct but I will back them out if you think this PR is worthwhile.

**Comment by mjmac** [comment]
> I blame @jolivier23 for that one. There was a merge-conflict and the script added the copyright change for every file in hte merge. As this PR was started this year they're all changes that have happened this year, so they are correct but I will back them out if you think this PR is worthwhile.

It certainly seems worthwhile to simplify the process of whitelisting things. I wonder, though, if we can see that an allocation occurs, and we can also see that a free occurs in a different location, why do we need to bother with whitelisting at all?

**Comment by ashleypittman** [comment]
> > I blame @jolivier23 for that one. There was a merge-conflict and the script added the copyright change for every file in hte merge. As this PR was started this year they're all changes that have happened this year, so they are correct but I will back them out if you think this PR is worthwhile.
> 
> It certainly seems worthwhile to simplify the process of whitelisting things. I wonder, though, if we can see that an allocation occurs, and we can also see that a free occurs in a different location, why do we need to bother with whitelisting at all?

You mean why do we even do this check?

There are two changes to the code to use d_rank_list_realloc() in this PR, that's the kind of interface use that we're trying to check for.

**Review by jolivier23 — APPROVED** [review]

**Review by frostedcmos — APPROVED** [review]

**Pull request merged**
