### PR TITLE
DAOS-4271 rebuild: Fix two ds_pool_child leaks

### PR DESCRIPTION
**Pull request by sydneyvanda**
The extra reference to ds_pool_child in the rebuild code was causing an error
when trying to destroy SPDK blobs on NVMe SSDs (since they were remaining open).
This issue was first discovered while manually running the daos_nvme_recovery
tests (daos_test -N), but could also be reproduced by a simple rebuild test.

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

### CODE REVIEW

**Comment by johannlombardi** [comment]
Has someone looked into the failures? Are they known?

**Comment by wangdi1** [comment]
> Has someone looked into the failures? Are they known?

The failure looks strange. 

23:54:38 INFO |   Failed to stop servers:Error stopping '/usr/lib64/openmpi3/bin/orterun --enable-recovery -x PATH --hostfile /var/tmp/avocado_JWJMT1/16-._daos_test_daos_core_test.py_DaosCoreTest.test_subtest_test_v-num_clients-num_replicas-hosts-server_config-a479/hostfile74298 --map-by node --mca pml "ob1" --mca btl_openib_warn_default_gid_prefix "0" --mca oob "tcp" --mca btl "tcp,self" --np 8 /var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-2031/install/bin/daos_server -o /var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-2031/install/tmp/daos_avocado_test.yaml -b start -i'
23:54:40 ERROR| 
23:54:40 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:628
23:54:40 ERROR| Traceback (most recent call last):

I restart the test to see if these are temporary.

**Comment by johannlombardi** [comment]
Still same errors?

**Comment by wangdi1** [comment]
17:32:40  mount.nfs: access denied by server while mounting wolf-7:/data/jenkins/jenkins-1/ci_node_wolf-54_wolf-142-149/workspace/daos-stack_daos_PR-2031
17:32:40  + echo 'Cluster setup (i.e. provisioning) failed'
17:32:40  Cluster setup (i.e. provisioning) failed

Environment failure.   I checked those previous run, at least 3# "passed" besides some known failure.  probably just land it.

**Pull request merged**
