### PR TITLE
DAOS-7187 test: Add a test to restart server under NLT.

### PR DESCRIPTION
**Pull request by ashleypittman**
Test for a bug where server leaks memory when data exists
as server is started.  Previously we only did server leak
checks on a clean start.

Improve the realloc() logging and parsing to be able to
anonymize realloc log lines so they only get reported once.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
This adds a test that actually restarts the server with existing data under NLT, and that is triggering the memory leaks that have always been present so it will report regressions in NLT due to the nature of the additional checks and therefore this will need force-landing.

**Review by ryon-jensen — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by ashleypittman** [comment]
I've just remembered something about this PR, the dmg/json output has changed so it won't even run without https://github.com/daos-stack/daos/pull/5815

**Comment by dmiter** [comment]
I think we have a lot of leaks:
```
[2021-06-09T09:16:52.615Z] Memsize: Total:953,499,311 HWM:953,499,311 50766 allocations, 160 frees 50606 possible leaks
```
because of engine was killed:
```
[2021-06-09T09:16:37.481Z] running ['/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-5357@2/install/bin/dmg', '--insecure', 'system', 'erase', '--json']
[2021-06-09T09:16:38.048Z] DEBUG 09:16:37.740131 mgmt_system.go:566: Received SystemQuery RPC: sys:"daos_server"
[2021-06-09T09:16:38.048Z] DEBUG 09:16:37.754702 mgmt_system.go:785: Received SystemErase RPC
[2021-06-09T09:16:38.048Z] DEBUG 09:16:37.754848 exec.go:115: Signalling I/O Engine instance 0 (killed)
```
Need to look into the logic of "system erase" but it's just kill the engine instead of sending signal for cleanup and shutdown like for "system stop".

**Comment by ashleypittman** [comment]
> I think we have a lot of leaks:
> 
> ```
> [2021-06-09T09:16:52.615Z] Memsize: Total:953,499,311 HWM:953,499,311 50766 allocations, 160 frees 50606 possible leaks
> ```
> 
> because of engine was killed:
> 
> ```
> [2021-06-09T09:16:37.481Z] running ['/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-5357@2/install/bin/dmg', '--insecure', 'system', 'erase', '--json']
> [2021-06-09T09:16:38.048Z] DEBUG 09:16:37.740131 mgmt_system.go:566: Received SystemQuery RPC: sys:"daos_server"
> [2021-06-09T09:16:38.048Z] DEBUG 09:16:37.754702 mgmt_system.go:785: Received SystemErase RPC
> [2021-06-09T09:16:38.048Z] DEBUG 09:16:37.754848 exec.go:115: Signalling I/O Engine instance 0 (killed)
> ```
> 
> Need to look into the logic of "system erase" but it's just kill the engine instead of sending signal for cleanup and shutdown like for "system stop".

Ah, I wonder if that's the issue, I notice that a little further down it also has this from the same log-file:

[2021-06-09T09:16:58.584Z] Pid 44886, 140785 lines total, 14 trace (0.01%)
[2021-06-09T09:16:58.584Z] Memsize: Total:0 HWM:1,221,169,567 67962 allocations, 67962 frees 0 possible leaks
[2021-06-09T09:16:58.584Z] Parsed 195321 lines of logs

@mjmac would need to comment, but perhaps this is because the server is killing, then restarting the engine in the case of existing data, and the "leaks" we're seeing here are from the initial process that was killed rather than the later one that wasn't?

It's going to be a bit of a pain to work around this in NLT, we could ignore the first pid in the server log-file if there is more than one (or more accurately only process the last one) but that's a bit of a hack.

**Comment by mjmac** [comment]
`dmg system erase` does forcefully kill the engine, yes. It's not intended to be graceful; it's the "big hammer" to force the system back into a known clean state. If that is causing a problem, then you should stop the system first before erasing.

**Comment by ashleypittman** [comment]
> `dmg system erase` does forcefully kill the engine, yes. It's not intended to be graceful; it's the "big hammer" to force the system back into a known clean state. If that is causing a problem, then you should stop the system first before erasing.

Yes, that'll be it.

Do you remember the reason we didn't do a system stop last time?  I've a feeling it wouldn't work for some reason.

**Review by dmiter — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
