### PR TITLE
DAOS-8049 Test: Fix nvme_fragmentation and nvme_fault test.

### PR DESCRIPTION
**Pull request by ravalsam**
- Adding container RF property to nvme_fault.py tests.
- Updated container UUID in to python dictionary after IOR writes
  and create the container

Test-tag-hw-medium: pr,hw,medium nvme_fragmentation nvme_fault

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
1. nvme_fragmentation test passed.
2. nvme_+health test passed but skipped for now because the health command does not work.

CI result can be found from https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6243/1/artifact/Functional%20Hardware%20Medium/nvme/

**Review by shimizukko — DISMISSED** [review]

**Comment by shimizukko** [comment]
Can you move `import queue` to after `from itertools import product`, so that it matches my PR-5972? Thanks.

**Comment by ravalsam** [comment]
> Can you move `import queue` to after `from itertools import product`, so that it matches my PR-5972? Thanks.

Is there any importing sequence issue or just to have syncup?

**Comment by shimizukko** [comment]
Just sync up to avoid a merge conflict.

**Review by shimizukko — DISMISSED** [review]
Thanks

**Comment by rpadma2** [comment]
Does any of the jenkins run  have the nvme_fragmentation, nvme_fault test run? I don't see them. Unless, I missed it...

**Comment by rpadma2** [comment]
Oh, found it... On the 1st run...

**Comment by rpadma2** [comment]
Are you planning to remove oclass from IOR run for nvme_fault test?
If so, it is not happening: 
/usr/lib64/mpich/bin/mpirun -hostfile /var/tmp/avocado_e8tyz_jb/avocado_job_l555xek0/1-._nvme_nvme_fault.py_NvmeFault.test_nvme_fault_transport_config-container-transport_config-single-single-single-10_Percent-hosts-client_processes-iorflags-RP_2G1-RP_2G1-16M-pool-0-1-transport_config-91aa/hostfile50002 -np 16 ior -a DFS -b 8992587776 -w -F -r -R -k -G 1 -i 1 -o /testfile -t 16777216 --dfs.chunk_size 1048576 --dfs.cont ECADF6D1-2A6C-4C96-A2E2-25D25F47C34D --dfs.dir_oclass RP_2G1 --dfs.group daos_server --dfs.oclass RP_2G1 --dfs.pool 7C759ACB-45C9-4ED8-8C99-79ED66C58214'

**Comment by rpadma2** [comment]
Ok. I believe if we set rf to the container a object class is selected by DAOS based on server/client confgiuration...Then we are trying set oclass which is compatible with the object class set for the container... It should work...

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Comment by ravalsam** [comment]
> Ok. I believe if we set rf to the container a object class is selected by DAOS based on server/client confgiuration...Then we are trying set oclass which is compatible with the object class set for the container... It should work...

Yes I changed it to create the container with rf:1

**Comment by sylviachanoiyee** [comment]
> 1. nvme_fragmentation test passed.
> 2. nvme_health test passed but skipped for now because the health command does not work.
> 
> CI result can be found from https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6243/1/artifact/Functional%20Hardware%20Medium/nvme/

Looks like nvme_fault failed. Is that a known issue? Do we have a ticket?
Could you update DAOS-8080 with instructions to re-enable test at the top of the ticket description?

**Review by shimizukko — APPROVED** [review]

**Review by sylviachanoiyee — APPROVED** [review]

**Pull request merged**
