### PR TITLE
DAOS-12611 build: Add protobufc to the test rpm depenency.

### PR DESCRIPTION
**Pull request by ashleypittman**
This is needed to run some of the tests.

Required-githooks: true
Test-tag: DaosBuild

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
@brianjmurrell @Michael-Hennecke can I request some help with this please?

This PR seems to work for el8 however fails for SLES so I'm wondering if that is related to https://daosio.atlassian.net/browse/DAOS-12585

**Comment by brianjmurrell** [comment]
> @brianjmurrell @Michael-Hennecke can I request some help with this please?
> 
> This PR seems to work for el8 however fails for SLES so I'm wondering if that is related to https://daosio.atlassian.net/browse/DAOS-12585

Could very well.  The PR for that ticket is just waiting for landing now.  In the meanwhile you could rebase on it, or merge it into this one to verify.  I would also strongly suggest that for this kind of change, you want to run all VM testing stages including the Leap 15.4 stage (i.e. `Skip-func-test-leap15: false`).  It's actually been a TODO in the back of my mind to have PRs run all VM testing stages if `daos.spec` is modified.

**Comment by ashleypittman** [comment]
That PR has landed now and I've updated this to include it and re-pushed with the suggested flags, thank you.

**Comment by ashleypittman** [comment]
I've verified the fix in working in that the test is no longer building protobufc and have now merged with master and re-pushed to include rpm information.

**Review by brianjmurrell — APPROVED** [review]

**Review by JohnMalmberg — APPROVED** [review]

**Pull request merged**
