### PR TITLE
DAOS-3900 tests Remove daosbench from daos stack repo

### PR DESCRIPTION
**Pull request by vvenkates27**
DAOSBENCH is legacy benchmark utility which is outdated, removing it
from the repository. daos_perf needs to be used for all other purpose.

Signed-off-by: Vishwanath Venkatesan <vishwanath.venkatesan@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
@vvenkates27 Do you want to kick this off from the Build stage again due to the Internet repo timeout in the RPM build?

**Comment by vvenkates27** [comment]
Seems still h/w tests are failing due to some error-signal.

**Comment by brianjmurrell** [comment]
> Seems still h/w tests are failing due to some error-signal.

The RPMs from the previous run that you tried to restart from are gone.  I think they expire after a period of time.  You are going to have to restart from the Build stage to have them rebuilt.

**Comment by johannlombardi** [comment]
Could you please look into the RPM build failure on CentOS? Is it due to this patch?

**Comment by brianjmurrell** [comment]
> Could you please look into the RPM build failure on CentOS? Is it due to this patch?

In the most [recent run](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-1806/16/pipeline/), the CentOS 7 RPM build succeeded, but the test run was aborted by @vvenkates27 before it completed.

**Pull request merged**
