### PR TITLE
DAOS-13510 chk: proper message for inconsistency report

### PR DESCRIPTION
**Pull request by Nasf-Fan**
To avoid confusing under dryrun mode.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by Nasf-Fan** [comment]
The patch only changes the log message, not related with the CI test failures.

**Comment by Nasf-Fan** [comment]
Ping @mjmac @liw , thanks!

**Review by liw — APPROVED** [review]
[Not requesting changes] Generally speaking, we should have two kinds of messages:

1. "Detected fault X."
2. "Repaired fault X."

Then in a dry run, we could print the first kind of messages but not the second kind of messages---conveying a clearer meaning to users. (Or we could print both kinds of messages but change "repaired" to "skipped repairing.")

**Comment by Nasf-Fan** [comment]
> [Not requesting changes] Generally speaking, we should have two kinds of messages:
> 
> 1. "Detected fault X."
> 2. "Repaired fault X."
> 
> Then in a dry run, we could print the first kind of messages but not the second kind of messages---conveying a clearer meaning to users. (Or we could print both kinds of messages but change "repaired" to "skipped repairing.")

Here is example of our current inconsistency report:

Inconsistency Reports:
  ID:         0x10e25057f98c0002
  Class:      POOL_NONEXIST_ON_ENGINE
  Message:    Check leader detects dangling pool.
  Pool:       mypool
  Resolution: IGNORE: Ignore the pool finding

The "Message" section describes what the inconsistency is; the "Resolution" section describes how the inconsistency is handled. You expect to change the "Resolution" instead of the "Message". That is possible. But "ignore" is already used for other purpose. We need to define new resolution type and transfer it from engine to MS, then MS can covert such new type to some suitable human readable string. That will change the proto between engine and MS. That is why I made current simple PR.

**Review by mjmac — COMMENTED** [review]
Hmm. From a UX standpoint, it seems a little awkward to me that we would expose a new verb (dryrun-detect) to the user and make all of these changes to user-visible strings. In other tools that I have used, the convention seems to be that dryrun mode is announced via a single line printed before the rest of the output.

If the concern is that we could have mixed reports in dryrun-on/dryrun-off mode, then perhaps the best way to handle this is to add a Dryrun bool to the report message, then we can properly handle this out in the display logic.

**Comment by Nasf-Fan** [comment]
> Hmm. From a UX standpoint, it seems a little awkward to me that we would expose a new verb (dryrun-detect) to the user and make all of these changes to user-visible strings. In other tools that I have used, the convention seems to be that dryrun mode is announced via a single line printed before the rest of the output.

I am fine for this way if you can improve the "check query" output with the expected dryrun information to avoid confusing. Thanks!

**Comment by Nasf-Fan** [comment]
The issue will be handled via control plane logic (by @mjmac ), do not need this patch any longer.

**Pull request closed without merging**
