### PR TITLE
DAOS-7312 Test: Functional testing for EC auto object class selection

### PR DESCRIPTION
**Pull request by omar-ocampo**
Multiple container delete uses EC object

Quick-build: true
Skip-unit-tests: true
Skip-nlt: true
Skip-unit-test: true
Skip-func-test-vm: true
Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true
Test-tag-hw-large: pr multicontainerdelete

Signed-off-by: Omar Ocampo <omar.ocampo.coronado@intel.com>

### CODE REVIEW

**Comment by omar-ocampo** [comment]
@saurabhtandan @ravalsam , could you help to understand why the test failed? 
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6675/1/artifact/Functional%20Hardware%20Large/container/multiple_container_delete.py/

I run in my dev machine and it worked fine but Im not able to find any reason in the log.

**Comment by ravalsam** [comment]
> @saurabhtandan @ravalsam , could you help to understand why the test failed?
> https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6675/1/artifact/Functional%20Hardware%20Large/container/multiple_container_delete.py/
> 
> I run in my dev machine and it worked fine but Im not able to find any reason in the log.

It looks like a bug to me which might be happening intermediate. Try this test again in CI and see if it fails consistently. 
`
2021-09-11 02:01:17,943 process          L0458 DEBUG| [stdout] Commencing write performance test: Sat Sep 11 02:01:17 2021
2021-09-11 02:04:47,956 process          L0458 DEBUG| [stderr] dfs_write() failed (1)
2021-09-11 02:04:47,956 process          L0458 DEBUG| [stdout] ERROR: cannot write to file, (ior.c:1643)
2021-09-11 02:04:47,956 process          L0714 INFO | Command '/usr/lib64/mpich/bin/mpirun -hostfile /var/tmp/a
`

**Comment by omar-ocampo** [comment]
> > @saurabhtandan @ravalsam , could you help to understand why the test failed?
> > https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6675/1/artifact/Functional%20Hardware%20Large/container/multiple_container_delete.py/
> > I run in my dev machine and it worked fine but Im not able to find any reason in the log.
> 
> It looks like a bug to me which might be happening intermediate. Try this test again in CI and see if it fails consistently.
> `2021-09-11 02:01:17,943 process L0458 DEBUG| [stdout] Commencing write performance test: Sat Sep 11 02:01:17 2021 2021-09-11 02:04:47,956 process L0458 DEBUG| [stderr] dfs_write() failed (1) 2021-09-11 02:04:47,956 process L0458 DEBUG| [stdout] ERROR: cannot write to file, (ior.c:1643) 2021-09-11 02:04:47,956 process L0714 INFO | Command '/usr/lib64/mpich/bin/mpirun -hostfile /var/tmp/a`

Thanks, re-running now.

**Comment by ravalsam** [comment]
This looks like a bug and it's able to reproduce, where after some time same IOR failed with 'dfs_write() failed (1)"

**Comment by omar-ocampo** [comment]
> This looks like a bug and it's able to reproduce, where after some time same IOR failed with 'dfs_write() failed (1)"

Sorry, just got time from the other project to work on Daos. Yes, Samir you are right, what about skipping this test with the appropriate jira bug opened?

**Comment by ravalsam** [comment]
> > This looks like a bug and it's able to reproduce, where after some time same IOR failed with 'dfs_write() failed (1)"
> 
> Sorry, just got time from the other project to work on Daos. Yes, Samir you are right, what about skipping this test with the appropriate jira bug opened?

Yes, sound good

**Comment by omar-ocampo** [comment]
> > > This looks like a bug and it's able to reproduce, where after some time same IOR failed with 'dfs_write() failed (1)"
> > 
> > 
> > Sorry, just got time from the other project to work on Daos. Yes, Samir you are right, what about skipping this test with the appropriate jira bug opened?
> 
> Yes, sound good

Done, this should be able to be merged

**Comment by omar-ocampo** [comment]
@ravalsam @saurabhtandan, could you help with a review? Tomorrow is my last day in daos and after that I wont be able to review this.

**Review by ravalsam — APPROVED** [review]

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Comment by omar-ocampo** [comment]
Thank you guys
@sylviachanoiyee could we merge this?

**Comment by sylviachanoiyee** [comment]
@omar-ocampo , where can I find the test result? I see in build #5, no tests were run.

**Pull request closed without merging**
