### PR TITLE
DAOS-7834 test: Add telemetry data to soak

### PR DESCRIPTION
**Pull request by mjean308**
Test-tag-hw-large: pr soak_smoke

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]

**Review by shimizukko — DISMISSED** [review]

**Review by shimizukko — APPROVED** [review]

**Review by saurabhtandan — DISMISSED** [review]
LGTM

**Comment by sylviachanoiyee** [comment]
Checkpatch failed and soak_smoke is somehow skipped. Can you check?

**Comment by sylviachanoiyee** [comment]
Can you check why soak smoke is skipped in build #4?

**Review by shimizukko — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
Looks like soak_smoke is cancelled for DAOS-7436 but the ticket was resolved since July 18.
Can you re-enable the test if the issue is resolved?

**Comment by mjean308** [comment]
daos_racer will be re-enabled in DAOS-8434

**Review by sylviachanoiyee — APPROVED** [review]

**Pull request merged**
