### PR TITLE
DAOS-6514 test: daos_test -z timeout

### PR DESCRIPTION
**Pull request by mjean308**
Adding cancel for ticket to skip daos_test -z

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### CODE REVIEW

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Review by dinghwah — APPROVED** [review]
LGTM

**Review by shimizukko — APPROVED** [review]
LGTM

**Comment by mjean308** [comment]
This PR is a duplicate of DAOS-6507

**Pull request closed without merging**
