### PR TITLE
DAOS-14539 client: fix pil4dfs strncmp compile in some envs

### PR DESCRIPTION
**Pull request by daltonbohning**
Features: pil4dfs

Workaround an issue with some compilers not playing nicely with the strncmp and STR_AND_SIZE macros in the case where strncmp is also defined as a macro.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by wiliamhuang — APPROVED** [review]

**Review by mchaarawi — APPROVED** [review]

**Review by ashleypittman — COMMENTED** [review]
This is technical debt neither the code change nor the ticket include and justification for the change.  I suspect this is to support older, no-longer-supported,  versions of compliers but this will also affect newer supported compilers/libc and could well force libc into a slower, non-optimised code path for all configurations, not just the non-supported ones.

IMO this would be better maintained on a branch, or at least have compiler/libc guards on it for the specific versions that require this change.

Is the ticket number here correct?

**Comment by wiliamhuang** [comment]
@ashleypittman 

# define strncmp(s1, s2, n)                                                   \
  (__extension__ (__builtin_constant_p (n)                                    \
&& ((__builtin_constant_p (s1)                              \
&& strlen (s1) < ((size_t) (n)))                       \
                      || (__builtin_constant_p (s2)                           \
&& strlen (s2) < ((size_t) (n))))                   \
                  ? strcmp (s1, s2) : strncmp (s1, s2, n)))
 
strncmp is defined as a macro in /usr/include/bits/string2.h on Frontera. We do not have string2.h file on the OS we tested.

**Comment by wiliamhuang** [comment]
> @wiliamhuang I talked with @ashleypittman and it seems disabling complier checks is probably a bad idea. Other than removing those `STR_AND_SIZE` macros, is there something else we could do here? E.g. maybe we could move those macros to an earlier header or something? (I'm not an expert)

The problem is that there is no way to control the order of macro expansion for strncmp and STR_AND_SIZE. If "STR_AND_SIZE" can be expanded first, there should be no issue.
A possible workaround here, we can try memcmp() instead of strncmp() in the places using strncmp and STR_AND_SIZE.

**Comment by wiliamhuang** [comment]
> STR_AND_SIZE

@daltonbohning You can search STR_AND_SIZE and STR_AND_SIZE_M1, then replace strncmp with memcmp.

**Review by wiliamhuang — APPROVED** [review]

**Comment by daltonbohning** [comment]
clang-format is telling me to make a change that would cause the line to exceed 100 chars
https://github.com/daos-stack/daos/actions/runs/9115650223/job/25062463031
```
diff --git a/src/client/dfuse/pil4dfs/int_dfs.c b/src/client/dfuse/pil4dfs/int_dfs.c
index c3956c71a..3dc78b96a 100644
--- a/src/client/dfuse/pil4dfs/int_dfs.c
+++ b/src/client/dfuse/pil4dfs/int_dfs.c
@@ -4137,8 +4137,8 @@ pre_envp(char *const envp[], char ***new_envp)
 				if (!env_set[i])
 					continue;
 				if (!env_found[i]) {
-					if (memcmp(envp[num_entry], STR_AND_SIZE_M1(env_list[i]))
-					    == 0) {
+					if (memcmp(envp[num_entry], STR_AND_SIZE_M1(env_list[i])) ==
+					    0) {
 						env_found[i] = true;
 						num_entry_found++;
 					}
Changes advised
```

**Comment by wiliamhuang** [comment]
@daltonbohning Somehow daos build with pil4dfs failed with timeout. I am going to restart your build.

**Comment by wiliamhuang** [comment]
@daltonbohning Timeout was observed in daos build with pil4dfs again. I will try this test locally today to see whether I can reproduce the issue.

**Comment by daltonbohning** [comment]
> @daltonbohning Timeout was observed in daos build with pil4dfs again. I will try this test locally today to see whether I can reproduce the issue.

Thank you!

**Comment by daltonbohning** [comment]
FWIW, the daos_build test clones and builds master, so it's not actually building THIS PR. So I probably need to run it with this PR to be safe before landing

**Comment by wiliamhuang** [comment]
@daltonbohning Please merge master in your PR. We got dead lock issues in daos build previously. It was fixed in https://github.com/daos-stack/daos/pull/14287 two weeks ago.

**Comment by wiliamhuang** [comment]
> @daltonbohning Please merge master in your PR. We got dead lock issues in daos build previously. It was fixed in #14287 two weeks ago.

Never mind. You already did it yesterday. Sorry for the noise.

**Comment by wiliamhuang** [comment]
I could not reproduce the timeout issue on boro node. I will try reproducing the issue with repeated test in CI and debug there later.

**Comment by wiliamhuang** [comment]
@daltonbohning It looks like the hang in cmake in daos build is not fully resolved yet. I am working on it. I will keep you updated. Thank you!

**Comment by wiliamhuang** [comment]
@daltonbohning The hang in daos build should be fixed by PR, https://github.com/daos-stack/daos/pull/14408
You can include this patch and rerun your PR. Thank you!

**Comment by daltonbohning** [comment]
> @daltonbohning The hang in daos build should be fixed by PR, #14408 You can include this patch and rerun your PR. Thank you!

Thanks!

**Review by wiliamhuang — APPROVED** [review]

**Review by mchaarawi — APPROVED** [review]

**Pull request merged**
