### PR TITLE
DAOS-5737 tests: Removing oclass param from create_cont()

### PR DESCRIPTION
**Pull request by saurabhtandan**
Removing oclass param from create_cont() inside
ftest/util/ior_test_base.py as it is breaking some
of the weekly tests.
The change was earlier added to the code for datamover
tests which now use an overriden version of this method.

Hence 'oclass' param is not needed anymore andn ot used
anywhere else.

Test-tag-hw-small: pr,hw,small dfusespacecheck ioaggregation dfusesparsefile
Test-tag-hw-large: pr,hw,large multicontainerdelete

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]
LGTM

**Comment by saurabhtandan** [comment]
Failing issues are unrelated to the changes made in this pr.
LLNL/romio: DAOS-6905
PoolCreateTest: DAOS-6784
ErasureCodeIor: DAOS-6788

**Review by dinghwah — APPROVED** [review]
LGTM.

**Comment by sylviachanoiyee** [comment]
The pool create tests are failing for DAOS-6932, not DAOS-6784

**Pull request merged**
