### PR TITLE
DAOS-6344 build: create daos_daemons secondary group

### PR DESCRIPTION
**Pull request by Michael-Hennecke**
Create daos_daemons secondary group for daos_server and daos_agent,
to enable both daemons to write their logfiles into the same
non-world-writeable logfile directory (being writeable by the
daos_daemons group will be sufficient).

Signed-off-by: Michael Hennecke <michael.hennecke@intel.com>

### CODE REVIEW

**Review by brianjmurrell — COMMENTED** [review]
Is there an additional patch/PR somewhere that arranges for the creation of the directory to put the logs into as [DAOS-6344](https://daosio.atlassian.net/browse/DAOS-6344) describes?

**Comment by Michael-Hennecke** [comment]
There is no PR yet to actually move the logfiles. This can be added after the prerequisite Unix group setup is in place.

**Review by johannlombardi — COMMENTED** [review]
Shouldn't we update debian/daos-server.preinst too?

**Review by dpquigl — COMMENTED** [review]
I don't see any changes to the spec file to use these secondary groups. Isn't the point to make things like /etc/daos owned by these secondary groups?

**Comment by Michael-Hennecke** [comment]
@dpquigl yes that is correct: this PR is only creating the secondary group but not actively using it anywhere yet. 
i would like to land this first while keeping the default locations for the logfiles. Then during a deployment, the daemon YML files can be adjusted to change the logfile locations, using the new group for directory permissions. 
we may or may not decide later on to make that the default, but for now all i want to do is create the possibility to do this (but keep the default locations as is).

**Review by dpquigl — APPROVED** [review]

**Pull request merged**
