### PR TITLE
DAOS-5361 test: Test_tag parsing improvement

### PR DESCRIPTION
**Pull request by saurabhtandan**
Test_Tag argument passing affected by switching
to RPM building. Hence modifying ci/functional/test_main.sh

Quick-build: true
Test-tag-hw-small: daos_admin
Test-tag-hw-medium: pr,hw,medium,ib2 crashior
Test-tag-hw-large: pr,hw,large iorinterceptmix iorinterceptmulticlient nvme_io_verification

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

### CODE REVIEW

**Comment by saurabhtandan** [comment]
> Change looks good but you need to re-run either without `Quick-build: true` or with `Skip_runtest: true`. The latter should be acceptable as this only affects functional test running.

Added `Skip_runtest: true` to the commit message.

**Comment by brianjmurrell** [comment]
> > Change looks good but you need to re-run either without `Quick-build: true` or with `Skip_runtest: true`. The latter should be acceptable as this only affects functional test running.
> 
> Added `Skip_runtest: true` to the commit message.

My apologies.  It's `Skip-run_test: true`.

**Comment by saurabhtandan** [comment]
> > > Change looks good but you need to re-run either without `Quick-build: true` or with `Skip_runtest: true`. The latter should be acceptable as this only affects functional test running.
> > 
> > 
> > Added `Skip_runtest: true` to the commit message.
> 
> My apologies. It's `Skip-run_test: true`.

Np. Updated with `Skip-run_test: true`

**Comment by saurabhtandan** [comment]
Closing this as the change intended for this PR was already merged as part of https://github.com/daos-stack/daos/pull/2921/

**Pull request closed without merging**
