### PR TITLE
DAOS-6585 common: bump cpf_ver for interoperability issues

### PR DESCRIPTION
**Pull request by Nasf-Fan**
Currently, we do not support old client (1.0) to talk with new
server (1.2), and vice versa. Bump the cpf_ver for RPC related
modules.

Signed-off-by: Fan Yong <fan.yong@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
This is the right approach, but is not comprehensive enough, you need to update at least these two from src/cart/crt_rpc.h as well.

#define CRT_PROTO_INTERNAL_VERSION 2
#define CRT_PROTO_FI_VERSION 1

**Review by jolivier23 — APPROVED** [review]

**Comment by Nasf-Fan** [comment]
> This is the right approach, but is not comprehensive enough, you need to update at least these two from src/cart/crt_rpc.h as well.
> 
> #define CRT_PROTO_INTERNAL_VERSION 2
> #define CRT_PROTO_FI_VERSION 1

Sorry, I do not know why need to bump cart internal version. As my understand, these two versions are used inside CaRT, not across nodes. I may miss something, would you please to explain some in detail? Thanks!

**Comment by ashleypittman** [comment]
> > This is the right approach, but is not comprehensive enough, you need to update at least these two from src/cart/crt_rpc.h as well.
> > #define CRT_PROTO_INTERNAL_VERSION 2
> > #define CRT_PROTO_FI_VERSION 1
> 
> @ashleypittman
> Sorry, I do not know why need to bump cart internal version. As my understand, these two versions are used inside CaRT, not across nodes. I may miss something, would you please to explain some in detail? Thanks!

There's more detail in https://jira.hpdd.intel.com/browse/DAOS-6620 but essentially both these protocols contain client->server RPCs, as well as server to server.

The IV rpcs are in the internal protocol, but should be in their own private, server-only protocol.  The FI protocol is used for configuring the server on the fly, from a client.

**Comment by Nasf-Fan** [comment]
> > > This is the right approach, but is not comprehensive enough, you need to update at least these two from src/cart/crt_rpc.h as well.
> > > #define CRT_PROTO_INTERNAL_VERSION 2
> > > #define CRT_PROTO_FI_VERSION 1
> > 
> > 
> > @ashleypittman
> > Sorry, I do not know why need to bump cart internal version. As my understand, these two versions are used inside CaRT, not across nodes. I may miss something, would you please to explain some in detail? Thanks!
> 
> There's more detail in https://jira.hpdd.intel.com/browse/DAOS-6620 but essentially both these protocols contain client->server RPCs, as well as server to server.
> 
> The IV rpcs are in the internal protocol, but should be in their own private, server-only protocol. The FI protocol is used for configuring the server on the fly, from a client.

Thanks! Refreshed the patch as suggested.

**Review by jolivier23 — APPROVED** [review]

**Comment by Nasf-Fan** [comment]
daos_test -m failed for DAOS-6539.

**Comment by Nasf-Fan** [comment]
@ashleypittman @johannlombardi , would you please to help review the patch? Thanks!

**Review by johannlombardi — APPROVED** [review]

**Review by ashleypittman — APPROVED** [review]

**Pull request merged**
