### PR TITLE
CART-89 log: Add D_LOG_LIMIT_MB envariable

### PR DESCRIPTION
**Pull request by frostedcmos**
- Add "D_LOG_LIMIT_MB" envariable to limit log size in mbs.
- Limit log size to 100mb in daos server config script

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

### CODE REVIEW

**Comment by frostedcmos** [comment]
> So does this limit the log to the first 100MB or last 100MB? It looks like the first 100MB.
> 
> If so, how is this going to affect debugging efforts on tests that fail? I'm all for getting CI going again, but is it worth getting going again if the failures that come out of it are undebuggable? I guess maybe it is as we can start to land things that don't have test failures.

It limits to first X mb per server log instance, in this case X=100, but i dont have any strong feelings on increasing it to say 1-2gb. I would imagine if someone hits the scenario where log limit causes them being unable to debug due to missing info then they could rerun their pr with particular test setting this envariable to 0 to disable it, or setting it to higher value.

**Comment by ashleypittman** [comment]
I am against this as I feel it's the wrong solution to the problem.  High quality logs and debugging from DAOS is important, and part of that is making sure that the right amount of logs, at the right level of priority.  This PR can only decrease the quality of the logs, and is paper overing the symptom of log size that is caused by inappropriate log settings and mask usage.

**Comment by brianjmurrell** [comment]
> It limits to first X mb per server log instance, in this case X=100, but i dont have any strong feelings on increasing it to say 1-2gb. I would imagine if someone hits the scenario where log limit causes them being unable to debug due to missing info then they could rerun their pr with particular test setting this envariable to 0 to disable it, or setting it to higher value.

Couldn't the same approach be done with the logging mask, defaulting everything to INFO or WARN even and then if a certain test needs more it can be increased individually?

Not saying this log limit isn't a good stop-gap.  Just spit-balling more permanent solutions.

**Comment by ashleypittman** [comment]
> > It limits to first X mb per server log instance, in this case X=100, but i dont have any strong feelings on increasing it to say 1-2gb. I would imagine if someone hits the scenario where log limit causes them being unable to debug due to missing info then they could rerun their pr with particular test setting this envariable to 0 to disable it, or setting it to higher value.
> 
> Couldn't the same approach be done with the logging mask, defaulting everything to INFO or WARN even and then if a certain test needs more it can be increased individually?
> 
> Not saying this log limit isn't a good stop-gap. Just spit-balling more permanent solutions.

Having the specific tests be able to set the appropriate logging level for the test is of course a good thing, and this already exists, some tests do this today.

**Comment by brianjmurrell** [comment]
> I am against this as I feel it's the wrong solution to the problem. High quality logs and debugging from DAOS is important, and part of that is making sure that the right amount of logs, at the right level of priority. This PR can only decrease the quality of the logs, and is paper overing the symptom of log size that is caused by inappropriate log settings and mask usage.

I don't disagree with your general sentiment and I agree with your position on more work being needed to increase the quality of the logs.

But we also have an emergency situation right now where nothing can land because everything is failing the entire Hardware Large testing stage and landing things in that state risks adding more failures to master.

If we do land this, yes, the quality of the logs of tests that do fail is potentially impacted (if they are > 1G) but on the other hand, we unblock master for any PRs that don't fail.

**Comment by ashleypittman** [comment]
> But we also have an emergency situation right now where nothing can land because everything is failing the entire Hardware Large testing stage and landing things in that state risks adding more failures to master.

Agreed, and I'm surprised this didn't get resolved whilst I was out yesterday.

What are your thoughts on https://github.com/daos-stack/daos/pull/3143

**Comment by phender** [comment]
> But we also have an emergency situation right now where nothing can land because everything is failing the entire Hardware Large testing stage and landing things in that state risks adding more failures to master.

Should we not just address the extra logging caused by these tests?

> Having the specific tests be able to set the appropriate logging level for the test is of course a good thing, and this already exists, some tests do this today.

I see a total of 7 tests with the `pr,hw,large` avocado tags (Functional HW Large tests):

- 1 test in `aggreagtion/aggregation_basic.py` - uses `log_mask: INFO` as set in its yaml file
- 1 test in `io/ior_small.py`  - uses the default `log_mask` setting (`DEBUG,RPC=ERR`)
- 1 test in `io/macsio_test.py` - currently skipped
- 1 test in `io/mdtest.py` - uses the default `log_mask` setting (`DEBUG,RPC=ERR`)
- 1 test in `io/nvme_object.py` - uses the default `log_mask` setting (`DEBUG,RPC=ERR`)
- 2 tests in `osa/osa_offline_reintegration.py` - uses the default `log_mask` setting (`DEBUG,RPC=ERR`)

**Comment by phender** [comment]
Looking at https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/2548 as an example, here are the sizes of the server logs produced:

- `aggreagtion/aggregation_basic.py` (uses `log_mask: INFO`)
```
aggregation_basic.py-1_daos_server.log-wolf-142 | Jul 19, 2020 2:29:44 AM | 24.85 KB | view
aggregation_basic.py-1_daos_server.log-wolf-143 | Jul 19, 2020 2:29:44 AM | 13.02 KB | view
aggregation_basic.py-2_daos_server.log-wolf-142 | Jul 19, 2020 2:29:45 AM | 24.73 KB | view
aggregation_basic.py-2_daos_server.log-wolf-143 | Jul 19, 2020 2:29:45 AM | 13.02 KB | view
```
- `io/ior_small.py` (uses `log_mask: DEBUG,RPC=ERR`)
```
ior_small.py-1_daos_server.log-wolf-142.bz2 | Jul 19, 2020 1:35:54 AM | 87.82 MB | view
ior_small.py-1_daos_server.log-wolf-143.bz2 | Jul 19, 2020 1:35:54 AM | 81.36 MB | view
ior_small.py-1_daos_server.log-wolf-144.bz2 | Jul 19, 2020 1:35:54 AM | 116.15 MB | view
ior_small.py-1_daos_server.log-wolf-145.bz2 | Jul 19, 2020 1:35:00 AM | 79.03 MB | view
```
- `io/mdtest.py` (uses `log_mask: DEBUG,RPC=ERR`)
```
mdtest_small.py-1_daos_server.log-wolf-142.bz2 | Jul 19, 2020 1:59:06 AM | 113.93 MB | view
mdtest_small.py-1_daos_server.log-wolf-143.bz2 | Jul 19, 2020 2:00:34 AM | 122.45 MB | view
mdtest_small.py-1_daos_server.log-wolf-144.bz2 | Jul 19, 2020 2:00:04 AM | 102.94 MB | view
mdtest_small.py-1_daos_server.log-wolf-145.bz2 | Jul 19, 2020 1:58:02 AM | 107.62 MB | view
```
- `io/nvme_object.py` (uses `log_mask: DEBUG,RPC=ERR`)
```
daos_server.log-wolf-142.bz2 | Jul 19, 2020 1:42:06 AM | 11.97 MB | view
daos_server.log-wolf-143.bz2 | Jul 19, 2020 1:42:06 AM | 11.95 MB | view
daos_server.log-wolf-144.bz2 | Jul 19, 2020 1:42:06 AM | 11.96 MB | view
daos_server.log-wolf-145.bz2 | Jul 19, 2020 1:42:06 AM | 11.96 MB | view
daos_server.log-wolf-146.bz2 | Jul 19, 2020 1:42:06 AM | 12.02 MB | view
daos_server.log-wolf-147.bz2 | Jul 19, 2020 1:42:06 AM | 11.97 MB | view
daos_server.log-wolf-148.bz2 | Jul 19, 2020 1:42:06 AM | 11.97 MB | view
```
- `osa/osa_offline_reintegration.py` (uses `log_mask: DEBUG,RPC=ERR`)
```
daos_server.log-wolf-142.bz2 | Jul 19, 2020 2:13:37 AM | 36.13 MB | view
daos_server.log-wolf-143.bz2 | Jul 19, 2020 2:12:13 AM | 197.24 KB | view
daos_server.log-wolf-144.bz2 | Jul 19, 2020 2:13:36 AM | 32.04 MB | view
daos_server.log-wolf-145.bz2 | Jul 19, 2020 2:12:13 AM | 125.18 KB | view

daos_server.log-wolf-142.bz2 | Jul 19, 2020 2:18:31 AM | 38.94 KB | view
daos_server.log-wolf-143.bz2 | Jul 19, 2020 2:18:31 AM | 43.89 KB | view
daos_server.log-wolf-144.bz2 | Jul 19, 2020 2:18:31 AM | 44.30 KB | view
daos_server.log-wolf-145.bz2 | Jul 19, 2020 2:18:31 AM | 44.10 KB | view
```

**Comment by phender** [comment]
> > Looking at https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/2548 as an example, here are the sizes of the server logs produced in the Function HW Large run:
> > 
> > * `io/ior_small.py` (uses `log_mask: DEBUG,RPC=ERR`)
> > 
> > ```
> > ior_small.py-1_daos_server.log-wolf-142.bz2 | Jul 19, 2020 1:35:54 AM | 87.82 MB | view
> > ior_small.py-1_daos_server.log-wolf-143.bz2 | Jul 19, 2020 1:35:54 AM | 81.36 MB | view
> > ior_small.py-1_daos_server.log-wolf-144.bz2 | Jul 19, 2020 1:35:54 AM | 116.15 MB | view
> > ior_small.py-1_daos_server.log-wolf-145.bz2 | Jul 19, 2020 1:35:00 AM | 79.03 MB | view
> > ```
> 
> These specifically are the ones that are causing problems, (possibly because they're the first to run) but uncompressed these logs are about 28Gb which is close to the size of the filesystem used for the compression. Until about 10 days ago the logs were ~40% of this size.

Thanks Ashley.  Shouldn't our first step be to reducing the logging for this test, e.g. `INFO`?  If a test produces a reasonable sized log with our current default, should we not retain that capability.  The concern with having limited logging when an error occurs is the issue may not be readily reproducible, so rerunning with addition logging levels may not encounter the problem.

**Comment by ashleypittman** [comment]
> > > Looking at https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/2548 as an example, here are the sizes of the server logs produced in the Function HW Large run:
> > > 
> > > * `io/ior_small.py` (uses `log_mask: DEBUG,RPC=ERR`)
> > > 
> > > ```
> > > ior_small.py-1_daos_server.log-wolf-142.bz2 | Jul 19, 2020 1:35:54 AM | 87.82 MB | view
> > > ior_small.py-1_daos_server.log-wolf-143.bz2 | Jul 19, 2020 1:35:54 AM | 81.36 MB | view
> > > ior_small.py-1_daos_server.log-wolf-144.bz2 | Jul 19, 2020 1:35:54 AM | 116.15 MB | view
> > > ior_small.py-1_daos_server.log-wolf-145.bz2 | Jul 19, 2020 1:35:00 AM | 79.03 MB | view
> > > ```
> > 
> > 
> > These specifically are the ones that are causing problems, (possibly because they're the first to run) but uncompressed these logs are about 28Gb which is close to the size of the filesystem used for the compression. Until about 10 days ago the logs were ~40% of this size.
> 
> Thanks Ashley. Shouldn't our first step be to reducing the logging for this test, e.g. `INFO`? If a test produces a reasonable sized log with our current default, should we not retain that capability. The concern with having limited logging when an error occurs is the issue may not be readily reproducible, so rerunning with addition logging levels may not encounter the problem.

This is being handled elsewhere, but what I think happened is that https://github.com/daos-stack/daos/commit/926589aced5c18a8b3c4c69ee97e3e37f32c796b caused the logs to grow massively in size and was landed early last week.  Before this PR there was no real issue, but once that landed there was barely enough space, but coincidentally it was right at the limit of what we had space for, since then there appear to have been relatively minor changes that just push things beyond the limit and got us to the point where we are now (it may well be that multiple PRs landed where each one passed as a PR but added a small amount of logging such that in combination master is no longer passing).

The fix is to set the default server mask to INFO which largely avoids the issue altogether, although this does appear to trigger a bug related to timing that we were not seeing before.

**Comment by frostedcmos** [comment]
> I am against this as I feel it's the wrong solution to the problem. High quality logs and debugging from DAOS is important, and part of that is making sure that the right amount of logs, at the right level of priority. This PR can only decrease the quality of the logs, and is paper overing the symptom of log size that is caused by inappropriate log settings and mask usage.

The purpose of this is not so much to fix the current problem which is indeed caused by wrong level of logging being done, but rather to put maximum limit in case any PR introduces a bug that causes logs to be filled up with repetitive errors.

Without having some maximum value, in situations like that you will end up with no logs at all as disk fills and we get nothing back.

**Comment by ashleypittman** [comment]
> > I am against this as I feel it's the wrong solution to the problem. High quality logs and debugging from DAOS is important, and part of that is making sure that the right amount of logs, at the right level of priority. This PR can only decrease the quality of the logs, and is paper overing the symptom of log size that is caused by inappropriate log settings and mask usage.
> 
> The purpose of this is not so much to fix the current problem which is indeed caused by wrong level of logging being done, but rather to put maximum limit in case any PR introduces a bug that causes logs to be filled up with repetitive errors.
> 
> Without having some maximum value, in situations like that you will end up with no logs at all as disk fills and we get nothing back.

This is an undesirable feature of CI certainly.  A potential fix has been discussed before which would be to put the logs on a dedicated partition, then when compressing them do it to a different filesystem where there would still be space so both the compression and saving would work.

https://jira.hpdd.intel.com/browse/DAOS-5345 is probably the best place for this discussion.

**Comment by mjmac** [comment]
@frostedcmos: Can we close this PR so that it doesn't show up in the list of gatekeeper review requests?

**Pull request closed without merging**
