### PR TITLE
CART-89 ofi: Compile ofi without gdrapi linkage

### PR DESCRIPTION
**Pull request by frostedcmos**
- Compile ofi with --with-gdrcopy=no to disable gdrapi linkage

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

### CODE REVIEW

**Comment by frostedcmos** [comment]
Corresponding libfabric rpm package change: https://github.com/daos-stack/libfabric/pull/35

**Review by brianjmurrell — APPROVED** [review]
Can you put a reason in the PR description and commit message?  Or at least have that added to the commit message on landing?

**Review by jolivier23 — APPROVED** [review]

**Comment by frostedcmos** [comment]
DO NOT MERGE this for now. There is an OFI issue that does not disable gdrapi even though we specify the option. It was filed as https://github.com/ofiwg/libfabric/issues/6602

**Review by jolivier23 — COMMENTED** [review]
Can you please move this to a draft if not ready for review.  For some reason, Github processed codeowners on a bunch of old reviews

**Pull request closed without merging**
