### PR TITLE
DAOS-6280 build: Update minimum libfabric version

### PR DESCRIPTION
**Pull request by brianjmurrell**
To 1.11.1.

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]
Only comment is that we should probably run some more tests for libfabric changes.  We've not had the best of luck in the past with that library and seamless upgrades

**Review by JohnMalmberg — COMMENTED** [review]
Does debian/control need a corresponding change?

**Review by sylviachanoiyee — APPROVED** [review]

**Comment by brianjmurrell** [comment]
> Only comment is that we should probably run some more tests for libfabric changes. We've not had the best of luck in the past with that library and seamless upgrades

This PR is not doing anything with the version of libfabric we actually use.  It is just enforcing that a newer version is installed on an **upgrade** from a previous version of DAOS.  We actually updated our libfabric to 1.11.1 2 months ago and have been testing with that version since then.  The DAOS RPMs were just not updated at the time to require that as a minimum version.  This just catches that up.

**Comment by brianjmurrell** [comment]
> Does debian/control need a corresponding change?

We don't actually seem to be doing any minimum version requirement for libfabric at all for Ubuntu.  If we are going to do it for RPMs we should do it for Ubuntu also.  I will push another PR to catch that up also.

**Pull request merged**
