### PR TITLE
DAOS-4617 test: Need to fix python exec_used errors B102 by Bandit check PR#2602

### PR DESCRIPTION
**Pull request by dinghwah**
Cherry-pick DAOS-4617 to release 0.9 branch.
Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

### CODE REVIEW

**Comment by dinghwah** [comment]
Bandit tests with bandit.config test passed.
[main]  INFO    profile include tests: B609,B502,B201,B503,B608,B102,B607,B701,B103,B101,B107,B112,B602,B110,B106,B505,B605,B104,B504,B501,B702,B105,B506,B601,B604,B606
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    using config: bandit.config2
[main]  INFO    running on Python 3.7.6
Run started:2020-05-12 20:43:39.910051

Test results:
        No issues identified.

Code scanned:
        Total lines of code: 97
        Total lines skipped (#nosec): 0

Run metrics:
        Total issues (by severity):
                Undefined: 0.0
                Low: 0.0
                Medium: 0.0
                High: 0.0
        Total issues (by confidence):
                Undefined: 0.0
                Low: 0.0
                Medium: 0.0
                High: 0.0
Files skipped (0):

**Comment by dinghwah** [comment]
7 tests failed triaged and not related to the fix:
(1)DaosCoreTest.test (case 1, 5, 6, 8), mdtest_small.test and DaosCoreTestRebuild.test
   DAOS-4490: /usr/bin/daos_admin EAL: No free hugepages reported 
(2)NvmeObject.test_nvme_object_single_pool: 
   DAOS-4766: daos_io_server:0 Process 19494 received signal 11

**Comment by jolivier23** [comment]
commit message should reference the original PR with #???? and it should follow the commit message format

**Comment by dinghwah** [comment]
The original PR is #2602
https://github.com/daos-stack/daos/pull/2602

**Comment by jolivier23** [comment]
By the way, env_modules.py is in 0.9 but it is in scons_local submodule...so really porting this would entail updating it there and updating the submodule

**Comment by jolivier23** [comment]
@dinghwah I will update scons_local in a patch I'm working on to a later revision so I had Johann land this

**Pull request merged**
