### PR TITLE
DAOS-10204 dtx: delay IO forward for conditional ops during rebuild

### PR DESCRIPTION
**Pull request by Nasf-Fan**
master-commit: 723ae128931048e6ba9321cdcc7e69e5923a5379
    master-commit: e73e148708437eaea47335c5d22b2a244cc3bf67
    
    During object rebuild, if the client triggers conditional operation
    on the object that is in rebuilding, then condition check cannot be
    properly handled on the in-rebuilding target as to cause unexpected
    result when double failures happened.
    
    To resolve such trouble, we will delay IO forwarding of conditional
    sub requests to the in-rebuilding targets until the healthy targets
    have processed related condition check.
    
    From client perspective, related RPC will become slow, but consider
    that the case (conditionally modify the in-rebuilding object shard)
    is rare, then the total overhead is not too much.
    
    For conditional modification against EC object, if all parity nodes
    are lost, then it will be handled via distributed transaction.
    
    This patch also contains some fixes:
    
    1) In dc_tx_convert logic for update/punch with condition and needs
       to be handled via distributed transaction. In old implementation
       the condition check was discarded by wrong during the convert.
    
    2) When check existence in VOS, do not prepare sub tree under akey.
    
    If a distributed transaction contains per akey based modification,
    then we need to check every related akey's existence via each own
    sub-task independently. Each one is a conditional akey fetch task.
    
    Signed-off-by: Fan Yong <fan.yong@intel.com>

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]

**Comment by jolivier23** [comment]
what does this mean?

For per-akey, it will be handled as non-per akey?  What happens if you do per akey and you have one key with cond_update and another with cond_insert ?

**Comment by Nasf-Fan** [comment]
> what does this mean?
> 
> For per-akey, it will be handled as non-per akey? What happens if you do per akey and you have one key with cond_update and another with cond_insert ?

Good question. I think we need either handle such case as per-akey when conditional fetch or separate it into multiple sub conditional fetch requests. I will make another patch to handle that.

**Comment by jolivier23** [comment]
> > what does this mean?
> > For per-akey, it will be handled as non-per akey? What happens if you do per akey and you have one key with cond_update and another with cond_insert ?
> 
> Good question. I think we need either handle such case as per-akey when conditional fetch or separate it into multiple sub conditional fetch requests. I will make another patch to handle that.

yeah, I think this may be a regression that we don't want to land to 2.2 otherwise.   A per-akey condition should only affect the akey it is set on.

**Review by jolivier23 — APPROVED** [review]

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Looks like there is a conflict now to resolve.

**Comment by Nasf-Fan** [comment]
Rebased to resolve the merge conflict.

**Review by liuxuezhao — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
