### PR TITLE
DAOS-11066 dtx: discard old DTX entries during server reintegration

### PR DESCRIPTION
**Pull request by Nasf-Fan**
During the server reintegration, some new update RPC may be sent to
the in-reintegrating server, that will generate new DTX entry which
version is newer than the version of server re-added. On the other
hand, there may be other server corruption during the reintegration
that will cause currern reintegration failure and be re-scheduled.
During the re-scheduled server reintegration, above mentioned new
generated DTX entry needs to be handled by normal DTX resync logic
instead of being discarded. The logic of discarding old DTX entries
for server reintegration is only applicable to the DTX entry which
version is older than the server re-added version.

Signed-off-by: Fan Yong <fan.yong@intel.com>

### CODE REVIEW

**Comment by Nasf-Fan** [comment]
Hit DAOS-10758, to be retested.

**Comment by Nasf-Fan** [comment]
Do not found the real test failure, to be rebased with the latest mercury.

**Review by jolivier23 — APPROVED** [review]

**Comment by kprantis** [comment]
If we could, please prioritize reviewing this 2.2 blocker.

**Review by wangdi1 — APPROVED** [review]

**Review by liuxuezhao — APPROVED** [review]

**Comment by kprantis** [comment]
Is this ready for gatekeeping?

**Pull request merged**
