### PR TITLE
DAOS-6494 dtx: improve object consistency verification

### PR DESCRIPTION
**Pull request by Nasf-Fan**
When verify the object data consistency, we will make all
committable DTX (that touch related object) to be committed
by froce, that is called object sync. Then we mark the sync
epoch on the object.

When the DTX leader stop the DTX, it needs to check whether
related modification is valid or not (if its epoch is older
than sync epoch) via vos_dtx_check_sync(). But such check
will fail if related object is removed from the VOS cache
during current DTX leader wait for other non-leaders' reply
as to vos_dtx_check_sync() cannot find related object for
sync epoch check, then the DTX will fail. That is wrong.

In fact, such check is unnecessary. We have done related
check when we do the modification in VOS. So we can remove
vos_dtx_check_sync() related logic.

On the other hand, dtx_obj_sync() cannot gurantee that all
the committable DTX that touch the specified object can be
committed because of distributed transaction that may make
the DTX leader to locate on any server. So by race, object
consistency verification logic may hit the case that when
it reads data from one replica (non-leader), some DTX may
be not committed yet; but when it reads data from another
replica, related DTX has been committed, that will cause
fake data inconsistency. To avoid such trouble, we will
force the non-leader to do dtx_refresh with leader when
hit non-committed DTX if required by the client (object
consistency verification) via the flag "ORF_DTX_REFRESH".

Signed-off-by: Fan Yong <fan.yong@intel.com>

### CODE REVIEW

**Comment by wangdi1** [comment]
> When verify the object data consistency, we will make all
> committable DTX (that touch related object) to be committed
> by froce, that is called object sync. Then we mark the sync
> epoch on the object.
> 
> When the DTX leader stop the DTX, it needs to check whether
> related modification is valid or not (if its epoch is older
> than sync epoch) via vos_dtx_check_sync(). But such check
> will fail if related object is removed from the VOS cache
> during current DTX leader wait for other non-leaders' reply
> as to vos_dtx_check_sync() cannot find related object for
> sync epoch check, then the DTX will fail. That is wrong.
> 
> In fact, such check is unnecessary. We have done related
> check when we do the modification in VOS. So we can remove
> vos_dtx_check_sync() related logic.
> 
> On the other hand, dtx_obj_sync() cannot gurantee that all
> the committable DTX that touch the specified object can be
> committed because of distributed transaction that may make
> the DTX leader to locate on any server. So by race, object
> consistency verification logic may hit the case that when
> it reads data from one replica (non-leader), some DTX may
> be not committed yet; but when it reads data from another
> replica, related DTX has been committed, that will cause
> fake data inconsistency. 

Sorry, a bit confusing here, I thought if read hit any uncommitted data, it will ask the leader, which can be found from the DTX entry, anyway.  Why do we need extra protocol here?   is this only for verification?  I would rather let client wait further time until all related DTX are committed, instead of add extra complexity.  or I miss sth?

To avoid such trouble, we will
> force the non-leader to do dtx_refresh with leader when
> hit non-committed DTX if required by the client (object
> consistency verification) via the flag "ORF_DTX_REFRESH".
> 
> Signed-off-by: Fan Yong [fan.yong@intel.com](mailto:fan.yong@intel.com)

**Comment by Nasf-Fan** [comment]
> Sorry, a bit confusing here, I thought if read hit any uncommitted data, it will ask the leader, which can be found from the DTX entry, anyway. Why do we need extra protocol here? is this only for verification? I would rather let client wait further time until all related DTX are committed, instead of add extra complexity. or I miss sth?

It is not new protocol, DTX refresh among servers has already been implemented. The patch only adds another use case for that. For "verification" case, we do not want the client to retry, because if there is real inconsistency between replicas, such client retry may cause the "verification" to hung.

**Comment by Nasf-Fan** [comment]
daos_test -T failed for DAOS-6539.
daos_test -z failed for DAOS-6507.

**Comment by Nasf-Fan** [comment]
daos_test -m failed for DAOS-6544.

**Comment by wangdi1** [comment]
> > Sorry, a bit confusing here, I thought if read hit any uncommitted data, it will ask the leader, which can be found from the DTX entry, anyway. Why do we need extra protocol here? is this only for verification? I would rather let client wait further time until all related DTX are committed, instead of add extra complexity. or I miss sth?
> 
> It is not new protocol, DTX refresh among servers has already been implemented. The patch only adds another use case for that. For "verification" case, we do not want the client to retry, because if there is real inconsistency between replicas, such client retry may cause the "verification" to hung.

So dtx refresh means the server will contact the leader itself to ask the dtx/data readable status ? instead of through client retry to the leader? I thought we used to do that?  Or I miss sth?

**Comment by Nasf-Fan** [comment]
daos_test -T failed for DAOS-6539.

**Review by jolivier23 — APPROVED** [review]

**Comment by Nasf-Fan** [comment]
@wangdi1 , @liw , would you please to help review the patch? Thanks!

**Comment by Nasf-Fan** [comment]
Recently, we hit several times of DTX_22 failure, that can be fixed by this patch. Please help to review. Thanks!

**Review by wangdi1 — APPROVED** [review]
Not sure I follow all the logic here, but since it can fix current CI failure, let's check later.

**Comment by jolivier23** [comment]
would you mind merging this with latest master ?  I'm seeing green PR's now so am hesitant to land stuff that isn't green and this is older.

**Comment by Nasf-Fan** [comment]
> would you mind merging this with latest master ? I'm seeing green PR's now so am hesitant to land stuff that isn't green and this is older.

Done.

**Pull request merged**
