### PR TITLE
DAOS-6258: weekly-test: Snapshot: Timeout reached

### PR DESCRIPTION
**Pull request by cibervicho**
All variants of snapshot test are timing out.
Increasing its timeout to fix this.

Signed-off-by: David Maldonado Moreno <david.maldonado.moreno@intel.com>

### CODE REVIEW

**Comment by cibervicho** [comment]
All tests are passing now:
`Test / Functional on Leap 15 / 01-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_S1-pool-server_config-snapshot-5400	19 sec	Passed
Test / Functional on CentOS 7 / 01-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_S1-pool-server_config-snapshot-a501	19 sec	Passed
Test / Functional on CentOS 7 / 02-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_S4-pool-server_config-snapshot-9824	20 sec	Passed
Test / Functional on Leap 15 / 02-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_S4-pool-server_config-snapshot-ace7	20 sec	Passed
Test / Functional on CentOS 7 / 03-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_SX-pool-server_config-snapshot-8f8e	18 sec	Passed
Test / Functional on Leap 15 / 03-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_SX-pool-server_config-snapshot-c6a1	20 sec	Passed
Test / Functional on CentOS 7 / 04-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_RP_2G1-pool-server_config-snapshot-87e1	19 sec	Passed
Test / Functional on Leap 15 / 04-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_RP_2G1-pool-server_config-snapshot-a58f	20 sec	Passed
Test / Functional on Leap 15 / 05-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_RP_2G2-pool-server_config-snapshot-34e0	20 sec	Passed
Test / Functional on CentOS 7 / 05-./container/snapshot.py:Snapshot.test_snapshot_negativecases;no_faults-hosts-OC_RP_2G2-pool-server_config-snapshot-5a80	19 sec	Passed
Test / Functional on Leap 15 / 06-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_S1-pool-server_config-snapshot-5400	1 min 7 sec	Passed
Test / Functional on CentOS 7 / 06-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_S1-pool-server_config-snapshot-a501	1 min 28 sec	Passed
Test / Functional on CentOS 7 / 07-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_S4-pool-server_config-snapshot-9824	1 min 36 sec	Passed
Test / Functional on Leap 15 / 07-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_S4-pool-server_config-snapshot-ace7	1 min 11 sec	Passed
Test / Functional on CentOS 7 / 08-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_SX-pool-server_config-snapshot-8f8e	1 min 44 sec	Passed
Test / Functional on Leap 15 / 08-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_SX-pool-server_config-snapshot-c6a1	1 min 11 sec	Passed
Test / Functional on CentOS 7 / 09-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_RP_2G1-pool-server_config-snapshot-87e1	9 min 34 sec	Passed
Test / Functional on Leap 15 / 09-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_RP_2G1-pool-server_config-snapshot-a58f	8 min 3 sec	Passed
Test / Functional on Leap 15 / 10-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_RP_2G2-pool-server_config-snapshot-34e0	8 min 4 sec	Passed
Test / Functional on CentOS 7 / 10-./container/snapshot.py:Snapshot.test_snapshots;no_faults-hosts-OC_RP_2G2-pool-server_config-snapshot-5a80	9 min 10 sec	Passed`

**Review by dinghwah — APPROVED** [review]
LGTM.
Please indicate the medium-failure is not related to the PR.
Also 600 seconds are appropriate to this test, after numbers of tests.

**Review by berserk-fury — APPROVED** [review]

**Comment by cibervicho** [comment]
Dear @daos-stack/daos-gatekeeper Blue Ocean shows that "Functional HW Medium" failed with an Error Signal and then when trying to record the results. This error is not caused by increasing the timeout of the snapshot.yaml file.

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Pull request merged**
