### PR TITLE
DAOS-5290 test: Fix csum_error_logging script issue with secure-mode.

### PR DESCRIPTION
**Pull request by dinghwah**
Update csum_error_logging.py to use new dmg class with correct certificates and keys. 

Modified: checksum/csum_error_logging.py
          checksum/csum_error_logging.yaml

Test-tag: pr,-hw csum_error_log
Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

### CODE REVIEW

**Comment by dinghwah** [comment]
Functional small, medium and large tests passed.
The failures in pr-head and test/functional are irrelated to the csum_error_logging.py dmg script fix.

**Comment by dinghwah** [comment]
14 testcases failed on the Functional test are different tests from csum_error_logging tests on this commit.

**Comment by dinghwah** [comment]
All tests passed after remerged to master.
Please merge. 
Thanks, Ding.

**Comment by mjmac** [comment]
@jolivier23: You ok with this one now?

**Pull request merged**
