### PR TITLE
DAOS-5618 test: Fixed regex for methods used in container/query_attribute.py

### PR DESCRIPTION
**Pull request by shimizukko**
Also removed some of the get_output usage.

Test-tag: pr,-hw cont_query_attr cont_list_attrs
Signed-off-by: Makito Kano <makito.kano@intel.com>

### CODE REVIEW

**Review by amjustin13 — APPROVED** [review]
Look good to me.

**Review by phender — DISMISSED** [review]
LGTM

**Review by amjustin13 — DISMISSED** [review]
LGTM

**Comment by shimizukko** [comment]
Test Failures:
security/container_security_acl.py -> Weekly regression
security/container_security_acl.py: -> DAOS-5610
io/ior_small.py -> DAOS-5610
nvme/nvme_object.py -> DAOS-4943
io/mascio_test.py -> DAOS-5706
io/mdtest_small.py -> DAOS-5610
osa/osa_online_reintegration.py -> DAOS-5610
osa/osa_online_drain.py -> DAOS-5610
io/io_consistency.py -> DAOS-4943
server/daos_server_restart.py -> DAOS-5610
aggregation/aggregation_basic.py -> DAOS-5502

**Review by amjustin13 — APPROVED** [review]

**Review by phender — APPROVED** [review]
LGTM

**Pull request merged**
