### PR TITLE
DAOS-16013 tools: Query all pool targets by default

### PR DESCRIPTION
**Pull request by mjmac**
Running `daos pool query-targets` with just a rank
argument should query all targets on that rank.

Required-githooks: true

Change-Id: Ib5fff358769679f8c282372fdfa8eaba2b5471cd
Signed-off-by: Michael MacDonald <mjmac@google.com>

### CODE REVIEW

**Review by kjacque — APPROVED** [review]

**Comment by kccain** [comment]
For symmetry should the dmg pool query-targets command support the same?

**Comment by mjmac** [comment]
> For symmetry should the dmg pool query-targets command support the same?

Hmm. Missed that! Yes, it should. Thanks for pointing it out, will push an update.

**Review by tanabarr — CHANGES_REQUESTED** [review]
Can you please add some unit tests to verify this change.

**Comment by mjmac** [comment]
> Can you please add some unit tests to verify this change.

It's not easy to thoroughly test this, but I've added what I can without heroics.

**Review by tanabarr — APPROVED** [review]
LGTM

**Review by kjacque — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]

**Pull request merged**
