### PR TITLE
DAOS-7174 cont: take a label for daos_cont_create

### PR DESCRIPTION
**Pull request by johannlombardi**
Change daos_cont_create() to take a label (string) an a input
parameter. This basically makes the label a requirement.

Backward API compatibility is supported via a macro that will
automatically convert a uuid_t (old API) to a UUID string.
We could eventually remove the macro in 2.2 or beyond.

Backward ABI compatibility is supported by keeping around
the daos_cont_create symbols, but not advertising them via
the header files (the macro overrides it).

Handle backward compatibility for the task API too.

Remove daos_cont_create_by_label() operations that is
no longer required.

Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

### CODE REVIEW

**Comment by johannlombardi** [comment]
@mchaarawi @kccain I know that this is not the perfect solution, but that's the simpler i could come up with. Please review and feel free to update it if you have a better proposal.

**Review by mchaarawi — COMMENTED** [review]
one thing here is that for the UNS, we don't know what label to use when creating a container. so if a label is required, the UNS does not know what to pass, where as it used to just uuid_generate() when using uuid.

**Comment by johannlombardi** [comment]
Then we have to adjust the behavior based on the number of arguments, so we could use something like this in the macro:
``
#define D_ARGS_COUNT(...) _D_ARGS_COUNT(__VA_ARGS__, 5, 4, 3, 2, 1)
``
``
#define _D_ARGS_COUNT(a, b, c, d, e, cnt, ...) cnt
``

The challenge is that we need to keep the daos_cont_create() symbol with the current signature and not include daos_cont.h since it will cause a function signature mismatch.

**Comment by johannlombardi** [comment]
Pushed a draft patch that i was working on. It does not compile due to the difference in signature of daos_cont_create() between the header file (daos_cont.h) and the symbol in the library (for ABI compat). Not sure how to address this.

```
src/client/api/compat.c:21:1: error: conflicting types for ‘daos_cont_create’
407  daos_cont_create(daos_handle_t poh, const char *cont, daos_prop_t *cont_prop,
408  ^
409 In file included from src/include/daos_task.h:23:0,
410                 from src/include/daos/task.h:17,
411                  from src/client/api/compat.c:8:
412 src/include/daos_cont.h:147:1: note: previous declaration of ‘daos_cont_create’ was here
413 daos_cont_create(daos_handle_t poh, const char *label, daos_prop_t *cont_prop,
414 ^
```

**Pull request closed without merging**
