### PR TITLE
DAOS-7247 test: Re-enable offline parallel test

### PR DESCRIPTION
**Pull request by rpadma2**
Test-tag-hw-medium: pr,hw,medium,ib2 offline_parallel

Signed-off-by: rpadma2 <ravindran.padmanabhan@intel.com>

### CODE REVIEW

**Review by ravalsam — DISMISSED** [review]

**Review by saurabhtandan — DISMISSED** [review]
LGTM

**Comment by sylviachanoiyee** [comment]
This is great but can we add one line to turn pool label off i.e. use uuid for pool creation/destroy instead?

**Comment by rpadma2** [comment]
> This is great but can we add one line to turn pool label off i.e. use uuid for pool creation/destroy instead?

Can we do it on a different test for coverage (ie: to use pool uuid)?

**Review by shimizukko — APPROVED** [review]
Sorry, maybe I did unnecessary work of converting it to use self.pool.

**Comment by rpadma2** [comment]
Restarted the testing after adding:
            # Use only pool UUID while running the test.
            self.pool.use_label = False

**Review by shimizukko — APPROVED** [review]

**Review by sylviachanoiyee — APPROVED** [review]

**Pull request merged**
