### PR TITLE
DAOS-9313 test: Update the object class and RF.

### PR DESCRIPTION
**Pull request by rpadma2**
Test-tag-hw-medium: pr,hw,medium,ib2 offline_reintegration_srv_stop

Summary
-  Update the object class and redundancy factor to make sure we don't encounter intermittent redundancy factor issue during daos container check at the end of the test case. 

Signed-off-by: rpadma2 <ravindran.padmanabhan@intel.com>

### CODE REVIEW

**Comment by rpadma2** [comment]
Ran the offline_reintegration_srv_stop under CI 3 times. Also, under IO500 ran test for 10 times and didn't hit the IO or redundancy factor failure.

**Review by shimizukko — APPROVED** [review]

**Review by dinghwah — APPROVED** [review]
LGTM.

**Comment by rpadma2** [comment]
All failures are known issues:
daos_test/suite.py:DaosCoreTest.test_daos_oid_allocator : DAOS-9519
daos_test/suite.py:DaosCoreTest.test_daos_single_rdg_tx : DAOS-9658
daos_test/suite.py:DaosCoreTest.test_daos_rebuild_ec : DAOS-9520

**Review by Nasf-Fan — APPROVED** [review]

**Comment by rpadma2** [comment]
Hi gatekeeper, Please merge this PR once the master branch is open.

**Pull request merged**
