### PR TITLE
DAOS-5863 tests: Avoid installing wrong daos-server debuginfo version

### PR DESCRIPTION
**Pull request by phender**
During post test execution when processing core files a version of the
daos-server RPM and its debuginfo package could be installed that
differed from the one being tested.  This could produce inaccurate
stacktrace information and adversely influence the daos code being
tested by subsequent tests.

The daos-server RPM is no longer reinstalled and debuginfo-install will
use the version that matches the installed daos-server version.

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by phender** [comment]
In the [Functional_Hardware_Medium](https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/daos/branches/PR-3698/runs/1/nodes/618/log/?start=0) console log the `daos-server-1.1.1-3.5159.g6fc1c77c.el7.x86_64` RPM is installed when provisioning the hosts.  A stack trace is then generated after running the daos_test/daos_core_test.py, where the matching daos debuginfo package isinstalled:
```
[2020-10-21T09:44:09.122Z]   Installing : daos-debuginfo-1.1.1-3.5159.g6fc1c77c.el7.x86_64           13/28 
```

**Comment by phender** [comment]
Test failues:
- Functional_Hardware_Medium: DaosCoreTest.09: daos_test/daos_core_test.py: test_i: https://jira.hpdd.intel.com/browse/DAOS-5873
- Functional_Hardware_Medium: DaosCoreTest.11: daos_test/daos_core_test.py: test_D: https://jira.hpdd.intel.com/browse/DAOS-5882
- Functional_Hardware_Medium: DaosCoreTest.12: daos_test/daos_core_test.py: test_K: https://jira.hpdd.intel.com/browse/DAOS-5882
- Functional_Hardware_Medium: DaosCoreTest.13: daos_test/daos_core_test.py: test_F: https://jira.hpdd.intel.com/browse/DAOS-5882

**Review by brianjmurrell — APPROVED** [review]

**Review by brianjmurrell — APPROVED** [review]

**Comment by phender** [comment]
Errors seen in (in-progress) https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3698/4/:
- Test / Functional on CentOS 7: pool/pool_svc.py:  https://jira.hpdd.intel.com/browse/DAOS-5919
- Test / Functional on Leap 15: pool/pool_svc.py: https://jira.hpdd.intel.com/browse/DAOS-5919

**Review by mjean308 — APPROVED** [review]
lgtm

**Pull request merged**
