### PR TITLE
dfs: Add support for reading symlink values.

### PR DESCRIPTION
**Pull request by ashleypittman**
Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
Again, this is an API change but I can't see a way of fetching this data with out, unless we can call dfs_ostat() and use that to refresh the string.

**Comment by mchaarawi** [comment]
> Again, this is an API change but I can't see a way of fetching this data with out, unless we can call dfs_ostat() and use that to refresh the string.

sigh.. yea im find with this API change since it shouldn't break any of the above middleware since it's not used there.
might need to rebuild everything in CI (ior, MPI-IO) if this lands.
will review more closely on Monday.

**Comment by mchaarawi** [comment]
> > Again, this is an API change but I can't see a way of fetching this data with out, unless we can call dfs_ostat() and use that to refresh the string.
> 
> sigh.. yea im fine with this API change since it shouldn't break any of the above middleware since it's not used there.
> might need to rebuild everything in CI (ior, MPI-IO) if this lands.
> will review more closely on Monday.

Actually come to think about it, I think this warrants a new api, dfs_readlink and keep this one that is useful in a read only use case (or a snapshot) where a fetch is not needed. Mpifileutils for example works on a snapshot and refetching here is not needed.

**Comment by ashleypittman** [comment]
> > > Again, this is an API change but I can't see a way of fetching this data with out, unless we can call dfs_ostat() and use that to refresh the string.
> > 
> > 
> > sigh.. yea im fine with this API change since it shouldn't break any of the above middleware since it's not used there.
> > might need to rebuild everything in CI (ior, MPI-IO) if this lands.
> > will review more closely on Monday.
> 
> Actually come to think about it, I think this warrants a new api, dfs_readlink and keep this one that is useful in a read only use case (or a snapshot) where a fetch is not needed. Mpifileutils for example works on a snapshot and refetching here is not needed.

I had another look at the code on Friday, and if we make dfs_ostat() refresh the value then I think it'll work just as well, dfuse_readlink() can just call both functions and the network cost will be the same but the API can remain unchanged.

**Comment by ashleypittman** [comment]
I don't think this is needed at all, there's no way to update a symlink, you have to delete + recreate it so it would get a different oid/inode and hence this wouldn't be used.

**Pull request closed without merging**
