### PR TITLE
DAOS-16508 csum: retry a few times on checksum mismatch on update (#1…

### PR DESCRIPTION
**Pull request by johannlombardi**
…5069)

Unlike fetch, we return DER_CSUM on update (turned into EIO by dfs) without any retry. We should retry a few times in case it is a transient error.

The patch also prints more information about the actual checksum mismatch.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by liuxuezhao — APPROVED** [review]

**Comment by daltonbohning** [comment]
@johannlombardi Since this hasn't been updated since Sep 10, could you please merge latest release/2.6?

**Comment by daltonbohning** [comment]
NLT timed out, which is common lately. So I retriggered the run

**Comment by johannlombardi** [comment]
@daltonbohning timed out again or still running? Thanks in advance.

**Comment by daltonbohning** [comment]
> @daltonbohning timed out again or still running? Thanks in advance.

It timed out 3 times in a row. I know there are issues, but I've seen other PRs have success so I'm not sure if you're just unlucky.

**Comment by daltonbohning** [comment]
> > @daltonbohning timed out again or still running? Thanks in advance.
> 
> It timed out 3 times in a row. I know there are issues, but I've seen other PRs have success so I'm not sure if you're just unlucky.

Seems the stage is just Yellow now instead of Red. Hopefully the rest goes okay :)

**Comment by daltonbohning** [comment]
Now the HW Stages failed before running the tests. I don't know why CI dislikes this PR so much. Restarted again...

**Comment by daltonbohning** [comment]
@johannlombardi I merged latest release/2.6 - Hopefully it makes it through testing this time...

**Review by gnailzenh — APPROVED** [review]

**Pull request merged**
