### PR TITLE
DAOS-3916 container: fix metadata times in CONT_OPEN_BYLABEL

### PR DESCRIPTION
**Pull request by kccain**
In commit d37f4fb the interoperability mechanism was not properly implemented for RPC CONT_OPEN_BYLABEL due to an oversight in rpc.h.

Without this change, when daos_cont_open() is invoked specifying a valid container label, the daos_cont_info_t information contains junk values in structure members ci_md_otime and ci_md_mtime. The problem is seen in client log messages when running daos_test -p (pool tests). The test still passes. It is also visible if daos_test -c (container tests) is changed to open containers by label (instead of UUID string typically done). Container test co_mdtimes() eplicitly fails in this scenario.

With this change, the RPC protocol version mechanism is corrected for opcode CONT_OPEN_BYLABEL, to use latest (v7) message definitions when applicable. Also, the daos_test co_mdtimes() test is updated to exercise open by label (and therefore catch any future regression).

Required-githooks: true

Signed-off-by: Kenneth Cain <kenneth.c.cain@intel.com>

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficent testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by kccain** [comment]
Initial draft form of PR passed all (per-PR) CI tests.

Waiting for PR https://github.com/daos-stack/daos/pull/10671 from kccain/daos_3916_filterapi branch to land first, then rebase this on (latest) master.

**Comment by kccain** [comment]
Still waiting for PR https://github.com/daos-stack/daos/pull/10671 from the base branch to land, which is taking some time. So in the meantime let's get code reviews started.

**Review by liw — APPROVED** [review]

**Review by wangshilong — APPROVED** [review]

**Review by liw — APPROVED** [review]

**Comment by kccain** [comment]
Build 3 had a single test failure in functional HW medium, osa_online_extend.py that is an instance of https://daosio.atlassian.net/browse/DAOS-12054

**Comment by kccain** [comment]
I have another attempt at the functional HW stages currently waiting for time on the CI cluster, to attempt a clean test run. If that passes I can remove the forced-landing label from the PR (presuming that the checkpatch false-positive failures do not require force landing)

https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-10746/4/pipeline/

**Comment by kccain** [comment]
Functional HW medium passed in build 4. Removed forced-landing tag (assuming it is not needed for the false-positives checkpatch errors that remain in the PR). I think this is ready for landing (subject to gatekeeper review, of course).

**Pull request merged**
