### PR TITLE
DAOS-6357 test: Fix NVMe Recovery 3 test failure

### PR DESCRIPTION
**Pull request by sydneyvanda**
Currently NVMe Recovery 3: Verify blobstore state NORMAL->OUT transition
test was failing when ran on more than 1 node. This was due to the fact
that the device being set as FAULTY and then queried for the device state
may not have been present on the server and then unable to be found in
the per-server metadata. The test was updated to use a device only on
rank 0 to avoid this error.

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

### CODE REVIEW

**Review by ravalsam — APPROVED** [review]
LGTM. Tested and Verify locally.

**Review by NiuYawei — APPROVED** [review]

**Comment by ravalsam** [comment]
@daos-stack/daos-gatekeeper 

This is ready for merge. Thanks

**Comment by sylviachanoiyee** [comment]
Is this test enabled to run in CI? Can you point me to the result if it is?
When was the last this PR was rebased/merged with master? There's a lot of failures reported in Jenkins.
To date, there should be no more than 3 intermittent failures that gatekeepers are aware of on master.
This PR will have a hard time getting approval to force land with this many failures.

**Comment by ravalsam** [comment]
> Is this test enabled to run in CI? Can you point me to the result if it is?
> When was the last this PR was rebased/merged with master? There's a lot of failures reported in Jenkins.
> To date, there should be no more than 3 intermittent failures that gatekeepers are aware of on master.
> This PR will have a hard time getting approval to force land with this many failures.

Yes this test is enabled to run in Ci and I tried this PR running locally and it works fine.
I did not see that many failures on the functional test let me rebase to master.

**Comment by sylviachanoiyee** [comment]
> > Is this test enabled to run in CI? Can you point me to the result if it is?
> > When was the last this PR was rebased/merged with master? There's a lot of failures reported in Jenkins.
> > To date, there should be no more than 3 intermittent failures that gatekeepers are aware of on master.
> > This PR will have a hard time getting approval to force land with this many failures.
> 
> Yes this test is enabled to run in Ci and I tried this PR running locally and it works fine.
> I did not see that many failures on the functional test let me rebase to master.

Sounds good, thanks. Just FYI, to force land anything even with known intermittent failures, a gatekeeper need to seek approval of 2 other gatekeepers to minimize bugs sneaking in.

**Comment by ravalsam** [comment]
After rebase everything looks good. It also passes the NVMe discovery test.
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4262/3/artifact/Functional/job-2021-01-20T01.05-60e3a5e-daos_test-daos_core_test-nvme_recovery/

**Pull request merged**
