### PR TITLE
DAOS-2172 api: split DAOS API in different header files

### PR DESCRIPTION
**Pull request by johannlombardi**
Create special header files for pool, container, object, transaction, array and kv API.

Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

### CODE REVIEW

**Comment by mchaarawi** [comment]
the change looks good to me, but any idea why the tests are not running?

**Comment by johannlombardi** [comment]
Because i created it as a draft PR. Will resubmit as a standard one.

**Comment by johannlombardi** [comment]
ok, i clicked on ready for review and it converted the PR to a real one. Nice.

**Comment by johannlombardi** [comment]
See https://github.com/daos-stack/daos/pull/245

**Pull request closed without merging**
