### PR TITLE
DAOS-14328 cart: Do not print error when exceeding context limit

### PR DESCRIPTION
**Pull request by frostedcmos**
- Do not print an internal layer error when exceeding the context limit, as daos client layer will try to allocate as many contexts as it can in some usage models. Printing an error is not user friendly in such situations.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by ashleypittman** [comment]
This feels like it should be an INFO so it's emitted by default.  The code will continue to work afterwards but with a work-around, and there are settings that could be applied to mitigate some of the workaround cost?

**Comment by frostedcmos** [comment]
> This feels like it should be an INFO so it's emitted by default. The code will continue to work afterwards but with a work-around, and there are settings that could be applied to mitigate some of the workaround cost?

Customers were confused to see these messages during a normal run, which is why i moved it to the debug. I can change it to info if that is preferred. @mchaarawi ?

I am not really sure what costs you are referring to or which settings.

**Comment by frostedcmos** [comment]
> > > This feels like it should be an INFO so it's emitted by default. The code will continue to work afterwards but with a work-around, and there are settings that could be applied to mitigate some of the workaround cost?
> > 
> > 
> > Customers were confused to see these messages during a normal run, which is why i moved it to the debug. I can change it to info if that is preferred. @mchaarawi ?
> > I am not really sure what costs you are referring to or which settings.
> 
> Oh, I thought `CRT_SRV_CONTEXT_NUM` was an env var, is it just a #define? The cost is I/O being on a shared context rather than a dedicated one isn't it so worse data locality?

It's the define, set to 64. I am not sure what we can do on our end wrt costs of using the same shared context; this is a daos client library decision to use one of the contexts as a shared one (as opposed to round-robbing among available context for example).

**Comment by mchaarawi** [comment]
> > > > This feels like it should be an INFO so it's emitted by default. The code will continue to work afterwards but with a work-around, and there are settings that could be applied to mitigate some of the workaround cost?
> > > 
> > > 
> > > Customers were confused to see these messages during a normal run, which is why i moved it to the debug. I can change it to info if that is preferred. @mchaarawi ?
> > > I am not really sure what costs you are referring to or which settings.
> > 
> > 
> > Oh, I thought `CRT_SRV_CONTEXT_NUM` was an env var, is it just a #define? The cost is I/O being on a shared context rather than a dedicated one isn't it so worse data locality?
> 
> It's the define, set to 64. I am not sure what we can do on our end wrt costs of using the same shared context; this is a daos client library decision to use one of the contexts as a shared one (as opposed to round-robbing among available context for example).

i think debug for this message is fine. the name is a little misleading though for this.
is there any reason why this can't be configurable with an env variable? why is the max 64 for example? why not 128?

**Review by jgmoore-or — APPROVED** [review]

**Review by soumagne — APPROVED** [review]

**Review by mchaarawi — APPROVED** [review]

**Pull request merged**
