### PR TITLE
DAOS-8333 dfuse: Fix and add test for read after truncate.

### PR DESCRIPTION
**Pull request by ashleypittman**
Add a test to create a file, truncate it longer and read after the truncate.

Fix an issue where dfuse was incorrectly enabling the 'zero-read' feature
in this case by having dfuse track the filesize during write calls.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
This fix isn't adequate and now the condition is racy.  What appears to be happening is the kernel is issuing a async write, then a setattr so there's no guarantee that the write will have completed by the time the setattr is called.

We could move the size check in setattr until after the size has been fetched which would close the window further but not completely, or we could try and set the size in the write call.  If we do it in the write completion callback then it'll still be racy, if we do it in the write itself then the write might fail and dfuse would have an incorrect size, although only until the next attr call.

**Comment by ashleypittman** [comment]
> We could move the size check in setattr until after the size has been fetched which would close the window further but not completely, or we could try and set the size in the write call. If we do it in the write completion callback then it'll still be racy, if we do it in the write itself then the write might fail and dfuse would have an incorrect size, although only until the next attr call.

Done, the size update is now done in the write request but I've thought it another scenario, the sequence could be write, setxattr, write complete in which case the write could set the new size, the setxattr might return the old size and then we'd see the bug on the next read.  I think we probably need to re-evaluate the original use-case for this and the ie_start_off and ie_end_off values in struct dfuse_inode and change the implementation to do proper region checking or simply to use a flag for "this file has been written to".

Simplest way forward might be a "maximum written offset" which we would only grow, or shrink on a successful truncate call.  This PR needs more work for that.

**Comment by ravalsam** [comment]
I added an Avocado test to verify the truncate https://github.com/daos-stack/daos/pull/6476.

I tried this PR locally and still observed the test failure https://gist.github.com/ravalsam/6594e1cbc8a5fb04e3a67a8bc202baed . So this PR is not actually fixing the test?

**Comment by ashleypittman** [comment]
> I added an Avocado test to verify the truncate #6476.
> 
> I tried this PR locally and still observed the test failure https://gist.github.com/ravalsam/6594e1cbc8a5fb04e3a67a8bc202baed . So this PR is not actually fixing the test?

I think this PR fixes some code-paths but the condition is now racey and will sometimes happen and sometimes not.  Further investigation is required.

**Review by ravalsam — APPROVED** [review]
Avocado test passed in CI, so LGTM...

**Review by mchaarawi — APPROVED** [review]

**Pull request merged**
