### PR TITLE
DAOS-6304 integration: harmonize systemd user/group setup

### PR DESCRIPTION
**Pull request by Michael-Hennecke**
add Group=daos_admins to daos_agent.service
update user.group in daosfiles.conf

Signed-off-by: Michael Hennecke <mhennecke@lenovo.com>

### CODE REVIEW

**Review by bfaccini — APPROVED** [review]

**Comment by johannlombardi** [comment]
@mjmac Could you please confirm that those changes are fine with you?

**Review by mjmac — CHANGES_REQUESTED** [review]
Sorry I hadn't looked at this sooner. Looks good except that daos_agent should not be in the daos_admins group. The daos_agent process is intended to be unprivileged.

**Comment by Michael-Hennecke** [comment]
What privilege does daos_agent receive by being a member of the daos_admins group? 

My goal here is to give both daos_server and daos_agent the privilege to write their logfiles into a /var/daos/ directory that is chmod 770 (or 775), and chgrp daos_admin. 
This could eliminate the reliance on /tmp for daemon logs, which isn't a good location for log files as it often gets cleaned up, and needs chmod 4777 to work.

**Comment by Michael-Hennecke** [comment]
closing out this PR, and starting a fresh branch and PR to implement what was decided in the meeting with johann and mjmac today...

**Pull request closed without merging**
