### PR TITLE
DAOS-9951 test: Add label update test case in pool/label.py

### PR DESCRIPTION
**Pull request by shimizukko**
Pool can be updated with dmg pool set-prop. Add a test case to test this feature.

1. Create a pool.
2. Update the label with dmg pool set-prop.
3. Call dmg pool get-prop and verify that the new label is returned.
4. Try to destroy the pool with the old label. It should fail.
5. Destroy the pool with the new label. Should work.

Skip-unit-tests: true
Test-tag: label_update
Signed-off-by: Makito Kano <makito.kano@intel.com>

### CODE REVIEW

**Review by daltonbohning — APPROVED** [review]
LGTM, but suggested updates:
1. These are vm tests, right? It would be good to add the `vm` tag.
2. Can we add a `pool_label` feature tag to each of these tests to group all tests in this file? I.e. `tags=pool,pool_label`.

**Review by daltonbohning — APPROVED** [review]
LGTM. thanks for updating!

**Comment by shimizukko** [comment]
> LGTM, but suggested updates:
> 
> 1. These are vm tests, right? It would be good to add the `vm` tag.
> 2. Can we add a `pool_label` feature tag to each of these tests to group all tests in this file? I.e. `tags=pool,pool_label`.

Done. Thanks

**Review by dinghwah — APPROVED** [review]
LGTM

**Pull request merged**
