### PR TITLE
DAOS-7172 test: Clean up pool rebuild test

### PR DESCRIPTION
**Pull request by sylviachanoiyee**
Move rebuild tests from ftests/pool to ftests/rebuild
Standardize class names to begin with Rbld for all rebuild tests

Test-tag-vm: pr rebuild
Test-tag-hw-small: pr rebuild
Test-tag-hw-medium: pr rebuild
Test-tag-hw-large: pr rebuild

### CODE REVIEW

**Comment by sylviachanoiyee** [comment]
Failures in cascading_failures, delete_objects and read_array are filed as
https://jira.hpdd.intel.com/browse/DAOS-7801
These are expected to fail in the upcoming weekly as well

**Review by phender — COMMENTED** [review]
Personally I find `RebuildCascadingFailures` easier on the eyes than `RbldCascadingFailures`.  Is there a specific reason for `Rbld` over `Rebuild`?

**Review by shimizukko — APPROVED** [review]

**Comment by shimizukko** [comment]
I also think Rebuild is better than Rbld.

**Comment by sylviachanoiyee** [comment]
I think the avocado naming is very long as is. I want to keep it as brief as possible to avoid truncation in the test result but still meaningful. I'm going to use 4 letters abbreviation for the other components as well and this can be documented in the test plan so I'm not too concerned.

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Comment by phender** [comment]
> I think the avocado naming is very long as is. I want to keep it as brief as possible to avoid truncation in the test result but still meaningful. I'm going to use 4 letters abbreviation for the other components as well and this can be documented in the test plan so I'm not too concerned.
> And all the rebuild results are rolled under FT_rebuild so that itself is clear I think.

If shorter names where a concern then we really didn't need to add `Rbld` to each class name as it just makes the test variant names longer.  The way we handle test names in Jenkins today only the ftest directory name and the file name contribute to the test identification, e.g. `./rebuild/cascading_failures.py`.   The class name and method name only come into play in the naming of the avocado test variant in the artifacts or test report, e.g.:

- https://build.hpdd.intel.com/job/daos-stack/job/daos/job/weekly-testing/185/artifact/Functional%20on%20CentOS%207/rebuild/cascading_failures.py/test-results/1-._rebuild_cascading_failures.py_CascadingFailures.test_simultaneous_failures_container-hosts-pool-rebuild-servers-4c93/
- https://build.hpdd.intel.com/job/daos-stack/job/daos/job/weekly-testing/185/testReport/FTEST_rebuild/CascadingFailures/1___rebuild_cascading_failures_py_CascadingFailures_test_simultaneous_failures_container_hosts_pool_rebuild_servers_e2d9/

In both cases the fact that the test is a rebuild test is already relayed by the test name (directory + filename).

**Pull request merged**
