### PR TITLE
DAOS-6356 TEST: Re-enable test test_evict_bad_server_name

### PR DESCRIPTION
**Pull request by cibervicho**
Now that the system name issue is fixed (DAOS-6375), I noticed
that the '--sys' flag was not used in the 'dmg pool evict' command.
Added this flag in the 'evict_badparam()' function to solve this and
re-enabled the test_evict_bad_server_name test.

Signed-off-by: David Maldonado Moreno <david.maldonado.moreno@intel.com>

### CODE REVIEW

**Comment by cibervicho** [comment]
Tests passed CI checks in both, CentOS and Leap.

CentOS 7:
[2021-03-17T14:41:04.156Z] Running: avocado-2.7 run --ignore-missing-references on --html-job-result on --tap-job-result off --filter-by-tags=pr,-hw --filter-by-tags=poolevict --mux-yaml /tmp/tmpClxt3a/pool-evict_test.yaml -- ./pool/evict_test.py
[2021-03-17T14:41:04.156Z] JOB ID     : 3d44e7c4389733e672f4e7785f22dcc7e705bb27
[2021-03-17T14:41:04.156Z] JOB LOG    : /var/tmp/ftest/avocado/job-results/job-2021-03-17T14.41-3d44e7c/job.log
[2021-03-17T14:42:12.317Z]  (1/3) ./pool/evict_test.py:EvictTests.test_evict;badparams-container-hosts-pool-server_config-0ada:  PASS (59.84 s)
[2021-03-17T14:42:27.220Z]  (2/3) ./pool/evict_test.py:EvictTests.test_evict_bad_server_name;badparams-container-hosts-pool-server_config-0ada:  PASS (22.38 s)
[2021-03-17T14:42:49.202Z]  (3/3) ./pool/evict_test.py:EvictTests.test_evict_bad_uuid;badparams-container-hosts-pool-server_config-0ada:  PASS (21.58 s)
[2021-03-17T14:42:49.202Z] RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

Leap 15:
[2021-03-17T17:37:57.996Z] Running: avocado-2.7 run --ignore-missing-references on --html-job-result on --tap-job-result off --filter-by-tags=pr,-hw --filter-by-tags=poolevict --mux-yaml /tmp/tmpDqdk0o/pool-evict_test.yaml -- ./pool/evict_test.py
[2021-03-17T17:37:57.996Z] JOB ID     : 04d0d7829c579d8ef69d07ec66daf353e5105d82
[2021-03-17T17:37:57.996Z] JOB LOG    : /var/tmp/ftest/avocado/job-results/job-2021-03-17T17.37-04d0d78/job.log
[2021-03-17T17:39:19.542Z]  (1/3) ./pool/evict_test.py:EvictTests.test_evict;badparams-container-hosts-pool-server_config-ab2f:  PASS (70.17 s)
[2021-03-17T17:39:34.624Z]  (2/3) ./pool/evict_test.py:EvictTests.test_evict_bad_server_name;badparams-container-hosts-pool-server_config-ab2f:  PASS (25.70 s)
[2021-03-17T17:40:01.644Z]  (3/3) ./pool/evict_test.py:EvictTests.test_evict_bad_uuid;badparams-container-hosts-pool-server_config-ab2f:  PASS (25.93 s)
[2021-03-17T17:40:01.644Z] RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

Re-pushing to CI without test tags for a complete run.

**Comment by cibervicho** [comment]
CI checks passed and the evict_test completed successfully in both: CentOS7 and Leap15:

CentOS 7:
[2021-03-19T10:50:38.292Z] Running: avocado-2.7 run --ignore-missing-references on --html-job-result on --tap-job-result off --filter-by-tags=pr,-hw --mux-yaml /tmp/tmpvkKVQD/pool-evict_test.yaml -- ./pool/evict_test.py
[2021-03-19T10:50:38.292Z] JOB ID     : cd61d41c2238b7104a5e191153d1065c2fb0d9a2
[2021-03-19T10:50:38.292Z] JOB LOG    : /var/tmp/ftest/avocado/job-results/job-2021-03-19T10.50-cd61d41/job.log
[2021-03-19T10:51:46.258Z]  (1/3) ./pool/evict_test.py:EvictTests.test_evict;badparams-container-hosts-pool-server_config-7139:  PASS (62.96 s)
[2021-03-19T10:52:04.344Z]  (2/3) ./pool/evict_test.py:EvictTests.test_evict_bad_server_name;badparams-container-hosts-pool-server_config-7139:  PASS (19.45 s)
[2021-03-19T10:52:22.527Z]  (3/3) ./pool/evict_test.py:EvictTests.test_evict_bad_uuid;badparams-container-hosts-pool-server_config-7139:  PASS (18.20 s)
[2021-03-19T10:52:22.527Z] RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

Leap 15:
[2021-03-19T14:11:34.655Z] Running: avocado-2.7 run --ignore-missing-references on --html-job-result on --tap-job-result off --filter-by-tags=pr,-hw --mux-yaml /tmp/tmpidNFRI/pool-evict_test.yaml -- ./pool/evict_test.py
[2021-03-19T14:11:34.916Z] JOB ID     : e799058220d4cac028b5bc1acfa74f063b11ed69
[2021-03-19T14:11:34.916Z] JOB LOG    : /var/tmp/ftest/avocado/job-results/job-2021-03-19T14.11-e799058/job.log
[2021-03-19T14:12:42.898Z]  (1/3) ./pool/evict_test.py:EvictTests.test_evict;badparams-container-hosts-pool-server_config-fdcc:  PASS (64.22 s)
[2021-03-19T14:13:09.481Z]  (2/3) ./pool/evict_test.py:EvictTests.test_evict_bad_server_name;badparams-container-hosts-pool-server_config-fdcc:  PASS (26.59 s)
[2021-03-19T14:13:31.429Z]  (3/3) ./pool/evict_test.py:EvictTests.test_evict_bad_uuid;badparams-container-hosts-pool-server_config-fdcc:  PASS (24.95 s)
[2021-03-19T14:13:31.429Z] RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

Adding reviewers.

**Review by shimizukko — DISMISSED** [review]
LGTM

**Comment by cibervicho** [comment]
There are conflicts in the evict_test.py file. Working on that.

**Review by shimizukko — APPROVED** [review]
LGTM

**Review by berserk-fury — APPROVED** [review]

**Comment by cibervicho** [comment]
Merging with latest master in PR#4974 to get Brian's provisioning fix.

**Comment by sylviachanoiyee** [comment]
Changes in the PR is for a test on Functional VM. Both the Centos7 and Leaps15 testing has completed and passed, waiting on Functional hw large. Since it should have no impact on fn hw large testing, will be stopping the job and landing this PR.

**Pull request merged**
