### PR TITLE
DAOS-7592 Test: Removed skip for EC tests.

### PR DESCRIPTION
**Pull request by ravalsam**
Updated the SCM/NVMe size to work with new cluster.

Quick-Functional: true
Test-tag-hw-large: ec_single ec_array

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
EC test results log can be found from Ci https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6317/4/artifact/Functional%20Hardware%20Large/erasurecode/

**Comment by ravalsam** [comment]
Single test failure is not related to this PR. It's an existing failure DAOS-8224.

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Pull request merged**
