### PR TITLE
DAOS-5322 test: Fix OSA reintegration bug.

### PR DESCRIPTION
**Pull request by rpadma2**
Summary: Online Server Reintegration test fails under CI with NOSPACE reported by IOR.
Increasing the pool scm/nvme size to address NOSPACE issue.
Signed-off-by: Padmanabhan <ravindran.padmanabhan@intel.com>

### CODE REVIEW

**Comment by rpadma2** [comment]
DAOS-5306 : Daos Core test failure.
DAOS-5215 : HDF5 failure.

**Comment by rpadma2** [comment]
> Why to reduce the IO load ? May be you can increase the SCM size.
The total space consumed under 2 pool configuration fails. If we have two pools and 20 parallel IO jobs, it is creating nospace issues. Reducing the number of parallel jobs helps to avoid the NOSPACE condition. 
NOTE: When we exclude nodes, it is going to reduce the SCM/NVME size availability by certain percentage. The space will be available only till a reintegration is done. The tests starts the IOR jobs and excludes certain ranks. This will automatically reduce the space available to IOR parallel jobs and we will hit this problem.

**Comment by rpadma2** [comment]
Ok. Now., I understand Samir's question. Ok. Let me try to increase the pool SCM/NVME size and see how it goes. (ie: scm_size to probably 30 GB and NVME size to 200GB).

**Comment by rpadma2** [comment]
Based on discussion with Samir, it is better to keep the workload same and modify the SCM/NVME size and see what is going on. 

Based on my analysis, the problem should be happening only under 2 pool testing.

Started a re-run with doubling the SCM/NVME pool size. 

Based on the calculation (SCM Size required)
================
For one pool
========
aggregation size = ior_block_size * number of slots : 51.xx * 2 = 93.xx MB (for one IOR job). For 10 jobs, it is around 1GB, With RP_2GP1, we need max of 2GB/server. Atleast, we should not see any issue NOSPACE for online reintegration for one pool configuration. (because SCM_SIZE is appx 6GB and NVME size is 54GB).
Total SCM size available is (svcn * scm_size) 4 * 6 = 24GB (seen in the logs) which is correct.
 
For Two pools
==========
When we create two pools, the SCM/NVME size are divided by number of pools. Total SCM/NVME sizes are reduced by half. This can cause issue. 
1st pool aggregation size is appx 2GB. 2nd pool aggregation size is 2GB. (SCM/NVME size under those condition is only 3GB, 27GB). 
Based on the logs, we can see Total SCM size available 12GB for those test condition.
This will definitely cause issue.

**Comment by rpadma2** [comment]
Ok. Now I don't see the NO SPACE issue for the OSA Online reintegration which is good. But, we are encountering the problem mentioned under DAOS-5332 bug. (reintegration command returns success and pool version incremented before Rebuild is complete (rebuild seems to be in scanning state)). Byron is working on PR: https://github.com/daos-stack/daos/pull/3154. Once that is landed, we will once again give it a try.  We may need some fine tuning on the script (to check the Rebuild status along with pool version).

**Comment by rpadma2** [comment]
One Test Failure is known issue:
https://jira.hpdd.intel.com/browse/DAOS-5215 : HDF5 test failure.

**Comment by rpadma2** [comment]
daos-gatekeeper: This PR is ready for merge.

**Comment by jolivier23** [comment]
Can you update the description, if needed?   I don't see any "reduction of parallel jobs" in the actual patch

**Comment by rpadma2** [comment]
> Can you update the description, if needed? I don't see any "reduction of parallel jobs" in the actual patch

Sorry.Based on the review, we decided to keep the parallel jobs same and increase the SCM/NVME size. Updated the description.

**Pull request merged**
