### PR TITLE
DAOS-5338 cli: Remove unnecessary warning in log

### PR DESCRIPTION
**Pull request by ryon-jensen**
A warning was logged when the provided io map is
smaller than what's returned and so is truncated
when returned to user. The user will have the
needed size for the map so the warning is
redundant and filling up logs too much so it's
being removed.

Signed-off-by: Ryon Jensen <ryon.jensen@intel.com>

### CODE REVIEW

**Comment by ryon-jensen** [comment]
> My only questions are should this be a D_DEBUG or return -DER_REC2BIG in this case but I'm not familiar with the code.
After thinking about it more, I think a DEBUG log message would be more noise then helpful. It isn't an error for the allocated memory to be too small in this case so shouldn't return an error.

> Anything that's logging as D_WARN under normal operation is a bug, in fact I'm surprised this hasn't been flagged in CI before.
Good to know :-)

**Comment by ashleypittman** [comment]
> > My only questions are should this be a D_DEBUG or return -DER_REC2BIG in this case but I'm not familiar with the code.
> After thinking about it more, I think a DEBUG log message would be more noise then helpful. It isn't an error for the allocated memory to be too small in this case so shouldn't return an error.

What would be the effect of the user provided data being too small?

> > Anything that's logging as D_WARN under normal operation is a bug, in fact I'm surprised this hasn't been flagged in CI before.
> Good to know :-)

Not so good as it didn't get flagged, but perhaps it only happens with larger message sizes.

**Comment by ryon-jensen** [comment]
> > > My only questions are should this be a D_DEBUG or return -DER_REC2BIG in this case but I'm not familiar with the code.
> > > After thinking about it more, I think a DEBUG log message would be more noise then helpful. It isn't an error for the allocated memory to be too small in this case so shouldn't return an error.
> 
> What would be the effect of the user provided data being too small?
> 
When requesting an I/O map (daos_iom_t) on an object fetch, the user allocates memory for the iom_recxs array and sets iom_nr to the number of elements allocated. While copying the I/O Map from the server to the user allocated array, daos_iom_t.iom_nr_out is set to the number of elements returned by the server. If the user allocated array isn't large enough, it will be filled as much as possible and the user can compare iom_nr_out to iom_nr to determine if the results were truncated or not.

**Comment by ashleypittman** [comment]
> > > > My only questions are should this be a D_DEBUG or return -DER_REC2BIG in this case but I'm not familiar with the code.
> > > > After thinking about it more, I think a DEBUG log message would be more noise then helpful. It isn't an error for the allocated memory to be too small in this case so shouldn't return an error.
> > 
> > 
> > What would be the effect of the user provided data being too small?
> 
> When requesting an I/O map (daos_iom_t) on an object fetch, the user allocates memory for the iom_recxs array and sets iom_nr to the number of elements allocated. While copying the I/O Map from the server to the user allocated array, daos_iom_t.iom_nr_out is set to the number of elements returned by the server. If the user allocated array isn't large enough, it will be filled as much as possible and the user can compare iom_nr_out to iom_nr to determine if the results were truncated or not.

I think I'd probably rather this was a debug message rather than removed entirely.  We're currently seeing this warning once for every read on a trivial well behaved benchmark which isn't what I'd necessarily expect.

**Pull request merged**
