### PR TITLE
DAOS-14568 control: dmg pool query info change targets to ranks

### PR DESCRIPTION
**Pull request by yyyshi**
DAOS-14568 control: dmg pool query info change targets to ranks (https://github.com/daos-stack/daos/pull/13259)
change 'targets' to 'ranks' & fix spell error
Signed-off-by: shiying [yshi1210@gmail.com](mailto:yshi1210@gmail.com)

### CODE REVIEW

**Comment by knard-intel** [comment]
@yyyshi , I have created a new PR as it seems to not yet be able to run the CI without being from Intel: creating a PR from a branch of the official repo.

**Comment by knard-intel** [comment]
It seems to not be possible to launch the Intel CI with this PR.
I have created a new one which will allowed to launch the Intel CI.
https://github.com/daos-stack/daos/pull/13298

**Comment by yyyshi** [comment]
> It seems to not be possible to launch the Intel CI with this PR. I have created a new one which will allowed to launch the Intel CI. #13298

hi, knard, what should I do to make this PR come to landed? I am not very familiar with this process

**Comment by knard-intel** [comment]
> > It seems to not be possible to launch the Intel CI with this PR. I have created a new one which will allowed to launch the Intel CI. #13298
> 
> @knard-intel hi, knard, what should I do to make this PR come to landed? I am not very familiar with this process, thanks

@yyyshi, From my understanding, this PR could not be landed because it is not yet possible for external contributor to run the full CI.  This is why I created the new PR https://github.com/daos-stack/daos/pull/13298.  This allowed me to fix some unit tests and pass the CI.  This last PR should be landed soon as all the requirements are completed (CI validation, reviewers validation, etc.).

Finally, @mjmac should be more aware on the way for non intel contributors to land their PRs.

**Comment by yyyshi** [comment]
> > > It seems to not be possible to launch the Intel CI with this PR. I have created a new one which will allowed to launch the Intel CI. #13298
> > 
> > 
> > @knard-intel hi, knard, what should I do to make this PR come to landed? I am not very familiar with this process, thanks
> 
> @yyyshi, From my understanding, this PR could not be landed because it is not yet possible for external contributor to run the full CI. This is why I created the new PR #13298. This allowed me to fix [510f857](https://github.com/daos-stack/daos/commit/510f85757388070a739e9fc16c6bf38fb1da3564) some unit tests and pass the CI. This last PR should be landed soon as all the requirements are completed (CI validation, reviewers validation, etc.).
> 
> Finally, @mjmac should be more aware on the way for non intel contributors to land their PRs.

@mjmac hello, Could you provide some guidance when you have time, thanks

**Pull request closed without merging**
