### PR TITLE
Revert "DAOS-3415 control: spdk setup no chmod as root (#1192)"

### PR DESCRIPTION
**Pull request by ravalsam**
This reverts commit 911ad23405b93fd010ce66f0d71d2cadc85c17b8.

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Comment by tanabarr** [comment]
I should have a PR to fix this shortly in case you want to land that rather than a revert

**Comment by ravalsam** [comment]
> I should have a PR to fix this shortly in case you want to land that rather than a revert

I am ok with it. Can you verify it locally as well to make sure it works for both case (root//non-root user)

**Comment by tanabarr** [comment]
https://github.com/daos-stack/daos/pull/1288 resolves the bug

**Comment by ravalsam** [comment]
Closing this revert

**Pull request closed without merging**
