### PR TITLE
DAOS-11868 build: Remove --with-rdma configure option from SPDK build

### PR DESCRIPTION
**Pull request by tanabarr**
Remove unnecessary --with-rdma configure option.

PR-repos: spdk@PR-51

Required-githooks: true

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficent testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by brianjmurrell — COMMENTED** [review]
While I have no opinion or understanding on whether this flag is actually needed or not for some/all fabrics perhaps, the syntax of the code change LGTM.

Since it is such a simple code change and the much bigger question is whether this option can actually safely be removed **and** always building without this option will still work on all fabrics, I will leave it to others more expert in that than me to leave +1s here.

If on the other hand, this option may be necessary for some fabrics but breaks the build on others, we will have to find a more build-time way of specifying whether to use this flag or not.

**Comment by tanabarr** [comment]
> While I have no opinion or understanding on whether this flag is actually needed or not for some/all fabrics perhaps, the syntax of the code change LGTM.
> 
> Since it is such a simple code change and the much bigger question is whether this option can actually safely be removed **and** always building without this option will still work on all fabrics, I will leave it to others more expert in that than me to leave +1s here.
> 
> If on the other hand, this option may be necessary for some fabrics but breaks the build on others, we will have to find a more build-time way of specifying whether to use this flag or not.

AFAIK this option is not required by any of the fabrics and can safely be removed, @NiuYawei and @mchaarawi  could you please confirm?

**Review by jolivier23 — APPROVED** [review]

**Comment by jolivier23** [comment]
Do we use this option in the RPM build ?

**Comment by tanabarr** [comment]
> Do we use this option in the RPM build ?

That is what https://github.com/daos-stack/spdk/pull/51 addresses, which should be landed at the same time as this..

**Comment by tanabarr** [comment]
Gatekeeper: Please land SPDK packaging PR https://github.com/daos-stack/spdk/pull/51 shortly before or after landing this PR. https://github.com/daos-stack/spdk/pull/51 is using the new test workflow for packaging and as such has run various tests against different DAOS branches.

**Review by NiuYawei — APPROVED** [review]

**Pull request merged**
