### PR TITLE
DAOS-5488 test: shrink the swim timeout for aggregation tests

### PR DESCRIPTION
**Pull request by dmiter**
Try to increase the swim timeout to allow aggregation tests pass.

### CODE REVIEW

**Comment by liuxuezhao** [comment]
To "workaround" DAOS-5488, it need to decrease the SWIM timeout (make it faster to detect node failure) right? this patch increases it?

**Comment by dmiter** [comment]
Sorry, I was thinking about wrong timeout.

**Review by Nasf-Fan — COMMENTED** [review]
For DA0S-5488, my understand is that the vos aggregation was triggered too early as to some non-committed DTX entry (but could be committed) was removed by the vos aggregation. So the expected behavior is to postpone the vos aggregation. That requires to increase the "DAOS_AGG_THRESHOLD".

**Review by sylviachanoiyee — APPROVED** [review]

**Comment by dmiter** [comment]
Don't need any more.

**Pull request closed without merging**
