### PR TITLE
DAOS-12227 cart: Fix Coverity CID-840053

### PR DESCRIPTION
**Pull request by knard-intel**
# Description

Fix illegal memory access to cart rpc structure.

From my understanding of the Coverity issue [CID-840053](https://coverityent.devtools.intel.com/prod8/reports.htm#v19571/p10828/fileInstanceId=35085004&defectInstanceId=4908399148&mergedDefectId=840053); a double free could happen if the `req->cr_ctx` given as parameter is `NULL`.

From my understanding of the ticket [DAOS-5254](https://github.com/daos-stack/daos/pull/3475); in the other situation, two free are needed to manage `RPC_ADDREF` done in the function and previously in Mercury related code or in the `crt_corpc_req_hdlr()` function.

# Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

# Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by knard-intel** [comment]
pylint errors are unrelated to this PR.
Do not understand why they are not ignored.

**Review by johannlombardi — DISMISSED** [review]

**Comment by johannlombardi** [comment]
@frostedcmos please inspect. This a 2.4 blocker.

**Review by frostedcmos — DISMISSED** [review]

**Comment by frostedcmos** [comment]
As a note, practically it is not possible to get to this point in the code with req->cr_ctx being null. This is being flagged/hit due to us making extra sanity check on line 1397, which should probably be just an assert instead

**Comment by knard-intel** [comment]
> As a note, practically it is not possible to get to this point in the code with req->cr_ctx being null. This is being flagged/hit due to us making extra sanity check on line 1397, which should probably be just an assert instead

From issue, no issue to convert the extra sanity check on line 1397 in an assert.
Just tell me what you prefer as both solution seems reasonable.

**Comment by frostedcmos** [comment]
> From my side, no issue to convert the extra sanity check on line 1397 in an assert.
> Just tell me what you prefer as both solution seems reasonable.

it's fine as is now, thanks:)

**Comment by knard-intel** [comment]
> > From my side, no issue to convert the extra sanity check on line 1397 in an assert.
> > Just tell me what you prefer as both solution seems reasonable.
> 
> it's fine as is now, thanks:)

Afterthought, I am going to change my patch to an assert as you suggested.
Indeed, I do not wat to add extra dead/useless code.
Thanks a lot for your feedback.

**Review by frostedcmos — APPROVED** [review]

**Review by johannlombardi — APPROVED** [review]

**Pull request merged**
