### PR TITLE
DAOS-12611 build: Add protobufc dependency to tests.

### PR DESCRIPTION
**Pull request by ashleypittman**
We had a hidden dependency here that was not specificially called out.

Required-githooks: true

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
The other issue this caught is the daos_build test is failing as a result of this.  This PR will fix that but the intention is that the protobuf-c-devel package is installed on the test nodes, @brianjmurrell I remember this discussion before but what's the best way to get daos dependencies installed on those nodes?

**Comment by brianjmurrell** [comment]
> The other issue this caught is the daos_build test is failing as a result of this. This PR will fix that but the intention is that the protobuf-c-devel package is installed on the test nodes, @brianjmurrell I remember this discussion before but what's the best way to get daos dependencies installed on those nodes?

Test dependencies should be added to an appropriate RPM (and debian) sub-package as a `Requires:` or `Depends:` respectively.

As I fix up our packaging and other various issues in order to get Ubuntu testing in CI, I am adding some of these dependencies.  Ultimately [ci/functional/required_packages.sh](https://github.com/daos-stack/daos/blob/master/ci/functional/required_packages.sh) and and hopefully [ci/unit/required_packages.sh](https://github.com/daos-stack/daos/blob/master/ci/unit/required_packages.sh) should go away, although for the latter, perhaps it might be more difficult as it's really for non-RPM build testing.

**Review by daltonbohning — COMMENTED** [review]
> The other issue this caught is the daos_build test is failing as a result of this. This PR will fix that but the intention is that the protobuf-c-devel package is installed on the test nodes

I think we should run that test to verify this PR fixes it

**Comment by phender** [comment]
> > The other issue this caught is the daos_build test is failing as a result of this. This PR will fix that but the intention is that the protobuf-c-devel package is installed on the test nodes
> 
> I think we should run that test to verify this PR fixes it

The testing so far in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11429/3/testReport/ has verified that the change doesn't beak the cart tests, so we could probably just kick off a run manually using Build with Parameters, skipping Unit Tests and using TestTag = DaosBuild.

**Comment by phender** [comment]
> Test dependencies should be added to an appropriate RPM (and debian) sub-package as a `Requires:` or `Depends:` respectively.

Is this something that's being addressed in a separate PR or should it be done here?

**Comment by brianjmurrell** [comment]
> Is this something that's being addressed in a separate PR or should it be done here?

It should be done here please.

**Comment by ashleypittman** [comment]
> > The other issue this caught is the daos_build test is failing as a result of this. This PR will fix that but the intention is that the protobuf-c-devel package is installed on the test nodes
> 
> I think we should run that test to verify this PR fixes it

https://github.com/daos-stack/daos/pull/10989 is a PR that updates the test to checkout this branch for testing and that's passed so I think we can say this fixes it.

**Comment by ashleypittman** [comment]
> > Is this something that's being addressed in a separate PR or should it be done here?
> 
> It should be done here please.

The build (and therefore the test) should work with the package if available or build from source if not so the package is not truly required and will not be until we remove the logic to download protobuf which is when we finally remove el7 support.  I can push a PR to add this to the rpm depends but until this PR lands I'm once again blocked for dfuse development so do not want to delay this essential bug-fix.

**Review by daltonbohning — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
