### PR TITLE
DAOS-10379 test: re-enable test_rebuild_with_container_rf

### PR DESCRIPTION
**Pull request by wangshilong**
Original engine stop issues are likely fixed by DAOS-10051,
enable the test again.

Test-tag: rebuild_container_rf
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

### CODE REVIEW

**Review by dinghwah — APPROVED** [review]
LGTM

**Review by daltonbohning — APPROVED** [review]

**Comment by jolivier23** [comment]
The test didn't run because it's in the skip-list under DAOS-10051

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Need to summbit an empty commit with DAOS-10051[space] and the test tag so it doesn't get skipped via skip-list.

**Comment by jolivier23** [comment]
See https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9004/1/testReport/FTEST_rebuild/RbldContRfTest/

**Pull request merged**
