### PR TITLE
DAOS-4018 control: stop from harness

### PR DESCRIPTION
**Pull request by tanabarr**
Rather than issuing KillRank dRPC to I/O Server to terminate the process,
send kill signal (SIGTERM normally and SIGKILL if force command option
is set) from the daos_server harness that manages the I/O Server
instances.

- remove kill rank drpc caller, handler, proto defns and plumbing
- add force param to instance runner Stop() and use it to decide signal
- rename KillRanks to StopRanks to align with command name

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Comment by tanabarr** [comment]
force shutdown (`dmg system stop --force`) implemented from harness (sends SIGKILL), we can see `daos_fini()` is not called:
```
01/24-11:33:10.44 wolf-72 DAOS[252658/252669] daos INFO src/iosrv/drpc_progress.c:295 drpc_handler_ult() dRPC handler ULT for module=2 method=218
01/24-11:33:10.44 wolf-72 DAOS[252658/252669] mgmt INFO src/mgmt/srv_drpc.c:76 ds_mgmt_drpc_prep_shutdown() Received request to prep shutdown 0
01/24-11:33:10.44 wolf-72 DAOS[252658/252669] mgmt INFO src/mgmt/srv_drpc.c:84 ds_mgmt_drpc_prep_shutdown() Service rank 0 is being prepared for controlled shutdown
01/24-11:33:10.44 wolf-72 DAOS[252658/252670] daos INFO src/iosrv/drpc_progress.c:409 process_session_activity() Session 615 connection has been terminated
01/24-11:33:10.44 wolf-72 DAOS[252658/252670] daos INFO src/common/drpc.c:664 drpc_close() Closing dRPC socket fd=615
```
normal shutdown (`dmg system stop`) sends SIGTERM and allows daos to attempt to shutdown gracefully. In the below example CART errors prevent `daos_fini()` from completing successfully:
```
01/24-11:28:19.91 wolf-72 DAOS[252658/252658] server INFO src/iosrv/init.c:602 server_fini() Service is shutting down
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rsvc DBUG src/rsvc/srv.c:799 stop() daos_server: stopping
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rdb  DBUG src/rdb/rdb_raft.c:2503 rdb_raft_resign() 64616f73[0]: resigning from term 0
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rdb  WARN src/rdb/rdb_raft.c:1648 rdb_raft_step_down() 64616f73[0]: no longer leader of term 0
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rsvc DBUG src/rsvc/srv.c:531 rsvc_step_down_cb() daos_server: stepping down from 0
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rsvc DBUG src/rsvc/srv.c:396 change_state() daos_server: term 0 state UP to DRAINING
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rsvc DBUG src/rsvc/srv.c:554 rsvc_step_down_cb() daos_server: waiting for 1 leader refs
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rdb  DBUG src/rdb/rdb.c:339 rdb_stop() 64616f73[0]: stopping db 0x7f8fdf4f8b80
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rdb  DBUG src/rdb/rdb_raft.c:1463 rdb_compactd() 64616f73[0]: compactd stopping
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rdb  DBUG src/rdb/rdb_raft.c:1957 rdb_timerd() 64616f73[0]: timerd stopping
01/24-11:28:19.91 wolf-72 DAOS[252658/252669] rdb  DBUG src/rdb/rdb_rpc.c:387 rdb_recvd() 64616f73[0]: recvd stopping
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] swim INFO src/swim/swim.c:635 swim_progress() 0: dping 0 => 1
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] swim INFO src/swim/swim.c:73 swim_dump_updates() 0 => 1: {1 S 0} {0 A 0}
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] rpc  DBUG src/cart/crt_register.c:215 crt_opc_lookup() looking up opcode: 0xfe000000
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # NA -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/na/na_ofi.c:2614
 # na_ofi_cq_read(): fi_cq_readerr() got err: 5(Input/output error), prov_errno: -5(Input/output error)
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # NA -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/na/na_ofi.c:4358
 # na_ofi_progress(): Could not read events from context CQ
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # HG -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/mercury_core.c:3041
 # hg_core_progress_na_cb(): Could not make progress on NA
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # HG Util -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/util/mercury_poll.c:581
 # hg_poll_wait(): poll cb failed
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # HG -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/mercury_core.c:3282
 # hg_core_progress_poll(): hg_poll_wait() failed
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # HG -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/mercury_core.c:4879
 # HG_Core_progress(): Could not make progress
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  src/cart/crt_hg.c:1369 crt_hg_progress() HG_Progress failed, hg_ret: 6.
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] rpc  ERR  src/cart/crt_context.c:1255 crt_progress() crt_hg_progress failed, rc: -1020.
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] server ERR  src/iosrv/srv.c:469 dss_srv_handler() failed to progress CART context: -1020
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # NA -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/na/na_ofi.c:2614
 # na_ofi_cq_read(): fi_cq_readerr() got err: 5(Input/output error), prov_errno: -5(Input/output error)
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # NA -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/na/na_ofi.c:4358
 # na_ofi_progress(): Could not read events from context CQ
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # HG -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/mercury_core.c:3041
 # hg_core_progress_na_cb(): Could not make progress on NA
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # HG Util -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/util/mercury_poll.c:581
 # hg_poll_wait(): poll cb failed
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # HG -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/mercury_core.c:3282
 # hg_core_progress_poll(): hg_poll_wait() failed
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  # HG -- Error -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/mercury_core.c:4879
 # HG_Core_progress(): Could not make progress
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] hg   ERR  src/cart/crt_hg.c:1369 crt_hg_progress() HG_Progress failed, hg_ret: 6.
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] rpc  ERR  src/cart/crt_context.c:1255 crt_progress() crt_hg_progress failed, rc: -1020.
01/24-11:28:20.67 wolf-72 DAOS[252658/252669] server ERR  src/iosrv/srv.c:469 dss_srv_handler() failed to progress CART context: -1020
01/24-11:28:21.67 wolf-72 DAOS[252658/252669] rpc  ERR  src/cart/crt_context.c:805 crt_context_timeout_check(0x7f8fdf481d60)  [opc=0xfe000000 xid=0x34f rank:tag=1:0] ctx_id 0, (status: 0x38) timed out, tgt rank 1, tag 0
01/24-11:28:21.67 wolf-72 DAOS[252658/252669] rpc  ERR  src/cart/crt_context.c:763 crt_req_timeout_hdlr(0x7f8fdf481d60)  [opc=0xfe000000 xid=0x34f rank:tag=1:0] aborting to group daos_server, rank 1, tgt_uri (null)
01/24-11:28:21.67 wolf-72 DAOS[252658/252669] hg   WARN # NA -- Warning -- /home/tanabarr/projects/daos_m/_build.external/mercury/src/na/na_ofi.c:4454
 # na_ofi_cancel(): fi_cancel() failed, rc: -2(No such file or directory)
01/24-11:28:21.67 wolf-72 DAOS[252658/252669] hg   ERR  src/cart/crt_hg.c:1156 crt_hg_req_send_cb(0x7f8fdf481d60)  [opc=0xfe000000 xid=0x34f rank:tag=1:0] RPC failed; rc: -1011
```

**Comment by johannlombardi** [comment]
Could you please paste there a meaningful commit message?

**Comment by johannlombardi** [comment]
ping

**Comment by tanabarr** [comment]
gatekeeper please use PR description for commit message

**Pull request merged**
