### PR TITLE
DAOS-623 build: Build static libdts instead

### PR DESCRIPTION
**Pull request by jolivier23**
I still can't explain why this caused bug with rpm installed
but this seems to address the issue.  Regardless, the server side
tests should not be linking with libdaos.so implicitely.
Addtional changes:
1. No need to not build crt_launch based on mpi or use mpi environment
2. Remove CPPPATH for src/include/daos.  All headers should use
   daos/[header] anyway.

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

Required-githooks: true
Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

### CODE REVIEW

**Comment by jolivier23** [comment]
@ashleypittman I pulled in your PR to fix the mpi issue.

**Review by ashleypittman — APPROVED** [review]

**Comment by jolivier23** [comment]
thoughts on landing this one?   The failure is in a test that doesn't use libdts

**Comment by ashleypittman** [comment]
I would really like to see this landed.

**Comment by jolivier23** [comment]
@johannlombardi ?

**Review by johannlombardi — APPROVED** [review]

**Pull request merged**
