### PR TITLE
DAOS-9065 Build: Fix daos.spec for SUSE

### PR DESCRIPTION
**Pull request by JohnMalmberg**
Fix a libpmemobj1 dependency for SUSE.

Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

### CODE REVIEW

**Review by jolivier23 — DISMISSED** [review]

**Review by daltonbohning — DISMISSED** [review]

**Review by brianjmurrell — APPROVED** [review]
@JohnMalmberg There was a question about the urgency of this issue WRT to 2.0.  My last impression was that you found something else that you suspected was being caused by this issue, is that right?  And so once you fixed that other issue this one was no longer causing you any problems?

**Comment by JohnMalmberg** [comment]
This issue is currently more of a cosmetic issue than a blocking issue, but if it shows up at a customer site it will cause confusion about what the actual problem is.

**Comment by brianjmurrell** [comment]
> if it shows up at a customer site it will cause confusion about what the actual problem is.

Agreed.  But in my testing I couldn't get it to actually cause a problem.  I did most testing with DNF however as I'm not terribly familiar with Zypper.

**Review by brianjmurrell — APPROVED** [review]

**Review by frostedcmos — APPROVED** [review]

**Review by daltonbohning — APPROVED** [review]

**Comment by JohnMalmberg** [comment]
This fix was has been merged in from another PR.

**Pull request closed without merging**
