### PR TITLE
DAOS-15417 build: use meson install --destdir 

### PR DESCRIPTION
**Pull request by daltonbohning**
Features: dfuse

Workaround a bug with meson install not using the --prefix from
configure by using:
meson configure --prefix=/
meson install --destdir

Require meson>=0.47 for the --destdir option.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by daltonbohning** [comment]
@ashleypittman @jolivier23 Any idea here?
It is correctly installing to the prefix, so the fact that this is breaking now suggests master is probably doing the wrong thing. I.e. installing to /usr instead of the prefix.

https://github.com/daos-stack/daos/actions/runs/8206092304/job/22444411626
```
#25 294.8 Installing lib/libfuse3.so.3.16.2 to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/lib64
#25 294.8 Installing lib/libfuse3.a to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/lib64
#25 294.8 Installing /home/daos/pre/build/external/release/fuse/include/fuse.h to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/include/fuse3
#25 294.8 Installing /home/daos/pre/build/external/release/fuse/include/fuse_common.h to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/include/fuse3
#25 294.8 Installing /home/daos/pre/build/external/release/fuse/include/fuse_lowlevel.h to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/include/fuse3
#25 294.8 Installing /home/daos/pre/build/external/release/fuse/include/fuse_opt.h to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/include/fuse3
#25 294.8 Installing /home/daos/pre/build/external/release/fuse/include/cuse_lowlevel.h to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/include/fuse3
#25 294.8 Installing /home/daos/pre/build/external/release/fuse/include/fuse_log.h to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/include/fuse3
#25 294.8 Installing /home/daos/pre/build/external/release/fuse.build/libfuse_config.h to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/include/fuse3
#25 294.8 Installing /home/daos/pre/build/external/release/fuse.build/meson-private/fuse3.pc to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/lib64/pkgconfig
#25 294.8 Installing symlink pointing to libfuse3.so.3.16.2 to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/lib64/libfuse3.so.3
#25 294.8 Installing symlink pointing to libfuse3.so.3 to /opt/daos/prereq/release/fuse/opt/daos/prereq/release/fuse/lib64/libfuse3.so
#25 294.9 Checking targets for component 'fuse'
#25 294.9 Checking for C header file fuse3/fuse.h... no
#25 294.9 MissingTargets: fuse has missing targets after build.  See config.log for details:
```

**Comment by daltonbohning** [comment]
Sorry, need to resolve pylint :(

**Comment by daltonbohning** [comment]
Ready for review

**Comment by ashleypittman** [comment]
This could be closed in preference for https://github.com/daos-stack/daos/pull/14017

**Pull request closed without merging**
