### PR TITLE
DAOS-5807 tests: enable test_osa_online_reintegration

### PR DESCRIPTION
**Pull request by Nasf-Fan**
Related issue should have been fixed via the patch PR#4135.

Signed-off-by: Fan Yong <fan.yong@intel.com>

### CODE REVIEW

**Comment by Nasf-Fan** [comment]
Restart the tests for the 2nd cycle verification.

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Comment by Nasf-Fan** [comment]
Re-trigger the test for the 3rd cycle verifications.

**Comment by rpadma2** [comment]
I am seeing an issue the rebuild. Getting data loss error (2026). Created ticket : https://jira.hpdd.intel.com/browse/DAOS-6439
I think we should not enable the test without addressing DAOS-6439.

**Review by rpadma2 — CHANGES_REQUESTED** [review]
I am seeing an issue under rebuild. Getting data loss error (2026). Created ticket : https://jira.hpdd.intel.com/browse/DAOS-6439
I think we should not enable the test without addressing DAOS-6439.

**Comment by Nasf-Fan** [comment]
> https://jira.hpdd.intel.com/browse/DAOS-6439

I made a patch https://github.com/daos-stack/daos/pull/4229, hope to fix related issue of data lost during rebuild.

**Comment by Nasf-Fan** [comment]
Rebase the patch with the fixes from PR#4135 and PR#4229.

**Comment by Nasf-Fan** [comment]
Not need it any longer.

**Pull request closed without merging**
