### PR TITLE
DAOS-623 ci: Remove build stages duplicted in GHA

### PR DESCRIPTION
**Pull request by brianjmurrell**
To make more room in the Jenkinsfile for other required stages.

Force Leap RPM test stage to use 15.2 so that we have coverage for that
platform when we move main testing to Leap 15.3.  Until then the change
is a NOOP as 15.2 is the currently used platform.

### CODE REVIEW

**Comment by ashleypittman** [comment]
I notice this leaves in "Build on CentOS 7" which is the longest build we have by about 7 minutes, is there any scope for removing that as well?

**Comment by brianjmurrell** [comment]
> I notice this leaves in "Build on CentOS 7" which is the longest build we have by about 7 minutes, is there any scope for removing that as well?

There is not unfortunately.  The product from that is used for the UT stages.

**Review by daltonbohning — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
Let's check in gatekeeping if we should get this landed

**Comment by brianjmurrell** [comment]
> Let's check in gatekeeping if we should get this landed

I've removed @daos-stack/daos-gatekeeper from this PR.  The changes here are incorporated into a much more important PR that is in hardware testing right now and if successful, and passes review, I hope to get landed today, if not this morning.

**Review by jolivier23 — APPROVED** [review]

**Comment by brianjmurrell** [comment]
Landed in 85fdd30736c2672eb123b1ddc12e78bc0a54ea39

**Pull request closed without merging**
