### PR TITLE
DAOS-14338 object: create migrate container in all cases

### PR DESCRIPTION
**Pull request by wangdi1**
Since exclude/drain might change the shard location as well, so let's create the container for all casing during migration.

Features: rebuild ec
Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by liuxuezhao — DISMISSED** [review]

**Review by ryon-jensen — APPROVED** [review]
Looks good to me.

**Comment by wangdi1** [comment]
Saw this failure in 2.4 version test,  so may need update this PR a bit.


Sep 13 05:44:02 wolf-202.wolf.hpdd.intel.com daos_server[424080]: ERROR: daos_engine:1 09/13-05:44:02.19 wolf-202 DAOS[424935/7/58952] pool EMRG src/pool/srv_target.c:405 pool_child_delete_one() Assertion 'd_list_empty(&child->spc_cont_list)' failed
05:49:04 INFO |     Sep 13 05:44:02 wolf-202.wolf.hpdd.intel.com daos_server[424080]: ERROR: daos_engine:1 daos_engine: src/pool/srv_target.c:405: pool_child_delete_one: Assertion `0' failed.

**Review by ryon-jensen — APPROVED** [review]

**Review by liuxuezhao — APPROVED** [review]

**Review by gnailzenh — APPROVED** [review]

**Comment by wangdi1** [comment]
Update the commit message to add allow-unstable-test: true for running all ec + rebuild test. The last test failure are unrelated with this PR. (pool destroy timeout).

**Comment by wangdi1** [comment]
Failure in Functional Medium test is due to DAOS-14242, unrelated with this PR.

**Comment by wangdi1** [comment]
Another failure in hardware Large test is DAOS-14320. unrelated with this PR as well.

**Pull request merged**
