### PR TITLE
DAOS-6961-test2: Pool rebuild test scripts update work around for DAOS-6865

### PR DESCRIPTION
**Pull request by dinghwah**
DAOS-6961-test: Pool rebuild test scripts update work around for DAOS-6865
Updated: pool/rebuild_tests.py
         pool/rebuild_tests.yaml
Skip-unit-tests: true
Skip-nlt: true
Test-tag-vm: pr,-hw rebuildmulti rebuildsimple
Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

### CODE REVIEW

**Review by shimizukko — DISMISSED** [review]
LGTM

**Review by shimizukko — APPROVED** [review]
LGTM

**Review by saurabhtandan — APPROVED** [review]
There are 3 rebuild test failures. They need to be either resolved or skipped with appropriate ticket before merging.
==> the 3 failures were only on Leap 15 which were passed before, we can open  DAOS-7075  to track for it.

**Comment by sylviachanoiyee** [comment]
I cannot land this if the pool rebuild tests are failing on Leap15 because it will impact PR/master testing stability.
If the 3 failures are consistent on the 3 pool rebuild variants, maybe disable them?

**Comment by dinghwah** [comment]
Worked with Di, the 3 failures from Leap 15 seems intermittent on VM, options to increase core# per vm. Discussed with John about the vm core#, currently, we are not able to increase the core # on the vm.  The second option is to remerge with master and push PR with regular test-Tag.   All rebuild tests are passed on (1)Leap-15 and (2)CentOS7.
(1)https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5026/5/artifact/Functional%20on%20Leap%2015/pool/rebuild_tests.py/
(2)https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5026/5/artifact/Functional%20on%20CentOS%207/pool/rebuild_tests.py/

**Pull request merged**
