### PR TITLE
DAOS-4419 dfuse: Reenable dfuse caching and get_attr.

### PR DESCRIPTION
**Pull request by ashleypittman**
Re-enable this code, and fix some issues on error paths.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
I've triggered a build with the daily_regression flag which should run the fio tests.

**Review by bfaccini — APPROVED** [review]
You could have simply reverted Johann's commit "d42d405331 DAOS-7671 dfuse: temporarily disable get_attr (#5838)" !!...

**Comment by ashleypittman** [comment]
> You could have simply reverted Johann's commit "d42d405331 DAOS-7671 dfuse: temporarily disable get_attr (#5838)" !!...

Yes, but during this process we've found some error codes which are either wrong or not logged properly so I've taken the opportunity to fix them as well.

**Comment by ashleypittman** [comment]
There looks to be an error with this and it's not reading the times properly, investigating.

**Comment by ashleypittman** [comment]
Only error handling/logging left in this one now but I'd still like to land it.

**Review by bfaccini — DISMISSED** [review]

**Review by jolivier23 — APPROVED** [review]

**Review by johannlombardi — APPROVED** [review]

**Review by bfaccini — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]
Is this ready to land or are we still stuck due to some issue at customer site?   Marking approved for now to clear gatekeeper.  Add it back if it's ready to go.

**Pull request merged**
