### PR TITLE
DAOS-13772 test: Bump system_ram_reserved for test_rf_pool_property

### PR DESCRIPTION
**Pull request by tanabarr**
Increase system_ram_reserved server config file parameter to ensure
that sufficient memory is reserved for system usage before allocating
to engine RAM-disks. This should avoid control-plane memory check
failures during the test.

Required-githooks: true

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by knard-intel — APPROVED** [review]

**Review by kjacque — APPROVED** [review]
Seems reasonable to me. Are there more tests that will be hit by this? Do we need to update all of them?

**Comment by tanabarr** [comment]
> Seems reasonable to me. Are there more tests that will be hit by this? Do we need to update all of them?

Not that I know of, when landing the PR that introduced the auto-sizing ran with one of the wider Pragmas to try to catch as many instances as possible and adjusted many ftest yamls. I Guess as tests are added and changed we may need to tune the relevant configs.

**Comment by kjacque** [comment]
@tanabarr I wonder if this is possibly an indication that the default is too small, if our tests are constantly colliding with it.

**Comment by tanabarr** [comment]
> @tanabarr I wonder if this is possibly an indication that the default is too small, if our tests are constantly colliding with it.

A small subsection of tests are occasionally colliding with it IMO, there is a tweak to the algorithm in an in-progress PR (which you have approved): https://github.com/daos-stack/daos/pull/12430 but there is not a magic number that will work in every case (that's why it's a tunable) so I'm working on it in an iterative fashion to move towards a sensible compromise. The level of variability of workloads and associated memory footprints across CI is high and so we are seeing some outliers which require specific training. This is a good thing IMO as it mimics what we will see "in the wild" and is shaping how we provide the ability to tune.

**Comment by kjacque** [comment]
> A small subsection of tests are occasionally colliding with it IMO, there is a tweak to the algorithm in an in-progress PR (which you have approved): #12430 but there is not a magic number that will work in every case (that's why it's a tunable) so I'm working on it in an iterative fashion to move towards a sensible compromise. The level of variability of workloads and associated memory footprints across CI is high and so we are seeing some outliers which require specific tuning. This is a good thing IMO as it mimics what we will see "in the wild" and is shaping how we attempt to estimate the value and understanding of when we need to tune with a custom value. Over estimating the reservation value will result in wastage of available resources and limit the performance of DAOS.

Fair points. Just wanted to ensure we were thinking about this. I am a little curious how we expect the users to measure this or diagnose if DAOS gets overzealous. Doesn't need to be addressed now, but it will be interesting to see once we start getting user feedback on this issue.

**Comment by tanabarr** [comment]
> > A small subsection of tests are occasionally colliding with it IMO, there is a tweak to the algorithm in an in-progress PR (which you have approved): #12430 but there is not a magic number that will work in every case (that's why it's a tunable) so I'm working on it in an iterative fashion to move towards a sensible compromise. The level of variability of workloads and associated memory footprints across CI is high and so we are seeing some outliers which require specific tuning. This is a good thing IMO as it mimics what we will see "in the wild" and is shaping how we attempt to estimate the value and understanding of when we need to tune with a custom value. Over estimating the reservation value will result in wastage of available resources and limit the performance of DAOS.
> 
> Fair points. Just wanted to ensure we were thinking about this. I am a little curious how we expect the users to measure this or diagnose if DAOS gets overzealous. Doesn't need to be addressed now, but it will be interesting to see once we start getting user feedback on this issue.

As we move from MD-on-SSD phase I -> phase II the use of RAM-disk (pressure) will also change so we will need to evolve anyhow. The obvious thing that indicates system_ram_reserved needs increasing is OOM killer, and we obviously don't want that to happen but there are many factors that will affect the usage and at the moment we can't factor all of them into the calculation.

**Pull request merged**
