### PR TITLE
Use latest version of go on rocky.

### PR DESCRIPTION
**Pull request by ashleypittman**
Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
@mjmac what do you think of this?  I don't think it's a hard requirement but it would bring our docker builds in-line with our Jenkins ones.  If you think this is a good idea I can apply the same change to our other dockerfiles, and I'm not sure of we should use the GO_BIN env var or not.  There's a minor currently where the output says checking $PATH however scons does not use PATH without this patch.

**Comment by mjmac** [comment]
Overall I'm not crazy about having another set of files to maintain in order to keep us building with the latest version. Why can't we use the internal repos to pull the go RPMs that I made?

For the record, the primary requirement is that we use the latest go version to build RPMs for distribution externally, in order to satisfy SDL concerns about hypothetical CVE issues in the runtime. I'm not opposed to having parity across all of the build environments, and ultimately think it would be ideal. I just don't want to impose undue burden in order to achieve that goal.

**Comment by ashleypittman** [comment]
> Overall I'm not crazy about having another set of files to maintain in order to keep us building with the latest version. Why can't we use the internal repos to pull the go RPMs that I made?

We really have two build processes, the rpm process and the docker process, rpms are used for distribution as you say but we use docker elsewhere in CI.

> For the record, the primary requirement is that we use the latest go version to build RPMs for distribution externally, in order to satisfy SDL concerns about hypothetical CVE issues in the runtime. I'm not opposed to having parity across all of the build environments, and ultimately think it would be ideal. I just don't want to impose undue burden in order to achieve that goal.

Yes, that's what I meant by I don't think this is required - it really was just to see if you felt that having parity was worth the additional cost of having the version maintained somewhere else.

**Comment by mjmac** [comment]
> We really have two build processes, the rpm process and the docker process, rpms are used for distribution as you say but we use docker elsewhere in CI.

Understood. I'm asking why the docker process can't use the internal repos. I guess because they run in github actions?

As a follow-on to the required RPM build changes that had to be made quickly for 2.0.2, I was contemplating some scons updates to enable an automatic download and local installation of the latest toolchain if the OS doesn't provide it. To me, that seems the best way to handle this as it will allow us to centralize the knowledge in one place. Do you see any disadvantages to that approach?

**Comment by ashleypittman** [comment]
> > We really have two build processes, the rpm process and the docker process, rpms are used for distribution as you say but we use docker elsewhere in CI.
> 
> Understood. I'm asking why the docker process can't use the internal repos. I guess because they run in github actions?

I think when our dockerfiles are used in CI they do use the internal repos, but as you say we use docker elsewhere as well.

> As a follow-on to the required RPM build changes that had to be made quickly for 2.0.2, I was contemplating some scons updates to enable an automatic download and local installation of the latest toolchain if the OS doesn't provide it. To me, that seems the best way to handle this as it will allow us to centralize the knowledge in one place. Do you see any disadvantages to that approach?

You mean the same way we do for the dependencies and build.config?  Yes, now that I've used the go download/install process a better approach than this PR would be to have scons do the download and install to a temp dir if required, then we could have the version number in build.config, and it would be enabled/disabled by the existing --build-deps option.

**Pull request closed without merging**
