### PR TITLE
Adding a .travis.yml file to trigger CI builds.

### PR DESCRIPTION
**Pull request by rajachan**
Added a `.travis.yml` file for automatic CI builds in Travis. Currently just kicking off `scons --build-deps=yes`, which fails due to a [CCI build issue](https://github.com/CCI/cci/issues/45). If you guys already have a way to build DAOS working around this issue, we can update the yml to reflect that.

You can see a sample build in my [fork's TravisCI](https://travis-ci.org/rajachan/daos/builds/177732469).

### CODE REVIEW

**Comment by ashleypittman** [comment]
Our master builds are blocked on the CCI build issue as well so we're currently working from a blessed build that predates that bug.  Hopefully it'll be resolved soon, and then we'll have to update from some Mercury API changes related to how checksums are calculated.

**Comment by johannlombardi** [comment]
Thanks for the patch Raghu. We currently use gerrit for patch review. I have pushed your patch here: https://review.whamcloud.com/#/c/27918/
Please let me know if you are ok with the signed-off-by and I will merge the patch. Thanks!

**Comment by rajachan** [comment]
Sure, I am okay with the signed-off-by.

**Comment by johannlombardi** [comment]
Landed. Thanks.

**Pull request closed without merging**
