### PR TITLE
DAOS-12366 control: Limit reference sharing when updating bdev stats

### PR DESCRIPTION
**Pull request by tanabarr**
The data race was made possible because of sharing object references
too liberally. Close the gap by reducing the scope of reference
sharing when updating in-use bdev stats.

Required-githooks: true

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by kjacque — APPROVED** [review]
Seems reasonable to me. I spent some time wondering if maybe this was too far in the other direction (more copies than we need), but it's hard for me to say. And storage scans don't seem likely to be that time-sensitive, anyway.

**Review by knard-intel — APPROVED** [review]
LGTM, thanks to @tanabarr explanation :)

**Comment by tanabarr** [comment]
Some notes on the changes (as discussed with @knard-intel ).

I wanted to be able to update in place the contents of the controller, i.e. change "ctrlrs = ctrlrs.Update(newCtrlrs)" to "ctrlrs.Update(newCtrlrs)", in order to do that the Update() needs to have a pointer receiver ("func (ncs *storage.NvmeControllers) Update(...)").

The data race was made possible because of sharing references too liberally. Changing the update method to take concrete controller objects, not references, and simplifying the updates by returning a new slice of concrete controller objects (not references) from updateInUseBdevs() both reduce the opportunity for the same reference controller to be inadvertently modified in different code paths simultaneously".

The previous implementation of passing in a map of references seemed errorprone so instead I've moved this into the updateInUseBdevs() function itself to avoid exposing those references outside.

**Comment by tanabarr** [comment]
Pylint failure seems unrelated to this PR.

**Pull request merged**
