### PR TITLE
DAOS-4183 engine: reduce virtual memory and swap footprint

### PR DESCRIPTION
**Pull request by bfaccini**
In order to limit the virtual memory and swap footprint, only mmap() the exact requested stack size (to be rounded up to the page size by the Kernel!), different sizes will be managed by a b-tree, and MAP_NORESERVE flag will now be used.

Required-githooks: true

Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficent testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by bfaccini** [comment]
@johannlombardi @NiuYawei can you review when you have some time ?! thx in advance ;-)

**Review by jolivier23 — APPROVED** [review]

**Review by NiuYawei — APPROVED** [review]

**Comment by jolivier23** [comment]
One comment, it looks like this enables the feature by default too.  Should that be in the message?

**Comment by bfaccini** [comment]
> One comment, it looks like this enables the feature by default too. Should that be in the message?

Oops, right @jolivier23 , I forgot that I had enabled it to expose it to the full CI testing...
Should I remove the specific change that enables by default (is everybody ok to enable the mmap()ing of ULTs stacks by default ?) ? Or just change the main PR msg to indicate it as you have suggested ?

**Comment by jolivier23** [comment]
> > One comment, it looks like this enables the feature by default too. Should that be in the message?
> 
> Oops, right @jolivier23 , I forgot that I had enabled it to expose it to the full CI testing... Should I remove the specific change that enables by default (is everybody ok to enable the mmap()ing of ULTs stacks by default ?) ? Or just change the main PR msg to indicate it as you have suggested ?

I'd be ok with just changing the description but it's probably a question for @johannlombardi whether we should enable the feature by default.

**Comment by jolivier23** [comment]
> > > One comment, it looks like this enables the feature by default too. Should that be in the message?
> > 
> > 
> > Oops, right @jolivier23 , I forgot that I had enabled it to expose it to the full CI testing... Should I remove the specific change that enables by default (is everybody ok to enable the mmap()ing of ULTs stacks by default ?) ? Or just change the main PR msg to indicate it as you have suggested ?
> 
> I'd be ok with just changing the description but it's probably a question for @johannlombardi whether we should enable the feature by default.

@johannlombardi I know you previously reviewed and approved but just wanted to make sure you were ok with the change of default in particular for this feature.

**Review by johannlombardi — DISMISSED** [review]

**Comment by johannlombardi** [comment]
I am ok with the patch and to eventually change it. The issue is that we still got a perf impact on frontera for IOPS benchmarks IIRC.  If so, we should address this before enabling it by default.

**Comment by bfaccini** [comment]
> I am ok with the patch and to eventually change it. The issue is that we still got a perf impact on frontera for IOPS benchmarks IIRC. If so, we should address this before enabling it by default.

Ah, you got new+bad perf numbers from Dalton ?
Will push a new commit to remove default enabling...

**Comment by bfaccini** [comment]
One more review turn-table, sorry guys .... To be honest I don't remember last time when I forgot to ask you reviewing again :-(

**Review by NiuYawei — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by bfaccini** [comment]
Even if mmap()'ed ULTs stacks feature seems to introduce some penalty, I would like to get this PR to land since this feature can be used at least for debugging purpose.
I would like to get some feedback and hear what do all my reviewers think about this ??

**Comment by daltonbohning** [comment]
> Even if mmap()'ed ULTs stacks feature seems to introduce some penalty, I would like to get this PR to land since this feature can be used at least for debugging purpose. I would like to get some feedback and hear what do all my reviewers think about this ??

I think if it's disabled by default, or at least for release builds, maybe it's okay to land?

**Comment by mchaarawi** [comment]
@NiuYawei , @jolivier23  do we still need this PR?

**Comment by daltonbohning** [comment]
> @NiuYawei , @jolivier23 do we still need this PR?

Ping again. Is this still useful?

**Comment by NiuYawei** [comment]
> > @NiuYawei , @jolivier23 do we still need this PR?
> 
> Ping again. Is this still useful?

Sorry, I missed the messages from @mchaarawi .

I don't think we need this PR anymore, since there is no plan to use mmap'd stack in near term. @knard-intel , what do you think? I see you recently pushed a PR for mmap'd stack (which one was closed eventually), what's your plan on the mmap'd stack?

**Comment by knard-intel** [comment]
@NiuYawei , From my side, this PR could be closed.
As indicated in the PRs #14713 and #14782, the current implementation is suffering of several issues which are fixed by these two PRs.  However, it was decided to remove the ULT mmap stack feature of DAOS and rely on the mguard feature from latest version 1.2 of argobots.
If needed, there is more info in the JIRA ticket [DAOS-16073](https://daosio.atlassian.net/browse/DAOS-16073)

**Comment by daltonbohning** [comment]
> @NiuYawei , From my side, this PR should be closed. As indicated in the PRs #14713 and #14782, the current implementation is suffering of several issues which are fixed by these two PRs. However, it was decided to remove the ULT mmap stack feature of DAOS and rely on the mguard feature from latest version 1.2 of argobots. If needed, there is more info in the JIRA ticket [DAOS-16073](https://daosio.atlassian.net/browse/DAOS-16073).
> 
> My apologies, for the late answer, I just seen your comments as I have just finished to setup my new laptop.

Thanks! I will close this

**Pull request closed without merging**
