### PR TITLE
DAOS-4593 remove daos_pool_add_replicas ()

### PR DESCRIPTION
**Pull request by GitHuaKuang**
DAOS-4595 remove daos_pool_remove_replicas ()

Change-Id: I99ec28e73ab8c7853e0e9bd484b79df8eb040509
Signed-off-by: Hua Kuang <hua.kuang@intel.com>

### CODE REVIEW

**Comment by GitHuaKuang** [comment]
This is a reported bug: https://jira.hpdd.intel.com/browse/DAOS-5922

**Review by berserk-fury — APPROVED** [review]

**Review by cibervicho — DISMISSED** [review]

**Review by kccain — CHANGES_REQUESTED** [review]
It seems perhaps the dc_pool_add_replicas() and dc_pool_remove_replicas() and dc_pool_membership_update() client functions in src/pool/cli.c could be removed as part of this.

At some point, maybe when DAOS-5010 is developed (control plane dmg command to add pool service replica) maybe the cart RPC definitions in src/pool/rpc.h for POOL_REPLICAS_ADD and POOL_REPLICAS_REMOVE can also be dropped.

**Comment by GitHuaKuang** [comment]
> It seems perhaps the dc_pool_add_replicas() and dc_pool_remove_replicas() and dc_pool_membership_update() client functions in src/pool/cli.c could be removed as part of this.
> 
> At some point, maybe when DAOS-5010 is developed (control plane dmg command to add pool service replica) maybe the cart RPC definitions in src/pool/rpc.h for POOL_REPLICAS_ADD and POOL_REPLICAS_REMOVE can also be dropped.

Great, it feels more like a surgery now.

**Comment by GitHuaKuang** [comment]
The failures are reported in:
DAOS-5852
DAOS-6012

**Review by kccain — APPROVED** [review]

**Review by cibervicho — APPROVED** [review]

**Review by berserk-fury — APPROVED** [review]

**Pull request merged**
