### PR TITLE
DAOS-7717 test: enable test_pool_large_attributes in CI

### PR DESCRIPTION
**Pull request by wangshilong**
test_pool_large_attributes is not running in CI, enable
extra daily_regreesion and all tags like test_pool_attributes
did.

Signed-off-by: Wang Shilong <shilong.wang@intel.com>

### CODE REVIEW

**Comment by sylviachanoiyee** [comment]
@wangshilong , since we are enabling this test in CI, could you repush with the following tag in your commit message? It will pick up the test and run it in your PR

Test-tag: pr large_poolattribute

**Review by shimizukko — APPROVED** [review]

**Review by shimizukko — DISMISSED** [review]

**Review by rpadma2 — APPROVED** [review]
Looks good to me.

**Comment by sylviachanoiyee** [comment]
Looks like the tests did not run for some reason. Maybe retrigger?

**Comment by wangshilong** [comment]
> Looks like the tests did not run for some reason. Maybe retrigger?

So i should repush patch to retrigger test or there is button somewhere on the  github page?

**Comment by sylviachanoiyee** [comment]
I think you can repush since none of the test stage started.

**Comment by wangshilong** [comment]
Sorry, this patch should be pushed to daos-stack github directly rather than forked repo, this is reason why test was not triggered.
I pushed a new PR here https://github.com/daos-stack/daos/pull/6456

**Pull request closed without merging**
