### PR TITLE
DAOS-6726 dlog: resolve deadlock in CaRT logging system

### PR DESCRIPTION
**Pull request by dmiter**
Don't resolve XS id until all modules will be initialized.
Move initialization of static members outside of locked region.

Test-tag: pr daily_regression

### CODE REVIEW

**Comment by dmiter** [comment]
Test failed because of DAOS-7863.

**Comment by dmiter** [comment]
Failure of ContainerAutotestTest and DmgPoolQueryTest are not related to this patch.

**Comment by ashleypittman** [comment]
This might help with https://jira.hpdd.intel.com/browse/DAOS-7966 as well.

**Review by NiuYawei — APPROVED** [review]

**Comment by ashleypittman** [comment]
Have you seen https://github.com/daos-stack/daos/pull/6061/files which has some similar changes for getting the abt thread ID.

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
