### PR TITLE
DAOS-5018 Hadoop Compatible Exception (re-submit)

### PR DESCRIPTION
**Pull request by zjf2012**
In PR #2800, I overlooked some integration tests which should be named as *IT. I just renamed them and re-submit it.

### CODE REVIEW

**Comment by zjf2012** [comment]
@jolivier23 , @johannlombardi , sorry for the trouble. I just fixed the test issue. please help review.

**Comment by johannlombardi** [comment]
Hey @zjf2012, it sounds like travis is still failing:

[Warning] daos2382763141609932059:74:73: Include operation failed, reverting to fallback. Resource error reading file as XML (href='auth-keys.xml'). Reason: /tmp/auth-keys.xml (No such file or directory)
[[1;31mERROR[m] [1;31mTests [0;1mrun: [0;1m9[m, [1;31mFailures: [0;1;31m1[m, Errors: 0, Skipped: 0, Time elapsed: 6.745 s[1;31m <<< FAILURE![m - in io.daos.fs.hadoop.[1mDaosFileSystemTest[m
[[1;31mERROR[m] testLoadingConfigFromCoreSite(io.daos.fs.hadoop.DaosFileSystemTest)  Time elapsed: 0.031 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[daos://id:2]> but was:<[file:///]>
	at io.daos.fs.hadoop.DaosFileSystemTest.testLoadingConfigFromCoreSite(DaosFileSystemTest.java:213)

**Comment by zjf2012** [comment]
@johannlombardi , it looks good. please help merge. thanks for the patience.

**Comment by zjf2012** [comment]
@johannlombardi could you please help approve it too?

**Pull request merged**
