### PR TITLE
DAOS-9040 common: Reduce rsvc_client leader_aliveness

### PR DESCRIPTION
**Pull request by liw**
Since we use reliable datagrams, it seems using at most 1 for
rsvc_client.sc_leader_aliveness (i.e., do not retry the leader before
starting a leader search) will make more sense in most cases. This patch
converts the maximum leader aliveness to a macro and reduces the value
from 2 to 1.

Signed-off-by: Li Wei <wei.g.li@intel.com>

### CODE REVIEW

**Comment by liw** [comment]
F_H_M failed due to CI issue: "[2022-01-14T06:26:19.362Z]  Problem: cannot install both daos-serialize-2.1.100-17.7616.g07d5a399.el8.x86_64 and daos-serialize-2.1.100-17.7613.g5ccf81cb.el8.x86_64".

**Comment by liw** [comment]
The failures above also seem to be CI issues.

**Comment by liw** [comment]
The F_H_S failure seems unrelated: DAOS-9647.

**Review by NiuYawei — APPROVED** [review]

**Comment by liw** [comment]
The F_H_M DTX test failure seems unrelated: DAOS-9652.

**Review by kccain — APPROVED** [review]

**Pull request merged**
