### PR TITLE
DAOS-16628 client: reset eq counter to zero after fork() in IL

### PR DESCRIPTION
**Pull request by wiliamhuang**
After fork(), child process inherits the value of the counter of event queues, d_eq_count in libpil4dfs and ioil_iog.iog_eq_count in libioil. They need to be reset to zero.

Required-githooks: true
Skipped-githooks: codespell

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]
What happens if you don't do this?

**Comment by wiliamhuang** [comment]
> What happens if you don't do this?

I have not observe any issue in common applications. I saw errors in destroying network contexts in a test code with multiple level of nested fork() due to wrong context counter in child processes.

**Review by knard-intel — APPROVED** [review]

**Comment by wiliamhuang** [comment]
@mchaarawi This PR is quite simple. Shall we back port it to 2.6? Thank you!

**Review by mchaarawi — APPROVED** [review]

**Comment by mchaarawi** [comment]
> @mchaarawi This PR is quite simple. Shall we back port it to 2.6? Thank you!

sure please make the req.

**Comment by wiliamhuang** [comment]
The only failed test (intercept_multi_client.py:IorInterceptMultiClient.test_ior_intercept_libpil4dfs) is due to performance noise. All other tests passed.

**Pull request merged**
