### PR TITLE
DAOS-15109 test: Add diagnostics for FI abort problem.

### PR DESCRIPTION
**Pull request by ashleypittman**
Skip-unit-tests: true

Required-githooks: true

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
I don't really know enough (anything in fact) about the FI testing to provide any meaningful review of this unfortunately.

**Comment by ashleypittman** [comment]
> I don't really know enough (anything in fact) about the FI testing to provide any meaningful review of this unfortunately.

No, I'm guessing on this front as well.

It seems Jenkins is occasionally killing a job as one of it's scripts isn't reporting back to Jenkins but that seems like an internal Jenkins issue.  When it fails there is no output reported for a few minutes before it gets killed so maybe the node has locked up somehow but also if I add a "sleep(10000)" to the code so there's no output then it does not get killed.  I was thinking a flush here was unlikely to hurt and might mean that whatever Jenkins script it is would have something to report which might help it stay awake.

The only other approach to this I can think of would be to see the flag that Jenkins is suggesting to increase the heartbeat timeout - that would be a Jenkins restart I think.

**Comment by ashleypittman** [comment]
> > It seems Jenkins is occasionally killing a job as one of it's scripts isn't reporting back to Jenkins
> 
> We do not have kind of output idleness detection in place that I am aware of. What is leading you to this conclusion, just so I can better understand the issue?

I don't think we do, I think Jenkins does and is killing the job when this fails to update.  I put a link in Teams yesterday but I'm going by the message https://groups.google.com/g/jenkinsci-issues/c/iS9ZiTSVRMM/m/hZQ_06RtEwAJ

> > When it fails there is no output reported for a few minutes before it gets killed
> 
> Where do you see this "killing" happening?

The last two lines if output from the fault injection test, most recent failure is at https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/9444/

> > The only other approach to this I can think of would be to see the flag that Jenkins is suggesting to increase the heartbeat timeout - that would be a Jenkins restart I think.
> 
> Again, I know of no such feature we have enabled in Jenkins which is why I'd like to understand what is making you think this is what might be happening.

It would be worth reading the Jenkins ticket for this PR as a background.  In general we've historically seen very occasional failures with the fault injection job getting killed, in the past this has only occurred during times when we've submitted multiple jobs concurrently and are overwhelming the docker servers, for example when 10 or so PRs are landed within a short time window or when master is opened after a period of time closed and lots of people rebase concurrently.

Recently, within the last month however we've seen this failure with the exact same warning message a lot and seemingly at times when the system is not particularly loaded.  I've also changed the job to reduce the concurrency if the load average is too high, we used to regularly see it progressing and completing with a load average of 250 or more but now it shouldn't go above 100 yet we're also seeing failures at a much greater rate than before.

We had a bunch of failures one day in August that I'm aware of, then no more until we re-opened landings on the 22nd but since around that time then we seem to have had about 15-20% of all builds fail.

**Comment by brianjmurrell** [comment]
> The last two lines if output from the fault injection test, most recent failure is at [build.hpdd.intel.com/job/daos-stack/job/daos/job/master/9444](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/9444/)

Ahhhh.  This part is new to me.  I had not seen this before or knew it was part of the problem.

Given that the "laggy" filesystem here is a local filesystem, if this is a docker (or other) overloading problem it should correlate with some system metrics that would explain why it's laggy.  To do that though, we will need an SRE ticket tracking exactly that symptom/problem with date/timestamps of when it's happening.  Likely we will need a number of {ex,s}amples to get any useful correlation.

**Comment by ashleypittman** [comment]
> > The last two lines if output from the fault injection test, most recent failure is at [build.hpdd.intel.com/job/daos-stack/job/daos/job/master/9444](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/9444/)
> 
> Ahhhh. This part is new to me. I had not seen this before or knew it was part of the problem.
> 
> Given that the "laggy" filesystem here is a local filesystem, if this is a docker (or other) overloading problem it should correlate with some system metrics that would explain why it's laggy. To do that though, we will need an SRE ticket tracking exactly that symptom/problem with date/timestamps of when it's happening. Likely we will need a number of {ex,s}amples to get any useful correlation.

It's probably worth moving this discussion to the Jira ticket.  I haven't been able to identify any useful correlation to narrow down the cause.

**Pull request closed without merging**
