### PR TITLE
DAOS-5506 Test: Skip MGMT5 daos_test.

### PR DESCRIPTION
**Pull request by ravalsam**
Skipping MGM5 test until MS pool create/destroy crash recovery
is handle for all scenarios as part of DAOS-2407.

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Review by mjmac — APPROVED** [review]

**Review by liw — COMMENTED** [review]
I thought we only needed to comment out the second fail injection (i.e., the one for the pool destroy operation). Would that leave some problem(s) around?

**Comment by ravalsam** [comment]
> I thought we only needed to comment out the second fail injection (i.e., the one for the pool destroy operation). Would that leave some problem(s) around?

So if I disable second fail injection, MGMT5 test fail for pool destroy.

[ RUN      ] MGMT5: retry MGMT_POOL_{CREATE,DESETROY} upon errors
setting DAOS_POOL_CREATE_FAIL_CORPC ... success
creating pool synchronously ... success uuid = 966a2add-91d6-43c2-9a07-7604de33b3f8
destroying pool synchronously ... [  ERROR   ] --- 0 != 0xfffffffffffffc0d
[   LINE   ] --- src/tests/suite/daos_mgmt.c:421: error: Failure!
[  FAILED  ] MGMT5: retry MGMT_POOL_{CREATE,DESETROY} upon errors
[==========] 5 test(s) run.
[  PASSED  ] 4 test(s).
[  FAILED  ] 1 test(s), listed below:
[  FAILED  ] MGMT5: retry MGMT_POOL_{CREATE,DESETROY} upon errors

```
09/16-16:00:35.90 wolf-154 DAOS[29224/29274] vos  DBUG src/vos/vos_pool.c:130 pool_hop_free() Closed VOS I/O context:0x7efcbcb84fd0 pool:988abbd1
09/16-16:00:35.94 wolf-154 DAOS[29224/29263] vos  DBUG src/vos/vos_pool.c:196 pool_lookup() can't find 988abbd1
09/16-16:00:35.94 wolf-154 DAOS[29224/29263] vos  DBUG src/vos/vos_pool.c:438 vos_pool_kill() Deleting blob for xs:0x7efd140dc9c0 pool:988abbd1
```

**Comment by liw** [comment]
> > I thought we only needed to comment out the second fail injection (i.e., the one for the pool destroy operation). Would that leave some problem(s) around?
> 
> So if I disable second fail injection, MGMT5 test fail for pool destroy.
> 
> [ RUN ] MGMT5: retry MGMT_POOL_{CREATE,DESETROY} upon errors
> setting DAOS_POOL_CREATE_FAIL_CORPC ... success
> creating pool synchronously ... success uuid = 966a2add-91d6-43c2-9a07-7604de33b3f8
> destroying pool synchronously ... [ ERROR ] --- 0 != 0xfffffffffffffc0d

This is due to

    assert_int_equal(rc, -DER_TIMEDOUT);

We expect the destroy to succeed after disabling the second fault injection.

**Comment by ravalsam** [comment]
> 
> This is due to
> 
> ```
> assert_int_equal(rc, -DER_TIMEDOUT);
> ```
> 
> We expect the destroy to succeed after disabling the second fault injection.

Yes, I only disabled the second fault injection. Pool destroy seems failing with first fault injection. Another option is to disable the second faulty injection and the rc check for dmg_pool_destroy. 

```
diff --git a/src/tests/suite/daos_mgmt.c b/src/tests/suite/daos_mgmt.c
index e8c12d4..c02e3de 100644
--- a/src/tests/suite/daos_mgmt.c
+++ b/src/tests/suite/daos_mgmt.c
@@ -388,7 +388,7 @@ pool_create_and_destroy_retry(void **state)
         * sequence.So Skipping this test until MS pool create/destroy crash
         * recovery mechanism handle for this test scenario.
         */
-       skip();
+       //skip();
        print_message("setting DAOS_POOL_CREATE_FAIL_CORPC ... ");
        rc = daos_mgmt_set_params(arg->group, 0, DMG_KEY_FAIL_LOC,
                                  DAOS_POOL_CREATE_FAIL_CORPC | DAOS_FAIL_ONCE,
@@ -406,12 +406,14 @@ pool_create_and_destroy_retry(void **state)
        assert_int_equal(rc, 0);
        print_message("success uuid = "DF_UUIDF"\n", DP_UUID(uuid));

+       /*
        print_message("setting DAOS_POOL_DESTROY_FAIL_CORPC ... ");
        rc = daos_mgmt_set_params(arg->group, 0, DMG_KEY_FAIL_LOC,
                                  DAOS_POOL_DESTROY_FAIL_CORPC | DAOS_FAIL_ONCE,
                                  0, NULL);
        assert_int_equal(rc, 0);
        print_message("success\n");
+       */

        print_message("destroying pool synchronously ... ");
        rc = dmg_pool_destroy(dmg_config_file, uuid, arg->group, 1);
```

**Comment by liw** [comment]
> Yes, I only disabled the second fault injection. Pool destroy is failing when we have first fault injection?

The first fault injection should only be hit by the pool create operation.

> Another option is to disable the second faulty injection and the rc check for dmg_pool_destroy.

Yes, that would be a good way to go. Apologies for forgetting to mention that the assert that "the pool destroy must time out" should be changed to "the pool destroy must succeed".

**Comment by liw** [comment]
Ah, just in case you didn't notice:

> destroying pool synchronously ... [ ERROR ] --- 0 != 0xfffffffffffffc0d

means that the pool destroy operation returned 0, while the test expected -DER_TIMEDOUT.

**Review by mjmac — APPROVED** [review]

**Review by liw — APPROVED** [review]

**Comment by mjmac** [comment]
Test failures are unrelated, as this PR only commented out part of a different test.

**Pull request merged**
