### PR TITLE
DAOS-2444 build: upgrade isal version

### PR DESCRIPTION
**Pull request by liuxuezhao**
To include the support of aarch64, and some other refines.

Signed-off-by: Xuezhao Liu <xuezhao.liu@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
> Does this githash correspond to a version tag? Of do, we should use the release version tag. Like we do for pmdk.

It looks like the tip of master.  So my next question would be, is what we want not in the latest release, [2.26.0](https://github.com/intel/isa-l/tree/v2.26.0)?

**Comment by liuxuezhao** [comment]
> Does this githash correspond to a version tag? Of do, we should use the release version tag. Like we do for pmdk.
it is about 5 commits after tag 2.26. compared to pmdk the isal is just a much smaller and simpler lib, so its normal commit is unlikely to cause bug. probably not must to use a tagged version.
> It looks like the tip of master. So my next question would be, is what we want not in the latest release, [2.26.0](https://github.com/intel/isa-l/tree/v2.26.0)?
Right, there is just a few small refining after 2.26 but not really related with us.
I'm fine to refresh to use 2.26.

**Comment by jolivier23** [comment]
A couple of changes have gone in related to the aggregate test.  Not sure about the other test failure.   One of daos_test cases is failing.

**Comment by liuxuezhao** [comment]
> We need to fix the src/common/SConscript to remove the requirement for building mchecksum in ARM platform since now we can use ISA-L in ARM?

well. I'll leave it to others who more familiar with checksum usage in ISAL in daos, or who have arm platform to test it.

**Comment by liuxuezhao** [comment]
> A couple of changes have gone in related to the aggregate test. Not sure about the other test failure. One of daos_test cases is failing.

you mean for your testing on boro? not sure what kind of failing? (I did not meet it).

**Comment by vvenkates27** [comment]
Ok sure, I can push a patch once this pull request is merged. Not sure how to make one pull request depend on another in github.

**Comment by liuxuezhao** [comment]
> Ok sure, I can push a patch once this pull request is merged. Not sure how to make one pull request depend on another in github.

you can just merge this one line change to your patch.
BTW, for performance probably no much benefit to use isal for checksum in arm, compared to just using mchecksum as before.

**Pull request closed without merging**
