### PR TITLE
DAOS-6446 Test: Update tags on tests.

### PR DESCRIPTION
**Pull request by omar-ocampo**
Added all and daily_regression tags to:
        container/basic_snapshot.py
        object/same_key_different_value.py
        pool/permission.py

Features: basicsnap,samekeydifferentvalue,connectpermission,filemodification
Signed-off-by: Omar Ocampo <omar.ocampo.coronado@intel.com>

### CODE REVIEW

**Comment by omar-ocampo** [comment]
New tests added are failing, need to open a few tickets and add skipForTicket in the failing tests.

**Review by ravalsam — COMMENTED** [review]
So If I remember there was the format we follow for tags mention below. But I could be wrong. please confirm with Scott or Sylvia.

Organized test tags on four lines:
- frequency
- test stage
- features
- tests

Example:
        :avocado: tags=all,pr,daily_regression
        :avocado: tags=hw,small
        :avocado: tags=daosio,checksum
        :avocado: tags=aggregationchecksum

**Comment by omar-ocampo** [comment]
> So If I remember there was the format we follow for tags mention below. But I could be wrong. please confirm with Scott or Sylvia.
> 
> Organized test tags on four lines:
> 
> * frequency
> * test stage
> * features
> * tests
> 
> Example:
> 🥑 tags=all,pr,daily_regression
> 🥑 tags=hw,small
> 🥑 tags=daosio,checksum
> 🥑 tags=aggregationchecksum

Do we have wiki for that? It sounds more like a recommendation rather than a bug.

**Comment by ravalsam** [comment]
> > So If I remember there was the format we follow for tags mention below. But I could be wrong. please confirm with Scott or Sylvia.
> > Organized test tags on four lines:
> > 
> > * frequency
> > * test stage
> > * features
> > * tests
> > 
> > Example:
> > 🥑 tags=all,pr,daily_regression
> > 🥑 tags=hw,small
> > 🥑 tags=daosio,checksum
> > 🥑 tags=aggregationchecksum
> 
> Do we have wiki for that? It sounds more like a recommendation rather than a bug.

I don't know if we have Wiki or not but it was discussed and some tester has started using it. Anyway, the patch looks ok to me

**Review by ravalsam — APPROVED** [review]

**Review by shimizukko — APPROVED** [review]

**Comment by omar-ocampo** [comment]
@sylviachanoiyee could you merge?

**Comment by sylviachanoiyee** [comment]
PR looks good. @omar-ocampo , can you update tickets DAOS-7220 and DAOS-7221 and provide instructions to re-enable the test at the top of the ticket description?

**Pull request merged**
