### PR TITLE
DAOS-4910 test: Increasing the runtime for daos_racer test.

### PR DESCRIPTION
**Pull request by saurabhtandan**
Increased daos_racer time limit to run for 2 hours
with object consistency check

Test-tag-hw-large: pr,hw,large daosracer

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

### CODE REVIEW

**Review by shimizukko — DISMISSED** [review]
Looks good to me

**Comment by sylviachanoiyee** [comment]
@saurabhtandan , can you look into tuning down verbosity of logs and ways to reduce logging?
Running test for 2 hrs is generating huge logs
https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/daos/branches/PR-3264/runs/8/nodes/547/steps/950/log/?start=0
Just a couple of examples from this run but if you look in link above, you will more huge files
4.4G /var/tmp/daos_testing/daos_racer_daos.log
5.4G /var/tmp/daos_testing/daos_server.log

CI complains No space left on device and this can be a problem because it might prevent other tests from running.

**Review by dinghwah — DISMISSED** [review]
Looks good to me.

**Comment by Nasf-Fan** [comment]
> @saurabhtandan , can you look into tuning down verbosity of logs and ways to reduce logging?
> Running test for 2 hrs is generating huge logs
> https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/daos/branches/PR-3264/runs/8/nodes/547/steps/950/log/?start=0
> Just a couple of examples from this run but if you look in link above, you will more huge files
> 4.4G /var/tmp/daos_testing/daos_racer_daos.log
> 5.4G /var/tmp/daos_testing/daos_server.log
> 
> CI complains No space left on device and this can be a problem because it might prevent other tests from running.

2 hours daos_racer test is some long for regular CI test, and will generate a lot of noisy warning/error message. But if without explicitly specifying the commit parameters "Test-tag-hw-large: daosracer", the CI test will not trigger daos_racer by default, right? If true, then it will not affect regular CI tests for most of other PRs.

The root reason for current huge log file is that the daos_racer test will randomly generate kinds of sized IO, including very large IO. If daos racer runs for very long time, it is normal that those IO will exhaust all available space. We expect that the VOS aggregation can reclaim some space. But unfortunately, it is found that the VOS aggregation logic cannot work under the case of server out of space.

So @NiuYawei , what is your suggestion? Continue to land this patch or wait for you to resolve the issue of space reservation for VOS aggregation/punch.

**Review by shimizukko — APPROVED** [review]
LGTM

**Comment by saurabhtandan** [comment]
> > > @saurabhtandan , can you look into tuning down verbosity of logs and ways to reduce logging?
> > > Running test for 2 hrs is generating huge logs
> > > https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/daos/branches/PR-3264/runs/8/nodes/547/steps/950/log/?start=0
> > > Just a couple of examples from this run but if you look in link above, you will more huge files
> > > 4.4G /var/tmp/daos_testing/daos_racer_daos.log
> > > 5.4G /var/tmp/daos_testing/daos_server.log
> > > CI complains No space left on device and this can be a problem because it might prevent other tests from running.
> > 
> > 
> > 2 hours daos_racer test is some long for regular CI test, and will generate a lot of noisy warning/error message. But if without explicitly specifying the commit parameters "Test-tag-hw-large: daosracer", the CI test will not trigger daos_racer by default, right? If true, then it will not affect regular CI tests for most of other PRs.
> > The root reason for current huge log file is that the daos_racer test will randomly generate kinds of sized IO, including very large IO. If daos racer runs for very long time, it is normal that those IO will exhaust all available space. We expect that the VOS aggregation can reclaim some space. But unfortunately, it is found that the VOS aggregation logic cannot work under the case of server out of space.
> > So @NiuYawei , what is your suggestion? Continue to land this patch or wait for you to resolve the issue of space reservation for VOS aggregation/punch.
> 
> Is it possible to post few hundreds of log messages somewhere for examine? (The log looks too huge for me to download)

Which logs do you want? Server or client?

**Comment by saurabhtandan** [comment]
@NiuYawei and @Nasf-Fan ,
Sample of both client and server log files attached to ticket DAOS-4910. Please have a look.

**Comment by Nasf-Fan** [comment]
> > > @saurabhtandan , can you look into tuning down verbosity of logs and ways to reduce logging?
> > > Running test for 2 hrs is generating huge logs
> > > https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/daos/branches/PR-3264/runs/8/nodes/547/steps/950/log/?start=0
> > > Just a couple of examples from this run but if you look in link above, you will more huge files
> > > 4.4G /var/tmp/daos_testing/daos_racer_daos.log
> > > 5.4G /var/tmp/daos_testing/daos_server.log
> > > CI complains No space left on device and this can be a problem because it might prevent other tests from running.
> > 
> > 
> > 2 hours daos_racer test is some long for regular CI test, and will generate a lot of noisy warning/error message. But if without explicitly specifying the commit parameters "Test-tag-hw-large: daosracer", the CI test will not trigger daos_racer by default, right? If true, then it will not affect regular CI tests for most of other PRs.
> > The root reason for current huge log file is that the daos_racer test will randomly generate kinds of sized IO, including very large IO. If daos racer runs for very long time, it is normal that those IO will exhaust all available space. We expect that the VOS aggregation can reclaim some space. But unfortunately, it is found that the VOS aggregation logic cannot work under the case of server out of space.
> > So @NiuYawei , what is your suggestion? Continue to land this patch or wait for you to resolve the issue of space reservation for VOS aggregation/punch.
> 
> Is it possible to post few hundreds of log messages somewhere for examine? (The log looks too huge for me to download)

It is also not easy to download the logs from my side. But I have some log pieces for some former failure instance, such as the following:

08/15-06:24:52.41 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:1676 reserve_space() Reserve 4045 from SCM failed.
08/15-06:24:52.41 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:1736 vos_reserve_single() Reserve SCM for SV failed. DER_NOSPACE(-1007)
08/15-06:24:52.41 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:2165 vos_update_begin() 1152922535398998256.240.0dkey update begin failed. -1007
08/15-06:24:52.41 wolf-143 DAOS[36922/36941] object ERR  src/object/srv_obj.c:1268 obj_local_rw() 1152922535398998256.240.0 Update begin failed: DER_NOSPACE(-1007)
08/15-06:24:52.41 wolf-143 DAOS[36922/36941] dtx  ERR  src/dtx/dtx_rpc.c:254 dtx_req_list_cb() DTX req for opc 1 (439ab176.162b5cf331fc0077) failed, count 2: -1005.
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:1676 reserve_space() Reserve 1424 from SCM failed.
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:1814 vos_reserve_recx() Reserve recx failed. DER_NOSPACE(-1007)
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:2165 vos_update_begin() 1152922535398998256.240.0dkey update begin failed. -1007
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] object ERR  src/object/srv_obj.c:1268 obj_local_rw() 1152922535398998256.240.0 Update begin failed: DER_NOSPACE(-1007)
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] dtx  ERR  src/dtx/dtx_rpc.c:254 dtx_req_list_cb() DTX req for opc 1 (439ab176.162b5cf332070001) failed, count 2: -1005.
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:1676 reserve_space() Reserve 3586 from SCM failed.
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:1814 vos_reserve_recx() Reserve recx failed. DER_NOSPACE(-1007)
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:2165 vos_update_begin() 1152922535398998256.240.0dkey update begin failed. -1007
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] object ERR  src/object/srv_obj.c:1268 obj_local_rw() 1152922535398998256.240.0 Update begin failed: DER_NOSPACE(-1007)
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] dtx  ERR  src/dtx/dtx_rpc.c:254 dtx_req_list_cb() DTX req for opc 1 (439ab176.162b5cf332160001) failed, count 2: -1005.
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:1676 reserve_space() Reserve 2781 from SCM failed.
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:1814 vos_reserve_recx() Reserve recx failed. DER_NOSPACE(-1007)
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] vos  ERR  src/vos/vos_io.c:2165 vos_update_begin() 1152922535398998256.240.0dkey update begin failed. -1007
08/15-06:24:52.42 wolf-143 DAOS[36922/36941] object ERR  src/object/srv_obj.c:1268 obj_local_rw() 1152922535398998256.240.0 Update begin failed: DER_NOSPACE(-1007)
...

**Review by Nasf-Fan — COMMENTED** [review]
The main purpose of daos_racer is to check whether there is system corruption or not, but it does not care about whether some individual operation succeed or fail. So if we can mask D_WARN()/D_ERROR() message from the log, then the issue of huge log file can be resolved.

**Comment by Nasf-Fan** [comment]
I am trying to shrink the log size via dropping unnecessary log message and controlling the invalid IO percentage. Related patch is in testing, please hold this patch for a while.

**Review by NiuYawei — APPROVED** [review]

**Pull request merged**
