### PR TITLE
DAOS-3908: Fix Signal 6 Encountered with Rebuild Test.

### PR DESCRIPTION
**Pull request by PetFet**
Re-enabling test to verify fix merged from other PR.

Signed-off-by: Peter Fetros <peter.fetros@intel.com>

### CODE REVIEW

**Comment by PetFet** [comment]
This was fixed in a separate PR of mine related to a different bug.
Please confirm that I re-enabled the test properly.

**Comment by jolivier23** [comment]
is the test stuck?

**Comment by PetFet** [comment]
This PR is so old those tests didn't exist when it last ran. You can see the old hardware tests passed near the bottom. Now the new tests are just showing up.

I can run it back through CI if you'd like.

**Comment by jolivier23** [comment]
> This PR is so old those tests didn't exist when it last ran. You can see the old hardware tests passed near the bottom. Now the new tests are just showing up.
> 
> I can run it back through CI if you'd like.

that would be good, I think

**Pull request merged**
