### PR TITLE
DAOS-10624 build: Pin build to EL8.5

### PR DESCRIPTION
**Pull request by brianjmurrell**

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]

**Review by phender — DISMISSED** [review]

**Comment by phender** [comment]
Confirmed that tests currently skipped:
```
/scratch/CI-skip-list-master:[['DAOS-10624', 'test_method_name', 'test_cart_iv', 'config', 'two_node']]
/scratch/CI-skip-list-master:[['DAOS-10624', 'test_method_name', 'test_cart_corpc', 'config', 'two_node']]
/scratch/CI-skip-list-master:[['DAOS-10624', 'test_method_name', 'test_cart_corpc', 'config', 'five_node']]
```
where run and passed in this PR: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9080/7/testReport/FTEST_cart/

**Review by JohnMalmberg — DISMISSED** [review]

**Comment by johannlombardi** [comment]
failures don't seem to be known, right?

**Comment by johannlombardi** [comment]
Patch needs to merge master ...

**Review by JohnMalmberg — APPROVED** [review]

**Review by jolivier23 — COMMENTED** [review]
"So I'd advocate closing this and resolving [SRE-337](https://daosio.atlassian.net/browse/SRE-337) instead."

Ok  by me

**Comment by brianjmurrell** [comment]
[SRE-337](https://daosio.atlassian.net/browse/SRE-337) has long been closed.  Given that this PR was targeted at master I cannot see how it's even relevant any more.

**Pull request closed without merging**
