### PR TITLE
DAOS-6534: Functional tests evading Avocado timeout mechanism

### PR DESCRIPTION
**Pull request by phender**
Restoring removed break from while True loop that prevented avocado
tests from completing.

Adding the output of journalctl for each failed server if detected
during test tearDown().

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by phender** [comment]
Only one test failure

Test / Functional_Hardware_Large / FTEST_mdtest.MdtestSmall.1-./mdtest/mdtest_small.py:MdtestSmall.test_mdtest_small;transport_config-container-dfuse-transport_config-hosts-np_8-pool-transport_config-a3bd

Due to https://jira.hpdd.intel.com/browse/DAOS-6788

**Comment by brianjmurrell** [comment]
Didn't this used to have a test_framework test in it to prove the fix?

**Comment by phender** [comment]
> Didn't this used to have a test_framework test in it to prove the fix?

There is (some of it is still in https://github.com/daos-stack/daos/pull/4522; the rest I've been running locally), but the problem with it is the pass criteria includes allowing the avocado test to be interrupted, so making it usable inside CI requires a different approach.  In other words its not fully baked yet.

I did run it manually with this version of the patch applied: https://jira.hpdd.intel.com/browse/DAOS-6756?focusedCommentId=257824&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-257824

**Review by brianjmurrell — APPROVED** [review]

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Pull request merged**
