### PR TITLE
DAOS-6637 bio: Make the VMD LED duration configurable for identify cmd

### PR DESCRIPTION
**Pull request by sydneyvanda**
Introduce a VMD_LED_PERIOD environment variable that when set will allow
for a customizable LED blinking duration when the device identify command
is issued ($ dmg storage identify vmd --uuid=UUID)

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

### CODE REVIEW

**Review by NiuYawei — APPROVED** [review]

**Review by tanabarr — COMMENTED** [review]
change seems fine. but what is the rationale behind making this settable through an environment variable rather than the server config file? @mjmac @johannlombardi thoughts?

**Comment by mjmac** [comment]
> 
> 
> change seems fine. but what is the rationale behind making this settable through an environment variable rather than the server config file? @mjmac @johannlombardi thoughts?

I assume it's set in the per-engine environment section of the config file, right?

**Comment by tanabarr** [comment]
> > change seems fine. but what is the rationale behind making this settable through an environment variable rather than the server config file? @mjmac @johannlombardi thoughts?
> 
> I assume it's set in the per-engine environment section of the config file, right?

it's not at the moment but is that the plan @sydneyvanda ? maybe to be stored within the BdevConfig along with VmdDisable?

**Review by tanabarr — DISMISSED** [review]

**Comment by sydneyvanda** [comment]
I agree, I will make this a server config file variable. will update patch accordingly

**Review by tanabarr — DISMISSED** [review]

**Review by NiuYawei — DISMISSED** [review]

**Comment by johannlombardi** [comment]
Please merge master.

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Conflict needs to be resolved

**Review by tanabarr — APPROVED** [review]

**Pull request merged**
