### PR TITLE
DAOS-10593 control: Fix NVMe available space

### PR DESCRIPTION
**Pull request by knard-intel**
# Description

The available space of NVMe devices was miscalculated: it was based on the hypothesis that all NVMe devices of one engine were fairly shared by its targets. At the end, one target can only manage one NVMe device. For one engine, if the number of its targets is greater than the number of NVMe devices, then some NVMe devices are fairly shared by two or more targets.

# Validation

The go unit tests have been updated according to the fix of the NVMe available space calculation.

The HW Functional tests have also been updated consequently. More over, the number of targets of one engine is now multiplexed to check that this parameter is properly managed.

The HW functional tests are currently disabled (see [DAOS-10448](https://daosio.atlassian.net/browse/DAOS-10448)). To validate these modifications, the commit of this PR was temporarily modified to run and validate them: details of the Jenkins job validating this patch could be found at:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9203/1/tests

# Miscellaneous

Some python indentation issues were also fixed.

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]

**Review by tanabarr — APPROVED** [review]
go code changes looked good to me

**Review by kjacque — APPROVED** [review]

**Comment by knard-intel** [comment]
Find a small bug into python test code which should not have impact.
However, I prefer rerun the functional tests. To this end, the commit message has to be tweaked to run these tests: workaround with skip list. This, this commit will have to be rebased.

**Comment by knard-intel** [comment]
Fixed some minor python changes which have been validated with the following Jenkins jobs:
- https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9203/6/tests
- https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9203/8/tests

Some commit titles and tags has been rebased to test last modification on python functional tests.

**Review by shimizukko — APPROVED** [review]

**Review by tanabarr — APPROVED** [review]

**Review by mjmac — APPROVED** [review]
LGTM

**Review by kjacque — APPROVED** [review]

**Comment by knard-intel** [comment]
Ping @daos-stack/daos-gatekeeper

**Comment by mjmac** [comment]
@knard-intel: master landings are closed at the moment -- hopefully back open soon.

**Comment by knard-intel** [comment]
> @knard-intel: master landings are closed at the moment -- hopefully back open soon.

Ok, my apologies for the disturbance, I was not aware of that. Thanks for the info.

**Comment by knard-intel** [comment]
@daos-stack/daos-gatekeeper master landings seems to be open now ?
If yes, could it be possible to land it or something is missing ?

**Pull request merged**
