### PR TITLE
DAOS-8207 test: re-enable vol tests after being disabled

### PR DESCRIPTION
**Pull request by mchaarawi**
also revert commit 75a46e5.
as that change does not work for HDF5-VOL IOR tests.
 
Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Comment by saurabhtandan** [comment]
@mchaarawi , Let me see the code what is breaking that test and if we can avoid a revert and get a solution to it rather.

**Comment by mchaarawi** [comment]
> @mchaarawi , Let me see the code what is breaking that test and if we can avoid a revert and get a solution to it rather.

since this PR is passing, i would rather get it landed since all the vol tests (not just IOR) are disabled.
so it's a high priority to get this landed

**Review by sylviachanoiyee — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
We do have other tests running ior with rp_2gx over dfs, aggregation basic is one example, though the API coverage is not as wide as ior_small.py
But I do think this pr is important considering we have 0 vol test running in CI.

**Review by jolivier23 — APPROVED** [review]

**Comment by saurabhtandan** [comment]
My PR with the fix https://github.com/daos-stack/daos/pull/6482 is pushed, but the nexus issue caused delay yesterday. If nobody objects waiting for one more day or may be end of day today for vol tests, and we can just land the fix instead, that will be great. It's just a matter of few hours IMO.

**Comment by mchaarawi** [comment]
> My PR with the fix #6482 is pushed, but the nexus issue caused delay yesterday. If nobody objects waiting for one more day or may be end of day today for vol tests, and we can just land the fix instead, that will be great. It's just a matter of few hours IMO.

sorry im going to object. this has been ready since the weekend, and i will have to rebase and push again and wait for test.
whereas yours hasn't gone through CI and can wait still.

**Comment by saurabhtandan** [comment]
> > My PR with the fix #6482 is pushed, but the nexus issue caused delay yesterday. If nobody objects waiting for one more day or may be end of day today for vol tests, and we can just land the fix instead, that will be great. It's just a matter of few hours IMO.
> 
> sorry im going to object. this has been ready since the weekend, and i will have to rebase and push again and wait for test.
> whereas yours hasn't gone through CI and can wait still.

You might not need to rebase, this PR can be closed after. I have incorporated the vol test enabling in my PR. But still if you want to go ahead it's fine. Just putting it out, that it's going to be a matter of few hours only.

**Comment by mchaarawi** [comment]
> You might not need to rebase, this PR can be closed after. I have incorporated the vol test enabling in my PR. But still if you want to go ahead it's fine. Just putting it out, that it's going to be a matter of few hours only.

OK if your PR re-enables VOL and the test tags to test all VOL, and passes, and can be reviewed/landed today before COB, then im ok with not landing this.

**Comment by mchaarawi** [comment]
> > You might not need to rebase, this PR can be closed after. I have incorporated the vol test enabling in my PR. But still if you want to go ahead it's fine. Just putting it out, that it's going to be a matter of few hours only.
> 
> OK if your PR re-enables VOL and the test tags to test all VOL, and passes, and can be reviewed/landed today before COB, then im ok with not landing this.

I just realized that your PR is not re-enabling the IOR small HDF5-VOL tests, which were the problem and why i had to revert your patch. so as is, your PR is not testing HDF5-VOL with IOR.

**Comment by saurabhtandan** [comment]
All vol tests and iorsmall test passed in #6482 (including HDF5-VOL)

**Pull request merged**
