### PR TITLE
DAOS-8938 test: fix str conversion for set_attr

### PR DESCRIPTION
**Pull request by daltonbohning**
Test-tag: pr daos_cmd DaosBuild
Skip-unit-tests: true
Skip-fault-injection-test: true

Commit 3934417 accidentally removed the implicit string conversion for set_attr, so make it explicit to cover all cases.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by ashleypittman — APPROVED** [review]
It bugs me that the pool ones are values but the container ones are vals

**Review by mjmac — APPROVED** [review]
LGTM, thanks. Maybe we should add the `daos_cmd` tag to whichever tests were broken by the change? I added that so that we can find the set of tests that need to be run whenever any significant changes to the daos command surface are made.

**Comment by daltonbohning** [comment]
> Maybe we should add the `daos_cmd` tag to whichever tests were broken by the change? I added that so that we can find the set of tests that need to be run whenever any significant changes to the daos command surface are made.

We **could**, but literally almost every test uses the daos command in some way. Ultimately, I think we should have standalone tests for each of the daos commands, and those tests should have the `daos_cmd` tag. Then, any other tests using daos commands can reasonably assume they work as long as the core `daos_cmd` tests do.
Unfortunately, tagging changes like this haven't been a high priority lately.

**Comment by mjmac** [comment]
> We **could**, but literally almost every test uses the daos command in some way. 
>
Sure, but I'm not suggesting that we add the tag to every test that uses the daos command. I'm observing that there is likely a relatively small subset of tests with unique uses of the command, and this would be a good set of tests to run whenever we make changes to the command surface in order to catch regressions before landing.

> Ultimately, I think we should have standalone tests for each of the daos commands, and those tests should have the `daos_cmd` tag. Then, any other tests using daos commands can reasonably assume they work as long as the core `daos_cmd` tests do. Unfortunately, tagging changes like this haven't been a high priority lately.
>
I'm not a big fan of those kinds of synthetic tests, because they rely on someone bothering to keep them updated with all of the various ways that the commands get used. Our CI process is already groaning under the strain of dozens of redundant tests being run pointlessly for each PR because we aren't confident that we understand what needs to be tested for PRs. Adding yet another set of synthetic test cases that will drift out of sync with actual usage doesn't seem all that helpful to me.

**Comment by ashleypittman** [comment]
> > Maybe we should add the `daos_cmd` tag to whichever tests were broken by the change? I added that so that we can find the set of tests that need to be run whenever any significant changes to the daos command surface are made.
> 
> We **could**, but literally almost every test uses the daos command in some way. Ultimately, I think we should have standalone tests for each of the daos commands, and those tests should have the `daos_cmd` tag. Then, any other tests using daos commands can reasonably assume they work as long as the core `daos_cmd` tests do. Unfortunately, tagging changes like this haven't been a high priority lately.

This wasn't broken by a change to daos or the go code, it was the change to ftest/util that's caused the issue.  Sometimes things have unintended consequences and I think this is a case where fixing it and moving on is quickest, it's not like we're expecting more major changes in this area.

If I was going to make any suggestion for ways to prevent this it would be that changes to ftest/util should pick up a wider set of tests, possibly daily_regression rather than pr but as yet we don't have a mechanism for dynamically choosing the default test-tags based on what's modified.

**Comment by daltonbohning** [comment]
> Sure, but I'm not suggesting that we add the tag to every test that uses the daos command. I'm observing that there is likely a relatively small subset of tests with unique uses of the command, and this would be a good set of tests to run whenever we make changes to the command surface in order to catch regressions before landing.

I agree with what Ashley said. This particular failure wasn't because of changes to the command itself, but changes to the utility. And if we add too many tags to a test, it becomes messier to maintain. We could add the tag to this one test, but that's a reactive approach, rather than proactive. I think we need a more proactive solution (see below for one generic example)

> I'm not a big fan of those kinds of synthetic tests, because they rely on someone bothering to keep them updated with all of the various ways that the commands get used. Our CI process is already groaning under the strain of dozens of redundant tests being run pointlessly for each PR because we aren't confident that we understand what needs to be tested for PRs. Adding yet another set of synthetic test cases that will drift out of sync with actual usage doesn't seem all that helpful to me.

I can agree with that :)


> If I was going to make any suggestion for ways to prevent this it would be that changes to ftest/util should pick up a wider set of tests, possibly daily_regression rather than pr but as yet we don't have a mechanism for dynamically choosing the default test-tags based on what's modified.

Personally, I find it's more often the full_regression tests that have unique use cases. I.e. are prone to these issues. An indirect solution we've been working on is to just write more robust utilities to begin with, and architect them in such a way that edge cases are less common.

**Comment by daltonbohning** [comment]
Unrelated failures:
- FTEST_daos_test.DAOS_Rebuild_EC - doesn't use set-attr
  - https://daosio.atlassian.net/browse/DAOS-12709
- nvme/pool_exclude.py - doesn't use set-attr
  - created ticket  https://daosio.atlassian.net/browse/DAOS-12713
- dfuse/daos_build.py
  - set-attr calls are working: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11534/2/artifact/Functional%20Hardware%20Medium/dfuse/daos_build.py/job.log
  - Failure looks like a dfuse crash

**Comment by ashleypittman** [comment]
dfuse/daos_build.py failure is https://daosio.atlassian.net/browse/DAOS-12075

I've re-triggered testing for this one.

**Pull request merged**
