### PR TITLE
DAOS-10602 build: Update DAOS-SPDK source build version to align with…

### PR DESCRIPTION
**Pull request by tanabarr**
… RPM

Align source build SPDK version with RPM packaging version v22.01.1 ->
v22.01.2.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]

**Review by brianjmurrell — COMMENTED** [review]
Wouldn't you need to update `daos.spec` and  `debian/*` in the same way you did in #10843?

**Comment by jolivier23** [comment]
> Wouldn't you need to update `daos.spec` and `debian/*` in the same way you did in #10843?

Good question.  A secondary question is why did we update the spec and debian files in master branch?

**Comment by brianjmurrell** [comment]
> Good question. A secondary question is why did we update the spec and debian files in master branch?

Not to sound sarcastic or anything like that as this is a genuine question that I just can't seem to find better words for but why wouldn't we update those?  Clearly I am completely missing your perspective.

**Comment by tanabarr** [comment]
> > Good question. A secondary question is why did we update the spec and debian files in master branch?
> 
> Not to sound sarcastic or anything like that as this is a genuine question that I just can't seem to find better words for but why wouldn't we update those? Clearly I am completely missing your perspective.

So on the master branch we want to be using SPDK v22.01.2 with DAOS to enable the capability to emulate hotplug with VMD.  On release/2.2 we don't need to be using v22.01.2 with DAOS because we are not supporting hotplug with VMD and haven't landed the relevant code to do the emulation. Therefore we don't need to require v22.01.2 in the daos.spec in this PR (release/2.2), but we do however want to keep the version used in source builds synchronised with the version used in RPM/deb builds on release/2.2. So if the v22.01.2 RPM is available then in a source build we should also pull in the same version, but we don't need to require it in the daos.spec. IMO this is an awkwardness caused by the fact we share the same packaging branches across different DAOS release branches. Does this make sense?

**Pull request merged**
