### PR TITLE
DAOS-7014 control: fix dmg system start segfault

### PR DESCRIPTION
**Pull request by tanabarr**
Sync WaitGroup used to know when to start collecting telemetry data can
be decremented below zero when an engine exits and is restarted within
the lifetime of a daos_server process. WaitGroup should be reset on
engine process exit.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Comment by tanabarr** [comment]
converted back to draft as it's not quite ready yet

**Comment by tanabarr** [comment]
@liw or @NiuYawei would you mind verifying this fixes the issue for you please, I've tested and it seems to resolve the problem on my side.

**Comment by tanabarr** [comment]
@johannlombardi perhaps we can prioritise landing this

**Comment by tanabarr** [comment]
From the following 2 CI runs https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-4980/6/pipeline https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-4980/5/pipeline , we can see that all tests pass and there are no changes in the PR inbetween (just master merges)

**Review by jbrosenz — APPROVED** [review]
LGTM.  Thank's Tom.

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
