### PR TITLE
DAOS-15654 control: Ignore NEW state NVMe devices when processing spa…

### PR DESCRIPTION
**Pull request by tanabarr**
…ce stats

NEW devices should be ignored Rather than causing a failure, situation
occurs when number of targets is less than the number of SSDs.

Features: control

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by kjacque — CHANGES_REQUESTED** [review]
Changes look good. I think we need a unit test for this change in behavior though.

**Comment by tanabarr** [comment]
> Changes look good. I think we need a unit test for this change in behavior though.

Good point. I think there isn't one actually so I will add one.

**Review by janekmi — APPROVED** [review]
I am no expert in Go but it looks reasonable. It also does the thing:

- [Before the fix](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13909/30/testReport/FTEST_aggregation/AggregationChecksum/Test_Hardware___Functional_Hardware_Medium___1___aggregation_checksum_py_AggregationChecksum_test_aggregationchecksum_run_container_hosts_ior_client_processes_objectclass_SX_transfersize_blocksize_2K_pool_server_config_engines_0_storage_0_1_26ad/)
- [After the fix](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14157/20/testReport/FTEST_aggregation/AggregationChecksum/Test_Hardware___Functional_Hardware_Medium___1___aggregation_checksum_py_AggregationChecksum_test_aggregationchecksum_run_container_hosts_ior_client_processes_objectclass_SX_transfersize_blocksize_2K_pool_server_config_engines_0_storage_0_1_26ad/)

Thanks @tanabarr!

**Review by kjacque — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]
LGTM

**Comment by tanabarr** [comment]
@daos-stack/daos-gatekeeper Can this PR be landed please?

**Pull request merged**
