### PR TITLE
DAOS-7070 build: Remove unused readline-devel from build

### PR DESCRIPTION
**Pull request by jolivier23**
Skip-func-test: true
Skip-unit-test: true

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

### CODE REVIEW

**Review by ashleypittman — APPROVED** [review]
I wonder how many more of these we have out there.

**Comment by jolivier23** [comment]
> I wonder how many more of these we have out there.

we probably do need to do a scrub

**Review by brianjmurrell — DISMISSED** [review]
Seems fine.  Any idea why one of the UT stages failed?

**Comment by jolivier23** [comment]
Don't see how this would have caused whatever failed so adding gatekeeper since I'm out and not having a VPN available to look

**Comment by ashleypittman** [comment]
> Don't see how this would have caused whatever failed so adding gatekeeper since I'm out and not having a VPN available to look

I've had a look and can't see where it failed.

**Comment by brianjmurrell** [comment]
> > Don't see how this would have caused whatever failed so adding gatekeeper since I'm out and not having a VPN available to look
> 
> I've had a look and can't see where it failed.

```
[2021-03-24T07:11:19.308Z]     wolf-125: rc=1, output:
[2021-03-24T07:11:19.308Z]       Logging get_remote_files.sh output to /tmp/get_remote_files_20210324_070942.log
[2021-03-24T07:11:19.308Z]       Checking if files exceed 1G threshold ...
[2021-03-24T07:11:19.308Z]         N: 8370 /var/tmp/daos_testing/DAOS_Checksum_daos_admin.log
[2021-03-24T07:11:19.308Z]         N: 315130 /var/tmp/daos_testing/DAOS_Checksum_daos_control.log
[2021-03-24T07:11:19.308Z]         N: 69164895 /var/tmp/daos_testing/DAOS_Checksum_daos_server_0.log
[2021-03-24T07:11:19.308Z]         N: 87505476 /var/tmp/daos_testing/DAOS_Checksum_daos_server_1.log
[2021-03-24T07:11:19.308Z]         N: 8370 /var/tmp/daos_testing/DAOS_Degraded_Mode_daos_admin.log
[2021-03-24T07:11:19.308Z]         N: 15528 /var/tmp/daos_testing/DAOS_Degraded_Mode_daos_control.log
[2021-03-24T07:11:19.308Z]         N: 34673593 /var/tmp/daos_testing/DAOS_Degraded_Mode_daos_server_0.log
[2021-03-24T07:11:19.308Z]         N: 1008628 /var/tmp/daos_testing/DAOS_Degraded_Mode_daos_server_1.log
[2021-03-24T07:11:19.308Z]         N: 8370 /var/tmp/daos_testing/DAOS_Management_daos_admin.log
[2021-03-24T07:11:19.308Z]         N: 14841 /var/tmp/daos_testing/DAOS_Management_daos_control.log
[2021-03-24T07:11:19.308Z]         N: 109703168 /var/tmp/daos_testing/DAOS_Management_daos_server_0.log
[2021-03-24T07:11:19.308Z]         N: 91178101 /var/tmp/daos_testing/DAOS_Management_daos_server_1.log
[2021-03-24T07:11:19.308Z]       Running /usr/lib/daos/TESTING/ftest/cart/cart_logtest.py ...
[2021-03-24T07:11:19.309Z]         Error: details in /var/tmp/daos_testing/DAOS_Management_daos_server_0.log_cart_testlog
```

and https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5131/2/artifact/Functional_Hardware_Medium/daos_test/daos_core_test.py/daos_logs/DAOS_Management_daos_server_0.wolf-125.cart_logtest.log:

```
Traceback (most recent call last):
  File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 729, in <module>
    run()
  File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 720, in run
    test_iter.check_log_file(args.warnings)
  File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 305, in check_log_file
    show_memleaks=show_memleaks)
  File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 368, in _check_pid_from_log_file
    self.save_log_line(line)
  File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 252, in save_log_line
    function = getattr(line, 'filename', None)
  File "/usr/lib/daos/TESTING/ftest/cart/cart_logparse.py", line 189, in __getattr__
    (filename, _) = self._fields[0].split(':')
IndexError: list index out of range
```

**Comment by ashleypittman** [comment]
> > > Don't see how this would have caused whatever failed so adding gatekeeper since I'm out and not having a VPN available to look
> > 
> > 
> > I've had a look and can't see where it failed.
> 
> ```
> [2021-03-24T07:11:19.308Z]     wolf-125: rc=1, output:
> [2021-03-24T07:11:19.308Z]       Logging get_remote_files.sh output to /tmp/get_remote_files_20210324_070942.log
> [2021-03-24T07:11:19.308Z]       Checking if files exceed 1G threshold ...
> [2021-03-24T07:11:19.308Z]         N: 8370 /var/tmp/daos_testing/DAOS_Checksum_daos_admin.log
> [2021-03-24T07:11:19.308Z]         N: 315130 /var/tmp/daos_testing/DAOS_Checksum_daos_control.log
> [2021-03-24T07:11:19.308Z]         N: 69164895 /var/tmp/daos_testing/DAOS_Checksum_daos_server_0.log
> [2021-03-24T07:11:19.308Z]         N: 87505476 /var/tmp/daos_testing/DAOS_Checksum_daos_server_1.log
> [2021-03-24T07:11:19.308Z]         N: 8370 /var/tmp/daos_testing/DAOS_Degraded_Mode_daos_admin.log
> [2021-03-24T07:11:19.308Z]         N: 15528 /var/tmp/daos_testing/DAOS_Degraded_Mode_daos_control.log
> [2021-03-24T07:11:19.308Z]         N: 34673593 /var/tmp/daos_testing/DAOS_Degraded_Mode_daos_server_0.log
> [2021-03-24T07:11:19.308Z]         N: 1008628 /var/tmp/daos_testing/DAOS_Degraded_Mode_daos_server_1.log
> [2021-03-24T07:11:19.308Z]         N: 8370 /var/tmp/daos_testing/DAOS_Management_daos_admin.log
> [2021-03-24T07:11:19.308Z]         N: 14841 /var/tmp/daos_testing/DAOS_Management_daos_control.log
> [2021-03-24T07:11:19.308Z]         N: 109703168 /var/tmp/daos_testing/DAOS_Management_daos_server_0.log
> [2021-03-24T07:11:19.308Z]         N: 91178101 /var/tmp/daos_testing/DAOS_Management_daos_server_1.log
> [2021-03-24T07:11:19.308Z]       Running /usr/lib/daos/TESTING/ftest/cart/cart_logtest.py ...
> [2021-03-24T07:11:19.309Z]         Error: details in /var/tmp/daos_testing/DAOS_Management_daos_server_0.log_cart_testlog
> ```
> 
> and https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5131/2/artifact/Functional_Hardware_Medium/daos_test/daos_core_test.py/daos_logs/DAOS_Management_daos_server_0.wolf-125.cart_logtest.log:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 729, in <module>
>     run()
>   File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 720, in run
>     test_iter.check_log_file(args.warnings)
>   File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 305, in check_log_file
>     show_memleaks=show_memleaks)
>   File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 368, in _check_pid_from_log_file
>     self.save_log_line(line)
>   File "/usr/lib/daos/TESTING/ftest/cart/cart_logtest.py", line 252, in save_log_line
>     function = getattr(line, 'filename', None)
>   File "/usr/lib/daos/TESTING/ftest/cart/cart_logparse.py", line 189, in __getattr__
>     (filename, _) = self._fields[0].split(':')
> IndexError: list index out of range
> ```

Ah, and looking at the daos log file it ends like this:

```
718953 03/24-06:47:17.58 wolf-125 DAOS[103522/103522] server INFO src/engine/module.c:322 dss_module_cleanup_all() Module cont: no sm_cleanup func
718954 03/24-06:47:17.58 wolf-125 DAOS[103522/103522] server INFO src/engine/module.c:325 dss_module_cleanup_all() Module pool: invoke sm_cleanup func
718955 03/24-06:47:17.58 wolf-125 DAOS[103522/103522] server INFO src/engine/module.c:332 dss_module_cleanup_all() Module pool: cleaned up
718956 03/24-06:47:17.58 wolf-125 DAOS[103522/103522] server INFO src/engine/module.c:322 dss_module_cleanup_all() Module dtx: no sm_cleanup func
718957 03/24-06:47:17.58 wolf-125 DAOS[103522/103522] server INFO src/engine/module.c:325 dss_module_cleanup_all() Module mgmt: invoke sm_cleanup func
718958 03/24-06:47:17.58 wolf-125 DAOS[103522/103522] server ERR
```
Looks like the log file is truncated somehow, whist logging an error.  Not a failure mode I'm famliar with, we should at least re-trigger testing on this (or merge with master).

**Review by johannlombardi — DISMISSED** [review]

**Comment by johannlombardi** [comment]
please merge master

**Review by johannlombardi — APPROVED** [review]

**Pull request merged**
