### PR TITLE
DAOS-8432 ci: Move EL8 testing to 8.5

### PR DESCRIPTION
**Pull request by johannlombardi**
EL8-version: 8.5.2111
Quick-Functional: true
Test-tag: pr daily_regression
Allow-unstable-test: true
Skip-PR-comments: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

### CODE REVIEW

**Review by phender — APPROVED** [review]

**Comment by johannlombardi** [comment]
Patch eventually passed the CI. Shall we land it? @phender

**Comment by brianjmurrell** [comment]
> Patch eventually passed the CI. Shall we land it? @phender

A couple of issues with going ahead and landing this:

1. None of the RPM installation test stages was run and this PR specifically adds an 8.4 installation test so that code, and the build are not tested on 8.4.
2. This PR is changing/testing the assumption that "centos8" in is 8.5 when in reality it's still 8.3, so this PR does not represent what testing will look like when it lands (i.e. release/2.0 doesn't have the **EL8-version: 8.5.2111** pragma making "centos8" actually be 8.5 and not 8.3.

The whole concept of "build on diistro version x.y and test on [other_]distro a.b" was never identified as a requirement and so the infrastructure doesn't really support it.  It was never identified that we'd support anything except the latest supported release.

So there is work needed to make this kind of cross distro/version functionality workable and make this PR actually work as intended along with other branches (i.e. master->release/2.2) that have different distro support requirements before this can land and function as it is in this PR.  This is DAOS-9802.

**Comment by johannlombardi** [comment]
> It was never identified that we'd support anything except the latest supported release.

@brianjmurrell I am shocked by this sentence TBH. Only supporting the latest was absolutely never a requirement. I have no idea where this comes from.

**Comment by brianjmurrell** [comment]
> @brianjmurrell I am shocked by this sentence TBH. Only supporting the latest was absolutely never a requirement. I have no idea where this comes from.

@johannlombardi  Exactly.  The problem is what we would support was never stated as a requirement (way back when all of the CI code was originally written) at all so it was left to assume that it would only be the latest, given that the latest is the only actually supported release.  Anything prior gets **no** updates, including security, so it wasn't reasonable (IMHO) to assume that we would not support such releases.

**Pull request closed without merging**
