### PR TITLE
DAOS-4862 tests: Correct test harness CRT_CTX_SHARE_ADDR usage

### PR DESCRIPTION
**Pull request by phender**
Ensuring the CRT_CTX_SHARE_ADDR setting configured in launch.py is the
default value used to create the daos_server yaml configuration file.
To allow easier custimization the CRT_CTX_SHARE_ADDR and CRT_TIMEOUT
values are now specified using the 'crt_ctx_share_addr' and
'crt_timeout' configuration file entries, respectively, instead of
being defiend as part of 'env_vars'.

The network/cart_self_test.py test has also been updated to ensure the
CRT_CTX_SHARE_ADDR value is configured the same in the daos_server
configuration file.

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by phender** [comment]
All the test failures in [Build 1](https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-2718/1/) are known issues:
- control/daos_control_config.py: [DAOS-3945](https://jira.hpdd.intel.com/browse/DAOS-3945)
- io/fio_small.py: [DAOS-4850](https://jira.hpdd.intel.com/browse/DAOS-4850)
- io/ior_small.py: [DAOS-4850](https://jira.hpdd.intel.com/browse/DAOS-4850)
- io/mdtest_small.py: [DAOS-4850](https://jira.hpdd.intel.com/browse/DAOS-4850)
- daos_test/daos_core_test-rebuild.py: [DAOS-4623](https://jira.hpdd.intel.com/browse/DAOS-4623)

**Comment by phender** [comment]
All of the network/cart_self_test.py variants passed:
https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-2718/1/artifact/Functional/job-2020-05-15T02.06-0d38a56-network-cart_self_test/results.html

**Comment by phender** [comment]
Failures seen in [Build 2](https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-2718/2) are known issues:
- io/hdf5.py: https://jira.hpdd.intel.com/browse/DAOS-4451
- daos_test/daos_core_test-rebuild.py (test_r_1-10): https://jira.hpdd.intel.com/browse/DAOS-4623

**Comment by mjmac** [comment]
Actually, in light of the work being done for [DAOS-4671](https://jira.hpdd.intel.com/browse/DAOS-4671), is there any reason to land this?

**Comment by frostedcmos** [comment]
> This looks fine to me, but just FYI since @jbrosenz's PR #2527 has landed to master, I think that CRT_CTX_SHARE_ADDR is no longer configurable on the client side. It won't hurt to set it, but I believe it's ignored now.

This might be true for daos clients, however cart level tests or tools that are launched in CI such as self_test or cart_ctl still rely on explicit setup of envariables, so this is still relevant

**Comment by mjmac** [comment]
> This might be true for daos clients, however cart level tests or tools that are launched in CI such as self_test or cart_ctl still rely on explicit setup of envariables, so this is still relevant

Ah, right. Didn't think about those tests. OK, makes sense to land, then.

**Pull request merged**
