### PR TITLE
DAOS-3571 tests: Improve launch.py remote cmd error messages

### PR DESCRIPTION
**Pull request by phender**
Enhance the existing launch.,py messaging to include details about any
remote command failures in addition to the current return code provided
today.

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
@phender, @amjustin13 Can you merge this into @amjustin13's patch so that we can see that it's doing what's intended and can see why the logs aren't getting collected in her patch before we land this as is.  Whatever's going on in her patch might highlight something else that needs doing in this patch.

**Comment by amjustin13** [comment]
@brianjmurrell, I pushed a commit including the changes in this PR to PR1008.

**Comment by brianjmurrell** [comment]
> @brianjmurrell, I pushed a commit including the changes in this PR to PR1008.

Yup, just saw the commit to #1008 with it in.  Will be most interested in seeing what the log collection error is in that.

**Comment by phender** [comment]
Are we happy with the current level of debug/output that this produces (6 lines of output per file per host when successful) when archiving the log files at the end of each test?  Given that the `set -x` includes the `hostname -s` and `ls -al` command output we lose the efficiency of the listing the same output for multiple hosts.  Granted, for #1008, having this output proved very useful.

Example normal output for one host:
```
03:07:57.852      wolf-116: rc=0, output: 
03:07:57.852        + ls -al /tmp/daos_control.log
03:07:57.852        -rw-rw-r-- 1 jenkins jenkins 45135 Oct 31 14:43 /tmp/daos_control.log
03:07:57.852        ++ hostname -s
03:07:57.852        + scp /tmp/daos_control.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/daos_control.log-wolf-116
03:07:57.852        + sudo -n rm -fr /tmp/daos_control.log
03:07:57.852        + set +x
03:07:57.852        + ls -al /tmp/server.log
03:07:57.852        -rw-rw-r-- 1 jenkins jenkins 375055 Oct 31 14:43 /tmp/server.log
03:07:57.852        ++ hostname -s
03:07:57.852        + scp /tmp/server.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/server.log-wolf-116
03:07:57.852        + sudo -n rm -fr /tmp/server.log
03:07:57.852        + set +x
```

Example worst case scenario for one host:
```
03:07:57.853      wolf-51: rc=0, output: 
03:07:57.853        + ls -al /tmp/daos_agent.log
03:07:57.853        -rw-rw-r-- 1 jenkins jenkins 525 Oct 31 14:42 /tmp/daos_agent.log
03:07:57.853        ++ hostname -s
03:07:57.853        + scp /tmp/daos_agent.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/daos_agent.log-wolf-51
03:07:57.853        + sudo -n rm -fr /tmp/daos_agent.log
03:07:57.853        + set +x
03:07:57.853        + ls -al /tmp/Functional_pr,hw/rebuild_tests_0-16_client_daos.log
03:07:57.853        -rw-rw-r-- 1 jenkins jenkins 3906 Oct 31 14:28 /tmp/Functional_pr,hw/rebuild_tests_0-16_client_daos.log
03:07:57.853        ++ hostname -s
03:07:57.853        + scp /tmp/Functional_pr,hw/rebuild_tests_0-16_client_daos.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/rebuild_tests_0-16_client_daos.log-wolf-51
03:07:57.853        + sudo -n rm -fr /tmp/Functional_pr,hw/rebuild_tests_0-16_client_daos.log
03:07:57.853        + set +x
03:07:57.853        + ls -al /tmp/Functional_pr,hw/rebuild_tests_18-24_client_daos.log
03:07:57.853        -rw-rw-r-- 1 jenkins jenkins 4731 Oct 31 14:33 /tmp/Functional_pr,hw/rebuild_tests_18-24_client_daos.log
03:07:57.853        ++ hostname -s
03:07:57.853        + scp /tmp/Functional_pr,hw/rebuild_tests_18-24_client_daos.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/rebuild_tests_18-24_client_daos.log-wolf-51
03:07:57.853        + sudo -n rm -fr /tmp/Functional_pr,hw/rebuild_tests_18-24_client_daos.log
03:07:57.853        + set +x
03:07:57.853        + ls -al /tmp/Functional_pr,hw/rebuild_tests_25_client_daos.log
03:07:57.853        -rw-rw-r-- 1 jenkins jenkins 410 Oct 31 14:35 /tmp/Functional_pr,hw/rebuild_tests_25_client_daos.log
03:07:57.853        ++ hostname -s
03:07:57.853        + scp /tmp/Functional_pr,hw/rebuild_tests_25_client_daos.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/rebuild_tests_25_client_daos.log-wolf-51
03:07:57.853        + sudo -n rm -fr /tmp/Functional_pr,hw/rebuild_tests_25_client_daos.log
03:07:57.853        + set +x
03:07:57.853        + ls -al /tmp/Functional_pr,hw/rebuild_tests_26_client_daos.log
03:07:57.853        -rw-rw-r-- 1 jenkins jenkins 410 Oct 31 14:36 /tmp/Functional_pr,hw/rebuild_tests_26_client_daos.log
03:07:57.853        ++ hostname -s
03:07:57.853        + scp /tmp/Functional_pr,hw/rebuild_tests_26_client_daos.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/rebuild_tests_26_client_daos.log-wolf-51
03:07:57.853        + sudo -n rm -fr /tmp/Functional_pr,hw/rebuild_tests_26_client_daos.log
03:07:57.853        + set +x
03:07:57.853        + ls -al /tmp/Functional_pr,hw/rebuild_tests_27_client_daos.log
03:07:57.853        -rw-rw-r-- 1 jenkins jenkins 525 Oct 31 14:38 /tmp/Functional_pr,hw/rebuild_tests_27_client_daos.log
03:07:57.853        ++ hostname -s
03:07:57.853        + scp /tmp/Functional_pr,hw/rebuild_tests_27_client_daos.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/rebuild_tests_27_client_daos.log-wolf-51
03:07:57.853        + sudo -n rm -fr /tmp/Functional_pr,hw/rebuild_tests_27_client_daos.log
03:07:57.853        + set +x
03:07:57.853        + ls -al /tmp/Functional_pr,hw/rebuild_tests_28_client_daos.log
03:07:57.853        -rw-rw-r-- 1 jenkins jenkins 2071 Oct 31 14:42 /tmp/Functional_pr,hw/rebuild_tests_28_client_daos.log
03:07:57.853        ++ hostname -s
03:07:57.853        + scp /tmp/Functional_pr,hw/rebuild_tests_28_client_daos.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/rebuild_tests_28_client_daos.log-wolf-51
06:16:18.110        + sudo -n rm -fr /tmp/Functional_pr,hw/rebuild_tests_28_client_daos.log
06:16:18.110        + set +x
06:16:18.110        + ls -al /tmp/Functional_pr,hw/rebuild_tests_31_client_daos.log
06:16:18.110        -rw-rw-r-- 1 jenkins jenkins 5010 Oct 31 14:46 /tmp/Functional_pr,hw/rebuild_tests_31_client_daos.log
06:16:18.110        ++ hostname -s
06:16:18.110        + scp /tmp/Functional_pr,hw/rebuild_tests_31_client_daos.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/rebuild_tests_31_client_daos.log-wolf-51
06:16:18.110        + sudo -n rm -fr /tmp/Functional_pr,hw/rebuild_tests_31_client_daos.log
06:16:18.110        + set +x
06:16:18.110        + ls -al /tmp/Functional_pr,hw/daos.log
06:16:18.110        -rw-rw-r-- 1 jenkins jenkins 2730 Oct 31 14:46 /tmp/Functional_pr,hw/daos.log
06:16:18.110        ++ hostname -s
06:16:18.110        + scp /tmp/Functional_pr,hw/daos.log wolf-51:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1008/src/tests/ftest/avocado/job-results/latest/daos_logs/daos.log-wolf-51
06:16:18.110        + sudo -n rm -fr /tmp/Functional_pr,hw/daos.log
06:16:18.110        + set +x
```

**Comment by phender** [comment]
Examples of the log file archive logging with the recent code changes:
```
[2019-11-01T01:16:35.049Z] Running on wolf-[52,122-129]: set -Eeu; rc=0; copied=(); for file in /tmp/daos_agent.log /tmp/Functional_pr,hw/*_client_daos.log /tmp/daos_control.log /tmp/Functional_pr,hw/*_server_daos.log /tmp/Functional_pr,hw/daos.log /tmp/Functional_pr,hw/rebuild_tests_31_server_daos.log; do if [ -e $file ]; then if scp $file wolf-52:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1320/src/tests/ftest/avocado/job-results/latest/daos_logs/${file##*/}-$(hostname -s); then copied+=($file); if ! sudo -n rm -fr $file; then ((rc++)); ls -al $file; fi; else ((rc++)); ls -al $file; fi; fi; done; echo Copied ${copied[@]}; exit $rc
[2019-11-01T01:16:35.049Z]     wolf-[122-129]: rc=0, output: Copied /tmp/daos_control.log /tmp/Functional_pr,hw/rebuild_tests_0-16_server_daos.log /tmp/Functional_pr,hw/rebuild_tests_18-24_server_daos.log /tmp/Functional_pr,hw/rebuild_tests_25_server_daos.log /tmp/Functional_pr,hw/rebuild_tests_26_server_daos.log /tmp/Functional_pr,hw/rebuild_tests_27_server_daos.log /tmp/Functional_pr,hw/rebuild_tests_28_server_daos.log /tmp/Functional_pr,hw/rebuild_tests_31_server_daos.log
[2019-11-01T01:16:35.049Z]     wolf-52: rc=0, output: Copied /tmp/daos_agent.log /tmp/Functional_pr,hw/rebuild_tests_0-16_client_daos.log /tmp/Functional_pr,hw/rebuild_tests_18-24_client_daos.log /tmp/Functional_pr,hw/rebuild_tests_25_client_daos.log /tmp/Functional_pr,hw/rebuild_tests_26_client_daos.log /tmp/Functional_pr,hw/rebuild_tests_27_client_daos.log /tmp/Functional_pr,hw/rebuild_tests_28_client_daos.log /tmp/Functional_pr,hw/rebuild_tests_31_client_daos.log /tmp/Functional_pr,hw/daos.log
```

```
[2019-11-01T01:23:29.536Z] Running on wolf-[52,122-129]: set -Eeu; rc=0; copied=(); for file in /tmp/daos_agent.log /tmp/Functional_pr,hw/*_client_daos.log /tmp/daos_control.log /tmp/Functional_pr,hw/*_server_daos.log /tmp/Functional_pr,hw/daos.log /tmp/Functional_pr,hw/ior_small.py-7_server_daos.log; do if [ -e $file ]; then if scp $file wolf-52:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1320/src/tests/ftest/avocado/job-results/latest/daos_logs/${file##*/}-$(hostname -s); then copied+=($file); if ! sudo -n rm -fr $file; then ((rc++)); ls -al $file; fi; else ((rc++)); ls -al $file; fi; fi; done; echo Copied ${copied[@]}; exit $rc
[2019-11-01T01:23:29.536Z]     wolf-[122-125]: rc=0, output: Copied /tmp/daos_control.log /tmp/Functional_pr,hw/ior_small.py-1_server_daos.log /tmp/Functional_pr,hw/ior_small.py-2_server_daos.log /tmp/Functional_pr,hw/ior_small.py-3_server_daos.log /tmp/Functional_pr,hw/ior_small.py-4_server_daos.log /tmp/Functional_pr,hw/ior_small.py-5_server_daos.log /tmp/Functional_pr,hw/ior_small.py-6_server_daos.log /tmp/Functional_pr,hw/ior_small.py-7_server_daos.log
[2019-11-01T01:23:29.536Z]     wolf-52: rc=0, output: Copied /tmp/daos_agent.log /tmp/Functional_pr,hw/daos.log
[2019-11-01T01:23:29.536Z]     wolf-[126-129]: rc=0, output: Copied /tmp/daos_agent.log /tmp/Functional_pr,hw/ior_small.py-1_client_daos.log /tmp/Functional_pr,hw/ior_small.py-2_client_daos.log /tmp/Functional_pr,hw/ior_small.py-3_client_daos.log /tmp/Functional_pr,hw/ior_small.py-4_client_daos.log /tmp/Functional_pr,hw/ior_small.py-7_client_daos.log
```

Example error:
```
Running on wolf-[10-11,68,74]: set -Eeu; rc=0; copied=(); for file in /tmp/daos_agent.log /tmp/*_client_daos.log /tmp/daos_control.log /tmp/*_server_daos.log /tmp/daos_server.log /tmp/ior_small.py-3_server_daos.log; do if [ -e $file ]; then if scp $file wolf-11:/home/pahender/avocado/job-results/latest/daos_logs/${file##*/}-$(hostname -s); then copied+=($file); if ! rm -fr $file; then ((rc++)); ls -al $file; fi; else ((rc++)); ls -al $file; fi; fi; done; echo Copied ${copied[@]}; exit $rc                                                                                                     
  Errors detected running "set -Eeu; rc=0; copied=(); for file in /tmp/daos_agent.log /tmp/*_client_daos.log /tmp/daos_control.log /tmp/*_server_daos.log /tmp/daos_server.log /tmp/ior_small.py-3_server_daos.log; do if [ -e $file ]; then if scp $file wolf-11:/home/pahender/avocado/job-results/latest/daos_logs/${file##*/}-$(hostname -s); then copied+=($file); if ! rm -fr $file; then ((rc++)); ls -al $file; fi; else ((rc++)); ls -al $file; fi; fi; done; echo Copied ${copied[@]}; exit $rc":                                                                                                       
    wolf-10: rc=0, output: Copied /tmp/daos_control.log /tmp/ior_small.py-1_server_daos.log /tmp/ior_small.py-2_server_daos.log /tmp/ior_small.py-3_server_daos.log                                   
    wolf-11: rc=1, output:                                                                                                                                                                            
      Authentication failed.                                                                                                                                                                          
      lost connection   
    wolf-[68,74]: timeout detected
```
(Inclusion of the "timeout detected" is part of an upcoming patch)

**Comment by jolivier23** [comment]
@skirvan44 or @phender, if you need this force landed, let me know.  Otherwise, you need to merge latest master to get the tests to pass.

**Comment by phender** [comment]
> @phender Did you ever work out why the output was so difficult to make use of due to being interspersed with the avocado output?

No, unfortunately I did not.  I do only see this behavior in the Jenkins logs.  When I run interactively the output appears in the correct order.
 
> ```
> [2019-11-06T06:09:29.863Z] Running on wolf-103vm[1-2]: set -Eeu; rc=0; copied=(); for file in /tmp/daos_agent.log /tmp/Functional_pr,-hw/*_client_daos.log /tmp/daos_control.log /tmp/Functional_pr,-hw/*_server_daos.log /tmp/Functional_pr,-hw/daos.log /tmp/server.log; do if [ -e $file ]; then if scp $file wolf-103vm1:/var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1320/src/tests/ftest/avocado/job-results/latest/daos_logs/${file##*/}-$(hostname -s); then copied+=($file); if ! rm -fr $file; then ((rc++)); ls -al $file; fi; else ((rc++)); ls -al $file; fi; fi; done; echo Copied ${copied[@]:-no files}; exit $rc
> [2019-11-06T06:09:29.863Z]     wolf-103vm1: rc=0, output: Copied /tmp/daos_agent.log /tmp/Functional_pr,-hw/daos.log
> [2019-11-06T06:09:29.863Z]     wolf-103vm2: rc=0, output: Copied /tmp/daos_control.log
> [2019-11-06T06:09:29.863Z] Renamed /var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1320/src/tests/ftest/avocado/job-results/job-2019-11-06T06.08-17d5a5b to /var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-1320/src/tests/ftest/avocado/job-results/job-2019-11-06T06.08-17d5a5b-container-global_handle
> [2019-11-06T06:09:29.863Z] Checking ./data/daos_server_baseline.yaml for daos log file locations
> [2019-11-06T06:09:29.863Z] Checking /tmp/tmp8IRd5t/container-simple_create_delete_test.yaml for daos log file locations
> [2019-11-06T06:09:29.863Z] Cleaning logs on ['wolf-103vm1', 'wolf-103vm2']
> [2019-11-06T06:09:29.863Z] Running on wolf-103vm[1-2]: rm -fr /tmp/daos_agent.log /tmp/daos_sockets /tmp/Functional_pr,-hw/*_client_daos.log /tmp/daos_control.log /tmp/Functional_pr,-hw/*_server_daos.log /tmp/Functional_pr,-hw/daos.log /tmp/server.log
> [2019-11-06T06:09:29.863Z]     wolf-103vm[1-2]: rc=0, output: <NONE>
> ```
> 
> I'm not seeing server `daos.log`s being copied and looking in the artifacts for the first few jobs I also don't see server logs. I do see control.log but no server daos.logs.

So the `daos.log` is being copied, is listed in the output: `[2019-11-06T06:09:29.863Z]     wolf-103vm1: rc=0, output: Copied /tmp/daos_agent.log /tmp/Functional_pr,-hw/daos.log`, and appears in the artifacts: `daos_logs/daos.log-wolf-103vm1.bz2`.

As for `daos_server.log` it is missing from the artifacts as you mentioned.  I ran a quick experiment using two wolf nodes.  I removed all `/tmp/*.log` files from both nodes and ran the `basictx` test from wolf-11 with wolf-10 as the server and wolf-11 as a client.  After the test completed the following logs had been created:
```
$ clush -w wolf-[10-11] "ls -al /tmp/*.log"
wolf-10: -rw-rw-r-- 1 pahender pahender 6664 Nov  8 19:08 /tmp/daos_control.log
wolf-10: -rw-rw-r-- 1 pahender pahender 4504 Nov  8 19:08 /tmp/server.log
wolf-11: -rw-rw-r-- 1 pahender pahender     75 Nov  8 19:07 /tmp/daos_agent.log
wolf-11: -rw-rw-r-- 1 pahender pahender 100590 Nov  8 19:08 /tmp/daos_server.log
```

At this point I'm wondering if it doesn't make sense to simplify the cleanup and archiving of the log files to just these two commands:
```
rm -fr /tmp/*.log
scp /tmp/*.log <test_runner>:/path/to/avocado/job_results/latest/daos_logs/
```

**Comment by phender** [comment]
I cannot explain why it appears to be working now, but the `avocado run` output is aligned with the `launch.py` output in the latest console log: https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/daos/branches/PR-1320/runs/19/nodes/469/steps/543/log/?start=0

**Comment by phender** [comment]
> I didn't search exhaustively, but in the half-dozen or so Functional (VM, not Hardware) tests I couldn't find a single server log.

This is what I think is happening:
1) In `server_utils.py` the `DaosServerConfig.update_log_file()` method is incorrectly being passed a `None` value for the log file - effectively removing the `log_file` entry from the daos_server yaml config file
2) As a result daos_server is called w/o a specific log file so the D_LOG_FILE env value is used, which is set in ftest.sh to `$TEST_TAG_DIR/daos.log`.

**Pull request merged**
