### PR TITLE
DAOS-13989 control: Condense checker findings in non-verbose mode

### PR DESCRIPTION
**Pull request by kjacque**
Print the checker findings as a condensed table when not using verbose output.

Features: recovery control

Required-githooks: true

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by Nasf-Fan** [comment]
Personally, the table formatted output is good for me. But I do not think the condensed repair options for interaction is expected. Because it may misguide the user to think that there is only one option to handle the inconsistency.

**Review by mjmac — COMMENTED** [review]
LGTM, I really like the condensed output, nice work. Only question I have is what the table looks like when you have a mix of reports that are resolved and in need of a resolution. Would probably be pretty messy to have a single table in that case, so you might want to have a table for each set. I would think that the table of reports that need a resolution should come last, because it's what the user will see first when looking at terminal scrollback.

**Review by tanabarr — APPROVED** [review]

**Review by Nasf-Fan — CHANGES_REQUESTED** [review]
I do not suggest to hide the repair options for check interaction. Different from other check status that the user may not care in detail, the check repair options are always independent each other, not like the relationship of "detail" and "summary". If we only print "condensed" options under non-verbose mode, then the user may thought that there is only one option unless he/she is an experienced user and re-query with "-v".

In fact, I like the table formatted output, it is not conflict with multiple repair options. For example we can print all the options under the same table column.

```
[fyong@boro-38 bin]$ ./dmg check query
DAOS System Checker Info
  Current status: RUNNING (started at: 2023-08-19T06:39:00.000+00:00)
  Current phase: PREPARE (Preparing check engine)
  Checking 1 pool

Inconsistency Reports:
ID                 Class          Pool         Resolution      Repair Options                    
--                 -----          ----         ----------      ----------------                    
0x126c2e00b8240001 POOL_BAD_LABEL mypool-fault Action required 0: Trust MS pool label [suggested]. 
                                                                                                                       1. XXXX
                                                                                                                       2. XXXX
```

**Review by tanabarr — APPROVED** [review]

**Comment by kjacque** [comment]
Test failures are both known issues:
- Pool consolidation test: https://daosio.atlassian.net/browse/DAOS-13998
- Upgrade test: https://daosio.atlassian.net/browse/DAOS-14188

**Review by mjmac — APPROVED** [review]
Looks great!

**Review by knard-intel — APPROVED** [review]

**Comment by kjacque** [comment]
@Nasf-Fan Do the changes look good to you?

**Review by Nasf-Fan — APPROVED** [review]
@kjacque thanks for the update. It looks fine for me.
Just one suggestion: it may be better to show the pool status and phase for non-verbose mode, no need other detailed information (such as how many inconsistency are found on each targets). Because these information give the summary for related pool. For example, if I run "dmg check query mypool", but the output does not contain the pool check status, then I almost known nothing from the feedback. "No inconsistency is reported" does not means there is no inconsistency for such pool, it also may because of such pool has not been checked yet.
Related issues can be resolved in other independent patch(es).

**Pull request merged**
