### PR TITLE
DAOS-5948 daos(8): Integrate obj_ctl utility into the daos utility

### PR DESCRIPTION
**Pull request by berserk-fury**
Moved daos mode from tests/obj_ctl.c to utils/daos_obj_ctl.c

    The existing obj_ctl cmd is for vos test only:

    $ obj_ctl
    obj_ctl -- interactive function testing shell for VOS

    daos mode obj_ctl is under this cmd:
    $ daos shell

Signed-off-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>
Co-authored-by: Hua Kuang <hua.kuang@intel.com>

### CODE REVIEW

**Comment by bfaccini** [comment]
@berserk-fury looks like you PR has triggered [DAOS-7016](https://jira.hpdd.intel.com/browse/DAOS-7016) for all 3 only failing tests...

**Review by bfaccini — APPROVED** [review]

**Review by cibervicho — COMMENTED** [review]
LGTM, but I will let a more experienced developer with this feature to give the approval.

**Review by gnailzenh — APPROVED** [review]
I think some further improvements should be made:
* remove epoch from the interface
* we should allow user to pass in pool & container uuid, instead of create/destroy pool & container all the time

These change can be done in follow-on patch

**Comment by berserk-fury** [comment]
@gnailzenh I created [PR-5182](https://github.com/daos-stack/daos/pull/5182) to address your comments.
epoch was removed from the interface.
The `--pool` flag is required.  The `--cont` flag was added. It is an optional flag. If it is not provided, a new container will be created.

**Pull request merged**
