### PR TITLE
DAOS-623 ci: ticket status need not to be updated to push PRs

### PR DESCRIPTION
**Pull request by mchaarawi**
this is annoying and adds spam IMO

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
The intent here was to catch PRs where the ticket number is incorrect, if the correct workflow is being followed then this check should never do anything but I do agree it's common to push a PR before updating Jira.  One possible step in the future would be to have this code set the ticket status to In-Progress rather than warn on the PR.  Another option might be to keep the comment but not mark the job as failed although that's only really correct if the status is Open, if the ticket is Resolved then it's likely a mistake has been made somewhere.

Indecently this PR has the wrong ticket number itself.

**Comment by mchaarawi** [comment]
> The intent here was to catch PRs where the ticket number is incorrect, if the correct workflow is being followed then this check should never do anything but I do agree it's common to push a PR before updating Jira. One possible step in the future would be to have this code set the ticket status to In-Progress rather than warn on the PR. Another option might be to keep the comment but not mark the job as failed although that's only really correct if the status is Open, if the ticket is Resolved then it's likely a mistake has been made somewhere.
> 
> Indecently this PR has the wrong ticket number itself.

sometimes we do use DAOS-623 (not 625) to push very small PRs - one liners that really do not warrent new tickets.
i really think this workflow should not try an enforce Jira semantics. i understand after discussing with Jeff that is mainly meant for adding labels, and maybe later add priority in CI. beyond that, let's please leave Jira management to each author.

**Comment by mchaarawi** [comment]
> if the ticket is Resolved then it's likely a mistake has been made somewhere.

i do sometimes push PRs with tickets as resolved mostly for testing purposes (not meant to be landed). my main complaint is really the email spam on that front.
but for really PRs, i have never marked a Jira ticket as in progress before pushing a PR. again i would prefer we do not add these checking in this workflow.

**Review by jolivier23 — APPROVED** [review]
This is fine though I think you get spam anyway.  The only real difference here is it doesn't fail the PR.  In general, people should not be using those disallowed values.   Maybe rather than failing the test, we could add a label (invalid-ticket) or some such.

**Review by jolivier23 — APPROVED** [review]

**Comment by mchaarawi** [comment]
@jolivier23 you approved this twice, but removed the gatekeeper review

**Comment by ashleypittman** [comment]
> @ashleypittman does the jira_query run from master branch version?

Yes, it uses the pull_request_target trigger so it runs based on the target branch rather than the branch.

**Comment by jolivier23** [comment]
Can you please backport this to 2.2?

**Pull request merged**
