### PR TITLE
DAOS-10344 object: fix OID leak in OIT

### PR DESCRIPTION
**Pull request by gnailzenh**
While iterating container, cont_iter_obj_cb() leaks the current
OID after writing the previosu batch. This function should store
the current OID after writing to OIT.

Signed-off-by: Liang Zhen <liang.zhen@intel.com>

### CODE REVIEW

**Review by wangshilong — APPROVED** [review]
I verified this could fix the problem.

**Review by daltonbohning — CHANGES_REQUESTED** [review]
We need to verify the skipped datamover tests are fixed:
`Features: dm_obj_large_posix dm_serial_large_posix`

**Comment by wangshilong** [comment]
> We need to verify the skipped datamover tests are fixed: `Features: dm_obj_large_posix dm_serial_large_posix`

Retriggered with tag specified.

**Comment by wangshilong** [comment]
Test passed for dm_obj_large_posix dm_serial_large_posix for last test, i retriggered Hardware test because of DAOS-11236

**Review by NiuYawei — APPROVED** [review]

**Comment by daltonbohning** [comment]
> Test passed for dm_obj_large_posix dm_serial_large_posix for last test, i retriggered Hardware test because of DAOS-11236

Are you sure those specific tests passed? Since they are in the skiplist (/scratch/CI-skip-list-master), they will only be ran if the most recent commit has DAOS-10344 in the commit title. @phender can confirm this.

Assuming those tests pass, LGTM.

**Comment by phender** [comment]
> > Test passed for dm_obj_large_posix dm_serial_large_posix for last test, i retriggered Hardware test because of DAOS-11236
> 
> Are you sure those specific tests passed? Since they are in the skiplist (/scratch/CI-skip-list-master), they will only be ran if the most recent commit has DAOS-10344 in the commit title. @phender can confirm this.
> 
> Assuming those tests pass, LGTM.

https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9838/4/testReport/FTEST_datamover/ did not run the skipped tests:

- test_dm_obj_large_posix_dcp:  FTEST_datamover/DmvrObjLargePosix (datamover/obj_large_posix.py)
- test_dm_obj_large_posix_cont_clone: FTEST_datamover/DmvrObjLargePosix (datamover/obj_large_posix.py)
- test_dm_serial_large_posix_dserialize: FTEST_datamover/DmvrSerialLargePosix (datamover/serial_large_posiz.py)

These are all weekly (full_regression) tagged tests and require the following commit pragma to be run by this PR:
```
DAOS-10344 object: fix OID leak in OIT

Test-tag: pr dm_obj_large_posix_dcp dm_obj_large_posix_cont_clone dm_serial_large_posix_dserialize
```

**Comment by wangshilong** [comment]
> ```
> Test-tag: pr dm_obj_large_posix_dcp dm_obj_large_posix_cont_clone dm_serial_large_posix_dserialize
> ```

OK, i repushed a new commit to include following change.
Thanks

**Comment by wangshilong** [comment]
@phender I pushed commit as your suggested and CI passed, would you double check if skipped test are run? i did find place where i could see all run tests.

**Comment by phender** [comment]
> @phender I pushed commit as your suggested and CI passed, would you double check if skipped test are run? i did find place where i could see all run tests.

The skipped datamover tests paased in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9838/5/testReport/FTEST_datamover/

**Comment by wangshilong** [comment]
> > @phender I pushed commit as your suggested and CI passed, would you double check if skipped test are run? i did find place where i could see all run tests.
> 
> The skipped datamover tests paased in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9838/5/testReport/FTEST_datamover/

Thanks for confirming.

**Pull request merged**
