### PR TITLE
DAOS-2726 tests: use large vs max_repl in array and addons test

### PR DESCRIPTION
**Pull request by mchaarawi**
we read after write in those tests, so using max repl triggers a lot of
retries. No need to do any replication in those cases anyways.

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Comment by jolivier23** [comment]
are the retries due to a bug?  do we have coverage elsewhere?

**Comment by mchaarawi** [comment]
> are the retries due to a bug? do we have coverage elsewhere?

no it's a feature not a bug..
if i understand correctly, if you have replication and you read right after write, the read might go to non leader and it might not be committed yet so it returns -2018, which requires retry to leader.

**Comment by mchaarawi** [comment]
> do we have coverage elsewhere?

I don't know about coverage, but i definitely didn't write those tests for replication test coverage.

**Comment by mchaarawi** [comment]
I am going to revert the large oclass def in this patch too, so please don't merge yet

**Pull request merged**
