### PR TITLE
DAOS-4132 Control: Upgrade netdetect to hwloc v2.x

### PR DESCRIPTION
**Pull request by jbrosenz**
The netdetect library now supports hwloc v1.x and v2.x

     Conditionally compiled wrapper functions in C were
     introduced that allow the GO functions to build and
     operate with either library.
Signed-off-by: Joel Rosenzweig <joel.b.rosenzweig@intel.com>

### CODE REVIEW

**Comment by jbrosenz** [comment]
> Looks good to me. Pretty straightforward and doesn't look like too much maintenance overhead. Only suggestion I have is to prefix the name of your functions with something like "cmpt_" in order to make it clear where you're calling hwloc directly and where you're calling through the compatibility shims.
> 
> Have you tested this on ubuntu 20.04? If not, you might try creating a new PR that is a combination of this one and Johann's #2530 PR in order to verify that this PR allows that one to pass build/test.

I'll add the prefixes as you suggested.  I'm double checking my implementation of the 2.x version of get_child() as well.  I may make an update to that depending on what I find.

I have not tested on ubuntu 20.04.  I asked him today to cherry pick this and see if it allowed him to progress on the 20.04 build.  I'll check with him to see how that went and can try your suggestion make a new PR with #2530 and this one if necessary.

**Comment by johannlombardi** [comment]
Thanks! Create a pull request based on this patch, check PR #2702

**Comment by johannlombardi** [comment]
Built complete successfully on ubuntu!
https://travis-ci.org/github/daos-stack/daos/builds/686651538

**Comment by mjmac** [comment]
> 
> 
> Built complete successfully on ubuntu!
> https://travis-ci.org/github/daos-stack/daos/builds/686651538

Very nice. Maybe we should have someone test it on latest Fedora... @jolivier23?

**Comment by jolivier23** [comment]
> > Built complete successfully on ubuntu!
> > https://travis-ci.org/github/daos-stack/daos/builds/686651538
> 
> Very nice. Maybe we should have someone test it on latest Fedora... @jolivier23?

works on Fedora

**Comment by jbrosenz** [comment]
> LGTM code-wise... @jbrosenz, are you looking at the test failures?

I'm looking for a reason for the 14 DaosCoreTestRebuild failures.  They all fail the same way, with a timeout after the agent returns a GetAttachInfo response.  There's a 9 minute delay, and the test is killed.  The other 22 failures are due to DAOS-4797.

**Comment by jbrosenz** [comment]
The remaining failures have nothing to do with the changes to hwloc.  The components using the netdetect.go changes (the daos_agent and daos_server) used hwloc successfully.  The client encountered an error at early init that I am working on decoding that occurs immediately at startup and repeats until the test is killed.

> 05/13-14:47:20.52 wolf-54 DAOS[11564/11564] rpc  ERR  src/cart/src/cart/crt_context.c:805 crt_context_timeout_check(0xee4750) [opc=0x1010000 xid=0x11e4 rank:tag=0:0] ctx_id 0, (status: 0x38) timed out, tgt rank 0, tag 0
05/13-14:47:20.52 wolf-54 DAOS[11564/11564] rpc  ERR  src/cart/src/cart/crt_context.c:763 crt_req_timeout_hdlr(0xee4750) [opc=0x1010000 xid=0x11e4 rank:tag=0:0] aborting to group daos_server, rank 0, tgt_uri (null)
05/13-14:47:20.52 wolf-54 DAOS[11564/11564] hg   ERR  src/cart/src/cart/crt_hg.c:1167 crt_hg_req_send_cb(0xee4750) [opc=0x1010000 xid=0x11e4 rank:tag=0:0] RPC failed; rc: -1011
05/13-14:47:20.53 wolf-54 DAOS[11564/11564] hg   WARN # NA -- Warning -- /var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-2688@3/_build.external/mercury/src/na/na_ofi.c:2569
na_ofi_cq_read(): fi_cq_readerr() got err: 5 (Input/output error), prov_errno: -5 (Input/output error)
05/13-14:47:20.53 wolf-54 DAOS[11564/11564] hg   WARN # NA -- Warning -- /var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-2688@3/_build.external/mercury/src/na/na_ofi.c:2569
na_ofi_cq_read(): fi_cq_readerr() got err: 5 (Input/output error), prov_errno: -5 (Input/output error)
05/13-14:47:20.53 wolf-54 DAOS[11564/11564] hg   WARN # HG -- Warning -- /var/lib/jenkins/jenkins-1/docker_1/workspace/daos-stack_daos_PR-2688@3/_build.external/mercury/src/mercury_core.c:2151
hg_core_send_input_cb(): NA callback returned error (NA_PROTOCOL_ERROR)

**Comment by jbrosenz** [comment]
Actually the error timing is more interesting.  There's a gap from 14:21:53 to 14:47:20.  There is no activity on the client during this gap, then the errors occur.
> 05/13-14:21:53.50 wolf-54 DAOS[11564/11564] fi   INFO src/cart/src/gurt/fault_inject.c:486 d_fault_inject_init() No config file, fault injection is OFF.
05/13-14:21:53.50 wolf-54 DAOS[11564/11564] common INFO src/common/misc.c:567 daos_crt_init_opt_get() for sockets provider force it to use regular EP.
05/13-14:21:53.50 wolf-54 DAOS[11564/11564] crt  INFO src/cart/src/cart/crt_init.c:278 crt_init_opt() libcart version 4.7.0 initializing
05/13-14:21:53.50 wolf-54 DAOS[11564/11564] crt  WARN src/cart/src/cart/crt_init.c:170 data_init() FI_UNIVERSE_SIZE was not set; setting to 2048
05/13-14:21:53.58 wolf-54 DAOS[11564/11564] daos INFO src/common/drpc.c:664 drpc_close() Closing dRPC socket fd=36
# nothing in the log here until 14:47:20.52
> 05/13-14:47:20.52 wolf-54 DAOS[11564/11564] rpc  ERR  src/cart/src/cart/crt_context.c:805 crt_context_timeout_check(0xee4750) [opc=0x1010000 xid=0x11e4 rank:tag=0:0] ctx_id 0, (status: 0x38) timed out, tgt rank 0, tag 0

**Comment by jbrosenz** [comment]
I didn't test the io_server thoroughly enough.  I verified that the daos_server and daos_agent built and ran successfully, but did not verify that the daos_io_server ran successfully.  The daos_io_server does not run properly with hwloc2.x.  I didn't change the io_server code in this PR because it built properly as-is.  I will debug that, fix it, and push an update.

**Comment by jbrosenz** [comment]
I cannot reproduce the error that I saw.  I've merged with master for the latest changes, but didn't change anything other than that.

**Comment by jbrosenz** [comment]
All failed tests explained by:

DAOS-4850 
Test / Functional_Hardware_Medium / FioSmall.1-./io/fio_small.py:FioSmall.test_fio_small;container-dfuse-bs_256B-sequential-test-hosts-pool-0-1-28cd
 Error Details
Unable to launch Dfuse.

DAOS-4850 
 Test / Functional_Hardware_Medium / FioSmall.2-./io/fio_small.py:FioSmall.test_fio_small;container-dfuse-bs_256B-random-test-hosts-pool-0-1-0190
 Error Details
Unable to launch Dfuse. 

DAOS-4850 
 Test / Functional_Hardware_Medium / FioSmall.3-./io/fio_small.py:FioSmall.test_fio_small;container-dfuse-bs_1M-sequential-test-hosts-pool-0-1-9ebb
 Error Details
Unable to launch Dfuse. 

DAOS-4850 
 Test / Functional_Hardware_Medium / FioSmall.4-./io/fio_small.py:FioSmall.test_fio_small;container-dfuse-bs_1M-random-test-hosts-pool-0-1-ff37
 Error Details
Unable to launch Dfuse. 

DAOS-4567
 Test / Functional_Hardware_Large / IorSmall.1-./io/ior_small.py:IorSmall.test_ior_small;container-dfuse-hosts-np_16-iorflags-pool-servers-server_manager-fd22
ERROR: dmg: pool create failed: rpc error: code = Unknown desc = DAOS error (-1020): DER_HG

DAOS-3945
Test / Functional / LlnlMpi4py.1-./io/llnl_mpi4py.py:LlnlMpi4py.test_llnl;client_processes-container-hosts-pool-server_config-test_repo-0da9
Failed to stop servers

DAOS-3945
 Test / Functional / LlnlMpi4py.2-./io/llnl_mpi4py.py:LlnlMpi4py.test_mpi4py;client_processes-container-hosts-pool-server_config-test_repo-0da9
Failed to stop servers

DAOS-4567
 Test / Functional_Hardware_Large / MdtestSmall.1-./io/mdtest_small.py:MdtestSmall.test_mdtest_small;container-dfuse-hosts-np_8-pool-server_config-d209
dmg: pool create failed: rpc error: code = Unknown desc = DAOS error (-1020): DER_HG

DAOS-4567
 Test / Functional_Hardware_Large / NvmeObject.1-./io/nvme_object.py:NvmeObject.test_nvme_object_single_pool;container-hosts-createmode-createset-createsize-createsvc-servers-server_manager-timeouts-4cea
ERROR: dmg: pool create failed: rpc error: code = Unknown desc = DAOS error (-1020): DER_HG

DAOS-3945
 Test / Functional / PoolAttributeTest.03-./pool/attribute.py:PoolAttributeTest.test_pool_attributes;validlongname-null-hosts-pool-server_config-35a5
Failed to stop servers

DAOS-3945
 Test / Functional / PoolAttributeTest.05-./pool/attribute.py:PoolAttributeTest.test_pool_attributes;specialcharacter-specialcharacter-hosts-pool-server_config-f37a
Failed to stop servers

DAOS-4853:
 Test / Functional / PoolAttributeTest.06-./pool/attribute.py:PoolAttributeTest.test_pool_attributes;specialcharacter-null-hosts-pool-server_config-1421
Error stopping agents: Failed to stop agents

**Comment by jbrosenz** [comment]
Nothing in the logs suggest there was any issue relating to hwloc support.  The daos_server, daos_agent all built and functioned normally, excluding the known errors.  daos_io_server is OK as is.

I've run this PR with the hwloc 2.1 library locally and daos_test.  Should this PR be run by someone against Ubuntu with hwloc2.x to run some tests?  Would Johan's PR run the tests if we let it?

**Pull request merged**
