### PR TITLE
DAOS-8460 vmd: Check for distro for lspci path in detectVMD() and remove device ID

### PR DESCRIPTION
**Pull request by sydneyvanda**
Currently VMD devices are queried via lspci, and on OpenSUSE no VMD devices are
returned as the command fails. $lspci is not in the default $PATH for non-root users on
OpenSUSE and SLES. Add check for distro, and if either opensuse, sles, or opensuse-leap,
then use /sbin/lspci.
Also remove VMD PCI device ID (0x201d) from query as the ID is specific to SKX
platforms. Instead only query for "Volume Management Device", as that
remains the same in ICX systems when parsing for VMD addresses.

Signed-off-by: Sydney Vanda <sydney.m.vanda@intel.com>

### CODE REVIEW

**Review by NiuYawei — APPROVED** [review]

**Review by mjmac — CHANGES_REQUESTED** [review]
The daos_admin binary (which is where this code is executed) already has root privileges so the sudo is redundant and will not work outside of our CI environment.

The real problem is that on opensuse (and presumably sles), lspci is in /sbin which is not in the default $PATH for non-root users. Simply adding /sbin to the command allows a normal user to run it:
```
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
macdonal@wolf-37:~> /sbin/lspci
00:00.0 Host bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 DMI2 (rev 02)
00:01.0 PCI bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCI Express Root Port 1 (rev 02)
00:02.0 PCI bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCI Express Root Port 2 (rev 02)
00:02.2 PCI bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCI Express Root Port 2 (rev 02)
```

On EL systems, however, lspci is in /usr/sbin. There are a couple of ways to fix this. My preference would be to not use lspci at all, as shelling out to external programs is problematic for a number of reasons (as we've found with this issue). It seems like we should be able to walk `/sys/bus/pci/devices` and figure out what we need from that. In the short term, though, I would be OK with using [system.GetDistribution()](https://github.com/daos-stack/daos/blob/master/src/control/provider/system/distribution.go#L187) to determine which path to use for the lspci call.

**Comment by sydneyvanda** [comment]
> The daos_admin binary (which is where this code is executed) already has root privileges so the sudo is redundant and will not work outside of our CI environment.
> 
> The real problem is that on opensuse (and presumably sles), lspci is in /sbin which is not in the default $PATH for non-root users. Simply adding /sbin to the command allows a normal user to run it:
> 
> ```
> CPE_NAME="cpe:/o:opensuse:leap:15.3"
> BUG_REPORT_URL="https://bugs.opensuse.org"
> HOME_URL="https://www.opensuse.org/"
> macdonal@wolf-37:~> /sbin/lspci
> 00:00.0 Host bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 DMI2 (rev 02)
> 00:01.0 PCI bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCI Express Root Port 1 (rev 02)
> 00:02.0 PCI bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCI Express Root Port 2 (rev 02)
> 00:02.2 PCI bridge: Intel Corporation Xeon E7 v3/Xeon E5 v3/Core i7 PCI Express Root Port 2 (rev 02)
> ```
> 
> On EL systems, however, lspci is in /usr/sbin. There are a couple of ways to fix this. My preference would be to not use lspci at all, as shelling out to external programs is problematic for a number of reasons (as we've found with this issue). It seems like we should be able to walk `/sys/bus/pci/devices` and figure out what we need from that. In the short term, though, I would be OK with using [system.GetDistribution()](https://github.com/daos-stack/daos/blob/master/src/control/provider/system/distribution.go#L187) to determine which path to use for the lspci call.

Will update accordingly for this PR, and I filed a new PR (https://daosio.atlassian.net/browse/DAOS-8532) to address removing lspci in the future most likely with /proc/bus/pci/devices and some more advanced parsing.

**Review by tanabarr — APPROVED** [review]

**Review by mjmac — APPROVED** [review]

**Review by NiuYawei — APPROVED** [review]

**Comment by mjmac** [comment]
@sydneyvanda: Please update the subject and commit body to reflect the actual content of this patch.

**Review by mjmac — CHANGES_REQUESTED** [review]
Temporary -1 to avoid landing with outdated subject/body.

**Comment by sydneyvanda** [comment]
> Temporary -1 to avoid landing with outdated subject/body.

Thanks for the catch @mjmac, updated both now

**Review by mjmac — APPROVED** [review]

**Pull request merged**
