### PR TITLE
DAOS-16645 cart: Bump file descriptor limit (#15224)

### PR DESCRIPTION
**Pull request by jolivier23**
With tcp provider, using many sockets can cause significant file descriptor usage.  Bump the soft limit, if possible and warn if it appears insufficient.
Valgrind sets hard limit to soft limit, so work around that in NLT.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by frostedcmos — APPROVED** [review]

**Comment by jolivier23** [comment]
Looks like 2.6 branch needs some valgrind backports to suppress go errors.

**Comment by daltonbohning** [comment]
This might be safe since it's a backport, but this PR does modify `utils/node_local_test.py` and NLT is failing

**Comment by daltonbohning** [comment]
> Looks like 2.6 branch needs some valgrind backports to suppress go errors.

To fix NLT?

**Comment by jolivier23** [comment]
> > Looks like 2.6 branch needs some valgrind backports to suppress go errors.
> 
> To fix NLT?

yes, we are probably missing some valgrind backports

> This might be safe since it's a backport, but this PR does modify `utils/node_local_test.py` and NLT is failing

It doesn't fundamentally change NLT though.  It just bumps the file descriptor limit to avoid a warning.

**Comment by daltonbohning** [comment]
FWIW we did just land this backport
https://github.com/daos-stack/daos/commit/79bf0817c45cde4bd54a91aa2f25ee84414d608a

But if you're reasonable confident this PR is safe, no objection from me

**Pull request merged**
