### PR TITLE
DAOS-13341 test: fix improper assert

### PR DESCRIPTION
**Pull request by NiuYawei**
Fix an improper assert in test code.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by Nasf-Fan — APPROVED** [review]

**Comment by daltonbohning** [comment]
> Since this is fixing a failure seen with `daos_racer/multi.py:DaosRacerTest.test_daos_racer`, this PR should run that test. It's an intermittent failure, so doesn't 100% verify the fix, but it's better than not running the failing test at all.

Or am I misunderstanding this fix and the failure in https://daosio.atlassian.net/browse/DAOS-13341?

**Review by kjacque — APPROVED** [review]

**Comment by NiuYawei** [comment]
PR branch doesn't follow rules, need to close this one and create a new PR.

**Comment by NiuYawei** [comment]
> > Since this is fixing a failure seen with `daos_racer/multi.py:DaosRacerTest.test_daos_racer`, this PR should run that test. It's an intermittent failure, so doesn't 100% verify the fix, but it's better than not running the failing test at all.
> 
> Or am I misunderstanding this fix and the failure in https://daosio.atlassian.net/browse/DAOS-13341?

Sorry, I missed this comment. @daltonbohning , what pragma should I use to run that racer test?

**Comment by daltonbohning** [comment]
> Sorry, I missed this comment. @daltonbohning , what pragma should I use to run that racer test?

You can use `Features: DaosRacerTest`
Which comes from this line of tags. It's usually the last line of tags that contains the unique tags for the test.
https://github.com/daos-stack/daos/blob/a0447b727ad3bb924e3040a567142ef83f518ac0/src/tests/ftest/daos_racer/multi.py#L34

FWIW, I'm working on a utility to make this easier.

**Pull request closed without merging**
