### PR TITLE
DAOS-16585 test: disable NLT fstat test for non-redhat systems.

### PR DESCRIPTION
**Pull request by ashleypittman**
Disable this test non non-el systems until we can add interception.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
@techbasset this adds on my other PR and should make the tests pass on Ubuntu.

**Review by jolivier23 — DISMISSED** [review]

**Review by techbasset — APPROVED** [review]
Works on Ubuntu 22.04 and Rocky 8 for me. I was getting errors on the latter before upgrading from python 3.6 to python 3.9.

**Review by jolivier23 — APPROVED** [review]

**Review by techbasset — APPROVED** [review]

**Comment by techbasset** [comment]
I meant to ask: are we sure this is Redhat-related? As opposed to glibc version or something like that?

**Comment by ashleypittman** [comment]
> I meant to ask: are we sure this is Redhat-related? As opposed to glibc version or something like that?

It's probably glibc related yes, but the only datapoints that we have are the rocky version we're testing are passing and the Ubuntu version you're testing is failing.  This PR is to get you unblocked and running on Ubuntu whilst we determine the scope and therefore priority of fixing/supporting this.

**Comment by ashleypittman** [comment]
Test failures are DAOS-16637 and DAOS-16646 which are both test/infrastructure issues.

**Pull request merged**
