### PR TITLE
DAOS-2998: csum_extent_tests.c: Error: Failure!

### PR DESCRIPTION
**Pull request by rpadma2**
Signed-off-by: Padmanabhan <ravindran.padmanabhan@intel.com>

### CODE REVIEW

**Comment by gnailzenh** [comment]
First of all, please always add commit message for your patch.
In addition, I do think there is bug in the patch: how can you guarantee "random() + 1" is not zero? if the random() outputs is 255, then we still get zero for the memset right?

**Comment by ryon-jensen** [comment]
> In addition, I do think there is bug in the patch: how can you guarantee "random() + 1" is not zero? if the random() outputs is 255, then we still get zero for the memset right?

I actually asked about this, too. random() returns a number between 0 and RAND_MAX. RAND_MAX (at least on my implementation) is INT_MAX. Because memset takes an int, 255+1 shouldn't be zero. INT_MAX + 1 is -2147483648, so I don't think it can be zero, unless I'm missing something.

**Comment by rpadma2** [comment]
It looks like Liang had problem on his PR 910 due to same issue after the merge. So I am not clear whether 255+1 is returning zero. I may need more testing in this area before we come with a solution.

**Comment by rpadma2** [comment]
Ok. I provided 255+1 as input and ran the test. It doesn't encounter the problem. Definitely, 255+1 is not returning zero.

**Pull request merged**
