### PR TITLE
DAOS-15045 vos: check tls before accessing

### PR DESCRIPTION
**Pull request by wangdi1**
Check vos tls in vos_pool_hhash_get(), since it maybe called in the system xstream.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]

**Review by liuxuezhao — APPROVED** [review]

**Review by NiuYawei — DISMISSED** [review]

**Comment by wangdi1** [comment]
The failure is due to some network environment issue(swim timeout, reconnect then causing the rank dead). Since there is only 1 failure of the test, should I retrigger? or it can be landed?  @daos-stack/daos-gatekeeper 

02/06-22:40:31.83 wolf-140 DAOS[164382/1/5] hg   ERR  src/cart/crt_hg.c:1375 crt_hg_req_send_cb(0x7fb31c55fb50) [opc=0xfe020000 (SWIM) rpcid=0x1fa9c9d300263488 rank:tag=5:1] RPC failed; rc: DER_TIMEDOUT(-1011): 'Time out'
02/06-22:40:31.83 wolf-140 DAOS[164382/1/5] swim WARN src/cart/crt_swim.c:670 crt_swim_cli_cb() excluded in group version 12 (self 11)
02/06-22:40:31.83 wolf-140 DAOS[164382/1/5] server WARN src/engine/init.c:584 dss_crt_event_cb() raising SIGKILL: exclusion of this engine (rank 2) detected
"test_osa_offline_drain_daos_server_1.log.164382" 617L, 101340B

**Review by jolivier23 — APPROVED** [review]

**Comment by daltonbohning** [comment]
Landing to 2.4 is closed until after 2.4.2 is released

**Review by liuxuezhao — APPROVED** [review]

**Comment by daltonbohning** [comment]
Looks like `osa/offline_drain.py` is failing to destroy a pool:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-13638/4/tests

Is that related?

**Comment by wangdi1** [comment]
> Looks like `osa/offline_drain.py` is failing to destroy a pool: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-13638/4/tests
> 
> Is that related?

no, very unlikely

**Review by NiuYawei — APPROVED** [review]

**Pull request merged**
