### PR TITLE
DAOS-12580 test: Fix vos md-on-ssd unit tests

### PR DESCRIPTION
**Pull request by tanabarr**
Fix the standalone vos_tests failure related to reading JSON config
file. nvme_glb.bd_nvme_conf is freed stack memory in bio_xsctxt_alloc()
when spdk_subsystem_init_from_json_config(nvme_glb.bd_nvme_conf, ...)
is called (as memory confined in scope to bio_nvme_init). Allocate by
copying string and free explicitly on bio_nvme_fini.

Required-githooks: true

Co-authored-by: Dmitry Ivanov <dmitry.ivanov2@hpe.com>
Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by jolivier23 — COMMENTED** [review]
I'm still seeing this in the run_test log
[2023-02-08T17:31:49.173Z] Running sudo -E /opt/daos/bin/vos_tests -a with log file: /tmp/daos_sudo--E--opt-daos-bin-vos_tests--a-9.log
[2023-02-08T17:31:49.173Z] [2023-02-08 17:31:44.944269] json_config.c: 533:app_json_config_read: *ERROR*: Read JSON configuration file �{:�LV failed: No such file or directory
[2023-02-08T17:31:49.173Z] Error initializing VOS instance

**Comment by tanabarr** [comment]
With the PR, "Error init" messages no longer seen in unit test logs. The issue of CI test results not indicating an error when vos_tests are not run still exists and has not been resolved by this PR.

**Review by jolivier23 — APPROVED** [review]

**Review by wangshilong — APPROVED** [review]

**Comment by ivadmitry** [comment]
> I'm still seeing this in the run_test log [2023-02-08T17:31:49.173Z] Running sudo -E /opt/daos/bin/vos_tests -a with log file: /tmp/daos_sudo--E--opt-daos-bin-vos_tests--a-9.log [2023-02-08T17:31:49.173Z] [2023-02-08 17:31:44.944269] json_config.c: 533:app_json_config_read: _ERROR_: Read JSON configuration file �{:�LV failed: No such file or directory [2023-02-08T17:31:49.173Z] Error initializing VOS instance

That's another issue, it caused by missing FAULT_INJECTION_REQUIRED() macro in src/vos/tests/vts_io.c: io_allocbuf_failure()
@NiuYawei Please consider this fix:
--- a/src/vos/tests/vts_io.c
+++ b/src/vos/tests/vts_io.c
@@ -2931,6 +2931,8 @@ io_allocbuf_failure(void **state)
        daos_size_t              buf_len = (40UL << 20); /* 40MB, larger than DMA chunk size */
        int                      rc;

+       FAULT_INJECTION_REQUIRED();
+
        vts_key_gen(&dkey_buf[0], arg->dkey_size, true, arg);
        vts_key_gen(&akey_buf[0], arg->akey_size, false, arg);
        set_iov(&dkey_iov, &dkey_buf[0], is_daos_obj_type_set(arg->otype, DAOS_OT_DKEY_UINT64));

**Comment by NiuYawei** [comment]
> > I'm still seeing this in the run_test log [2023-02-08T17:31:49.173Z] Running sudo -E /opt/daos/bin/vos_tests -a with log file: /tmp/daos_sudo--E--opt-daos-bin-vos_tests--a-9.log [2023-02-08T17:31:49.173Z] [2023-02-08 17:31:44.944269] json_config.c: 533:app_json_config_read: _ERROR_: Read JSON configuration file �{:�LV failed: No such file or directory [2023-02-08T17:31:49.173Z] Error initializing VOS instance
> 
> There is another issue, it caused by missing FAULT_INJECTION_REQUIRED() macro in src/vos/tests/vts_io.c: io_allocbuf_failure() @NiuYawei Please consider this fix:
> 
> ```
> --- a/src/vos/tests/vts_io.c
> +++ b/src/vos/tests/vts_io.c
> @@ -2931,6 +2931,8 @@ io_allocbuf_failure(void **state)
>         daos_size_t              buf_len = (40UL << 20); /* 40MB, larger than DMA chunk size */
>         int                      rc;
> 
> +       FAULT_INJECTION_REQUIRED();
> +
>         vts_key_gen(&dkey_buf[0], arg->dkey_size, true, arg);
>         vts_key_gen(&akey_buf[0], arg->akey_size, false, arg);
>         set_iov(&dkey_iov, &dkey_buf[0], is_daos_obj_type_set(arg->otype, DAOS_OT_DKEY_UINT64));
> ```

Yeah, thanks. @tanabarr , could you incorporate the fix in this PR as well?

**Comment by tanabarr** [comment]
https://github.com/daos-stack/daos/pull/11422 for the other suggested fix

**Pull request merged**
