### PR TITLE
DAOS-6865 tests: Providing debug info

### PR DESCRIPTION
**Pull request by phender**
Quick-Functional: true

Test-tag-vm: pool,rebuild
Skip-func-hw-test: true

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by jolivier23** [comment]
Aborted due to conflict and CI provisioning slowness.  Please merge latest master and resubmit

**Comment by jolivier23** [comment]
Needs rebase before resubmitting to avoid too much time in provisioning

**Review by dinghwah — APPROVED** [review]
Results for rebuild tests look good. 
no failure.

**Review by shimizukko — APPROVED** [review]

**Comment by saurabhtandan** [comment]
Failing DaosCoreTestDfs is due to pre-existing DAOS-6378.

**Comment by sylviachanoiyee** [comment]
> Failing DaosCoreTestDfs is due to pre-existing DAOS-6378.

Was looking at the job.log of the failing test, but I don't see error messages pointing to checksum error described in DAOS-6378.
maybe a different issue?

**Pull request merged**
