### PR TITLE
CART-89: Update mercury to release v2.0.1

### PR DESCRIPTION
**Pull request by frostedcmos**
- Update mercury to release v2.0.1

PR-repos: mercury@PR-59

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

### CODE REVIEW

**Comment by frostedcmos** [comment]
Corresponding daos-stack/mercury PR https://github.com/daos-stack/mercury/pull/59

**Comment by frostedcmos** [comment]
Corresponding daos-stack/mercury change https://github.com/daos-stack/mercury/pull/59

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Merge conflict on SConstruct.  Ashley made a change to how we setup compilers that moved a lot of code from SConstruct to site_scons/compiler_setup.py so you may have to handle some manual merging

Also, we should probably run with

Test-tag: pr daily_regression

**Comment by frostedcmos** [comment]
> Merge conflict on SConstruct. Ashley made a change to how we setup compilers that moved a lot of code from SConstruct to site_scons/compiler_setup.py so you may have to handle some manual merging
> 
> Also, we should probably run with
> 
> Test-tag: pr daily_regression

done

**Review by jolivier23 — APPROVED** [review]

**Review by jgmoore-or — APPROVED** [review]

**Comment by ashleypittman** [comment]
It looks like this change introduces a number of memory leaks in mercury which are causing CI failures.

**Pull request merged**
