### PR TITLE
DAOS-5736: Update ior_hdf5 test with correct hw tag.

### PR DESCRIPTION
**Pull request by dinghwah**
Modify file: io/ior_hdf5.py

Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

### CODE REVIEW

**Comment by dinghwah** [comment]
The 3 errors from functional test are due to:
(1)DAOS-5748  and
(2)DAOS-5745
irrelevant to the tag change of the script.

**Review by phender — CHANGES_REQUESTED** [review]
The fix looks correct but you are not verifying the change in this PR.  Your commit message needs the following:
```
Test-tag-hw-large: pr,hw,large iorhdf5vol
```

**Comment by dinghwah** [comment]
Functional failures are due to irrelevant known bugs.
DAOS-5768, daos_control_config test failed on start daos_agent
DAOS-5784  Daos core_test_rebuild r0_10 test   failed on rebuild and timeout
DAOS-5745  Csum error-log dmg unable to load certs files.

**Review by phender — APPROVED** [review]
LGTM.  The test ran in the correct phase and passed.

**Review by shimizukko — APPROVED** [review]
LGTM

**Pull request merged**
