### PR TITLE
DAOS-6076 test:  daos_vol: disabled h5_partest_testphdf5

### PR DESCRIPTION
**Pull request by mjean308**
Disable h5_partest_testphdf5 and h5_partest_t_shapesame
Enabled daos vol tests
Enabled IOR small hdf5 vol tests

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### CODE REVIEW

**Comment by mjean308** [comment]
The only failures in Functional HW were due to:
ERROR: Detected one or more tests that failed archiving!

**Review by shimizukko — APPROVED** [review]
LGTM

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Comment by sylviachanoiyee** [comment]
@mjean308 , for the tests you are disabling, are there tickets to re-enable them and have those tickets block the bug they are associated with?

**Comment by mjean308** [comment]
@sylviachanoiyee The tickets to re-enable the disable daos vol tests are:
DAOS-6228-6231.  They are all blocked by respective DAOS bugs.

**Pull request merged**
