### PR TITLE
DAOS-14022 test: new container test co_op_dup_timing

### PR DESCRIPTION
**Pull request by kccain**
Verify performance of several container metadata engine handlers when detecting actual duplicate RPCs
(injected via fault injection mechanism in the test).

And, lower the minimum acceptable value for pool property svc_ops_entry_age to 60 seconds, since the test needs to run a "dummy workload" of this duration to stabilize metadata workload execution time (predictability).

Features: pool
Skip-func-hw-test-medium-md-on-ssd: false

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by kccain** [comment]
> Test stage Functional Hardware Medium completed with status UNSTABLE. https://build.hpdd.intel.com/job/daos-stack/job/daos//view/change-requests/job/PR-14046/2/testReport/

(same problem as seen in the other MD on SSD testing) 
- [rebuild/with_ior.py](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14046/2/testReport/junit/FTEST_rebuild/RbldWithIOR/Test_Hardware___Functional_Hardware_Medium___1___rebuild_with_ior_py_RbldWithIOR_test_rebuild_with_ior_run_container_hosts_ior_client_processes_iorflags_pool_server_config_engines_0_storage_0_1_e0db/) failure due to known issue https://daosio.atlassian.net/browse/DAOS-15441

**Comment by kccain** [comment]
The Unit [testing/Run_in_docker](https://github.com/daos-stack/daos/actions/runs/8384746257/job/22962557517?pr=14046) GHA failure is due to a known problem on master that has since been resolved with a subsequent master commit. It wasn't worth stopping the testing in progress by the time the issue was announced.

**Comment by kccain** [comment]
Ready for review.
The objective daos_test/suite.py test for this PR [passed ](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14046/2/artifact/Functional%20Hardware%20Medium%20Verbs%20Provider/daos_test/suite.py/results.json)in 568 seconds (about 100 seconds more than in a recent daily master [result](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/daily-testing/109/artifact/Functional%20Hardware%20Medium%20Verbs%20Provider/daos_test/suite.py/results.json)).

**Review by liw — APPROVED** [review]

**Review by tanabarr — APPROVED** [review]
Go changes LGTM

**Comment by kccain** [comment]
> Test stage Functional on EL 8.8 completed with status FAILURE. https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14046/3/execution/node/1173/log

looks like this one is an SRE issue, noted in that ticket https://daosio.atlassian.net/browse/SRE-514

**Review by kjacque — APPROVED** [review]

**Review by liw — APPROVED** [review]

**Pull request merged**
