### PR TITLE
DAOS-12105 control: Ordered output for dmg pool list

### PR DESCRIPTION
**Pull request by 0xE0F**
Adds sorted output of `dmg pool list` command by pool label,
which makes it a bit more convenient to run with `watch` et el.

Signed-off-by: Denis Barakhtanov <denis.barahtanov@croit.io>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficent testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by mjmac** [comment]
Created #10904 to test from an internal branch.

**Comment by mjmac** [comment]
> Created #10904 to test from an internal branch.

Passed all tests. Pylint failure seems to be some kind of issue on master.

**Review by mjmac — APPROVED** [review]

**Review by knard-intel — DISMISSED** [review]
LGTM

**Review by tanabarr — DISMISSED** [review]
just needs a commit message

**Comment by 0xE0F** [comment]
@tanabarr thank you, done!

**Review by knard-intel — APPROVED** [review]
Nit, from what I know, the _Features: control_ pragma should be added to the commit message to enable CI tests dedicated to the control plane.
Otherwise, LGTM.

**Comment by tanabarr** [comment]
> @tanabarr thank you, done!

the commit message update doesn't seem to have come through on the GH webpage description (here at the top). please copy it in there

**Review by tanabarr — APPROVED** [review]

**Comment by 0xE0F** [comment]
@tanabarr  done (this time for sure ™️), thank you !

**Review by mjmac — APPROVED** [review]
@daos-stack/daos-gatekeeper: I think this will need a forced landing as it's from an external branch. I created #10904 to test it from an internal branch and it passed.

**Pull request merged**
