### PR TITLE
DAOS-9875 tests: Set server param crt_timeout=10

### PR DESCRIPTION
**Pull request by liw**
Add a 10-second default value for the crt_timeout parameter of
DaosServerYamlParameters, so that tests that may have to wait out full
RPC timeouts can progress faster. This is generally desirable in our
controlled, small-scale CI testing.

Remove the setting of the CRT_TIMEOUT environment variable for pydaos,
which was added due to my ignorance. All libdaos clients are supposed to
get this value from daos_server, who supplies the crt_timeout value from
daos_server.yml.

Signed-off-by: Li Wei <wei.g.li@intel.com>

### CODE REVIEW

**Comment by liw** [comment]
> Test stage Functional Hardware Small completed with status FAILURE. https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8434/4/display/redirect

F_H_S: "provision" error

**Comment by liw** [comment]
F_H_L failures due to the API issue Jeff and Huang discussed in the Build and Test channel.

**Review by johannlombardi — DISMISSED** [review]

**Comment by johannlombardi** [comment]
@phender please review ASAP. I would like to land this one.

**Comment by liw** [comment]
The failed check is "Flake /Lint" for unrelated Python lines; the CI testing has passed.

**Review by shimizukko — APPROVED** [review]

**Review by phender — APPROVED** [review]

**Pull request merged**
