### PR TITLE
DAOS-15738 control: Update required Go build version

### PR DESCRIPTION
**Pull request by kjacque**
Go 1.20 is the latest version currently available via EPEL.

This update will enable developers to use newer Go language features.

Features: control

Required-githooks: true

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by tanabarr — COMMENTED** [review]
I'm running Rocky 8.9 as my dev platform and I just updated and go was bumped to 1.20.12. Shouldn't we still support what's shipped by distros?

**Comment by kjacque** [comment]
> I'm running Rocky 8.9 as my dev platform and I just updated and go was bumped to 1.20.12. Shouldn't we still support what's shipped by distros?

I've gone back and forth on this. @mjmac made a good point that the Go team only supports the 2 latest versions at any given time ([source](https://go.dev/doc/devel/release)):

>Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including [critical security problems](https://go.dev/security), in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

The argument for limiting support to what Go supports seems compelling to me, especially in light of the recent security issues. But we also don't want to make it more painful to build than necessary... I hadn't been keeping track of what was in EPEL since our internal clusters are using a more recent version.

**Comment by kjacque** [comment]
The latest commit uses 1.20. If EPEL is still providing 1.20, it seems like a reasonable version for our build requirement.

**Review by tanabarr — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]

**Comment by kjacque** [comment]
Test failures are unrelated. In our CI system, this PR does not actually change anything, as a newer Go version greater than the minimum specified here is already used to build DAOS.

**Comment by kjacque** [comment]
@daos-stack/daos-gatekeeper please use the title/description of this PR as the commit message.

**Comment by kjacque** [comment]
@daos-stack/daos-gatekeeper Anything keeping this from being force-landed? It would be good to get this change into master, and possibly into 2.6.x as well.

**Comment by daltonbohning** [comment]
> @daos-stack/daos-gatekeeper Anything keeping this from being force-landed? It would be good to get this change into master, and possibly into 2.6.x as well.

I usually defer to @mjmac for control PRs. But maybe it's not merged because @mjmac doesn't have force-landing privs?

**Comment by kjacque** [comment]
@daltonbohning yeah, he does not have force landing privileges.

**Comment by daltonbohning** [comment]
@kjacque This does look sane, but since this PR is unfortunately 3 weeks old now, could you please merge master? Then I can force land if needed

**Comment by kjacque** [comment]
Passed everything this time. @daos-stack/daos-gatekeeper this is ready to land.

**Comment by daltonbohning** [comment]
Thanks @kjacque

**Pull request merged**
