### PR TITLE
DAOS-7220 Test: Test SameKeyDifferentValue, pool create fails, scm to small

### PR DESCRIPTION
**Pull request by omar-ocampo**
Increased pool scm_size

Signed-off-by: Omar Ocampo <omar.ocampo.coronado@intel.com>

### CODE REVIEW

**Review by rpadma2 — APPROVED** [review]

**Review by shimizukko — APPROVED** [review]

**Comment by omar-ocampo** [comment]
@sylviachanoiyee , could you merge this please?

**Comment by omar-ocampo** [comment]
@sylviachanoiyee friendly reminder

**Comment by omar-ocampo** [comment]
@sylviachanoiyee, could we merge?

**Review by sylviachanoiyee — CHANGES_REQUESTED** [review]
I don't see the test in the Jenkins results.
Can you point me to the result if it is run?

**Comment by omar-ocampo** [comment]
> I don't see the test in the Jenkins results.
> Can you point me to the result if it is run?

Why the tests didn't run if those have the tag daily regression?

**Comment by sylviachanoiyee** [comment]
> > I don't see the test in the Jenkins results.
> > Can you point me to the result if it is run?
> 
> Why the tests didn't run if those have the tag daily regression?

So daily_regression is our 'nightly' tag. PRs run a smaller set of tests with tag 'pr'.
If you are enabling a test in weekly (full_regression) or nightly(daily_regression), you would need to use either Test-tag or Feature pragma to include those test in the PR testing

**Comment by omar-ocampo** [comment]
> > > I don't see the test in the Jenkins results.
> > > Can you point me to the result if it is run?
> > 
> > 
> > Why the tests didn't run if those have the tag daily regression?
> 
> So daily_regression is our 'nightly' tag. PRs run a smaller set of tests with tag 'pr'.
> If you are enabling a test in weekly (full_regression) or nightly(daily_regression), you would need to use either Test-tag or Feature pragma to include those test in the PR testing

Ok, re-run set. Time to wait another day

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Review by shimizukko — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
@omar-ocampo , looking at the results of this PR, i'm quite worried to see that you have 2 builds, build #2 and #4 failed with 138 failures. This is not normal. 
Though the changes in this PR is specific to a test, are we sure it is not somehow indirectly causing failure in other tests?
This PR is also based off of master commit from about 10 days ago and probably need update.
Was going to retrigger for you but seeing the test-tag in retrigger was not updated, which tells me it was based off a pretty old commit on master.

**Comment by omar-ocampo** [comment]
> @omar-ocampo , looking at the results of this PR, i'm quite worried to see that you have 2 builds, build #2 and #4 failed with 138 failures. This is not normal.
> Though the changes in this PR is specific to a test, are we sure it is not somehow indirectly causing failure in other tests?
> This PR is also based off of master commit from about 10 days ago and probably need update.
> Was going to retrigger for you but seeing the test-tag in retrigger was not updated, which tells me it was based off a pretty old commit on master.

Please help to review a bit faster so we can avoid PRs getting too old. Merged master and waiting for results.

**Comment by sylviachanoiyee** [comment]
@omar-ocampo , looks like builds #5 and #6 has 144 failures. 
Can you investigate why there's massive failures in this PR? so far we've seen it on 4 builds (build #2, #4, #5, #6) despite having merge with master recently.

**Comment by omar-ocampo** [comment]
> @omar-ocampo , looks like builds #5 and #6 has 144 failures.
> Can you investigate why there's massive failures in this PR? so far we've seen it on 4 builds (build #2, #4, #5, #6) despite having merge with master recently.

There is no clear issue for me, perhaps it is related to the pragma, updating it.

**Comment by shimizukko** [comment]
I believe these tests require hardware, but they ran on VM, so that's why they all failed. It looks like there's an issue with the tag parsing and test allocation to hardware/VM. I think Brian is fixing it, but until then you should use -hw, so try

Test-tag-vm: pr,-hw samekeydifferentvalue

**Comment by omar-ocampo** [comment]
> I believe these tests require hardware, but they ran on VM, so that's why they all failed. It looks like there's an issue with the tag parsing and test allocation to hardware/VM. I think Brian is fixing it, but until then you should use -hw, so try
> 
> Test-tag-vm: pr,-hw samekeydifferentvalue

Thanks Makito, we had the same conclusion :), wiki says -hw is not required but it seems it is being fixed as we speak.

**Review by sylviachanoiyee — APPROVED** [review]

**Pull request merged**
