### PR TITLE
DAOS-15121 test: do not check errno after rewind() (#13743)

### PR DESCRIPTION
**Pull request by wiliamhuang**
cherry-pick [9f38bc5](https://github.com/daos-stack/daos/commit/9f38bc5e44df9994cf52492567a64fb4c01e6dc8) from master to 2.4.

errno may be misleading. ftello() checks the offset anyway.
Fix bug in the run_remote log.debug call when there is not a timeout.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by daltonbohning — APPROVED** [review]

**Comment by wiliamhuang** [comment]
Issues was reported in "Fault injection testing on EL 8.8".
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-13757/2/pipeline/
@daltonbohning Shall we force landing this PR? The issues are not supposed to be relevant to this PR.

**Comment by wiliamhuang** [comment]
@daltonbohning Do we need to get more review or ready to land this PR?

**Comment by daltonbohning** [comment]
@wiliamhuang Merge to 2.4 is closed except for required for 2.4.2. After 2.4.2 releases we can move forward with 2.4.3 PRs.
And, at that time, we'll want to merge in the latest 2.4 so they aren't stale.

**Comment by wiliamhuang** [comment]
> @wiliamhuang Merge to 2.4 is closed except for required for 2.4.2. After 2.4.2 releases we can move forward with 2.4.3 PRs. And, at that time, we'll want to merge in the latest 2.4 so they aren't stale.

@daltonbohning Thank you! This is approved to land 2.4.3. I will merge with latest release/2.4 later then.

**Pull request merged**
