### PR TITLE
DAOS-5719 compression: add framework and lz4/deflate support

### PR DESCRIPTION
**Pull request by wli5**
Add compressor functions
Add LZ4 compression algorithm
Add DEFLATE compression algorithm with ISA-L
Add compression tests

Signed-off-by: Weigang Li <weigang.li@intel.com>

### CODE REVIEW

**Review by johannlombardi — APPROVED** [review]
Looks good to me. Thanks!

**Review by johannlombardi — COMMENTED** [review]
I am afraid that you are going to have to push this patch via a different PR once you have accepted the invite to join our group. That's how CI testing will be triggered.
I created a jira ticket for this activity: DAOS-5719.
Please change the first line of the commit message to be:
"DAOS-5719 compression: add framework and lz4/deflate support"

**Comment by wli5** [comment]
@johannlombardi I've modified the commit and edited the PR, please let me know if it works or I need submit a separate one.

**Comment by wli5** [comment]
Close and resubmit.

**Pull request closed without merging**
