### PR TITLE
DAOS-14718 test: Fix reading of DAOS_TEST_INSECURE_MODE envar (#13441)

### PR DESCRIPTION
**Pull request by tanabarr**
The ConfigGenerateRun tests fail to use certs because insecure mode is
enabled when trying to access non-existent DAOS_INSECURE_MODE env. Fix
by updating env keyname to DAOS_TEST_INSECURE_MODE.

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by daltonbohning — APPROVED** [review]

**Comment by phender** [comment]
I've kicked off https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13560/2/ to run control/config_generate_run.py (a weekly test not run with the default tags).

**Comment by tanabarr** [comment]
@phender Jenkins seems to have passed but some of the checks seem to have not started, what should I do in this instance?

**Comment by phender** [comment]
> @phender Jenkins seems to have passed but some of the checks seem to have not started, what should I do in this instance?

Everything ran as intended.  I kicked off a manual build to only run the `control/config_generate_run.py` tests with https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13560/2/parameters/ since the previous run did not run this test.

**Comment by tanabarr** [comment]
@phender thanks for the response, so can we land this then please?

**Pull request merged**
