### PR TITLE
DAOS-14707 control: Allow multiple agents simultaneously

### PR DESCRIPTION
**Pull request by kjacque**
This allows for the case where multiple agents are used to allow a client connections to multiple systems. The agent log prints a NOTICE-level message to indicate the presence of other daos_agent processes on startup.

Features: control

Required-githooks: true

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by Michael-Hennecke — APPROVED** [review]

**Comment by kjacque** [comment]
> This seems reasonable to me... Only question is what happens when two agents are started with the same config. I assume that one will fail because it can't create the socket, but is the error message clear in that case?

When I attempted this, both agents cheerfully started without issue. The agent automatically deletes and re-create the socket file, which does not actually disconnect the old socket. So the first agent thinks it is still listening, although it wouldn't get any new connections on that socket.

I wonder if we should remove the auto-delete of the socket file. It looks like we're cleaning it up during a normal daos_agent shutdown. If someone killed it, though, obviously there would be a dead socket file left over, and that would need to be manually deleted.

**Comment by knard-intel** [comment]
> > This seems reasonable to me... Only question is what happens when two agents are started with the same config. I assume that one will fail because it can't create the socket, but is the error message clear in that case?
> 
> When I attempted this, both agents cheerfully started without issue. The agent automatically deletes and re-create the socket file, which does not actually disconnect the old socket. So the first agent thinks it is still listening, although it wouldn't get any new connections on that socket.
> 
> I wonder if we should remove the auto-delete of the socket file. It looks like we're cleaning it up during a normal daos_agent shutdown. If someone killed it, though, obviously there would be a dead socket file left over, and that would need to be manually deleted.

From what I understand, the agent is removing the socket during the shutdown.  Thus, in your use case, if the first agent is gracefully shutdown, does he will remove the newly created socket by the second agent.

**Review by tanabarr — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]
LGTM

**Review by mjmac — APPROVED** [review]
Looks good. Nice solution for the socket file conflict!

**Review by knard-intel — APPROVED** [review]

**Review by tanabarr — APPROVED** [review]

**Comment by Michael-Hennecke** [comment]
> > From what I understand, the agent is removing the socket during the shutdown. Thus, in your use case, if the first agent is gracefully shutdown, does he will remove the newly created socket by the second agent.
> 
> Yeah, it would. I think the most efficient way to deal with this, while still allowing two agents, is to not delete the socket on startup. I'll make that change, with a clarifying error message for the admin.

I believe that the "cleanup-on-start" was a conscious decision after discussing more complicated scenarios of cleaning up at the end of a job. it is much more cumbersome to do a cleanup after hangs or aborts (at the end of a job). if we just clean up before we start, that's much easier.  but this certainly makes it more tricky to start two agents on the same node...

is there a way to check if somebody is still at the other end of that socket connection before cleaning it up?

**Review by Michael-Hennecke — CHANGES_REQUESTED** [review]
see comment above

**Comment by kjacque** [comment]
> is there a way to check if somebody is still at the other end of that socket connection before cleaning it up?

Yes, this is actually the solution I ended up using. We attempt to connect to the socket. If there's no error, someone is listening. If connection is refused, the file exists but no one is listening, and we clean it up.

**Review by mjmac — APPROVED** [review]

**Review by Michael-Hennecke — APPROVED** [review]
lgtm

**Pull request merged**
