### PR TITLE
DAOS-623 cq: Upgrade yamllint package

### PR DESCRIPTION
**Pull request by ashleypittman**
Required-githooks: true

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Review by brianjmurrell — APPROVED** [review]
Nice to see this working.  Did anyone get an alert about the `version-checks.yml` failures on master or did it take somebody being proactive and looking to see that it was failing?

**Comment by ashleypittman** [comment]
> Nice to see this working. Did anyone get an alert about the `version-checks.yml` failures on master or did it take somebody being proactive and looking to see that it was failing?

People whose PRs land are getting emails about it.

You can also see it via the red dot next to commits at the main daos github page https://github.com/daos-stack/daos and through the actions page at https://github.com/daos-stack/daos/actions/workflows/version-checks.yml

I'm sure there are yet more improvements to come however.

**Review by daltonbohning — APPROVED** [review]
We should consider backported to 2.4 after https://github.com/daos-stack/daos/pull/13322. Otherwise, the checks could be out of sync there too.

Something else I'm realizing is that githooks don't necessarily use the newer versions. Maybe we need a githook to check that the currently installed versions are the "recommended"?

**Comment by ashleypittman** [comment]
> We should consider backported to 2.4 after #13322. Otherwise, the checks could be out of sync there too.

Personally I think it's OK if the checks there are a little behind, code should be going through master anyway.  The version_checks job is only on master for now.

> Something else I'm realizing is that githooks don't necessarily use the newer versions. Maybe we need a githook to check that the currently installed versions are the "recommended"?

I don't think that matters.  Users should update periodically but unless they hit a failure there's probably no need to check.

**Comment by daltonbohning** [comment]
> > Something else I'm realizing is that githooks don't necessarily use the newer versions. Maybe we need a githook to check that the currently installed versions are the "recommended"?
> 
> I don't think that matters. Users should update periodically but unless they hit a failure there's probably no need to check.

But if they hit a failure they might not necessarily know it's due to version mismatch locally and in the GHA. Anyway, not a huge deal

**Comment by ashleypittman** [comment]
> > > Something else I'm realizing is that githooks don't necessarily use the newer versions. Maybe we need a githook to check that the currently installed versions are the "recommended"?
> > 
> > 
> > I don't think that matters. Users should update periodically but unless they hit a failure there's probably no need to check.
> 
> But if they hit a failure they might not necessarily know it's due to version mismatch locally and in the GHA. Anyway, not a huge deal

If we assume that newer versions enable more checks then if they've got an old version then they'd miss some checks locally that were caught in GHA, that should be rare and checking you're up-to-date if that happens isn't onerous.

The only problem would be is if a program removed a check, then we updated the codebase to violate that check, it's possible but I'm not going to loose any sleep over it.

**Pull request merged**
