### PR TITLE
DAOS-11174 control: Update vendored dependencies

### PR DESCRIPTION
**Pull request by mjmac**
Raise minimum supported go version to 1.16, and:  
  - update raft to v1.3.9
  - update raft-grpc-transport to v1.2.0
  - update go-cmp to v0.5.8
  - update uuid to v1.3.0
  - update go-flags to v1.5.0
  - update prometheus/client_golang to v1.12.2
  - update grpc to v1.47.0
  - update protobuf to v1.28.0
  - update yaml to v2.4.0

Updates hclogger wrapper to remove panics on
unimplemented methods and instead implements
basic stub functionality.

Features: control

Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>

### CODE REVIEW

**Review by jolivier23 — COMMENTED** [review]
Wow, this is big.  You can avoid jira query error if you set ticket to in-progress before uploading.

**Comment by mjmac** [comment]
> Wow, this is big. You can avoid jira query error if you set ticket to in-progress before uploading.

Yeah, probably should have iterated in draft mode too, sorry for the noise.

**Review by tanabarr — APPROVED** [review]
Should probably have some mention in the commit message about the changes to telemetry_utils.py as it seems unrelated to the PR title.

Also could you add a one-liner to explain to people how to update the vendored dependencies locally after pulling this change.

Otherwise, looks great.

**Comment by mjmac** [comment]
> Should probably have some mention in the commit message about the changes to telemetry_utils.py as it seems unrelated to the PR title.
> 
They're necessary to avoid having the test fail whenever the prometheus client library is updated. The test really shouldn't be looking at that stuff anyhow. That part was ported over from a smaller required update on the 2.2 branch: #8654

> Also could you add a one-liner to explain to people how to update the vendored dependencies locally after pulling this change.
> 
There shouldn't be anything required. Just git pull, as usual.

**Review by brianjmurrell — COMMENTED** [review]
Most of this is outside my wheelhouse, but the build/packaging parts LGTM.

**Comment by mjmac** [comment]
There are two code changes that are required due to the updated dependencies:

- [hclogger wrapper updates](https://github.com/daos-stack/daos/pull/9790/files#diff-465a30b3626233599d6eb6df99994e4309c9f2fb20410821cd912c0695952c1c) needed to avoid a runtime panic due to new usage of a previously-unused method
- [telemetry_utils.py updates](https://github.com/daos-stack/daos/pull/9790/files#diff-6e25370e373cb7c8ca614e696e921903ec4b4988124e44160b1105922eb3e036) needed to avoid failing telemetry tests whenever the prometheus client library is updated (we shouldn't be testing the prometheus library anyhow)

**Comment by mjmac** [comment]
Two unrelated failures in hw-medium due to [DAOS-11180](https://daosio.atlassian.net/browse/DAOS-11180).

**Review by knard-intel — APPROVED** [review]

**Pull request merged**
