### PR TITLE
DAOS-12942 bio: enable SSD auto faulty

### PR DESCRIPTION
**Pull request by NiuYawei**
- Enable SSD auto faulty by default.
- Fixed client retry code to retry update on -DER_NVME_IO error.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by Nasf-Fan — DISMISSED** [review]
It is better to add some comment about the purpose of allow retry update under DER_NVME_IO, that will avoid confusing for other developers.

**Review by wangdi1 — APPROVED** [review]

**Review by wangdi1 — DISMISSED** [review]

**Review by liuxuezhao — APPROVED** [review]

**Comment by NiuYawei** [comment]
merge to pick fix of DAOS-12857

**Comment by NiuYawei** [comment]
Looks the test failure is DAOS-9509, I don't think this PR would affect cart-self test.

**Comment by NiuYawei** [comment]
ping reviewers.

**Review by wangdi1 — APPROVED** [review]

**Review by Nasf-Fan — APPROVED** [review]

**Comment by NiuYawei** [comment]
There is only one cart-self test failure, I created DAOS-13080.

**Pull request merged**
