### PR TITLE
DAOS-6798 container: stop aggregation ULT when stopping pool

### PR DESCRIPTION
**Pull request by wangdi1**
Stop aggregation if the pool is being destoryed(sp_stopping = 1).

Signed-off-by: Di Wang <di.wang@intel.com>

### CODE REVIEW

**Review by NiuYawei — CHANGES_REQUESTED** [review]
Let's fix the real deadlock problem I mentioned in DAOS-6798.

**Comment by wangdi1** [comment]
> Let's fix the real deadlock problem I mentioned in DAOS-6798.

Yes, this won't fix the issue of 6798, but I think it makes sense to stop aggregation when the pool are being destroyed. 

I do not see how it will add extra complexity?  Or what is your real concern here?

**Comment by NiuYawei** [comment]
> > Let's fix the real deadlock problem I mentioned in DAOS-6798.
> 
> Yes, this won't fix the issue of 6798, but I think it makes sense to stop aggregation when the pool are being destroyed.
> 
> I do not see how it will add extra complexity? Or what is your real concern here?

Yes, we have to stop aggregation ULTs when pool are going to be destroyed, and that's what we did in existing code.

The extra 'pool->sp_stopping' checks from this patch are redundant and racy. For instance: 1. what if 'sp_stopping' is set after the check? 2. 'ds_pool' is maintained by xstream 0, and the updating to bit flag 'sp_stopping' isn't atomic, so checking 'sp_stopping' on other xstreams could get unexpected result. (you may wrongly get sp_stopping == 1 when xstream 0 updating other bit fields)

IMHO, acessing (without locking) to 'ds_pool' from other xstreams should be restricted to the scenario of: atomic read on an integer, and reader doesn't care if the value would be immediately changed after reading.

**Comment by liw** [comment]
I tend to agree with Niu. Even if accessing sp_stopping is safe, I prefer not to do it in src/container, unless absolutely necessary. Unlike sp_map, sp_stopping is more of a private field.

**Comment by wangdi1** [comment]
> > > Let's fix the real deadlock problem I mentioned in DAOS-6798.
> > 
> > 
> > Yes, this won't fix the issue of 6798, but I think it makes sense to stop aggregation when the pool are being destroyed.
> > I do not see how it will add extra complexity? Or what is your real concern here?
> 
> Yes, we have to stop aggregation ULTs when pool are going to be destroyed, and that's what we did in existing code.
> 
> The extra 'pool->sp_stopping' checks from this patch are redundant and racy. For instance: what if 'sp_stopping' is set after the check?
> 
> IMHO, acessing (without locking) to 'ds_pool' from other xstreams should be restricted to the scenario of: atomic read on an integer, and reader doesn't care if the value would be immediately changed after reading.

Hmm, this is never precise check here, otherwise we won't have this problem. I mean this will help us expedite stop process and mitigate those -2017 error during pool destroy or system stop, especially if there are a lot containers.

Sorry, I do not see how this is redundant.

**Comment by wangdi1** [comment]
> I tend to agree with Niu. Even if accessing sp_stopping is safe, I prefer not to do it in src/container, unless absolutely necessary. Unlike sp_map, sp_stopping is more of a private field.

Hmm, I thought it makes sense for container to know the status of pool? No?

**Review by NiuYawei — APPROVED** [review]
Discussed with Di. I'm fine with landing this.

**Comment by liw** [comment]
> > I tend to agree with Niu. Even if accessing sp_stopping is safe, I prefer not to do it in src/container, unless absolutely necessary. Unlike sp_map, sp_stopping is more of a private field.
> 
> Hmm, I thought it makes sense for container to know the status of pool? No?

Yes. When stopping a ds_pool object, we will call into pool_child_delete_one -> ds_cont_child_stop_all -> cont_stop_agg_ult. Looking at the agg ULT code, without this patch, I think the ULT will exit at the beginning of cont_aggregate_epr. Therefore, this patch seems unnecessary, ..., no?

The real issue is there's no way to abort an IV operation. I feel we should just go in the direction of adding IV operation descriptors and an API to abort such a descriptor.

**Comment by wangdi1** [comment]
> > > I tend to agree with Niu. Even if accessing sp_stopping is safe, I prefer not to do it in src/container, unless absolutely necessary. Unlike sp_map, sp_stopping is more of a private field.
> > 
> > 
> > Hmm, I thought it makes sense for container to know the status of pool? No?
> 
> Yes. When stopping a ds_pool object, we will call into pool_child_delete_one -> ds_cont_child_stop_all -> cont_stop_agg_ult. Looking at the agg ULT code, without this patch, I think the ULT will exit at the beginning of cont_aggregate_epr. Therefore, this patch seems unnecessary, ..., no?

If there are a lot containers, it will help to stop the most container go into aggregation, and expedite the stop process. Yes, it will not stop all of them.  

> 
> The real issue is there's no way to abort an IV operation. I feel we should just go in the direction of adding IV operation descriptors and an API to abort such a descriptor.

Hmm, it is not only abort the IV operation. Note: to do IV, each xstream will also need create an ULT on xstream 0, then it can see iv stop during stop process. IMHO.

**Comment by liw** [comment]
> > Yes. When stopping a ds_pool object, we will call into pool_child_delete_one -> ds_cont_child_stop_all -> cont_stop_agg_ult. Looking at the agg ULT code, without this patch, I think the ULT will exit at the beginning of cont_aggregate_epr. Therefore, this patch seems unnecessary, ..., no?
> 
> If there are a lot containers, it will help to stop the most container go into aggregation, and expedite the stop process. Yes, it will not stop all of them.

ds_cont_child_stop_all will stop all of them, ..., no? If an aggregation ULT will stop with the patch, it will also stop without this patch. That's not the case?

> > The real issue is there's no way to abort an IV operation. I feel we should just go in the direction of adding IV operation descriptors and an API to abort such a descriptor.
> 
> Hmm, it is not only abort the IV operation. Note: to do IV, each xstream will also need create an ULT on xstream 0, then it can see iv stop during stop process. IMHO.

The real issue is when the IV operation on xstream 0 has already started when stopping the pool.

**Comment by wangdi1** [comment]
> 
> ds_cont_child_stop_all will stop all of them, ..., no? If an aggregation ULT will stop with the patch, it will also stop without this patch. That's not the case?
> 

Yes, but ds_cont_child_stop_all() will wait for all containers's aggregate ULT to stop.  If the aggregate ULT is still trying to go ahead, which will create extra ULT on xstream 0 to do IV fetch etc,  instead of being stopped by checking sp_stopping,  then it will need longer time to wait.   Especially, if there are a lot containers needs to be stopped.


> > > The real issue is there's no way to abort an IV operation. I feel we should just go in the direction of adding IV operation descriptors and an API to abort such a descriptor.
> > 
> > 
> > Hmm, it is not only abort the IV operation. Note: to do IV, each xstream will also need create an ULT on xstream 0, then it can see iv stop during stop process. IMHO.
> 
> The real issue is when the IV operation on xstream 0 has already started when stopping the pool.

Oh, this is different issue, if aggregate ULT is in the middle of IV, there is no easy way to abort the ULT promptly.

**Comment by liw** [comment]
> If the aggregate ULT is still trying to go ahead, which will create extra ULT on xstream 0 to do IV fetch etc, instead of being stopped by checking sp_stopping, then it will need longer time to wait.
> 
> Oh, this is different issue, if aggregate ULT is in the middle of IV, there is no easy way to abort the ULT promptly.

If IV operations are abortable, "it will need longer time to wait" won't be as long as a full RPC timeout, and we probably won't care so much about stopping an aggregation ULT by sp_stopping, right? The abort issue will rise again.

**Review by liw — APPROVED** [review]

**Pull request merged**
