### PR TITLE
test conditional java build

### PR DESCRIPTION
**Pull request by zjf2012**
Signed-off-by: jiafu zhang <jiafu.zhang@intel.com>

### CODE REVIEW

**Comment by zjf2012** [comment]
@johannlombardi , I tested several times with failed and successful DAOS build. The conditional Java build worked as expected. please help review. thanks.

**Comment by jolivier23** [comment]
> Is there any reason all of this isn't baked into our `scons` build orchestrator instead of having multiple different (`scons`, `make`) external build commands?
> 
> Our RPM builder (`make -C utils/rpms rpms`) has an scons entry-point
> 
> https://github.com/daos-stack/daos/blob/0611da5d71bb24a59ebf4fa8129ed73aaa0f7c97/SConstruct#L428-L429
> 
> for example.
> Although I would expect integration of the building of this java client to be more automatic, such that `scons build` builds the java client automatically assuming all local dependencies are built successfully and all build tools necessary are installed.
> 
> I'm not sure how popular the java client is going to be and/or how many users we might frustrate by requiring them to install java build tools if they don't want the java client, so perhaps it should be optional, with a warning that it won't be built if the tools are missing, similar to how we don't build any MPI tests if there is no MPI stack found

We could probably add a sticky option to build the java stuff directly that is default disabled to alleviate the concern about requiring it.

**Comment by jolivier23** [comment]
> > Is there any reason all of this isn't baked into our `scons` build orchestrator instead of having multiple different (`scons`, `make`) external build commands?
> > Our RPM builder (`make -C utils/rpms rpms`) has an scons entry-point
> > https://github.com/daos-stack/daos/blob/0611da5d71bb24a59ebf4fa8129ed73aaa0f7c97/SConstruct#L428-L429
> > 
> > for example.
> > Although I would expect integration of the building of this java client to be more automatic, such that `scons build` builds the java client automatically assuming all local dependencies are built successfully and all build tools necessary are installed.
> > I'm not sure how popular the java client is going to be and/or how many users we might frustrate by requiring them to install java build tools if they don't want the java client, so perhaps it should be optional, with a warning that it won't be built if the tools are missing, similar to how we don't build any MPI tests if there is no MPI stack found
> 
> We could probably add a sticky option to build the java stuff directly that is default disabled to alleviate the concern about requiring it.

one question I have though is whether we can pass flags to the build to build against intermediate build location rather than install location.   I don't like the idea of a build depending on "install" target getting specified.

**Comment by brianjmurrell** [comment]
> > We could probably add a sticky option to build the java stuff directly that is default disabled to alleviate the concern about requiring it.

Don't really have an opinion about sticky or not.  Just thinking about how our MPI auto-detection-and-use is done, and how many other GNU Autotools projects have optional bits that can be built dependent on finding the tools/libs needed to build them and disabling their build if they are missing.
 
> one question I have though is whether we can pass flags to the build to build against intermediate build location rather than install location. I don't like the idea of a build depending on "install" target getting specified.

Oh yeah.  Definitely.  Whatever is being built by Java build needs to be able to build with the intermediate product and not require `scons install` first.

**Comment by jolivier23** [comment]
> er GNU Autotools projects have optional bits that can be built dependent on finding the tools/libs needed to build them and disabling their build if they are missing.

that is certainly another option, to just do it automatically based on what is installed though it's harder to detect when it breaks without subsequent testing

**Comment by brianjmurrell** [comment]
> that is certainly another option, to just do it automatically based on what is installed though it's harder to detect when it breaks without subsequent testing

I've seem one common approach is for `./configure` to display a list of what it's building and what it's not based on what it found.

> all that said, I have no issue with the immediate patch

I don't really either.  I was just wondering if there was a better way to do it, relatively easily, rather than building out more things that have to be done which will eventually want their own wrapper around them.

**Comment by zjf2012** [comment]
Thanks for all your comments. First of all, I think the Java client build here is for development purpose. It's not included in the RPM build.  For the Java build tool, maven, there is no alternative for now since the Java project is managed by Maven which is most popular tool in Java world if not defacto standard. Maven not only does build, but also manages dependencies, like downloading all deps automatically. Of course, we can integrate it to scons which invokes maven then.

**Comment by brianjmurrell** [comment]
> Of course, we can integrate it to scons which invokes maven then.

Yes, indeed.  I wouldn't even imagine trying to replace maven with `scons` (at this point at least, if ever), but having the java client build (via maven) done from `scons` provides the most seamless experience, rather than growing the list of tasks that a user/developer has to do to build the whole stack, IMHO.

They can then decide which optional parts they want to build by making sure the dependencies for them are installed rather than having to know to run more commands to build more of the stack.

**Comment by zjf2012** [comment]
@johannlombardi , will you approve this for now? We can move the mvn build to scons later.

**Pull request merged**
