### PR TITLE
CART-574 cache: HG cache updates

### PR DESCRIPTION
**Pull request by frostedcmos**
- Only a single hg address cache is now stored
- Cache operations are no longer dependant on local context

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

### CODE REVIEW

**Comment by liuxuezhao** [comment]
> have not read details, but need to confirm one thing firstly
> 
> Some HG plugin is connection-based, for example HG SM plugin. When different source contexts send msg to same target context (on the same node), the internal socket connection is different. If you mix the cache of different source context together, i don't know how can it work.
> 
> Did you test with HG SM plugin, and create multiple local contexts and communicate with each other?

And even for most commonly used socket provider, if we use regular EP, when create multiple local contexts (each is one regular EP), and communicate with same target tag, it will mix the different addr with each other, I think it will not work for this either, since each regular EP pari (source + tgt) is with different socket connection.

**Comment by frostedcmos** [comment]
> > have not read details, but need to confirm one thing firstly
> > Some HG plugin is connection-based, for example HG SM plugin. When different source contexts send msg to same target context (on the same node), the internal socket connection is different. If you mix the cache of different source context together, i don't know how can it work.
> > Did you test with HG SM plugin, and create multiple local contexts and communicate with each other?
> 
> And even for most commonly used socket provider, if we use regular EP, when create multiple local contexts (each is one regular EP), and communicate with same target tag, it will mix the different addr with each other, I think it will not work for this either, since each regular EP pair (source + tgt) is with different socket connection.

The new lookup routine HG_Lookup_Addr2() that Jerome provided no longer relies on a local context, it only needs hg class now to lookup endpoint address. We've verified with Jerome (and requested from him in a first place) that addresses are not formed by relying on source EP; the only information is required is destination EP that differentiates each remote EP address. Further Jerome has refactored sm plugin in 2.0 to fit into this new model. I have only done very brief sm testing locally myself. 
For sockets provider we have passed both local and CI testing with this change.

**Comment by liuxuezhao** [comment]
> > And even for most commonly used socket provider, if we use regular EP, when create multiple local contexts (each is one regular EP), and communicate with same target tag, it will mix the different addr with each other, I think it will not work for this either, since each regular EP pair (source + tgt) is with different socket connection.
> 
> The new lookup routine HG_Lookup_Addr2() that Jerome provided no longer relies on a local context, it only needs hg class now to lookup endpoint address. We've verified with Jerome (and requested from him in a first place) that addresses are not formed by relying on source EP; the only information is required is destination EP that differentiates each remote EP address. Further Jerome has refactored sm plugin in 2.0 to fit into this new model. I have only done very brief sm testing locally myself.
> For sockets provider we have passed both local and CI testing with this change.

OK, thx for the info about the SM plugin change.

But even after HG_Lookup_Addr2() added that it only bind to hg class (and decoupled from hg context), I think it is still unsafe to make this patch's change to cart.
Let's see a use case --
At node A we create two local cart contexts A_1 and A_2, each one corresponds to one hg class (one hg class corresponds to one OFI regular EP). Now with one target node B and with one local context on node B - context B_1.
Now A_1 send RPC to B_1, internal socket connection established between those two regular EPs of A_1 and B_1.
Then A_2 send RPC to B_1, it will firstly lookup local cart-level addr cache and get the cached addr that is actually the connection between A_1 and B_1, it will cause some problem if reuse that addr for the communication between A_2 and B_1, because they *should* establish independent socket connection between A_2 and B_1 and send msg over that new connection.
Probably that case is not well covered by the CI test, but that use case looks cannot work correctly after this patch, by my understanding.

**Comment by frostedcmos** [comment]
> > > And even for most commonly used socket provider, if we use regular EP, when create multiple local contexts (each is one regular EP), and communicate with same target tag, it will mix the different addr with each other, I think it will not work for this either, since each regular EP pair (source + tgt) is with different socket connection.
> > 
> > 
> > The new lookup routine HG_Lookup_Addr2() that Jerome provided no longer relies on a local context, it only needs hg class now to lookup endpoint address. We've verified with Jerome (and requested from him in a first place) that addresses are not formed by relying on source EP; the only information is required is destination EP that differentiates each remote EP address. Further Jerome has refactored sm plugin in 2.0 to fit into this new model. I have only done very brief sm testing locally myself.
> > For sockets provider we have passed both local and CI testing with this change.
> 
> OK, thx for the info about the SM plugin change.
> 
> But even after HG_Lookup_Addr2() added that it only bind to hg class (and decoupled from hg context), I think it is still unsafe to make this patch's change to cart.
> Let's see a use case --
> At node A we create two local cart contexts A_1 and A_2, each one corresponds to one hg class (one hg class corresponds to one OFI regular EP). Now with one target node B and with one local context on node B - context B_1.
> Now A_1 send RPC to B_1, internal socket connection established between those two regular EPs of A_1 and B_1.
> Then A_2 send RPC to B_1, it will firstly lookup local cart-level addr cache and get the cached addr that is actually the connection between A_1 and B_1, it will cause some problem if reuse that addr for the communication between A_2 and B_1, because they _should_ establish independent socket connection between A_2 and B_1 and send msg over that new connection.
> Probably that case is not well covered by the CI test, but that use case looks cannot work correctly after this patch, by my understanding.

I've locally modified now no_pmix_launcher test, which starts 5 servers and 1 client; server has 8 tags, client creates 10 contexts. client first sends ping rpc from context0 to all server tags on all servers. In modification client then sends pings again to each server tag, but this time in a loop from contexts 1 through 9. 

I've also added error prints to see when i perform hg_address lookups, and they are only look-ed up on first iteration, so subsequent ones reuse existing cached hg_addr. This portion of test worked fine:

CLI [rank=0 pid=2082]   Sending ping to 0:1
>>> ALEXMOD: Performing address lookup for 0:1
CLI [rank=0 pid=2082]   Ping response from 0:1
CLI [rank=0 pid=2082]   Sending ping to 0:2
>>> ALEXMOD: Performing address lookup for 0:2
CLI [rank=0 pid=2082]   Ping response from 0:2
CLI [rank=0 pid=2082]   Sending ping to 0:3
>>>  ALEXMOD: Performing address lookup for 0:3
CLI [rank=0 pid=2082]   Ping response from 0:3
....

CLI [rank=0 pid=195346] --------------------------------
CLI [rank=0 pid=195346] Sending over EXTRA CTXs
CLI [rank=0 pid=195346] --------------------------------
CLI [rank=0 pid=195346] Sending ping to 0:0
CLI [rank=0 pid=195346] Response (ext_ctx=0) from 0:0
CLI [rank=0 pid=195346] Response (ext_ctx=1) from 0:0
CLI [rank=0 pid=195346] Response (ext_ctx=2) from 0:0
...
CLI [rank=0 pid=195346] Response (ext_ctx=8) from 0:0
CLI [rank=0 pid=195346] Sending ping to 0:1
CLI [rank=0 pid=195346] Response (ext_ctx=0) from 0:1
....


however i do see some strange issue at finalize where client somehow ends up with extra hg_addrs according to mercury:

07/23-16:33:25.73 wolf-55 CaRT[195346/195548] hg   ERR  # HG -- Error -- /home/aaoganez/github/daos/build/external/dev/mercury/src/mercury_core.c:1091
 # hg_core_finalize(): HG addrs must be freed before finalizing HG (-8 remaining)

(Number of addresses to be free-ed varies from run to run, sometimes 3, other times 15). 

Let's take this conversation into email with Jerome to get clarifications from him

**Comment by liuxuezhao** [comment]
For the testing you ran, not sure is it using regular EP or SEP. When using regular EP, I think it cannot work well for the case of A_1 and A_2 both communicate with B_1 as mentioned above. When using SEP, it probably can work.

"I've locally modified now no_pmix_launcher test, which starts 5 servers and 1 client; server has 8 tags, client creates 10 contexts. client first sends ping rpc from context0 to all server tags on all servers. In modification client then sends pings again to each server tag, but this time in a loop from contexts 1 through 9."
A specific test can be using both context0 and context1 on client, to send RPC to same server's context0. (config it to use regular EP).

For the "hg_core_finalize" issue, seems some addrs were not cleanup/tear-down (but not sure what exactly caused the failure in your testing).

**Comment by frostedcmos** [comment]
> For the testing you ran, not sure is it using regular EP or SEP. When using regular EP, I think it cannot work well for the case of A_1 and A_2 both communicate with B_1 as mentioned above. When using SEP, it probably can work.
> 
> "I've locally modified now no_pmix_launcher test, which starts 5 servers and 1 client; server has 8 tags, client creates 10 contexts. client first sends ping rpc from context0 to all server tags on all servers. In modification client then sends pings again to each server tag, but this time in a loop from contexts 1 through 9."
> A specific test can be using both context0 and context1 on client, to send RPC to same server's context0. (config it to use regular EP).
> 
> For the "hg_core_finalize" issue, seems some addrs were not cleanup/tear-down (but not sure what exactly caused the failure in your testing).

This was using regular EP, this test does not utilize SEP. This also verified by fact that each remote taghad its own address and its own hg (with SEP we would just have 1 endpoint for all server tags).

This test essentially does what you describe but instead of using context0 and context1 on client it uses context0 through context9 going to same server's context0 (after which it tries same loop going all to same server's context1 and so on)

**Comment by frostedcmos** [comment]
hg_core_finalize() issue seems related to this somehow. From the test logs itself I can see that we are looking up and hg-free-ing same number of addresses. When test is only sending on local context0 this issue does not happen. When I modified to also send on other local contexts i see this issue at finalize time, though number of hg addr lookups and hg frees does not change in those 2 cases. I will upload test changes so you can see on your own if you are interested

To run test locally:
aaoganez@wolf-55 daos> cd install/lib/cart/TESTING/

modify nopmix_launcher/cart_nopmix_launcher_one_node.yaml  to set proper server/client nodes

aaoganez@wolf-55 TESTING> ./launch.py -s no_pmix_launcher,one_node

**Comment by liuxuezhao** [comment]
I met some issue when try to run the test as you said (maybe due to my mpi environment/config issue).

But anyway, even if the test can pass, I still think there is some problems. A little bit more explanation -
at local node A:
cart context A1, map to mercury-level HG class_A1 and na_class_A1, and ofi-level socket regular EP A1  
cart context A2, map to mercury-level HG class_A2 and na_class_A2, and ofi-level socket regular EP A2
at remote node B:
cart context B1, map to mercury-level HG class_B1 and na_class_B1, and ofi-level socket regular EP B1

1st step A1 send RPC to B1, by hg_addr_lookup() cart will get back hg_addr_A1 from mercury, in that process ofi-level will establish socket connection_A1 between A1 and B1, the hg_addr_A1 internally associated with socket connection_A1.
2nd step, A2 send RPC to B1, after this patch crt_req_ep_lc_lookup() will get back the cached hg_addr_A1, that is actually socket connection between A1 and B1, but ideally the msg should send through A2 --> B1 connection.

We ever had a very old cart ticket (https://jira.hpdd.intel.com/browse/CART-8) related with this issue, but TBH I forgot the very details of that old issue.

**Comment by frostedcmos** [comment]
Based on response from Jerome, is there a reason why we cant just reuse same hg_class but different hg_contexts for each cart context? Is there some tangible benefit we get out of the fact that each cart context has individual hg_class vs them all sharing same hg class?

**Comment by liuxuezhao** [comment]
> tangible

When using OFI regular EP (note that SEP possibly not supported by some OFI providers like verbs), if we only use one HG class that means we can only use one single regular EP, that is not good for performance.

**Pull request closed without merging**
