### PR TITLE
DAOS-5984 [daos-java] enhanced getFileAttribute method by truncating …

### PR DESCRIPTION
**Pull request by zjf2012**
…too long username and groupname of file due to potential DAOS error coding

Signed-off-by: jiafu zhang <jiafu.zhang@intel.com>

### CODE REVIEW

**Comment by zjf2012** [comment]
@carsonwang @johannlombardi please help review.

**Comment by carsonwang** [comment]
Can you add a test case that fails before and passes with this patch?

**Comment by zjf2012** [comment]
> Can you add a test case that fails before and passes with this patch?

I had the IT to verify this function. But as I said it worked in most of time. Like you tested in Argonne, it just failed in two tasks where they read same file with same username and group. This patch is just an enhancement. Long time ago, I tried to do the boundary test, like full length of username and group, but rolled back due to permission to create username and group in test env, like travis. And I cannot mock it too since they are from DAOS. What do you think?

**Review by carsonwang — APPROVED** [review]
LGTM

**Pull request merged**
