### PR TITLE
DAOS-13670 control: Add system name validation on startup

### PR DESCRIPTION
**Pull request by knard-intel**
# Description

Explicitly check the configured system name and fail if it does not meet requirements.
Miscellaneous small improvements of the src/tests/ftest/control/version.py test.

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by knard-intel** [comment]
PR will fail until PR #12544 has been landed within release 2.4 branch.

**Comment by knard-intel** [comment]
The last PR build [5](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12644/5/pipeline) failed on one known issue:
* [DAOS-13931](https://daosio.atlassian.net/browse/DAOS-13931): Trace of build failure  [daos/test_suite.py:DaosCoreTest:test_daos_extend_simple](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-12644/5/testReport/FTEST_daos_test/DaosCoreTest/Test_Hardware___Functional_Hardware_Medium_Verbs_Provider___20___daos_test_suite_py_DaosCoreTest_test_daos_extend_simple_run_agent_config_transport_config_daos_tests_args_daos_test_num_clients_pools_created_scalable_endpoint_stopped_ranks_test_name_dmg_hosts_pool_server_config_engines_0_storage_0_1_timeouts_ba06//)

**Review by shimizukko — APPROVED** [review]

**Review by kjacque — APPROVED** [review]

**Review by tanabarr — APPROVED** [review]
The only comment I left is minor and should only be addressed if you have to re-push, thanks

**Comment by tanabarr** [comment]
@daos-stack/daos-gatekeeper please could this PR be force landed?

**Pull request merged**
