### PR TITLE
Add compilation_db tool and cdb command

### PR DESCRIPTION
**Pull request by zalsader**
This change allows the creation of [compile_commands.json](https://scons.org/doc/production/HTML/scons-user/ch27.html) ([example](https://github.com/daos-stack/daos/files/8384552/compile_commands.json.txt)) using the following command:
```bash
scons [...] cdb
```
and the file `compile_commands.json` will be created in the same directory.

# Why?
Generating `compile_commands.json` helps with static code analysis using tools like [scanyp](https://www.scanyp.com/ScanyxForC) (commercial) or [cppcheck](https://cppcheck.sourceforge.io/) (Free - GPLv3)

# Notes
a side effect of this is that the minimum required version for scons is 4.0. The version installed by pip is always the latest version, but package managers might have outdated versions.

### CODE REVIEW

**Comment by jolivier23** [comment]
Ok, I just experimented with this a bit.  An alternative would be to do this in ~/.scons_localrc.  But if it's beneficial to add it, we can do so.  But I think it really should be available only if 4.0 is the version of scons used.
Import('env')
env.Replace(COMPILATIONDB_USE_ABSPATH=True)
env.Tool('compilation_db')
cdb = env.CompilationDatabase()
Alias('cdb', cdb)

**Comment by zalsader** [comment]
> Ok, I just experimented with this a bit. An alternative would be to do this in ~/.scons_localrc. But if it's beneficial to add it, we can do so. But I think it really should be available only if 4.0 is the version of scons used. Import('env') env.Replace(COMPILATIONDB_USE_ABSPATH=True) env.Tool('compilation_db') cdb = env.CompilationDatabase() Alias('cdb', cdb)

Oh, that's a great idea, I will try it, thank you. 
Feel free to close or keep the PR if you think it is beneficial.

**Comment by jolivier23** [comment]
> > Ok, I just experimented with this a bit. An alternative would be to do this in ~/.scons_localrc. But if it's beneficial to add it, we can do so. But I think it really should be available only if 4.0 is the version of scons used. Import('env') env.Replace(COMPILATIONDB_USE_ABSPATH=True) env.Tool('compilation_db') cdb = env.CompilationDatabase() Alias('cdb', cdb)
> 
> Oh, that's a great idea, I will try it, thank you. Feel free to close or keep the PR if you think it is beneficial.

I'll consider it.  I've never used these tools.   By the way, the compile database in this case got placed in the home directory

**Review by jolivier23 — COMMENTED** [review]
did you figure something out here?  This came up in my inbox again because github seems to have recently processed CODEOWNERS on old PRs and this changes SCons code.

**Comment by zalsader** [comment]
Let's just close this. It will require changing the minimum scons version. Besides, if it's possible to do without changing code then let's do it.

**Pull request closed without merging**
