### PR TITLE
DAOS-12077 test: Failover improvement with pool query test

### PR DESCRIPTION
**Pull request by knard38**
# Description

Add yaml configuration parameter allowing to define the number of access point replicas of the system.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by daltonbohning — COMMENTED** [review]
Is the intention just to change the number of access points to 3?
If so, that should already be done by the framework here:
https://github.com/daos-stack/daos/blob/7e04780d5490ff155a5a2a042b3fe893e35be86b/src/tests/ftest/util/apricot/apricot/test.py#L714

Even in release/2.2:
https://github.com/daos-stack/daos/blob/c67e6dcf33b0433b07a3662e2bffec0d85e5abbf/src/tests/ftest/util/apricot/apricot/test.py#L697C63-L697C63

Am I misunderstanding?

**Comment by knard-intel** [comment]
> Is the intention just to change the number of access points to 3? If so, that should already be done by the framework here:
> 
> https://github.com/daos-stack/daos/blob/7e04780d5490ff155a5a2a042b3fe893e35be86b/src/tests/ftest/util/apricot/apricot/test.py#L714
> 
> Even in release/2.2: https://github.com/daos-stack/daos/blob/c67e6dcf33b0433b07a3662e2bffec0d85e5abbf/src/tests/ftest/util/apricot/apricot/test.py#L697C63-L697C63
> 
> Am I misunderstanding?

Did not know about that functionality of the framework.
From what I understood from the ticket it was (as you said) just to increase the number of access points.
I am going to check with the ticket reporter.

**Comment by knard-intel** [comment]
Thanks @daltonbohning , it seems that I have misunderstood the ticket.
I am going to rework my PR.

**Comment by knard-intel** [comment]
> > Is the intention just to change the number of access points to 3? If so, that should already be done by the framework here:
> > https://github.com/daos-stack/daos/blob/7e04780d5490ff155a5a2a042b3fe893e35be86b/src/tests/ftest/util/apricot/apricot/test.py#L714
> > 
> > Even in release/2.2: https://github.com/daos-stack/daos/blob/c67e6dcf33b0433b07a3662e2bffec0d85e5abbf/src/tests/ftest/util/apricot/apricot/test.py#L697C63-L697C63
> > Am I misunderstanding?
> 
> * [x]  Increase pool service replicas

Fixed with commit 9b2bc5cf9

**Review by daltonbohning — COMMENTED** [review]
From the commit pragmas:
```
Test-tags: pr all,DmgPoolQueryRanks
```
`Test-tags` should be `Test-tag`, it's not necessary to use `all`, and if you're only modifying a single functional test, you don't even need `pr`. So
```
Test-tag: DmgPoolQueryRanks
```

But, isn't the default svcn for pools 3+ if there are enough ranks? Is this PR needed at all? Maybe the ticket is stale?

**Comment by knard-intel** [comment]
> From the commit pragmas:
> 
> ```
> Test-tags: pr all,DmgPoolQueryRanks
> ```
> 
> `Test-tags` should be `Test-tag`, it's not necessary to use `all`, and if you're only modifying a single functional test, you don't even need `pr`. So
Lastly, I prefer to always add `pr` as I recently have some bad surprise with modification of functional tests which have some unplanned consequences on other tests :'(  However, with this modification, I agree that it is clearly impossible that there 
Otherwise, Thanks for the pragma typo correction: I was not understanding why with my previous pragma the DmgPoolQueryRanks tests were not run.
I am gong to fix this with merging with master.

> 
> ```
> Test-tag: DmgPoolQueryRanks
> ```
> 
> But, isn't the default svcn for pools 3+ if there are enough ranks? Is this PR needed at all? Maybe the ticket is stale?

Without this configuration option the `--nsvc` option is not defined with the pool create command.  Thus, this ticket seems still valid from my understanding.

**Comment by knard-intel** [comment]
> * fix commit pragma

Fixed with commit eb1e53be8

**Comment by knard-intel** [comment]
> > Without this configuration option the `--nsvc` option is not defined with the pool create command. Thus, this ticket seems still valid from my understanding.
> 
> Looking at a previous daily run https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/8770/artifact/Functional%20on%20EL%208/control/dmg_pool_query_ranks.py/job.log
> 
> ```
> 2023-07-05 05:57:08,068 process          L0604 INFO | Running '/usr/bin/dmg -o /etc/daos/daos_control.yml -d -j pool create TestPool_1 --group=jenkins --size=4GB --user=jenkins'
> 2023-07-05 05:57:08,094 process          L0416 DEBUG| [stderr] DEBUG 05:57:08.093959 main.go:209: debug output enabled
> 2023-07-05 05:57:08,095 process          L0416 DEBUG| [stderr] DEBUG 05:57:08.094366 main.go:235: control config loaded from /etc/daos/daos_control.yml
> 2023-07-05 05:57:08,108 process          L0416 DEBUG| [stderr] DEBUG 05:57:08.108219 pool.go:275: Create DAOS pool request: *mgmt.PoolCreateReq uuid:93217253-a339-43ac-b31d-2aa0b3fc1e2e u:jenkins@ g:jenkins@ p:[number:1 strval:"TestPool_1"] ranks: tiers:
> 2023-07-05 05:57:08,109 process          L0416 DEBUG| [stderr] DEBUG 05:57:08.108980 rpc.go:260: request hosts: [wolf-233vm2:10001 wolf-233vm3:10001 wolf-233vm4:10001]
> 2023-07-05 05:57:09,775 process          L0416 DEBUG| [stderr] DEBUG 05:57:09.774966 response.go:168: wolf-233vm2:10001: *mgmt.PoolCreateResp svc_ldr:0 svc_ranks:0-2 tgt_ranks:0-2 tiers:0:1333346304 1:0 
> 2023-07-05 05:57:09,776 process          L0416 DEBUG| [stdout] {
> 2023-07-05 05:57:09,776 process          L0416 DEBUG| [stdout]   "response": {
> 2023-07-05 05:57:09,777 process          L0416 DEBUG| [stdout]     "uuid": "93217253-a339-43ac-b31d-2aa0b3fc1e2e",
> 2023-07-05 05:57:09,777 process          L0416 DEBUG| [stdout]     "svc_ldr": 0,
> 2023-07-05 05:57:09,777 process          L0416 DEBUG| [stdout]     "svc_reps": [
> 2023-07-05 05:57:09,777 process          L0416 DEBUG| [stdout]       0,
> 2023-07-05 05:57:09,777 process          L0416 DEBUG| [stdout]       1,
> 2023-07-05 05:57:09,778 process          L0416 DEBUG| [stdout]       2
> 2023-07-05 05:57:09,778 process          L0416 DEBUG| [stdout]     ],
> 2023-07-05 05:57:09,778 process          L0416 DEBUG| [stdout]     "tgt_ranks": [
> 2023-07-05 05:57:09,778 process          L0416 DEBUG| [stdout]       0,
> 2023-07-05 05:57:09,778 process          L0416 DEBUG| [stdout]       1,
> 2023-07-05 05:57:09,779 process          L0416 DEBUG| [stdout]       2
> 2023-07-05 05:57:09,779 process          L0416 DEBUG| [stdout]     ],
> 2023-07-05 05:57:09,779 process          L0416 DEBUG| [stdout]     "tier_bytes": [
> 2023-07-05 05:57:09,779 process          L0416 DEBUG| [stdout]       1333346304,
> 2023-07-05 05:57:09,779 process          L0416 DEBUG| [stdout]       0
> 2023-07-05 05:57:09,780 process          L0416 DEBUG| [stdout]     ]
> 2023-07-05 05:57:09,780 process          L0416 DEBUG| [stdout]   },
> 2023-07-05 05:57:09,780 process          L0416 DEBUG| [stdout]   "error": null,
> 2023-07-05 05:57:09,780 process          L0416 DEBUG| [stdout]   "status": 0
> 2023-07-05 05:57:09,780 process          L0416 DEBUG| [stdout] }
> ```
> 
> Isn't this the same as using `--nsvc 3`?
> 
> ```
> "svc_reps": [
>   0,
>   1,
>   2
> ],
> ```

Indeed, you are right again: I have to admit that I am not familiar with this part of the code.
Thanks for all your remarks which allowed me to not push useless modifications.
I am going to update the ticket according to your last remarks.
Thanks again.

**Pull request closed without merging**
