### PR TITLE
DAOS-8737 test: Skip the online reintegration test.

### PR DESCRIPTION
**Pull request by rpadma2**
Test-tag-hw-medium: pr,hw,medium,ib2 online_reintegration

Signed-off-by: rpadma2 <ravindran.padmanabhan@intel.com>

### CODE REVIEW

**Review by dinghwah — APPROVED** [review]
LGTM

**Comment by kprantis** [comment]
SInce this enables extra tests, are the failures therein just other tests that are already known to be failing?

**Comment by rpadma2** [comment]
> SInce this enables extra tests, are the failures therein just other tests that are already known to be failing?

The failures are not related to this PR. I will take a look at it and see whether there is already any tickets associated with the failure.

**Review by shimizukko — APPROVED** [review]

**Comment by rpadma2** [comment]
Created new tickets for the following failures:
DaosCoreTest/test_daos_ec_obj : DAOS-9236 (https://daosio.atlassian.net/browse/DAOS-9236 )
erasurecode/mdtest_smoke.py : DAOS-9235 (https://daosio.atlassian.net/browse/DAOS-9235 )

**Comment by rpadma2** [comment]
@daos-stack/daos-gatekeeper : This PR is ready for merge.

**Pull request merged**
