### PR TITLE
DAOS-623 build: Retry jira-query once if it gets rate-lmited.

### PR DESCRIPTION
**Pull request by ashleypittman**
Required-githooks: true

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]

**Review by JohnMalmberg — APPROVED** [review]

**Comment by brianjmurrell** [comment]
Could it be that the rate-limit is being hit because it's pretty low for unauthenticated access?  Could the GITHUB_TOKEN perhaps be used to (hopefully) get a higher limit on the rate?

**Comment by ashleypittman** [comment]
> Could it be that the rate-limit is being hit because it's pretty low for unauthenticated access? Could the `GITHUB_TOKEN` perhaps be used to (hopefully) get a higher limit on the rate?

It's JIRA that's rate-limiting us, but yes in future it would be great to setup authentication tokens so that we can also have GitHub updates tickets as they're being worked.

**Comment by brianjmurrell** [comment]
> It's JIRA that's rate-limiting us, but yes in future it would be great to setup authentication tokens so that we can also have GitHub updates tickets as they're being worked.

I must be misunderstanding something.  The code change is adding a retry to the fetch from `gh_url` which is:

```python
         gh_url = f'https://api.github.com/repos/{github_repo}/pulls/{pr_number}'
```

That's GitHub, not Jira.

**Comment by ashleypittman** [comment]
Oh yeah.  Room for improvement sure but this is still a step forward.

**Comment by brianjmurrell** [comment]
> Oh yeah. Room for improvement sure but this is still a step forward.

But to be clear, it is indeed GH queries that are being rate limited, and not Jira, right?  And so a potential (future, perhaps, but I don't think it's very complicated at all) remedy might be to use the GHA `GITHUB_TOKEN` to use an authenticated access, yes?

**Comment by ashleypittman** [comment]
> 



> > Oh yeah. Room for improvement sure but this is still a step forward.
> 
> But to be clear, it is indeed GH queries that are being rate limited, and not Jira, right? And so a potential (future, perhaps, but I don't think it's very complicated at all) remedy might be to use the GHA `GITHUB_TOKEN` to use an authenticated access, yes?

You're correct, it's a github URL.

**Pull request merged**
