### PR TITLE
CART-89 grp: Squash DER_GRPVER error prints in common handlers

### PR DESCRIPTION
**Pull request by frostedcmos**
- Remove -DER_GRPVER errors from being printed from common rpc
and corpc handlers

Signed-off-by: Alexnader Oganezov <alexander.a.oganezov@intel.com>

### CODE REVIEW

**Review by jgmoore-or — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
One of the cart test failed

**Comment by ashleypittman** [comment]
No complaints from me, how did you find which ones to silence and how do we check you haven't missed any?

Just so everyones aware, we silence warnings with DER_SHUTDOWN and DER_NOTLEADER from log messages during shutdown, so these don't create NLT failures/warnings.
https://github.com/daos-stack/daos/blob/master/src/tests/ftest/cart/util/cart_logtest.py#L436-L441

**Review by jolivier23 — APPROVED** [review]
Would it make sense to move the check internal to RPC_ERROR and use D_CDEBUG to either log an error or INFO/DEBUG ?

**Comment by ashleypittman** [comment]
> Would it make sense to move the check internal to RPC_ERROR and use D_CDEBUG to either log an error or INFO/DEBUG ?

I was wondering this.

**Comment by sylviachanoiyee** [comment]
One of the cart test failed.

**Comment by frostedcmos** [comment]
> Would it make sense to move the check internal to RPC_ERROR and use D_CDEBUG to either log an error or INFO/DEBUG ?

it would require changing every place where RPC_ERROR macro is used to pass rc into it, not sure if its worth it

**Comment by frostedcmos** [comment]
> No complaints from me, how did you find which ones to silence and how do we check you haven't missed any?
> 
> Just so everyones aware, we silence warnings with DER_SHUTDOWN and DER_NOTLEADER from log messages during shutdown, so these don't create NLT failures/warnings.
> https://github.com/daos-stack/daos/blob/master/src/tests/ftest/cart/util/cart_logtest.py#L436-L441

We did initial squashing of errors from obvious places, but those had to find from customer reports of some errors still being printed. From there, code analyzed all common rpc RC processing functions. it is possible we might have missed something still, but if so, we will squash them in subsequent patch

**Pull request closed without merging**
