### PR TITLE
DAOS-5621 test: add all test servers in dmg.yaml hostlist

### PR DESCRIPTION
**Pull request by tanabarr**
List all test servers under dmg.yaml hostlist parameter to enable dmg
non-MS commands to run across all hosts.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Review by ravalsam — COMMENTED** [review]
PR looks ok to me but do you see the tagged daos_core_test_nvme test result in Ci JOB?

**Comment by tanabarr** [comment]
> PR looks ok to me but do you see the tagged daos_core_test_nvme test result in Ci JOB? The medium test is finished but that daos_core_test_nvme test did not ran?

I think I had a mistake in the pragma, have tried to fix and repushed

**Review by ravalsam — APPROVED** [review]
LGTM.
Tried running the test locally and confirm that dmg file has all the servers listed in it.
Skipped the test with another defect DAOS-5134.

**Comment by tanabarr** [comment]
intermittent CI failures:
- https://jira.hpdd.intel.com/browse/DAOS-7014

**Review by ravalsam — APPROVED** [review]

**Review by ashleypittman — APPROVED** [review]

**Pull request merged**
