### PR TITLE
DAOS-12344 control: nvme and scm cmds run without conf file

### PR DESCRIPTION
**Pull request by tanabarr**
daos_server nvme|scm prepare|reset commands should not require a
server config file to exist in order to run.

Required-githooks: true

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by tanabarr** [comment]
Existing CI failure: https://daosio.atlassian.net/browse/DAOS-12326

**Review by daltonbohning — COMMENTED** [review]
Should the `--ignore-config` option try to load the config at all?
```
$ daos_server nvme reset --ignore-config
DAOS Server config loaded from /home/dbohning/daos/install/etc/daos_server.yml
Reset locally-attached NVMe storage...
```

If the config can't be loaded (for any reason), the command fails. E.g.:
```
$ chmod -r /home/dbohning/daos/install/etc/daos_server.yml
$ daos_server nvme reset --ignore-config
ERROR: failed to load config from /home/dbohning/daos/install/etc/daos_server.yml: reading file: open /home/dbohning/daos/install/etc/daos_server.yml: permission denied
```

**Comment by tanabarr** [comment]
> Should the `--ignore-config` option try to load the config at all?
> 
> ```
> $ daos_server nvme reset --ignore-config
> DAOS Server config loaded from /home/dbohning/daos/install/etc/daos_server.yml
> Reset locally-attached NVMe storage...
> ```
> 
> If the config can't be loaded (for any reason), the command fails. E.g.:
> 
> ```
> $ chmod -r /home/dbohning/daos/install/etc/daos_server.yml
> $ daos_server nvme reset --ignore-config
> ERROR: failed to load config from /home/dbohning/daos/install/etc/daos_server.yml: reading file: open /home/dbohning/daos/install/etc/daos_server.yml: permission denied
> ```

The `--ignore-config` does what it says, i.e. it ignores the configured values. The changes in this PR enable the command to be run even if no file exists which is the correct behaviour but I don't think the `--ignore-config` needs to mask config read errors.

**Review by daltonbohning — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]
LGTM

**Review by mjmac — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]
LGTM.

**Pull request merged**
