### PR TITLE
DAOS-7671 dfuse: change attrs names memory location

### PR DESCRIPTION
**Pull request by bfaccini**
Alloc/free attributes names to prevent names/strings to be
stored in the text/code region and thus avoid EFAULT errors during
memory registration for RDMA xfer to the server

### CODE REVIEW

**Comment by ashleypittman** [comment]
I had tried similar to this by using D_ALLOC(), memcpy() to send from non-bss memory and it hadn't worked for me so I'm not sure why it would be different by using strdup().

**Comment by bfaccini** [comment]
> I had tried similar to this by using D_ALLOC(), memcpy() to send from non-bss memory and it hadn't worked for me so I'm not sure why it would be different by using strdup().

I am unable to reproduce with my patch. Let's expose it to the CI and see how it goes ....

**Comment by ashleypittman** [comment]
> > I had tried similar to this by using D_ALLOC(), memcpy() to send from non-bss memory and it hadn't worked for me so I'm not sure why it would be different by using strdup().
> 
> I am unable to reproduce with my patch. Let's expose it to the CI and see how it goes ....

CI won't run under verbs so I don't think that'll tell us anything useful.

**Review by ashleypittman — APPROVED** [review]
I was no longer able to reproduce the issue on the test cluster I had before this patch so I can't verify the fix.

**Review by johannlombardi — APPROVED** [review]

**Pull request merged**
