### PR TITLE
DAOS-16037 pool: Fix upgrade for svc_ops

### PR DESCRIPTION
**Pull request by kccain**
This is a cherry-pick of master PR 14753.
 
 - pool_upgrade_props should take care of ds_pool_prop_svc_ops_{num,max} too.

  - pool_upgrade_props modifies ds_pool_prop_svc_ops_{enabled,age,max}, which are cached by pool_svc. It must also update the cached values too.

  - read_db_for_stepping_up should only access ds_pool_prop_svc_ops_{enabled,age,max} when the pool global version is high enough. If one of the properties is expected but absent, it should be an error; recovering the value to 0 may not be desirable.

Features: pool

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by kccain** [comment]
> Test stage Functional Hardware Large completed with status FAILURE. https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-14759/5/execution/node/1508/log

This one I don't quite know how to resolve. I've been discussing a bit with @JohnMalmberg and @phender 
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14759/5/testReport/junit/FTEST_launch/launch-functional_hardware_large/Test_Hardware___Functional_Hardware_Large___00___launch_py/

"Unknown exception raised during launch.py execution: 1"
and
"No VMD devices found on wolf-[219-226]"

So a plan here is let build 5 run to completion on other HW clusters
Then, I will start a build 6 that will perform Functional HW Large only - and will avoid this cluster which is probably not ready to process builds at this time.

**Comment by kccain** [comment]
@daos-stack/daos-gatekeeper FYI, when we get to landing for this, do note that the unit test, functional (VM) testing and all functional HW testing *except* HW large is going to come from build [5](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14759/5/pipeline-graph/), whereas functional HW large testing results will come from the final Jenkins build of this PR (anticipated to be build 6), and this is due to working around this ticket https://daosio.atlassian.net/browse/DAOS-16147

**Review by liw — APPROVED** [review]

**Review by wangshilong — APPROVED** [review]

**Comment by liw** [comment]
Build 5 completed with a known issue related to the absence of pci.h. I've triggered build 6 for only CI_large_TEST according to @kccain's instructions.

**Comment by liw** [comment]
Ready to land after the master #14753.

**Pull request merged**
