### PR TITLE
DAOS-4183 engine: build and run CI with ULTs stacks mmap()'ed

### PR DESCRIPTION
**Pull request by bfaccini**
make ULTs stacks mmap()'ed feature the default to expose the
changes for DAOS-4183 to the build and the CI tests.

Change-Id: Ib163351ea3d26cdefcea5cffc6324fd8a0375422
Signed-off-by: Bruno Faccini <bruno.faccini@intel.com>

### CODE REVIEW

**Review by johannlombardi — DISMISSED** [review]

**Comment by johannlombardi** [comment]
Test results look good to me :) Let's review and land the other PR then.

**Comment by bfaccini** [comment]
> Test results look good to me :) Let's review and land the other PR then.

Well looks like I will need to merge with recent master to fix the 2 CI failures, but did you mean on a performance point of view ?? Also the other [PR-5111](https://github.com/daos-stack/daos/pull/5111) still needs to be updated with defensive code against max number of mmap()'ed regions per process (vm.max_map_count) ....

**Comment by bfaccini** [comment]
> Test results look good to me :) Let's review and land the other PR then.

Well looks like I will need to merge with recent master to fix the 2 CI failures, but did you mean on a performance point of view ?? Also the other [PR-5111](https://github.com/daos-stack/daos/pull/5111) still needs to be modified in order to become as much as possible lockless (ie, with one stack free list per-Stream) and to get some defensive code to address the case where the max number of mmap()'ed regions per-process (vm.max_map_count) has been reached !!...

**Comment by bfaccini** [comment]
Hmmm, there are only 2 tests failures during `Hardware Medium` stage ... 1) the timeout during `23-./daos_test/suite.py:DaosCoreTest.test_daos_rebuild_ec`looks definitely like the issue reported in [DAOS-9860](https://daosio.atlassian.net/browse/DAOS-9860) and still under investigations , but 2) is a failure during `1-./osa/offline_drain.py:OSAOfflineDrain.test_osa_offline_drain` due to several servers/engines not found in expected state, and where the root cause appears to be OOMs, which needs to be fully investigated to ensure it is not related to my changes ...

**Comment by bfaccini** [comment]
Looks like the only CI test failure is a timeout during `daos_test/suite.py:DaosCoreTest.test_daos_rebuild_ec` which is unrelated to my changes and better looks as the problem described in [DAOS-9861](https://daosio.atlassian.net/browse/DAOS-9861)/[DAOS-9860](https://daosio.atlassian.net/browse/DAOS-9860) which is still under investigations ...

**Comment by bfaccini** [comment]
Again, looks like the only CI test failure is a timeout during daos_test/suite.py:DaosCoreTest.test_daos_rebuild_ec that seems to be unrelated to my changes and better looks as the problem described in [DAOS-9861](https://daosio.atlassian.net/browse/DAOS-9861)/[DAOS-9860](https://daosio.atlassian.net/browse/DAOS-9860) for which associated PRs has landed very recently and will be integrated with the merge I have just done, so will see how things go with last push/commit CI tests ...

**Review by jolivier23 — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]
any reason not to merge this into the other branch?

**Comment by bfaccini** [comment]
> any reason not to merge this into the other branch?

This may be too early to make it the default behaviour ...

**Review by jolivier23 — COMMENTED** [review]
I think you should just land this to the other one.

**Comment by bfaccini** [comment]
Abandoned because too old and with latest changes from DAOS-4183/PR-5111 that has already landed onto master, there is a much simpler way to enable ULTs stacks mmap()'ed feature now !!

**Pull request closed without merging**
