### PR TITLE
DAOS-5517 test: Removed -E from io_aggregation.yaml

### PR DESCRIPTION
**Pull request by ajskaar**
Description: Fixed issued with io aggregation test by removing 
the '-E' option from the ior command. See DAOS-5517 for details.

Signed-off-by: Anders Skaar <ajskaar@gmail.com>
Test-tag-hw-small: pr,hw,small ioaggregation

### CODE REVIEW

**Review by mchaarawi — CHANGES_REQUESTED** [review]
you should follow the commit message format in:
https://wiki.hpdd.intel.com/display/DC/Commit+Comments

**Review by saurabhtandan — CHANGES_REQUESTED** [review]
You also need to add following line in your last commit before push in order to run this test as part of your PR. As this test don't have 'pr' tag you need to do this or else this test won't be run and we can't verify if the change actually worked in CI.
Test-tag-hw-small: pr,hw,small ioaggregation

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Review by mchaarawi — APPROVED** [review]

**Comment by jolivier23** [comment]
this needs a merge with latest master.   Too many failures

**Pull request merged**
