### PR TITLE
DAOS-5893,DAOS-5894 Test: Adding EC test for offline, online and disabled rebuild.

### PR DESCRIPTION
**Pull request by ravalsam**
ec_offline_rebuild: Verify that supported EC object type works for offline
		    rebuild, IOR data is intact after killing the servers.

ec_online_rebuild: Verify supported EC object type works for online rebuild,
		   Kill server while IOR write phase in progress, IOR should
		   continue without any error, Read and verify IOR data.

ec_disabled_rebuild: Verify supported EC object type works when rebuild is
                     disabled, After creating the pool disabled rebuild for
		     pool, Write IOR data and kill server. Rebuild should not
		     trigger because it's disabled. Read and verify IOR data.

Test-tag-hw-large: ec_offline_rebuild,ec_online_rebuild,ec_disabled_rebuild

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Review by ravalsam — COMMENTED** [review]
Test-tag-hw-large: pr,hw,large ec_offline_rebuild ec_online_rebuild ec_disabled_rebuild
Skip-func-test-leap15: true

**Comment by ravalsam** [comment]
Offline rebuild:
    - First test failed because of DAOS-6153 
    - Second test failed because rebuild is getting stuck (Most defects are closed so I need to rebase and try again)

Online rebuild:
    - Observed DAOS-5729
    - Test failed seems because of DAOS-6153
    - Online rebuild test need to fix as right now it's writing multiple IOR container and removing the server for first IOR write, instead we need to write only single IOR command.

Disabled Rebuild:
     - Test1 and Test3: Data corruption DAOS-6086
     - Test2: File size mismatch (Need to rebase to get latest code)

**Review by wangdi1 — DISMISSED** [review]

**Review by liuxuezhao — DISMISSED** [review]
good to add those tests. not sure why those EC cases failed...

**Comment by ravalsam** [comment]
> good to add those tests. not sure why those EC cases failed...

I mention some of the defect on comment above. Most of it failed because of DAOS-6153,DAOS-5729,  DAOS-6086. But I need to rebase and try in Ci before we merge as some of the fixes was landed after this PR created,

**Review by wangdi1 — APPROVED** [review]

**Review by jgmoore-or — APPROVED** [review]

**Pull request merged**
