### PR TITLE
DAOS-10828 mercury: Update to mercury 2.2.0rc6

### PR DESCRIPTION
**Pull request by soumagne**
- Switch UCX to use active messages and fix UCX issues with hostname parsing / address key not set
- Enable CXI and OPX as supported plugins
- Fix ctrl-c issue that was happening in DAOS when interrupting a bulk transfer that required usage of overflow mechanism  
- Update Cart to use new CXI init string
- Remove dependency on mercury_util and use HG_Set_log routines
- Remove rpath fix as mercury now automatically adds rpath info

- Additional fixes and new features: Full notes: https://github.com/mercury-hpc/mercury/blob/v2.2.0rc6/Documentation/CHANGES.md

PR-repos: mercury@PR-79

### CODE REVIEW

**Review by frostedcmos — APPROVED** [review]

**Review by brianjmurrell — DISMISSED** [review]
I think you also want to update https://github.com/daos-stack/daos/blob/fbcb5513ac374880fb36ae48cca33cc73e141e07/debian/control#L13, yes?

**Review by jgmoore-or — DISMISSED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by soumagne** [comment]
@brianjmurrell I addressed your previous comment. I'm honestly not really sure if we really need those but I did update it, thanks for letting me know about it.

**Comment by soumagne** [comment]
there is already a ticket filed in the list for the test that fails:
https://daosio.atlassian.net/browse/DAOS-10923

**Review by frostedcmos — APPROVED** [review]

**Comment by soumagne** [comment]
To merge this, https://github.com/daos-stack/mercury/pull/79 must also be merged

**Comment by ashleypittman** [comment]
@soumagne to have this ticket marked as Priority you'd need to set "Required for Version" as "2.4 Community Release" in the ticket.

**Comment by soumagne** [comment]
@ashleypittman ah thanks, any idea also on how I fix the error "unknown components" in the ticket check?

**Review by brianjmurrell — APPROVED** [review]
If you found a need to push anything more to this PR, even if it's just a merge, you could freshen up the dates in the debian and rpm changelogs.

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
