### PR TITLE
DAOS-6325 test: Adding replication to ior_small.py

### PR DESCRIPTION
**Pull request by saurabhtandan**
Enabe ior_small.py to run with replication. As of now it was
only running with SX oclass.

Quick-Functional: true
Test-tag: iorsmall

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]

**Review by ravalsam — APPROVED** [review]

**Review by rpadma2 — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
Re-started gha workflow

**Comment by mchaarawi** [comment]
this PR seems to have broken IOR tests with VOL..
note that those tests were disabled. when enabling them:
```
15:26:02 INFO | Command '/usr/bin/daos container create D983C3E4-CA8A-4933-A1E8-A5D3E11F92AA --oclass=SX --properties=cksum:crc16,cksum_size:16384,srv_cksum:on --sys-name=daos_server --type=POSIX' finished with 0 after 0.3130936622619629s
15:26:02 INFO |   Container created with uuid CA5A2AE7-868E-42EA-9D59-47BC1E4372CB
15:26:02 DEBUG| Updated param dfs_pool => D983C3E4-CA8A-4933-A1E8-A5D3E11F92AA
15:26:02 DEBUG| Updated param dfs_group => daos_server
15:26:02 DEBUG| Updated param dfs_cont => CA5A2AE7-868E-42EA-9D59-47BC1E4372CB
15:26:02 ERROR| 
15:26:02 ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:871
15:26:02 ERROR| Traceback (most recent call last):
15:26:02 ERROR|   File "/usr/lib/daos/TESTING/ftest/ior/ior_hdf5.py", line 51, in test_ior_hdf5_vol
15:26:02 ERROR|     self.run_ior_with_pool(plugin_path=hdf5_plugin_path)
15:26:02 ERROR|   File "/usr/lib/daos/TESTING/ftest/util/ior_test_base.py", line 136, in run_ior_with_pool
15:26:02 ERROR|     mount_dir = os.path.join(mount_dir, sub_dir)
15:26:02 ERROR|   File "/usr/lib64/python3.6/posixpath.py", line 80, in join
15:26:02 ERROR|     a = os.fspath(a)
15:26:02 ERROR| TypeError: expected str, bytes or os.PathLike object, not NoneType
```

https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-6464/4/tests

**Comment by saurabhtandan** [comment]
@mchaarawi , Let me see the code what is breaking that test and if we can avoid a revert and get a solution to it rather.

**Comment by mchaarawi** [comment]
but why are we testing ior_small with replication and not using the RF property instead?

**Pull request merged**
