### PR TITLE
DAOS-6053 enhance stability of Java build in DAOS

### PR DESCRIPTION
**Pull request by zjf2012**
When maven builds, it downloads all dependencies from central repo by default. However, central repo is not very stable sometimes. User can customize maven to download from mirror of central repo by putting settings.xml under <HOME>/.m2. The settings.xml was put under /home/daos/.m2 folder whilst it should be put under /root/.m2. This PR is to correct this mistake.

Signed-off-by: jiafu zhang <jiafu.zhang@intel.com>

### CODE REVIEW

**Comment by zjf2012** [comment]
@jolivier23 @mjmac please help review this ticket. It's related to https://github.com/daos-stack/daos/pull/3888. With this PR, maven artifacts are downloaded from google instead of central maven repo which is unstable and slow. thanks.

**Review by jolivier23 — APPROVED** [review]
Can you add a bit of description to the PR text

https://wiki.hpdd.intel.com/display/DC/Commit+Comments

**Comment by zjf2012** [comment]
> Can you add a bit of description to the PR text
> 
> https://wiki.hpdd.intel.com/display/DC/Commit+Comments

Just put some text. please help review again.

**Comment by mjmac** [comment]
Hi @zjf2012, thanks for taking a look at this. Would you please explain how this PR fixes the problem? If I understand the dockerfiles correctly, the build is running as the daos user in the container, so it seems as if moving the settings to /root would make them unavailable to the daos user.

**Comment by jolivier23** [comment]
> Hi @zjf2012, thanks for taking a look at this. Would you please explain how this PR fixes the problem? If I understand the dockerfiles correctly, the build is running as the daos user in the container, so it seems as if moving the settings to /root would make them unavailable to the daos user.

@mjmac the review comment addresses it

**Review by jolivier23 — APPROVED** [review]

**Comment by mjmac** [comment]
> 
> 
> > Hi @zjf2012, thanks for taking a look at this. Would you please explain how this PR fixes the problem? If I understand the dockerfiles correctly, the build is running as the daos user in the container, so it seems as if moving the settings to /root would make them unavailable to the daos user.
> 
> @mjmac the commit comment he edited addresses it

Hmm, I think I understand now. The settings.xml is for the mvn command run as root in travis.yml?

**Comment by zjf2012** [comment]
> > > Hi @zjf2012, thanks for taking a look at this. Would you please explain how this PR fixes the problem? If I understand the dockerfiles correctly, the build is running as the daos user in the container, so it seems as if moving the settings to /root would make them unavailable to the daos user.
> > 
> > 
> > @mjmac the commit comment he edited addresses it
> 
> Hmm, I think I understand now. The settings.xml is for the mvn command run as root in travis.yml?

Yes, you are correct.

**Review by mjmac — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
