### PR TITLE
DAOS-9355 doc: set up doc-watchers in CODEOWNERS (#8176)

### PR DESCRIPTION
**Pull request by Michael-Hennecke**
set up doc-watchers in CODEOWNERS
(also set up build-and-release-watchers and
client-api-watchers for consistency with 2.2)

Skip-build: true
Skip-test: true
Signed-off-by: Michael Hennecke <michael.hennecke@intel.com>

### CODE REVIEW

**Comment by Michael-Hennecke** [comment]
it seems that most of the existing v2.0 CODEOWNERS file's contents is in error and should be removed? should we just use the exact same file as on master?

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
As you suggest, I would agree to just use the same content from master.

**Review by mchaarawi — APPROVED** [review]

**Review by mchaarawi — CHANGES_REQUESTED** [review]
when i open that file here it says there are errors with some non existing groups like go-owners

**Comment by brianjmurrell** [comment]
> when i open that file here it says there are errors with some non existing groups like go-owners

Indeed.  The content should just be copied from master to fix up all of the issues with it with what we have recently discovered and fixed on master.

**Comment by Michael-Hennecke** [comment]
just pushed master CODEOWNERS, this fixes the issues with the old rel/2.0 file.

**Review by mchaarawi — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
