### PR TITLE
DAOS-9335 doc: online docfix

### PR DESCRIPTION
**Pull request by Michael-Hennecke**
fix hyperlink

Doc-only: true
Signed-off-by: Michael Hennecke <michael.hennecke@intel.com>

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by kccain** [comment]
It looks like there is another instance of the broken link in the section immediately preceding the one that is fixed here
i.e., in "DAOS Servers running CentOS Linux 8, RHEL 8.3, or RHEL 8.5". I assume that should also be updated with the new link target?

**Review by johannlombardi — APPROVED** [review]

**Comment by johannlombardi** [comment]
Could you please update the summary and provide a DAOS jira ticket in the title?

**Comment by Michael-Hennecke** [comment]
this was a test of an online document edit - not sure how to automatically populate those with a Jira ID, searching...

**Review by kccain — APPROVED** [review]

**Comment by Michael-Hennecke** [comment]
this was a test to edit doc pages directly from the website's "Edit" link, so there was no JIRA ticket number in the commit. added this manually to the PR - please land.

**Pull request merged**
