### PR TITLE
DAOS-7337 test: Adding EC test cases verification with all DAOS server restart. (#6891)

### PR DESCRIPTION
**Pull request by ravalsam**
- Adding test which will write EC date with different object types,
  Wait for aggregation to trigger and restart all the servers.
  Read and verify the data after start.
- Adding test which will write the EC data with different object types,
  Restart all the servers, Verify aggregation is getting trigger after start.
  Read and verify the data after aggregation.
- Disabled the aggregation, Write EC data with different object types,
  Enable the time mode aggregation and wait for ~20 seconds.
  Restart all the servers when aggregation is also happening.
  read and verify the data after aggregation.

Quick-build: true
Test-tag: ec nvme

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
Test result looks good there are some failure which are not related to this patch.

- daos_test/nvme_recovery.py is new test regression and nothing to do with this PR
- erasurecode/online_rebuild.py failing because of existing defect DAOS-7378
- server/metadata.py is failed because of existing issue DAOS-9078
- erasurecode/restart.py single test failure is test side issue and new defect open DAOS-9522

**Review by rpadma2 — APPROVED** [review]

**Review by dinghwah — APPROVED** [review]
LGTM.

**Comment by sylviachanoiyee** [comment]
@ravalsam , could you file a ticket for daos_test/nvme_recovery.py failure?
Make sure to mention this was on branch 2.0.
Let me know when you have done so with logs attached so we can get this pr landed. Thanks!

**Comment by ravalsam** [comment]
> @ravalsam , could you file a ticket for daos_test/nvme_recovery.py failure? Make sure to mention this was on branch 2.0. Let me know when you have done so with logs attached so we can get this pr landed. Thanks!

For NVMe recovery test, defect was open DAOS-9525 and PR has been created https://github.com/daos-stack/daos/pull/7819.

**Pull request merged**
