### PR TITLE
DAOS-3407 control: dmg call nodeset to parse hostlists

### PR DESCRIPTION
**Pull request by tanabarr**
Simple implementation calling clustershell's nodeset binary if it
exists to parse supplied hostlist.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Comment by tanabarr** [comment]
first pass
```
root@boro-45:/home/tanabarr/projects/daos_m$ dmg -l boro-4[5-9]:10001 -i storage scan --summary
ERROR: failed to connect to boro-46:10001 (socket connection is not active (TRANSIENT_FAILURE))
ERROR: failed to connect to boro-47:10001 (socket connection is not active (TRANSIENT_FAILURE))
ERROR: failed to connect to boro-48:10001 (socket connection is not active (TRANSIENT_FAILURE))
ERROR: failed to connect to boro-49:10001
 (socket connection is not active (TRANSIENT_FAILURE))
Inactive: boro-[46-49]:10001

Active: boro-45:10001

boro-45:10001
        Summary:
                SCM: 0.00B total capacity over 0 modules (unprepared)
                NVMe: 375.00GB total capacity over 1 controller
```

**Comment by tanabarr** [comment]
experimenting with table -based display
```
tanabarr@boro-45:~/projects/daos_m$ dmg -i -l boro-4[0-9]:10001 storage scan --summary
boro-[41,43,46-49]:10001 Inactive
boro-[40,42,44-45]:10001 Active
HOST            SCM-CAP NS-COUNT        NVMe-CAP        SSD-COUNT
boro-40:10001   0.00B   0               0.00B           0
boro-42:10001   0.00B   0               NVMe Error: NVMe storage scan: SPDK env init, has setup been run?: spdk_env_opts_init: 1
boro-44:10001   0.00B   0               375.00GB                1
boro-45:10001   0.00B   0               375.00GB                1
```

**Comment by mjmac** [comment]
I think this PR can be closed as it was replaced by #1464, right?

**Comment by tanabarr** [comment]
superseded by https://github.com/daos-stack/daos/pull/1464

**Pull request closed without merging**
