### PR TITLE
DAOS-623 cq: update actions/upload-artifact version

### PR DESCRIPTION
**Pull request by daltonbohning**
Skip-test: true
Skip-tests: true
Skip-unit-tests: true
Skip-fault-injection-test: true

Update actions/upload-artifact used in ossf-scorecard due to deprecation notice.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by daltonbohning** [comment]
Example warning being fixed: https://github.com/daos-stack/daos/actions/runs/8802445176

**Review by ashleypittman — COMMENTED** [review]
Does dependabot not submit PRs for us to do this?  How do we know this is an issue?

**Review by ashleypittman — APPROVED** [review]

**Comment by brianjmurrell** [comment]
> Does dependabot not submit PRs for us to do this? How do we know this is an issue?

Interesting question.  I feel fairly sure I have seen dependabot PRs in our repo.  But it seems that we don't have dependabot enabled in the daos repo and enabling it requires creating `.github/dependabot.yml` to provide options for how we want it to function.

Maybe there is some kind of non-optional dependabot functionality that only creates PRs for CVEs.

**Comment by daltonbohning** [comment]
Maybe this is on the right track?
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

If we start getting more strict security requirements, and as we add more GHA, automating will be nice

**Comment by ashleypittman** [comment]
https://github.com/daos-stack/daos/pull/14197 is from dependabot.

**Comment by brianjmurrell** [comment]
> If we start getting more strict security requirements, and as we add more GHA, automating will be nice

Yeah, I was reviewing that also.  Not really sure that there is much difference between us specifying (say) `v4` (and automatically getting all of the updates) and having something more-or-less automatedly updating githashes through `v4.0.0` and then `v4.1.0` and `v4.1.1`, etc.

**Comment by brianjmurrell** [comment]
> #14197 is from dependabot.

Ah, you found one.  I went looking but couldn't find one by trying to filter on assignee.  I knew I saw one at some point.

**Review by brianjmurrell — APPROVED** [review]

**Comment by ashleypittman** [comment]
> > If we start getting more strict security requirements, and as we add more GHA, automating will be nice
> 
> Yeah, I was reviewing that also. Not really sure that there is much difference between us specifying (say) `v4` (and automatically getting all of the updates) and having something more-or-less automatedly updating githashes through `v4.0.0` and then `v4.1.0` and `v4.1.1`, etc.

tags are mutable where as commit hashes are not.  It's a pain to have to do this though, even if we have dependabot pushing PRs for us every time there's a new upstream release.

**Comment by daltonbohning** [comment]
> tags are mutable where as commit hashes are not. It's a pain to have to do this though, even if we have dependabot pushing PRs for us every time there's a new upstream release.

Yeah, this goes back to what @brianjmurrell said (on another PR) about SHA-pinning not being feasible to maintain.
Being able to just put, e.g., `v4` means we'll get minor and patch updates for free, which should be backwards compatible anyway / low risk of breaking

**Comment by daltonbohning** [comment]
Skipped Jenkins testing since the change is contained to GHA

**Comment by brianjmurrell** [comment]
> tags are mutable where as commit hashes are not.

Yes, this occurred to me as I was writing my comment but I didn't want to delve into it.  It's indeed a true story.  How much of a problem is it in the real world though.

> It's a pain to have to do this though, even if we have dependabot pushing PRs for us every time there's a new upstream release.

Indeed.  The churn!  Aye Karumba.

**Pull request merged**
