### PR TITLE
Jbrosenz daos 1673

### PR DESCRIPTION
**Pull request by jbrosenz**
The functions get called like this:
netDevsList, err := DetectNetworkDevices()
// handle errors
netAdapterAffinity, err := DetectNUMANodeForDevices(netDevsList)
// handle errors
// Do something with the netAdapterAffinity string

Calling this from server main.go gives sample output from my machine:
2019/05/20 15:25:50 main.go:78: debug: netDevsList: lo,eth0,eth1,ib0
2019/05/20 15:25:50 main.go:84: debug: netAdapterAffinity: eth0:0:0,eth1:0:0,ib0:0:0

The output shows that there are 4 network devices, lo, eth0, eth1 and ib0
"lo" isn't part of the topology.  The remaining devices are part of the topology, and are each part of logical and physical NUMA node 0 (of two on the machine).

### CODE REVIEW

**Comment by jbrosenz** [comment]
New call sequence:
	netDevsList, err := DetectNetworkDevices()
        // handle errors
	hwlocStr, err := DetectTopology("/bin/lstopo")
        // handle errors
	netAdapterAffinity, err := DetectNUMANodeForDevices(netDevsList, hwlocStr)
       // Do something with the netAdapterAffinity string

**Comment by jbrosenz** [comment]
> Overall looks like it does what's intended, and I like the tests. I just have concerns about the overall approach. Is there a reason to parse a human-readable string rather than use the hwloc library (which lstopo apparently uses under the covers)? If there's an API available in C, we can access it with CGo. IMO that's better and more reliable than parsing application output.

Kris, I completely agree with you.  I presented both options to Tom before I implemented this.  He wanted me to keep it simple and implement a version that does screen scraping at this time.

**Comment by kjacque** [comment]
> Kris, I completely agree with you. I presented both options to Tom before I implemented this. He wanted me to keep it simple and implement a version that does screen scraping at this time.

Hmm, okay. I wouldn't think using an API would be more complex than scraping data from a string, but I haven't looked into hwloc vs. what lstopo provides.

**Comment by jbrosenz** [comment]
> > Kris, I completely agree with you. I presented both options to Tom before I implemented this. He wanted me to keep it simple and implement a version that does screen scraping at this time.
> 
> Hmm, okay. I wouldn't think using an API would be more complex than scraping data from a string, but I haven't looked into hwloc vs. what lstopo provides.

Using the API is straight forward.  I started by prototyping the network detection with a C program before going with the screen scraping approach.  That said, Johann expressed some concerns offline about the screen scraping approach as well.  I'm continuing the conversation with him and Tom and we'll see what approach they want.

**Comment by jbrosenz** [comment]
> > > Kris, I completely agree with you. I presented both options to Tom before I implemented this. He wanted me to keep it simple and implement a version that does screen scraping at this time.
> > 
> > 
> > Hmm, okay. I wouldn't think using an API would be more complex than scraping data from a string, but I haven't looked into hwloc vs. what lstopo provides.
> 
> Using the API is straight forward. I started by prototyping the network detection with a C program before going with the screen scraping approach. That said, Johann expressed some concerns offline about the screen scraping approach as well. I'm continuing the conversation with him and Tom and we'll see what approach they want.

Johann contacted me offline and said he would like me to implement this through the hwloc library directly.  I'll make a new implementation that does that.

**Pull request closed without merging**
