### PR TITLE
DAOS-11764 build: Enable debuginfo sub-packages

### PR DESCRIPTION
**Pull request by brianjmurrell**
On Leap 15.

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficent testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by JohnMalmberg — APPROVED** [review]

**Comment by ashleypittman** [comment]
I keep getting notifications about this PR that says there are 0 updates, do you know how or why that's happening?

**Comment by brianjmurrell** [comment]
> I keep getting notifications about this PR that says there are 0 updates, do you know how or why that's happening?

@ashleypittman I wonder if it's some side-effect of me adding you as a reviewer and then removing you (and everyone else) when I discovered that it needs more work.  I'm really just looking for your +1 on the two `githooks/pre-commit.d/*` changes.  Those are not going to change so if you can just let me know if you are good with those that'd be great.  Thanks!

**Review by JohnMalmberg — APPROVED** [review]

**Comment by brianjmurrell** [comment]
Could I please get another review on this from @raydennis or @phender?  Thanks in advance.

**Review by raydennis — APPROVED** [review]

**Comment by raydennis** [comment]
Looks good to me.

**Comment by brianjmurrell** [comment]
@daos-stack/daos-gatekeeper _Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set._: Hardware testing was skipped due to this being a change that only affects Leap 15 packages which are not tested on hardware.

**Pull request merged**
