### PR TITLE
DAOS-14799 container: interoperability fix for OIT OID KVS

### PR DESCRIPTION
**Pull request by wangshilong**
1.The OIT OID KVS will be only created if the pool global version is greater than or equal to 2. Otherwise, pool upgrade will fail with EEXIST. (Thanks Li Wei's pointing this out)

2. To walk around the upgrade failure, the upgrade process will skip the creation of OIT OID KVS if it already exists.

3. When destroying a container, if the OIT OID KVS doesn't exist, it will be skipped for destruction.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by liw — APPROVED** [review]
We might want to document somewhere the known issue that containers created by some 2.4 releases (assuming that this patch will also land to release/2.4) in 2.2 pools may not be destroyed completely if the servers are downgraded to 2.2.

**Comment by wangshilong** [comment]
> We might want to document somewhere the known issue that containers created by some 2.4 releases (assuming that this patch will also land to release/2.4) in 2.2 pools may not be destroyed completely if the servers are downgraded to 2.2.

I agreed, i have no idea where we should document for this? i suppose it should be documented in release 2.4 notes somewhere. maybe @ipoddubn or @Michael-Hennecke have some ideas?

**Review by kccain — APPROVED** [review]
looks good for a patch that would be cherry-picked to release/2.4 branch (will it be?).

On master (daos 2.6, for which DAOS_POOL_GLOBAL_VERSION=3) will the parts of the code that executes for daos 2.2 pools even get run? i.e., when a pool's global_ver=1 < DAOS_POOL_GLOBAL_VERSION_WITH_OIT_OID_KVS=2. Since in 2.6 I don't think will even allow a pool handle connection to a 2.2 pool?

**Comment by wangshilong** [comment]
> looks good for a patch that would be cherry-picked to release/2.4 branch (will it be?).
> 
> On master (daos 2.6, for which DAOS_POOL_GLOBAL_VERSION=3) will the parts of the code that executes for daos 2.2 pools even get run? i.e., when a pool's global_ver=1 < DAOS_POOL_GLOBAL_VERSION_WITH_OIT_OID_KVS=2. Since in 2.6 I don't think will even allow a pool handle connection to a 2.2 pool?

Yup, in generally we don't support jump upgrading. but in the codes we don't forbid it, eg just for upgrading.

I think this better go to 2.4, let's try to land it master firstly..

**Pull request merged**
