### PR TITLE
DAOS-13416 tests: enable debug log for UCX provider

### PR DESCRIPTION
**Pull request by Nasf-Fan**
Only for test.

Test-tag-hw-medium-ucx-provider: test_daos_distributed_tx test_daos_verify_consistency
Test-repeat-hw-medium-ucx-provider: 10
Skip-func-hw-test-medium-ucx-provider: false

Signed-off-by: Fan Yong <fan.yong@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by Nasf-Fan** [comment]
Test-tag-hw-medium-ucx-provider: test_daos_distributed_tx test_daos_verify_consistency
Test-repeat-hw-medium-ucx-provider: 10


@brianjmurrell , I expected that only the two tests "test_daos_distributed_tx" and "test_daos_verify_consistency" are repeatedly tested for 10 times. But the real case is that all the tests specified in src/tests/ftest/daos_test/suite.yaml are tested only for once. So which commit parameters should I use? Thanks!

**Comment by brianjmurrell** [comment]
> Test-tag-hw-medium-ucx-provider: test_daos_distributed_tx test_daos_verify_consistency Test-repeat-hw-medium-ucx-provider: 10
> 
> @brianjmurrell , I expected that only the two tests "test_daos_distributed_tx" and "test_daos_verify_consistency" are repeatedly tested for 10 times. But the real case is that all the tests specified in src/tests/ftest/daos_test/suite.yaml are tested only for once. So which commit parameters should I use? Thanks!

The **Test Hardware / Functional Hardware Medium UCX Provider** stage was not even run:

image

You can see in the [log](https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/daos/branches/PR-12209/runs/3/log/?start=0): _[2023-05-27T12:16:18.296Z] Stage "Functional Hardware Medium UCX Provider" skipped due to when conditional_.  The log though, is unfortunately impossible to follow for any given stage due to having the output from all of the parallel stages being spewed in parallel.  My guess though is that it was some failure for your tags to match one or more tests.

Perhaps @phender can shed more light on this one.

**Comment by Nasf-Fan** [comment]
@phender , do you have some idea for the issues? Thanks!

**Comment by Nasf-Fan** [comment]
> > @phender , do you have some idea for the issues? Thanks!
> 
> It's https://daosio.atlassian.net/browse/DAOS-13329. Currently in a PR you cannot run the `Test / Functional Hardware Medium UCX Provider` stage.

Thanks, then let's wait DAOS-13329 solution.

**Comment by Nasf-Fan** [comment]
Not need it any longer.

**Pull request closed without merging**
