### PR TITLE
DAOS-8508-test release_2.0 Fix script and add test case for EC Snapshots

### PR DESCRIPTION
**Pull request by dinghwah**
Description: For release_2.0 update snapshot data size and snapshot number for EC test.
modified: snapshot.yaml
Test-tag: pr snapshots
Signed-off-by: Ding Ho ding-hwa.ho@intel.com

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]

**Review by rpadma2 — APPROVED** [review]

**Comment by dinghwah** [comment]
All snapshots and related tests are passed.

**Comment by dinghwah** [comment]
All snapshot tests associated with this PR are passing.
The error shown on the pr-head is irrelated to this PR.

**Comment by sylviachanoiyee** [comment]
Let's get https://github.com/daos-stack/daos/pull/7229 landed first

**Comment by sylviachanoiyee** [comment]
Landing is only open for 2.0 required tickets.
Looking at DAOS-8508, it is not a required for 2.0.
Will wait to land when master/2.0 is open to all tickets.

**Review by jolivier23 — CHANGES_REQUESTED** [review]
@dinghwah the correct process is to get patch landed to master branch first and then cherry-pick the change on release/2.0 and upload a new PR based on that but only after master PR has landed.
==>ok, please land this PR to master if possible. I will open a JIRA and checrrypick it to rel2.0

**Comment by sylviachanoiyee** [comment]
@dinghwah , looks like you removed the required for 2.0 on DAOS-8508.

**Comment by sylviachanoiyee** [comment]
@skirvan44 , is DAOS-8508 a required for 2.0?

**Comment by kprantis** [comment]
@sylviachanoiyee Let's proceed with merging this one, even with the current lock-down.

**Pull request merged**
