### PR TITLE
DAOS-8576 tools: Return UUID from cont create when query fails

### PR DESCRIPTION
**Pull request by kjacque**
The daos cont create command wasn't returning the container UUID
and type if it wasn't able to query the container after creating
it. The tool already has the container UUID, label and type after
the create succeeds, so we can provide that to the user.

Signed-off-by: Kris Jacque <kristin.jacque@intel.com>

### CODE REVIEW

**Comment by kjacque** [comment]
Not too surprising, the tests still fail because of another issue with the same tests, DAOS-8442. But we are getting past this issue and into teardown, which means this specific issue is solved.

**Comment by kjacque** [comment]
> Not too surprising, the tests still fail because of another issue with the same tests, DAOS-8442.

Just added a fix in the test scripts for DAOS-8442 as well.

**Comment by mchaarawi** [comment]
that sounds like a weird use case.
so are we supposed to return the uuid of the container is one is not allowed to query it?

**Review by shimizukko — APPROVED** [review]

**Comment by kjacque** [comment]
> that sounds like a weird use case.
> so are we supposed to return the uuid of the container if one is not allowed to query it?

The case is that the user has created a container with a different user as the owner. But they have created an ACL with, say, read-data permissions for themselves on the container, but not read-props permissions. They would be allowed to open the container but not to query the properties. It's a corner case, but the weekly container_security_acl test hits it. The cont create API call returns the UUID, so I thought we should return it from the tool as well.

I was thinking of doing the same for the case where the creator creates a container for another user/group and doesn't give themselves any permissions at all, but I think that's outside the scope of this ticket at least. (There's another long-standing ticket that touches on that case.)

**Review by dinghwah — APPROVED** [review]
LGTM.

**Review by kccain — APPROVED** [review]

**Review by mchaarawi — APPROVED** [review]

**Pull request merged**
