### PR TITLE
DAOS-623 build: Update PMDK to 1.9.2

### PR DESCRIPTION
**Pull request by brianjmurrell**
PR-repos: pmdk@PR-14
Skip-PR-comments: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
@jolivier23 Could add another reviewer or two, ideally people who interact with PMDK the most and would be the most informed about whether this is a change we do[n't] want to make at this point please?  Much thanks.

**Comment by jolivier23** [comment]
> @jolivier23 Could add another reviewer or two, ideally people who interact with PMDK the most and would be the most informed about whether this is a change we do[n't] want to make at this point please? Much thanks.

why not 1.10 ?   I tried building against 1.10 locally and it worked fine.   The library change is specific to libpmem but we use libpmemobj which uses the old version so it's fine.   1.10 builds both at present.

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Adding a request just to get this off my plate until you respond

**Comment by brianjmurrell** [comment]
> why not 1.10 ? I tried building against 1.10 locally and it worked fine. The library change is specific to libpmem but we use libpmemobj which uses the old version so it's fine. 1.10 builds both at present.

Did you do any testing?

I just chose the relative safety of staying on the existing code base, while having the latest of a maintained release stream.

If you think the risk of going to 1.10 at this point, for 1.2 is low, I can certainly push an update for that.

**Comment by brianjmurrell** [comment]
> why not 1.10 ? I tried building against 1.10 locally and it worked fine. The library change is specific to libpmem but we use libpmemobj which uses the old version so it's fine. 1.10 builds both at present.

I just tried to build the RPM for it.  It seems to need a bit of work.  So in the interest of expediency, I think we should just go forward with 1.9.2 and double back for 1.10 if time permits.

**Review by mjmac — APPROVED** [review]
Seems fine to me. There is a single failure in the cart tests that is probably not related.

**Review by JohnMalmberg — APPROVED** [review]

**Comment by jolivier23** [comment]
> > why not 1.10 ? I tried building against 1.10 locally and it worked fine. The library change is specific to libpmem but we use libpmemobj which uses the old version so it's fine. 1.10 builds both at present.
> 
> 
> 
> Did you do any testing?
> 
> 
> 
> I just chose the relative safety of staying on the existing code base, while having the latest of a maintained release stream.
> 
> 
> 
> If you think the risk of going to 1.10 at this point, for 1.2 is low, I can certainly push an update for that.

I only tested locally.  In fact, I haven't downgraded.  But I only run as much as run_test.ah on my workstation

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
