### PR TITLE
 DAOS-2798 test: daos_test and dmg should use more than one PS replica

### PR DESCRIPTION
**Pull request by dinghwah**
Update test.yaml for DAOS-2798: daos_test and dmg should use more than one PS replica
test.yaml in dfuse, pool, container, nvme, io, ior
By default svcn: 3
Quick-Functional: true
Skip-unit-test: true
Test-tag: dfusecontainercheck multicontainerdelete rootcontainer bashcmd findcmd fiosmall ioconsistency largefilecount mpi4py parallelio crashior iorhdf5 iorlarge iorsmall nvme_fragmentation nvme_io nvme_server_restart nvme_pool_capacity rebuildwithior storage_ratio
Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

### CODE REVIEW

**Comment by dinghwah** [comment]
All commit related tests passed, 1 failure was due to the following known issue which is not related to this commit:
DAOS-6788: unresponsive dmg pool destroy --force

**Review by shimizukko — APPROVED** [review]
LGTM

**Review by saurabhtandan — COMMENTED** [review]
Everything else looks good. But it seems like ticket's requirement also mentions 'daos_test'. This PR does not include 'daos_test'. Is there separate PR for it or there is work in progress for that test somewhere else?

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Comment by sylviachanoiyee** [comment]
@dinghwah , can you rerun all the test for this PR?
Because there are changes to many tests in this PR, it is hard for me to check to make sure all the affected tests are run.
For example, I have found one test that is affected but not run in this PR: largefilecount_rc

**Review by sylviachanoiyee — CHANGES_REQUESTED** [review]
Please rerun all tests for this PR

**Comment by dinghwah** [comment]
Merge to master after Brian's commit landed. 
This commit including all the available functional tests.

**Pull request merged**
