### PR TITLE
DAOS-12456 test: replace ftest/container/async.py with cmocka test

### PR DESCRIPTION
**Pull request by daltonbohning**
Features: test_daos_container

- Replace ftest/container/async.py with a cmocka test.
- Remove ftest support for TestPool.cb_handler and TestContainer.cb_handler

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by daltonbohning** [comment]
Known failures in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12229/2/tests
- test_daos_rebuild_ec - https://daosio.atlassian.net/browse/DAOS-12883

**Comment by daltonbohning** [comment]
Known failures in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12229/5/tests
- test_daos_rebuild_ec - https://daosio.atlassian.net/browse/DAOS-12883

**Review by shimizukko — APPROVED** [review]

**Review by kjacque — APPROVED** [review]

**Comment by daltonbohning** [comment]
Request forced landing due to known failure in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12229/5/tests

- test_daos_rebuild_ec - https://daosio.atlassian.net/browse/DAOS-12883

Also, the clang-format suggestion doesn't make sense. It wants me to replace a tab with spaces, but we use tabs in C-code

**Comment by ashleypittman** [comment]
> Also, the clang-format suggestion doesn't make sense. It wants me to replace a tab with spaces, but we use tabs in C-code

https://github.com/daos-stack/daos/blob/master/.clang-format#L10. For indentation and Continuation we do, for alignment we use spaces.  If you're committing on wolf I can help you with a setup to enable the clang-format commit hook.

**Comment by daltonbohning** [comment]
> 

Interesting. Even in the file I modified, there are many other non-conforming lines. I work from boro, but it should still be possible to setup the hook

**Comment by daltonbohning** [comment]
> Interesting. Even in the file I modified, there are many other non-conforming lines. I work from boro, but it should still be possible to setup the hook

Interesting. Even in the file I modified, there are many other non-conforming lines. I work from boro, but it should still be possible to setup the hook

**Pull request merged**
