### PR TITLE
DAOS-5969 dfs: remove access checks in DFS

### PR DESCRIPTION
**Pull request by mchaarawi**
The security access checks in the DFS were mearly for convenience
purposes as security is only enforced at the container through the ACL.
This patch removes the access checks from DFS to not give the false
sense of real security checks implemented in the DFS layer since they
can be bypassed through the object layer.

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
This seems to remove the file ownership/group checks but leave in place the open flags which seems reasonable as they're a lot simpler.  I was initially confused about why check_access() was left unchanged but I see it's now a helper function for dfs_access() only.

The kernel permissions are not enabled in fuse currently, https://github.com/daos-stack/daos/pull/3828 should address that and I'd prefer if that one could land first if possible so we don't have any builds without any checking.

**Comment by mchaarawi** [comment]
> This seems to remove the file ownership/group checks but leave in place the open flags which seems reasonable as they're a lot simpler. I was initially confused about why check_access() was left unchanged but I see it's now a helper function for dfs_access() only.
> 

right, the open flags are needed as they verify the type of handle you have (W or  R). anyway, i think they are verified internally in the obj API anyway, so you can't bypass them.
and yes i left check for dfs_access only which will be this convenience function if one wants to just call it; even though never enforced.

> The kernel permissions are not enabled in fuse currently, #3828 should address that and I'd prefer if that one could land first if possible so we don't have any builds without any checking.

i have no strong opinion here, only that i would like to get things off my plate.. if the other patch is ready / close to land, sure.

**Review by ashleypittman — APPROVED** [review]
I think this will also fix https://jira.hpdd.intel.com/browse/DAOS-5862

**Review by daltonbohning — APPROVED** [review]
My review wasn't requested, but I stumbled on this from #3828 
LGTM

**Pull request merged**
