### PR TITLE
DAOS-15774 test: fix pool_acl and pool_groups

### PR DESCRIPTION
**Pull request by daltonbohning**
Test-tag: SecurityPoolGroupsTest SecurityPoolACLTest
Skip-unit-tests: true
Skip-fault-injection-test: true

Skip container cleanup in teardown since the pool is destroyed explicitly first.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by mjmac** [comment]
Would it make more sense to make `skip_cleanup()` the default behavior? Seems like there were two commits prior to this one that are adding the `skip_cleanup()` because it's not needed (perhaps due to some other change?). 

To put it another way: If most tests should not be doing the container cleanup, then maybe this should be the new default, because otherwise this is likely to be a recurring problem as tests are added.

I guess another way to approach it would be to make the container destroy in cleanup optional. If the destroy fails due to the container not existing, and it's in the teardown phase, just ignore the error?

**Comment by daltonbohning** [comment]
> Would it make more sense to make `skip_cleanup()` the default behavior? Seems like there were two commits prior to this one that are adding the `skip_cleanup()` because it's not needed (perhaps due to some other change?).
> 
> To put it another way: If most tests should not be doing the container cleanup, then maybe this should be the new default, because otherwise this is likely to be a recurring problem as tests are added.
> 

Most tests should - and do - want to destroy containers in teardown. It's just oddball cases that destroy the container by some other means, or tests that have overly complicated handling, that need `skip_cleanup`


> I guess another way to approach it would be to make the container destroy in cleanup optional. If the destroy fails due to the container not existing, and it's in the teardown phase, just ignore the error?

That's not easy to do automatically because we could end up ignoring real errors.

Part of the trouble here is the codebase has years of tech debt built up and fixing these architectural issues is unfortunately not simple. Most code has been throwing all variables into the `self.*` namespace, which is effectively using global variables for everything.

**Comment by daltonbohning** [comment]
Tests are passing now:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-14284/1/tests

**Review by mjean308 — APPROVED** [review]

**Review by jamesanunez — APPROVED** [review]

**Comment by rpadma2** [comment]
@daltonbohning  : With this PR, can we address the other two issues mentioned in DAOS-15774 [control/dmg_system_cleanup.py, nvme/enospace.py] ?

**Pull request merged**
