### PR TITLE
DAOS-8872 Test: Fix IOR Hard rebuild test for multiple reads.

### PR DESCRIPTION
**Pull request by ravalsam**
Do not use stoneWallingWearOut for read, as we need to read the same
data multiple times for online rebuild.

Test-tag-hw-large: pr ec_ior_hard_online_rebuild

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
Hard rebuild test got passed but failed during cleanup because of existing defect DAOS-8856

**Review by dinghwah — APPROVED** [review]
LGTM

**Review by rpadma2 — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
Looks good but landing to master is closed since this morning. Will land when open

**Comment by sylviachanoiyee** [comment]
Looks like DAOS-8872 and DAOS-8856 (which is causing failures in the test this PR is fixing) are not a blockers for 2.0. Will wait for landing to open to all on master.

**Pull request merged**
