### PR TITLE
CORCI-1200 Build: Collect Job Information to YAML

### PR DESCRIPTION
**Pull request by JohnMalmberg**
Add methods to allow recording job status while the job runs
and write out a YAML file with the results.

Signed-off-by: John E Malmberg <john.e.malmberg@intel.com>

### CODE REVIEW

**Review by jolivier23 — CHANGES_REQUESTED** [review]
If this is a clean-cherry-pick, add that label and request gatekeeper again. Otherwise, it will need reviews for the backport first.

**Comment by JohnMalmberg** [comment]
I do not know if is a clean cherry pick or not. The Jenkinsfile for the master diverged from the branches, so I had to cut/paste the changes. I have been adding reviewers to these PRs.

**Comment by jolivier23** [comment]
> I do not know if is a clean cherry pick or not. The Jenkinsfile for the master diverged from the branches, so I had to cut/paste the changes. I have been adding reviewers to these PRs.

if you ported it manually then it is, by definition, an unclean-cherry-pick and should be marked as such.  You'll need to get reviews for it.

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Once you have reviews, add gatekeeper back.

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
