### PR TITLE
DAOS-8082 swim: memory leak

### PR DESCRIPTION
**Pull request by wangdi1**
Missing free upds allocated in swim_updates_prepare().

Signed-off-by: Di Wang <di.wang@intel.com>

### CODE REVIEW

**Review by dmiter — CHANGES_REQUESTED** [review]
D_FREE() eats NULL pointer fine. We everywhere removed this additional IF. So, please don't add them.

**Comment by dmiter** [comment]
Also, you should not explicitly free rpc_out->upds.ca_arrays. It will be free during RPC destroy.

**Comment by wangdi1** [comment]
> Also, you should not explicitly free rpc_out->upds.ca_arrays. It will be free during RPC destroy.

I do not think RPC destroy will destroy this upds buffer, these array buffer has to be explicitly freed.

**Review by dmiter — APPROVED** [review]
It looks you are right. This memory should be free explicitly.

**Review by frostedcmos — APPROVED** [review]

**Comment by wangdi1** [comment]
merge this to #6340

**Pull request closed without merging**
