### PR TITLE
DAOS-4299 test: dfuse teardown exceptions being ignored by Avocado

### PR DESCRIPTION
**Pull request by Puspalogan**
Test-tag: pr,-hw full_regression,-hw
Test-tag-hw-small: pr,hw,small full_regression,hw,small
Test-tag-hw-medium: pr,hw,medium,ib2 full_regression,hw,medium,ib2
Test-tag-hw-large: pr,hw,large full_regression,hw,large

  - Modified the way Dfuse.stop() method is invoked. Removed
    calling of stop() from Dfuse.__del__() because the exception
    thrown in __del__() is being ignored by the avocado framework.
  - Modified the classes that uses Dfuse to call the Dfuse.stop()
    in tearDown()
  - Removed util/test_utils.py file as it was erroneously
    introduced back in PR #1702

Signed-off-by: Logan Sundaram <logan.sundaram@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
I've cherry-picked this into https://github.com/daos-stack/daos/pull/2205

**Comment by brianjmurrell** [comment]
> I've cherry-picked this into #2205

Should we cherry-pick it yet given your previous comment?

> This change isn't doing what we expect, it's a step forward but previously dfuse would be stopped for each subtest, where now it isn't.

What is the probability of a dirty dfuse from one test tainting another?

**Comment by ashleypittman** [comment]
> > I've cherry-picked this into #2205
> 
> Should we cherry-pick it yet given your previous comment?

I cherry-picked it, and then fixed the remaining issues.

> > This change isn't doing what we expect, it's a step forward but previously dfuse would be stopped for each subtest, where now it isn't.
> 
> What is the probability of a dirty dfuse from one test tainting another?

Low, but possible.  These changes should reduce that.

**Comment by Puspalogan** [comment]
The changes are cherrypicked to #2205

**Pull request closed without merging**
