### PR TITLE
DAOS-8981 dfuse: Allow setattr of uid/gid in dfuse if data is unchanged.

### PR DESCRIPTION
**Pull request by ashleypittman**
A lot of clients seem to do this, often with other metadata updates
in the same call, so if this happens allow the change, but do not
attempt to apply it.

Remove ctime setattr check, this often happens with any type of
caching enabled.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Review by daltonbohning — DISMISSED** [review]
FWIW, mpifileutils does this as well when preserving attributes (but I think the error is ignored/silenced already)

**Comment by ashleypittman** [comment]
> FWIW, mpifileutils does this as well when preserving attributes (but I think the error is ignored/silenced already)

dfuse was returning ENOTSUP in this case which is often silently ignored.

**Review by mchaarawi — COMMENTED** [review]
sounds like an nlt test case should be added?

**Comment by ashleypittman** [comment]
> sounds like an nlt test case should be added?

Should be possible with this feature yes, I'll add one.

**Comment by ashleypittman** [comment]
Test added, this new test fails on master without this PR but passes locally with the new code.

**Review by bfaccini — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by ashleypittman** [comment]
@daos-stack/daos-gatekeeper this is approved and passed all client tests, but has failed with erasure code tests and what looks to be a server issue.  Should I re-trigger or can this be force landed?

**Review by johannlombardi — APPROVED** [review]

**Pull request merged**
