### PR TITLE
DAOS-6792 sched: fix improper assert

### PR DESCRIPTION
**Pull request by NiuYawei**
Fix the improper assert in sched_try_relax().

Signed-off-by: Niu Yawei <yawei.niu@intel.com>

### CODE REVIEW

**Review by ashleypittman — APPROVED** [review]

**Review by liuxuezhao — APPROVED** [review]

**Comment by jolivier23** [comment]
Another one I merged latest master to get provisioning fix due to its location in the build queue.

**Comment by NiuYawei** [comment]
All tests passed, but there is an new NLT warning: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5005/4/VM_test/new/source.a9f3e533-e0b3-4fa1-8ee7-38222f737ac6/#827

I don't think it's relevant to this patch.

**Comment by ashleypittman** [comment]
> All tests passed, but there is an new NLT warning: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5005/4/VM_test/new/source.a9f3e533-e0b3-4fa1-8ee7-38222f737ac6/#827
> 
> I don't think it's relevant to this patch.

NLT has been stable recently, and I don't recognise that issue.  I agree that it doesn't look relevant to this PR but perhaps @frostedcmos could comment?

**Comment by frostedcmos** [comment]
This issue is likely caused by very rare situations where 2 'first' rpcs going to the same target happen at the same time from a single client, causing double hg address lookup.
now that hg address lookups are synchronous we can modify cart code to hold lock in between 'we dont know hg address' and 'lookup+insert hg address'.
Ticket submitted: https://jira.hpdd.intel.com/browse/CART-960

**Pull request merged**
