### PR TITLE
DAOS-7589 test: Update pool_list() in dmg_utils.py and affected tests

### PR DESCRIPTION
**Pull request by shimizukko**
Use JSON for dmg pool list.
Fixed affected tests.

Skip-unit-tests: true
Test-tag: pr list_pools dynamic_server_pool
Signed-off-by: Makito Kano <makito.kano@intel.com>

### CODE REVIEW

**Review by phender — APPROVED** [review]

**Review by dinghwah — APPROVED** [review]
lgtm.

**Review by sylviachanoiyee — CHANGES_REQUESTED** [review]
The dmg_system_reformat test needs to be re-enabled to test the changes.
DAOS-6004 is resolved.
Since this will require another commit, can we implement suggestions from Phil for better error guidance in case of failure?
Thanks!

**Comment by shimizukko** [comment]
> The dmg_system_reformat test needs to be re-enabled to test the changes.
> DAOS-6004 is resolved.
> Since this will require another commit, can we implement suggestions from Phil for better error guidance in case of failure?
> Thanks!

@sylviachanoiyee I noticed that dmg_system_reformat.py uses NVMe. I don't have any working environment with NVMe, so testing it will take a long time, either locally or in CI. If you really want me to enable it, I will drop this file and create a new PR for just enabling the test. This work is out of scope of this PR and my other work is blocked by this PR. I would rather make the PR smaller than bigger. Also, Phil is implementing these suggestions in his own PR. Thanks.

**Comment by sylviachanoiyee** [comment]
> > The dmg_system_reformat test needs to be re-enabled to test the changes.
> > DAOS-6004 is resolved.
> > Since this will require another commit, can we implement suggestions from Phil for better error guidance in case of failure?
> > Thanks!
> 
> @sylviachanoiyee I noticed that dmg_system_reformat.py uses NVMe. I don't have any working environment with NVMe, so testing it will take a long time, either locally or in CI. If you really want me to enable it, I will drop this file and create a new PR for just enabling the test. This work is out of scope of this PR and my other work is blocked by this PR. I would rather make the PR smaller than bigger. Also, Phil is implementing these suggestions in his own PR. Thanks.

Ok. Please push a PR to enable the test. Thanks!

**Pull request merged**
