### PR TITLE
DAOS-6362 tests: Improving the cancelForTicket option.

### PR DESCRIPTION
**Pull request by phender**
Adding a apricot.Test.CANCEL_FOR_TICKET tuple which can be populated
with a tuple of a (<jira_ticket>, <param_name>, <param_value>) to define when
a test variant should be skipped/cancelled.  If the <param_name> is
assigned the <param_value> the test varaint will be marked as CANCEL for
the <jira_ticket>.

Test-tag: pr,-hw rebuildcontcreate connectpermission

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Review by mjean308 — DISMISSED** [review]
LGTM

**Review by shimizukko — APPROVED** [review]
LGTM
Are we going to implement the similar thing for skipForTicket?

**Review by brianjmurrell — APPROVED** [review]

**Comment by phender** [comment]
My last commit resulted in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4131/3/ where all tests passed.

For an unknown reason, https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4131/4/ was also run, where 2 of the 13 daos_core_test-rebuild tests failed due to https://jira.hpdd.intel.com/browse/DAOS-6409

**Comment by phender** [comment]
> LGTM
> Are we going to implement the similar thing for skipForTicket?

I'm not exactly sure what you're asking @shimizukko.  Could you please elaborate?  

If you are asking if `@skipForTicket(<ticket>)` could be enhanced to include the test parameter conditional as an option, that was the original intent of the ticket - which would have negated the need for `cancelForTicket()`.  In my attempt to implement that approach (see DAOS-6362) I ran into the problem where `self.params` was not initialized when the the decorator was executed, so the optional conditional could not be verified.

**Review by shimizukko — APPROVED** [review]
LGTM

**Comment by shimizukko** [comment]
> > LGTM
> > Are we going to implement the similar thing for skipForTicket?
> 
> I'm not exactly sure what you're asking @shimizukko. Could you please elaborate?
> 
> If you are asking if `@skipForTicket(<ticket>)` could be enhanced to include the test parameter conditional as an option, that was the original intent of the ticket - which would have negated the need for `cancelForTicket()`. In my attempt to implement that approach (see DAOS-6362) I ran into the problem where `self.params` was not initialized when the the decorator was executed, so the optional conditional could not be verified.

I understand better after reading the ticket description. Thanks.

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
