### PR TITLE
DAOS-10037 mgmt: Add incarnation to GroupUpdateReq

### PR DESCRIPTION
**Pull request by liw**
This is a prerequisite for implementing the following behavior as part
of the DAOS-10037 design.

  - When modifying the primary group, if the incarnation of a rank
    increases, mark the rank and its epi as being alive.

This is necessary because of the following scenario.

  - When a rank X rejoins a system, the rank Y that is responsible for
    broadcasting the latest system membership to every member, including
    rank X, may think that rank X is dead and cancel the broadcast RPC
    to rank X. Hence, rank X won’t be able to initialize its local PG.

Signed-off-by: Li Wei <wei.g.li@intel.com>
Required-githooks: true

### CODE REVIEW

**Review by tanabarr — APPROVED** [review]
LGTM, this PR is adding the incarnation information into the database and a subsequent PR will use the added information.

**Comment by liw** [comment]
> LGTM, this PR is adding the incarnation information into the database and a subsequent PR will use the added information.

Thanks, Tom. Just a clarification: The incarnation info is _already_ in the database (if I'm not mistaken); this PR ships the info with GroupUpdateReq, and yes, a follow-on PR will make use the info.

**Comment by tanabarr** [comment]
> > LGTM, this PR is adding the incarnation information into the database and a subsequent PR will use the added information.
> 
> Thanks, Tom. Just a clarification: The incarnation info is _already_ in the database (if I'm not mistaken); this PR ships the info with GroupUpdateReq, and yes, a follow-on PR will make use the info.

Right sorry I meant that it was added to the GroupMap in the database, thanks for the clarification.

**Comment by liw** [comment]
> > > LGTM, this PR is adding the incarnation information into the database and a subsequent PR will use the added information.
> > 
> > 
> > Thanks, Tom. Just a clarification: The incarnation info is _already_ in the database (if I'm not mistaken); this PR ships the info with GroupUpdateReq, and yes, a follow-on PR will make use the info.
> 
> Right sorry I meant that it was added to the GroupMap in the database, thanks for the clarification.

Cool. If it were a database addition, we'd have an upgrade/downgrade problem. Thanks.

**Review by kjacque — APPROVED** [review]
LGTM.

Thanks for the heads up @mjmac. I think the merge work with the multiprovider branch will be minor.

**Comment by liw** [comment]
Thanks for the quick responses, @tanabarr, @mjmac, and @kjacque.

**Pull request merged**
