### PR TITLE
DAOS-7332 control: allow hostname with negative port

### PR DESCRIPTION
**Pull request by mlawsonca**
DAOS-7332 control: allow hostname with negative port

Adjusted the parse function in hostlist.go to disallow IP addresses
with a negative port number. An IP address with a negative port
number now throws an "invalid hostname" error. The "negative port"
unit test in hostlist_test.go was modified to expect this new
behavior.

Signed-off-by: Margaret Lawson <mlawsonca@google.com>

### CODE REVIEW

**Comment by mlawsonca** [comment]
Hi, thank you for your reply. I could not imagine why negative port numbers should be allowed, but thought that both the Jira ticket and the TODO comment in the repo implied the negative port should be allowed. I will submit a fix. Also, just in general, if I want to clarify a Jira bug, who is the right person to ask (the Jira assigner or assignee, or someone else) and the right way to do so (commenting on the ticket, in the Git repo, or by e-mail)?

**Comment by mjmac** [comment]
> Also, just in general, if I want to clarify a Jira bug, who is the right person to ask (the Jira assigner or assignee, or someone else) and the right way to do so (commenting on the ticket, in the Git repo, or by e-mail)?

We use jira as the primary project management tool, so a comment on the ticket is probably best.

**Comment by mjmac** [comment]
Looks reasonable now, thanks. Only problem is that the PR seems to have deleted the `.gitignore` file, so it can't land as-is.

**Comment by mlawsonca** [comment]
Thank you. I have fixed the gitignore issue (sorry for that) and updated the comment.

**Review by tanabarr — APPROVED** [review]
LGTM

**Comment by mjmac** [comment]
I forgot that we don't currently allow PRs from external repos to run on our internal CI cluster, so I've created #10252 to get full coverage. It still shows @mlawsonca as the author of the commits, so I think attribution should work out OK.

**Comment by mjmac** [comment]
I just landed #10252. Unfortunately, it looks like it attributed authorship of the squashed commit to me, even though you were the author of the commits on the branch before it was squashed. Apologies for that; we're still working through the best way to accept external contributions. The ideal solution would be to follow the standard github flow and just accept PRs directly from external repos, but there is some technical reason we're not doing that (yet?). I'll figure out how to avoid this in the future... You did get a signed-off-by credit, though.

**Pull request closed without merging**
