### PR TITLE
DAOS-6325 test: Fix broken ior_hdf5_vol test

### PR DESCRIPTION
**Pull request by saurabhtandan**
Fix broken ior_hdf5_vol test

Quick-Functional: true
Skip-unit-tests: true
Test-tag: iorsmall, vol

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

### CODE REVIEW

**Review by mchaarawi — COMMENTED** [review]
just FYI, you have not removed the commented our IOR HDF5-VOL tests in the ior_small yaml file. so your fix is not testing the broken case that i saw in my PR.

**Comment by saurabhtandan** [comment]
> just FYI, you have not removed the commented our IOR HDF5-VOL tests in the ior_small yaml file. so your fix is not testing the broken case that i saw in my PR.

I though the problem was for ior_hdf5.py which you were seeing in your PR?
image

But regardless, I agree this didn't have HDF5_VOL. I can update it.

**Comment by mchaarawi** [comment]
> > just FYI, you have not removed the commented our IOR HDF5-VOL tests in the ior_small yaml file. so your fix is not testing the broken case that i saw in my PR.
> 
> I thought the problem was for ior_hdf5.py which you were seeing in your PR?
> image
> 
> But regardless, I agree this didn't have HDF5_VOL. I can update it.

yes it is IOR HDF5, but using the DAOS VOL and not over MPIIO. the latter was not disabled.

**Comment by saurabhtandan** [comment]
> > > just FYI, you have not removed the commented our IOR HDF5-VOL tests in the ior_small yaml file. so your fix is not testing the broken case that i saw in my PR.
> > 
> > 
> > I thought the problem was for ior_hdf5.py which you were seeing in your PR?
> > image
> > But regardless, I agree this didn't have HDF5_VOL. I can update it.
> 
> yes it is IOR HDF5, but using the DAOS VOL as you can see in that image and not over MPIIO. the latter was not disabled.

I meant to say, as per your PRs failure ior_hdf5.py was failing which runs HDF5 as well as HDF5-VOL tests `def test_ior_hdf5(self):` and `def test_ior_hdf5_vol(self):`, so I believe HDF5 over MPIIO was checked as part of ior_hdf5.py test as well.
But as I said, I agree 'HDF5-VOL' run for ior_small was not enabled as part of this PR which I have fixed and re-pushed. If you want to go ahead and get your PR landed feel free. Just stating that HDF5 with MPIIO was checked as part of ior_hdf5.py and it passed for my last push.

**Comment by saurabhtandan** [comment]
All vol tests and iorsmall test passed.

**Review by shimizukko — APPROVED** [review]

**Review by ravalsam — APPROVED** [review]

**Review by mchaarawi — APPROVED** [review]

**Pull request merged**
