### PR TITLE
DAOS-4078 swim: Add swim_rank_dead RAS event

### PR DESCRIPTION
**Pull request by mjmac**
When a rank is marked dead, raise a RAS event to the control plane so that
the system map can be updated.

Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>

### CODE REVIEW

**Review by tanabarr — DISMISSED** [review]

**Review by dmiter — COMMENTED** [review]
I'm not clear about how this event will affect behavior.  Who is responsible for primary group change? If this event will be handled in two places how they will be synced?

**Comment by mjmac** [comment]
> 
> 
> I'm not clear about how this event will affect behavior. Who is responsible for primary group change? If this event will be handled in two places how they will be synced?

The way this works is that we register for swim events on iosrv init. When a dead node event is received in the callback, that ioserver rank raises a swim_node_dead RAS event to the local control plane server (daos_server).

The swim_node_dead RAS event is forwarded to the current Management Service leader, which takes care of updating the rank state in the system database and also performs a primary group change on one of its local ranks. The updated map is asynchronously broadcast to the rest of the ranks.

If multiple RAS events are created for the same dead rank, only the first matters. The others are effectively ignored.

What this PR doesn't address is swim_node_alive events. I'm not sure if or how these should be handled. My (perhaps naive) expectation is that once a node is marked as dead, it has to be stopped and restarted in order to rejoin.

**Comment by dmiter** [comment]
I'm just worry about the second event wich is catched now in the pool eviction logic. If this rank will be evicted from pool in parallel how it will be handled by your logic?

**Comment by mjmac** [comment]
> 
> 
> I'm just worry about the second event wich is catched now in the pool eviction logic. If this rank will be evicted from pool in parallel how it will be handled by your logic?

I didn't add the callback for the pool service, so I'm not very familiar with what it is doing. I assume that a rank can only be evicted by a pool if the event is received by a rank acting as the pool service leader. I don't believe that any primary group update occurs in that case, either.

This second case doesn't have anything to do with the pool service -- it's intended to catch swim events on any rank regardless of whether or not the catching rank is in the same pool as the dead rank.

@liw, @kccain: Is there a gap here? Is my understanding of the pool service event handling ([here](https://github.com/daos-stack/daos/blob/master/src/pool/srv_pool.c#L934)) correct in that a swim death event for a pool rank might be missed if it's not received by the pool service leader? If so, should there be some glue that forwards a dead rank notification to all pools with that rank in their membership?

**Comment by mjmac** [comment]
>
> Maybe the expectation is that eventually the dead rank notification is received by the pool service leader via gossip? Sorry, I don't have a strong understanding of how swim works.

Hmm. There is an implication here that I hadn't considered before. If the expectation is that eventually all ranks in the system learn about the dead rank, then if there are N ranks in the system then there will be N-1 swim_node_dead events raised and forwarded to the MS. The MS logic should handle this OK as an idempotent situation, but it seems wasteful to process all of those extra events. It would be ideal if only a small subset would forward the event, but I'm not sure how all of the other ranks would know that they don't need to forward.

**Comment by dmiter** [comment]
When on the first rank the DEAD timeout is expired it throws this event and it starts spreading this information to other ranks. When this information come to other rank it also throws this event locally and it continue spreading this information to other ranks. This will continue until all ranks receive this information.

**Comment by mjmac** [comment]
> 
> 
> When on the first rank the DEAD timeout is expired it throws this event and it starts spreading this information to other ranks. When this information come to other rank it also throws this event locally and it continue spreading this information to other ranks. This will continue until all ranks receive this information.

OK, this makes sense. Is there a way to tell in the event callback that it was triggered via timeout on the local node vs. received via gossip?

**Comment by dmiter** [comment]
> OK, this makes sense. Is there a way to tell in the event callback that it was triggered via timeout on the local node vs. received via gossip?

No. This is not possible for now.

**Comment by liw** [comment]
> @liw, @kccain: Is there a gap here? Is my understanding of the pool service event handling ([here](https://github.com/daos-stack/daos/blob/master/src/pool/srv_pool.c#L934)) correct in that a swim death event for a pool rank might be missed if it's not received by the pool service leader? If so, should there be some glue that forwards a dead rank notification to all pools with that rank in their membership?

The design for a single pool is the following pool service algorithm:

    Upon SWIM event:
        Queue it

    Upon nonempty queue:
        Consume one or more event from the queue
        Handle them

    Upon Pool Service stepping up:
        Read map from DB
        Query map members' SWIM status
        Recover potentially lost events for DEAD members and queue them
        Register for future SWIM events // Note that daos_io_server can avoid races between this and the last step by avoiding reschedules

    Upon Pool Service stepping down:
        Deregister for future SWIM events
        Discard queue

The current code doesn't implement the queue; the rest are implemented, I think.

**Comment by liw** [comment]
The bigger problem is that subsequent PG rank removals may have issues. E.g., either rejected because some SGs still references that rank, or maybe processed by incorrectly changing such SGs. That's why we didn't simply merge Di's implementation for the old MS.

**Comment by mjmac** [comment]
> 
> 
> The bigger problem is that subsequent PG rank removals may have issues. E.g., either rejected because some SGs still references that rank, or maybe processed by incorrectly changing such SGs. That's why we didn't simply merge Di's implementation for the old MS.

OK. I've updated the PR to avoid updating the PG after rank is evicted by swim hint, with a note that it should be enabled once CART-944 is finished.

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
