### PR TITLE
DAOS-5166 test: Integrate storage_query functions into dmg_utils.py

### PR DESCRIPTION
**Pull request by amjustin13**
Add storage query functionality into dmg_utils.py

Signed-off-by: Justiniano-pagn <amanda.justiniano-pagn@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
> The code looks good, but is there a test to go along with these new methods? How are we confirming that they work as intended?
> 
> One other thing to consider is the more complicated regex entries can be difficult for another developer to use without some better documentation or another class/method that uses them and translates the return value from `re.findall()` into something more usable, e.g. this in progress edit to [TestPool](https://github.com/daos-stack/daos/blob/052a4ecaad9947e9c97dc1570dffc610fc9173ce/src/tests/ftest/util/test_utils_pool.py#L356). Do we have something like that planned for the storage?

There is discussion on why we want to land this utility only and not the test cases are mention in DAOS-3925.
I am working on PR, which will utilize dmg command implemented in this PR. I am using this PR currently in my local test development.

**Comment by phender** [comment]
> > The code looks good, but is there a test to go along with these new methods? How are we confirming that they work as intended?
> > One other thing to consider is the more complicated regex entries can be difficult for another developer to use without some better documentation or another class/method that uses them and translates the return value from `re.findall()` into something more usable, e.g. this in progress edit to [TestPool](https://github.com/daos-stack/daos/blob/052a4ecaad9947e9c97dc1570dffc610fc9173ce/src/tests/ftest/util/test_utils_pool.py#L356). Do we have something like that planned for the storage?
> 
> There is discussion on why we want to land this utility only and not the test cases is mention in DAOS-3925.
> I am working on PR, which will utilize dmg command implemented in this PR. I am using this PR currently in my local test development.

Ok.  Just wanted to make sure it is tested somewhere.

**Comment by amjustin13** [comment]
Not sure what failed in HW Medium run, it looks like all the tests passed. It is also reporting failures in run_test.sh step. I'll re run the build.

**Comment by amjustin13** [comment]
Reran test stage since last run hit this error that seems to be due to bad nvme ssd:
```
[stderr] [1,6]<stderr>:ERROR:   format of nvme device 0000:da:00.0 failed: bdev: code = 320 description = "NVMe format failed: NVMe Format(): C.nvme_format(): spdk: code = 759 description = \"SPDK binding failed, rc: -6, namespace with id 1 not found\""
```

**Comment by amjustin13** [comment]
Failure of known flaky test for IOR_small: https://jira.hpdd.intel.com/browse/DAOS-4989

**Pull request merged**
