### PR TITLE
DAOS-7762 rpm: Move daos_metrics to server RPM

### PR DESCRIPTION
**Pull request by kjacque**
daos_metrics must be run on the same machine where the daos_server
and daos_engines are running.

Signed-off-by: Kris Jacque <kristin.jacque@intel.com>

### CODE REVIEW

**Review by mjmac — APPROVED** [review]

**Review by tanabarr — DISMISSED** [review]

**Comment by kjacque** [comment]
The two test failures are unrelated to these changes. One is a test timeout that resembles DAOS-8216, and the other is DAOS-8224.

**Review by jolivier23 — CHANGES_REQUESTED** [review]
debian changes?  Also, we usually would have a version bump and change log entry here.

**Review by mjmac — DISMISSED** [review]

**Comment by kjacque** [comment]
There is one unrelated test failure, an intermittent pool_create_capacity timeout that has existed on master. Not relevant to this change.

**Review by mjmac — APPROVED** [review]

**Comment by kjacque** [comment]
The test failure is DAOS-8229.

**Review by tanabarr — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
