### PR TITLE
DAOS-5277 cart: fix for memory leak

### PR DESCRIPTION
**Pull request by dmiter**
Fix incorrect condition check.

### CODE REVIEW

**Comment by ashleypittman** [comment]
This caused a crash, which shows up both in the NLT results, but because there was a segv it re-ran under Jenkins and there are additional details here https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-3957/2/valgrindResult/

Specifically 

https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-3957/2/valgrindResult/pid=11742,0x0/

**Comment by dmiter** [comment]
@ashleypittman, I don't see those issues any more. Do you see them?

**Comment by ashleypittman** [comment]
Looks like the NLT issues are fixed but there's still one valgrind error

https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3957/3/valgrindResult/pid=3500,0x5/

**Comment by dmiter** [comment]
OSAOnlineDrain - DAOS-5350
OSAOfflineDrain - DAOS-6107
OSAOfflineParallelTest - DAOS-6107

**Review by frostedcmos — APPROVED** [review]

**Review by ashleypittman — APPROVED** [review]
Confirmed this resolves the valgrind reports as well.

**Comment by dmiter** [comment]
Let's land this...

**Pull request merged**
