### PR TITLE
DAOS-2703 control: suppress logging during go unit tests

### PR DESCRIPTION
**Pull request by tanabarr**
Supply buffer as default logger io.Writer during unit tests and only
print on failure. Log to testing.T.Log for any test specific output.
Apply small lint fixes and formatting adjustments on the way.

Changes make unit test output cleaner and more useful.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Comment by mjmac** [comment]
Functionally, this looks straightforward and should do the job without any problems. I do wonder if it would be better to capture the output in a buffer and display it on test failure, though. My concern is that the suppressed output might contain useful information in the event of a failure, and it would be a shame to have to re-run tests with output enabled in order to try and reproduce the failure.

That having been said, I'm not overly familiar with what is being output, so maybe it's completely useless. I'll defer to the judgement of others with more experience in this area.

**Comment by tanabarr** [comment]
> Functionally, this looks straightforward and should do the job without any problems. I do wonder if it would be better to capture the output in a buffer and display it on test failure, though. My concern is that the suppressed output might contain useful information in the event of a failure, and it would be a shame to have to re-run tests with output enabled in order to try and reproduce the failure.
> 
> That having been said, I'm not overly familiar with what is being output, so maybe it's completely useless. I'll defer to the judgement of others with more experience in this area.

it's a good point and really to debug failures the output is useful and probably someone would need to  point the default logger somewhere useful to retrieve the error output and more context regarding the failure. this change is just cosmetic and reduces the noise for successful tests which has confused some as errors are printed for tests that succeed (because the tests raise and verify the error). we could redirect to testing.T log which would only print on failure or -v, much like the buffer you describe. otherwise we could log to a file and expose that in CI reports.

in any case I would prefer to do the above as follow-up tasks and land this to clean up and so as to not confuse people, to debug we can rerun the unit tests with logging redirected to somewhere visible if needed.

**Comment by mjmac** [comment]
> > Functionally, this looks straightforward and should do the job without any problems. I do wonder if it would be better to capture the output in a buffer and display it on test failure, though. My concern is that the suppressed output might contain useful information in the event of a failure, and it would be a shame to have to re-run tests with output enabled in order to try and reproduce the failure.
> > That having been said, I'm not overly familiar with what is being output, so maybe it's completely useless. I'll defer to the judgement of others with more experience in this area.
> 
> it's a good point and really to debug failures the output is useful and probably someone would need to point the default logger somewhere useful to retrieve the error output and more context regarding the failure. this change is just cosmetic and reduces the noise for successful tests which has confused some as errors are printed for tests that succeed (because the tests raise and verify the error). we could redirect to testing.T log which would only print on failure or -v, much like the buffer you describe. otherwise we could log to a file and expose that in CI reports.
> 
> in any case I would prefer to do the above as follow-up tasks and land this to clean up and so as to not confuse people, to debug we can rerun the unit tests with logging redirected to somewhere visible if needed.

As with the linter suppression patch -- I don't understand the motivation for doing things "wrong" with the hope that eventually they'll be done correctly. Not meaning to be contentious here, but it's just good practice to fix things at the time they're recognized as needing to be fixed. It doesn't seem like a major change to add a bytes.Buffer (or strings.Builder, as the SLES12.3 environment has been fixed) as the io.Writer and then dump its contents to stderr on test failure with a helper. e.g.

```go
func failWithBufferedOutput(t *testing.T, err error, output fmt.Stringer) {
        t.Fail()
        t.Logf("Failure due to error %s", err)
        t.Logf("Additional output: %s", output)
}
```

**Comment by tanabarr** [comment]
gatekeeper please use PR title and description as commit message when merging

**Pull request merged**
