### PR TITLE
DAOS-10300 control: improve pool list output

### PR DESCRIPTION
**Pull request by wangshilong**
improve "Upgrade?" to "UpgradeNeeded?" to make output
more clear, also clean up codes a bit.

Signed-off-by: Wang Shilong <shilong.wang@intel.com>
Required-githooks: true

### CODE REVIEW

**Review by knard-intel — APPROVED** [review]

**Review by mjmac — APPROVED** [review]

**Review by kjacque — APPROVED** [review]

**Comment by wangshilong** [comment]
@daos-stack/daos-gatekeeper PR shall be ready for landing control/config_generator.py test failures are known issue

**Review by jolivier23 — COMMENTED** [review]
Are there any general tests (not added by Features control, dmg) that may fail because the fields changed?

**Comment by mjmac** [comment]
> Are there any general tests (not added by Features control, dmg) that may fail because the fields changed?

None of the tests _should_ be using the human-formatted output, so if something does break, then it's a test that needs to be fixed anyhow. That having been said, nothing broke when the original patch added the new field.

**Comment by wangshilong** [comment]
@jolivier23 there is a mdtest failure here https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9739/8/tests which i think should be not related to this PR.

**Comment by wangshilong** [comment]
@daos-stack/daos-gatekeeper PR is ready for landing now.

**Pull request merged**
