### PR TITLE
DAOS-6721 build: Update submodule raft

### PR DESCRIPTION
**Pull request by liw**
Update submodule raft to pick up a fix that avoids removed replicas from
disrupting current replicas as well as fixes for some Coverity issues.

Signed-off-by: Li Wei <wei.g.li@intel.com>

### CODE REVIEW

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
This will need to merge master once the [version update PR](https://github.com/daos-stack/daos/pull/4752) lands there.

https://github.com/daos-stack/raft/ will also need updating to build the new tag.  You can do that yourself if you want or you can open a DAOS ticket to have that done, blocking DAOS-6721 to have somebody else do that update.

**Comment by liw** [comment]
> This will need to merge master once the [version update PR](https://github.com/daos-stack/daos/pull/4752) lands there.
> 
> https://github.com/daos-stack/raft/ will also need updating to build the new tag. You can do that yourself if you want or you can open a DAOS ticket to have that done, blocking DAOS-6721 to have somebody else do that update.

@brianjmurrell, may I ask why #4752 can not wait for this one, please?

**Review by kccain — DISMISSED** [review]

**Comment by brianjmurrell** [comment]
> @brianjmurrell, may I ask why #4752 can not wait for this one, please?

Per @kprantis the branch for 1.2 was created today/already and the first PR to land on master MUST be the one updating it's future potential version (#4752), so that we are not creating the same version packages from both master and [release/1.2](https://github.com/daos-stack/daos/tree/release/1.2).

**Comment by liw** [comment]
@brianjmurrell, okay, fair enough. Could you elaborate why raft.git needs updating to build the new tag? What new tag? Thanks.

**Review by gnailzenh — APPROVED** [review]

**Comment by brianjmurrell** [comment]
> @brianjmurrell, okay, fair enough. Could you elaborate why raft.git needs updating to build the new tag? What new tag? Thanks.

It seems that this has already been done in https://github.com/daos-stack/raft/commit/3fa7f4e4f6410b372c906057e43c007d1839966e.  I hadn't realised that since it doesn't seem to have been done through a PR.  Unless I am misunderstanding something.

**Review by brianjmurrell — APPROVED** [review]
Other than resolving the conflicts, looks good.

**Comment by liw** [comment]
> It seems that this has already been done in [daos-stack/raft@3fa7f4e](https://github.com/daos-stack/raft/commit/3fa7f4e4f6410b372c906057e43c007d1839966e). I hadn't realised that since it doesn't seem to have been done through a PR. Unless I am misunderstanding something.

Right, I pushed to raft.git master by mistake. Immediately after the push, I disabled this for raft.git to prevent it from happen again unintentionally.

**Review by kccain — APPROVED** [review]

**Comment by liw** [comment]
The NLT failures (-DER_SHUTDOWNs) are known issues, for instance, in DAOS-6788.

**Review by brianjmurrell — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
