### PR TITLE
DAOS-5034 documentation: API documentation changes

### PR DESCRIPTION
**Pull request by cdurf1**
These changes enable the groupings requested for the API and updates to current

Skip-build: true
Skip-test: true

Signed-off-by: craig <craig.durfey@intel.com>

### CODE REVIEW

**Review by Michael-Hennecke — APPROVED** [review]
I don't understand the "GitHub Actions / Run doxygen" warnings, is that a tools problem?

**Comment by ashleypittman** [comment]
> I don't understand the "GitHub Actions / Run doxygen" warnings, is that a tools problem?

The doxygen action will report warnings for all incorrectly formatted doxygen annotations which is what you're seeing here.  The check itself will only run however if src/include/ is modified, so most PRs do not see these warnings.

Without having looked at what the remaining warnings are we did have an exercise to remove them all earlier this year, obviously there's still work to do there.

**Review by johannlombardi — APPROVED** [review]

**Comment by johannlombardi** [comment]
Please merge master.

**Comment by ashleypittman** [comment]
Did you mean to close this branch as well?

**Pull request closed without merging**
