### PR TITLE
daos-3945 DaosCoreTest Failed to stop servers

### PR DESCRIPTION
**Pull request by GitHuaKuang**
Adding extra debug for diagnosing.
Skip-test:true

Change-Id: Ia285e43ee7ea6ebfc903c0b2ab598e7113e476d7
Signed-off-by: Hua Kuang <hua.kuang@intel.com>

### CODE REVIEW

**Comment by johannlombardi** [comment]
What is the status of this PR?
On a side node, the commit message does not comply to our standards.

**Comment by GitHuaKuang** [comment]
@johannlombardi @daos-stack/daos-gatekeeper This is a debug enhancement PR  trying to help capturing more helpful debug info for this CI server stopping failure, currently almost zero useful info from the logs.

It's been approved and skipped test due to only added several lines of logs. Please help land it if it's OK, so we can start capturing logs for next step.

**Comment by kjacque** [comment]
@GitHuaKuang I think Johann is saying you need to update the commit message to get landed. It isn't correct for [our commit message format](https://wiki.hpdd.intel.com/display/DC/Commit+Comments). Plus the top line doesn't indicate that this is debugging logic, not a full fix.

I believe you can either amend the real message in git or update the title/description of this PR and the gatekeeper can use that.

**Comment by GitHuaKuang** [comment]
Thanks, Kris, Johann for reminding about the commit message.

**Pull request merged**
