### PR TITLE
DAOS-4926 il: Update IL setup process.

### PR DESCRIPTION
**Pull request by ashleypittman**
Complete rewrite of code to attach to files under the IL

Handle multiple pools and containers correctly.
Do not call daos_init() until a file of interest is found
Downgrade most logging from INFO to DEBUG.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
I need to do more testing on this yet, but it's working if you want to use it for multiple pools.

**Review by jolivier23 — DISMISSED** [review]

**Review by mchaarawi — APPROVED** [review]
maybe should include a commit pragma to run the IL testing that are done on weekends before this lands?

**Comment by ashleypittman** [comment]
> maybe should include a commit pragma to run the IL testing that are done on weekends before this lands?

There are already some IL tests run on PRs, and the weekly tests only run with one container so I don't think it'll make a difference.  I do have another PR already that enables them as part of DAOS-5857 so I'll rebase that onto this once it merges, and I'll check the weekly tests on Monday.

@daos-stack/daos-gatekeeper three test failures, all in OSA, DAOS-6061 and possibly others.

**Comment by ashleypittman** [comment]
I ran some more tests on this and found a deadlock where daos_debug_init() was opening files so I've rebased and resolved that issue.

**Review by jolivier23 — DISMISSED** [review]

**Comment by ashleypittman** [comment]
This should be ready but will conflict with https://github.com/daos-stack/daos/pull/3885 so can that one land first this time?

**Comment by ashleypittman** [comment]
Failures are leap-15 related, DAOS-6022, DAOS-6047, and what I think is DAOS-6107.  This patch previously had approvals and has only been rebased due to conflicts, please re-review.

**Pull request merged**
