### PR TITLE
DAOS-13519 control: Control metadata path invalid if no bdevs in cfg

### PR DESCRIPTION
**Pull request by tanabarr**
Control metadata path should not be specified in a server config file
if no bdev tiers exist.

Required-githooks: true

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by knard-intel — DISMISSED** [review]
Looks good to me

**Review by kjacque — DISMISSED** [review]

**Comment by Michael-Hennecke** [comment]
My take on this is that we should disallow `control_meta` when no **bdev_role** is present (e.g. when we are not in MD-on-SSD mode), not only when no **bdev** is present (which would allow it in "ephemeral" mode with a DRAM class and an NVMe class that does not specify bdev_roles).
And vice-versa, we should **require** `control_meta` when bdev_roles **are** present.

**Review by knard-intel — DISMISSED** [review]

**Comment by tanabarr** [comment]
> My take on this is that we should disallow `control_meta` when no **bdev_role** is present (e.g. when we are not in MD-on-SSD mode), not only when no **bdev** is present (which would allow it in "ephemeral" mode with a DRAM class and an NVMe class that does not specify bdev_roles). And vice-versa, we should **require** `control_meta` when bdev_roles **are** present.
> 
> (I did not check what the code actually does, just went by the title of the PR...)

Yes, this is in line with what is currently implemented on the vos_on_blob branch. @Michael-Hennecke can you please approve the PR then we can get it landed, thanks.

**Review by knard-intel — APPROVED** [review]

**Review by Michael-Hennecke — APPROVED** [review]

**Comment by tanabarr** [comment]
CI test failures attributable to https://daosio.atlassian.net/browse/DAOS-12883 (https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12222/8/tests/)

**Comment by tanabarr** [comment]
@daos-stack/daos-gatekeeper can we please land this PR?

**Comment by ashleypittman** [comment]
> @daos-stack/daos-gatekeeper can we please land this PR?

The gatekeepers get notified when you add them as a reviewers, there's no need to chase immediately as we'll already have the email/notification.

**Comment by tanabarr** [comment]
> > @daos-stack/daos-gatekeeper can we please land this PR?
> 
> The gatekeepers get notified when you add them as a reviewers, there's no need to chase immediately as we'll already have the email/notification.

ok, thanks for that, duly noted

**Pull request merged**
