### PR TITLE
DAOS-623 cq: skip jenkinsfile hook if URL not accessible

### PR DESCRIPTION
**Pull request by daltonbohning**
Skip-test: true
Skip-tests: true

build.hpdd.intel.com is not accessible externally. Ideally githooks should not use network calls at all but workaround this for now by skipping.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by daltonbohning** [comment]
Skipped functional test to save CI resources:
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-14121/1/pipeline

**Comment by daltonbohning** [comment]
> Honestly, this isn't something that should be in the repo anyway as it's useless for external developers and enabled-by-default. We have the option for user-provided githooks and few people edit the Jenkinsfile so this should be something that is documented internally and added as an attachment to a Jira discussion page for people who want to opt-into it.

If we ever move to a Jenkins model that is accessible by external devs, we might have external devs touch the Jenkinsfile. If we do want such a check for Jenkinsfile, it might as well be automated if feasible.

**Comment by brianjmurrell** [comment]
> Honestly, this isn't something that should be in the repo anyway as it's useless for external developers

Not true.  It's useful to anyone who has access to a[ny] Jenkins instance.  They just need to set the `$HOST` variable to a different Jenkins instance hostname.

> and enabled-by-default.

But only if you edit the `Jenkinsfile`.  As you say, few people do that so few people should be affected.  Just to keep it in perspective.

**Review by brianjmurrell — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by daltonbohning** [comment]
Force landing because tests were skipped to save CI resources. This only modified the githooks

**Pull request merged**
