### PR TITLE
DAOS-5524 tests: Add --use_cfg option

### PR DESCRIPTION
**Pull request by mallove79**
Add --use_cfg option to test_group_np_cli client in order to enable
cart_nopmix_multictx_one_node test.

Ticket description:
  Add --use_cfg, which accepts 0 or 1. If not set, assume true (so majority of
  tests would not be impacted), and for nopmix_launcher_one_node test – pass it as
  --use_cfg=0.

  Per Alexander Oganezov: We use the same test_group_np_cli in other tests as
  well, in all other tests it was assuming use_cfg=true was set, but this
  particular test is specifically executing code-path where use_cfg would be ==
  false; since the value is hard-coded to true now in PR-3139, it will use wrong
  code path and therefore fails.

  See use_cfg parameter to tc_cli_start_basic() here:
    https://github.com/daos-stack/daos/blob/emallovx_DAOS-4582/src/cart/src/test/tests_common.h#L371

Skip-build-leap15-rpm: true
Skip-build-ubuntu-clang: true
Skip-build-leap15-icc: true
Skip-coverity-test: true
Skip-checkpatch: true
Quick-build: true
Test-tag: cart
Skip-func-test-leap15: true
Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true
Skip-func-hw-test-large: true

Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>

### CODE REVIEW

**Comment by sylviachanoiyee** [comment]
When it is ready for review after going through CI, leave comment here with JIRA ticket (if there is any known failures). Thanks!

**Comment by mallove79** [comment]
> When it is ready for review after going through CI, leave comment here with JIRA ticket (if there is any known failures). Thanks!

[Two failures](https://build.hpdd.intel.com/job/daos-stack/job/daos/view/change-requests/job/PR-3778/5/) accounted for in [DAOS-5972](https://jira.hpdd.intel.com/browse/DAOS-5972) `punch_test failed with heartbeat timeout and group update failed`.

**Comment by sylviachanoiyee** [comment]
Do you know why travis is failing?

**Comment by mallove79** [comment]
> Do you know why travis is failing?

From @zjf2012:

_https://github.com/daos-stack/daos/pull/3603 should be caused by unstable maven central repo or network. I believe the issue should be gone in a retry. I’ve set maven to use google mirror of maven central repo in the dockerfiles. But it seems that maven still tried to download artifacts from the maven central repo. I just created a ticket to fix it._

**Comment by mallove79** [comment]
> Can you increase the num of occurrence and attach logs to DAOS-5972?

Re `failed with heartbeat` errors ([DAOS-5972](https://jira.hpdd.intel.com/browse/DAOS-5972)):  Are you looking for local dev env logs or CI/Jenkins logs?  Which occurrences do you want increased?

**Review by sylviachanoiyee — APPROVED** [review]

**Comment by mallove79** [comment]
> > Can you increase the num of occurrence and attach logs to DAOS-5972?
> 
> Re `failed with heartbeat` errors ([DAOS-5972](https://jira.hpdd.intel.com/browse/DAOS-5972)): Are you looking for local dev env logs or CI/Jenkins logs? Which occurrences do you want increased?

👍  I incremented _Occurrences_ and attached CI/Jenkins logs to [DAOS-5972](https://jira.hpdd.intel.com/browse/DAOS-5972).

**Review by frostedcmos — APPROVED** [review]

**Pull request merged**
