### PR TITLE
DAOS-7323 tests: add aggregation and punch test

### PR DESCRIPTION
**Pull request by wangdi1**
Add update punch aggregation then degrade fetch test.

Signed-off-by: Di Wang <di.wang@intel.com>

### CODE REVIEW

**Review by liuxuezhao — DISMISSED** [review]

**Comment by wangdi1** [comment]
>@wangdi1 , I only find deagrade ec tests up to degrade23 in the jenkins results. Looks like 24-28 did not run for some reason.

Ah, let me retrigger

**Comment by jolivier23** [comment]
> > @wangdi1 , I only find deagrade ec tests up to degrade23 in the jenkins results. Looks like 24-28 did not run for some reason.
> 
> Ah, let me retrigger

Looks like the yaml file specifies 8-23 explicitly for this test so re-triggering doesn't help.

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Update the test yaml to run the new tests

**Review by jolivier23 — APPROVED** [review]

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Conflict needs resolving

**Review by liuxuezhao — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Pull request merged**
