### PR TITLE
DAOS-12392 test: Allow test_core_files to pass in launch.py

### PR DESCRIPTION
**Pull request by mjean308**
A change was made to fail launch.py if any test passed but created a core file.  This change also had the side effect of failing launch if test_core_files ran correctly (i.e. created and processed a core file).  This PR will allow launch.py to to PASS if test_core_files* correctly creates and processes a corefile.

Quick-build: true
Skip-unit-tests: true
Test-tag: pr test_core_files

Required-githooks: true

Signed-off-by: Maureen Jean <maureen.jean@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by brianjmurrell** [comment]
FWIW:

If you are just looking for the quickest functional testing results, which:

```
Quick-build: true
Skip-unit-tests: true
```

seems to imply, `Quick-functional: true` is even quicker as it skips all of the pre-build steps such as linting etc.

**Review by phender — APPROVED** [review]

**Review by phender — CHANGES_REQUESTED** [review]
We also need to fix quoting on this command:
```
2023/01/18 03:52:59 DEBUG                      run_local: Running on wolf-105vm1: rpm -q --qf %{name} %{version} %{release} %{epoch} libfabric
2023/01/18 03:52:59 DEBUG                      run_local:   wolf-105vm1 (rc=3):
2023/01/18 03:52:59 DEBUG                      run_local:     package %{version} is not installed
2023/01/18 03:52:59 DEBUG                      run_local:     package %{release} is not installed
2023/01/18 03:52:59 DEBUG                      run_local:     package %{epoch} is not installed
2023/01/18 03:52:59 DEBUG                      run_local:     libfabric
```

**Comment by ashleypittman** [comment]
I think this a regression from before https://github.com/daos-stack/daos/commit/a63d9da754ec569b3eb0fe68f01c7c73535a52cb landed, previously the code was using lists for passing options, now it's using space delimitated stings which are known to be error prone, the kernel takes a list (via subprocess.run) and now you're adding in escape characters so that when it's converted from a string to a list the representation is correct yet if it was a list to begin with there would be nothing to escape.

**Review by phender — APPROVED** [review]
Core file processing in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11231/11/artifact/Functional%20on%20EL%208/launch/functional_on_el_8/job.log (06:56:52-06:57:53) looks good.  Expected stacktraces generated:

- https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11231/11/artifact/Functional%20on%20EL%208/harness/core_files.py/stacktraces.wolf-100vm3/core.daos_engine.1674068192.19045.stacktrace/*view*/
- https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-11231/11/artifact/Functional%20on%20EL%208/harness/core_files.py/stacktraces.wolf-100vm1/core.gdb.harness.advanced/*view*/

**Review by ashleypittman — APPROVED** [review]

**Review by daltonbohning — APPROVED** [review]

**Comment by mjean308** [comment]
There were two failures:
https://daosio.atlassian.net/browse/DAOS-12421 - daos_test/rebuild.py
https://daosio.atlassian.net/browse/DAOS-12420 - orterun segfault; Test Passed but corefile was found in launch

**Pull request merged**
