### PR TITLE
DAOS-6282 Daos_test rebuild unittest dmg pool exclude -i hardcoded

### PR DESCRIPTION
**Pull request by GitHuaKuang**
Removed all hardcoded "-i" for dmg pool command in daos_test

Change-Id: If6297d8b6514b714f85b8eaf393b6f6570893779
Signed-off-by: Hua Kuang <hua.kuang@intel.com>

### CODE REVIEW

**Comment by GitHuaKuang** [comment]
@dinghwah @berserk-fury It passed all checks(and the dmg pool exclude cmds) with -i removed in daos_test.

**Review by dinghwah — APPROVED** [review]
Functional tests of daos_test_rebuild Passed, resolved the original issue.

**Review by berserk-fury — APPROVED** [review]

**Comment by GitHuaKuang** [comment]
@daos-stack/daos-gatekeeper I hope this one is ready to land.

**Comment by mjmac** [comment]
Verified that the tests ran: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4243/4/testReport/(root)/DaosCoreTestRebuild/

Wanted to double-check, because a number of tests have been removed from the normal PR runs.

**Pull request merged**
