### PR TITLE
DAOS-8926 test: Address flaky Rebuild/basic.py test failures.

### PR DESCRIPTION
**Pull request by rpadma2**
Skip-func-test-el7: false
Skip-func-test-leap15: false
Test-tag: test_simple_rebuild test_multipool_rebuild
Test-repeat: 20

Summary:
- Check whether rebuild started on first pool alone wait_for_rebuild(True). Since the test uses small data the rebuild can be completed on other pools while we iterate all pools. Just check the start on the first pool and see whether rebuild completed on other pools later with wait_for_rebuild(False) call.

Signed-off-by: rpadma2 <ravindran.padmanabhan@intel.com>

### CODE REVIEW

**Comment by rpadma2** [comment]
After the changes, the test was run 10 times. Don't see any failures.

**Review by dinghwah — DISMISSED** [review]
LGTM

**Review by phender — CHANGES_REQUESTED** [review]
The issue only occurs infrequently when checking for rebuild to start on multiple pools, but rebuild is always detected on the first pool.  Instead of removing checking for rebuild to start I'd recommend limiting the rebuild start check to just the first pool:
```
        # Wait for recovery to start on the first pool
        self.pool[0].wait_for_rebuild(True)
```

**Review by shimizukko — DISMISSED** [review]

**Comment by rpadma2** [comment]
> The issue only occurs infrequently when checking for rebuild to start on multiple pools, but rebuild is always detected on the first pool. Instead of removing checking for rebuild to start completely I'd recommend limiting the rebuild start check to just the first pool:
> 
> ```
>         # Wait for recovery to start on the first pool
>         self.pool[0].wait_for_rebuild(True)
> ```

Hmm... That's seems to be not correct... Is it not? How do we know if rebuild really happened on other pools... Maybe have a thread to check the the rebuild in parallel on all pools. Let me think more in this area.

**Comment by rpadma2** [comment]
Manual testing seems to show tests pass with my changes alone. Let's wait for the CI testing to complete. I have added tests to run 20 times... Hope it will throw some light on the issue.

**Comment by rpadma2** [comment]
The Rebuild/basic.py tests passed 8 iterations before the job was killed due to extensive usage of CI resources.

I think the changes are resolving the issues. Going to request for re-view and we should be merging the changes to master and 2.0.

**Review by dinghwah — COMMENTED** [review]
On line97, and 98. The rebuild timing is critical, shouldn't we choose the very last pool to start?

**Review by phender — APPROVED** [review]

**Comment by rpadma2** [comment]
> The rebuild timing is critical, shouldn't we choose the very last pool to start?

@phender suggestion was to use the first pool. See the previous comments. I am ok with anything...

**Review by dinghwah — APPROVED** [review]
LGTM

**Comment by rpadma2** [comment]
Hi @daos-stack/daos-gatekeeper , This PR is ready for merge. Thanks,

**Review by shimizukko — APPROVED** [review]

**Pull request merged**
