### PR TITLE
DAOS-16208 test: Update control/dmg_scale.py to run on CI

### PR DESCRIPTION
**Pull request by shimizukko**
Update control/dmg_scale.py to run on CI. Currently it’s a manual test, so move it to hw,medium.

Skip-unit-tests: true
Skip-fault-injection-test: true
Skip-func-hw-test-medium-md-on-ssd: false
Test-tag: test_dmg_scale

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by shimizukko** [comment]
@daltonbohning I'm trying to run dmg_scale.py in CI, but noticed that the script fails when it tries to create the 49th pool due to DER_NOSPACE. I can change the number to 48 or something, but then the person who executes this test might forget to change it back to 49 when they run it on Aurora. What do you think we should do? Keep this as manual test and not run it in CI?

**Comment by daltonbohning** [comment]
> @daltonbohning I'm trying to run dmg_scale.py in CI, but noticed that the script fails when it tries to create the 49th pool due to DER_NOSPACE. I can change the number to 48 or something, but then the person who executes this test might forget to change it back to 49 when they run it on Aurora. What do you think we should do? Keep this as manual test and not run it in CI?

1. Could we just create 48 pools on Aurora as well?
2. Do we know why we run out of space, or if there is a way to know upfront how many pools could be created?

**Comment by shimizukko** [comment]
> > @daltonbohning I'm trying to run dmg_scale.py in CI, but noticed that the script fails when it tries to create the 49th pool due to DER_NOSPACE. I can change the number to 48 or something, but then the person who executes this test might forget to change it back to 49 when they run it on Aurora. What do you think we should do? Keep this as manual test and not run it in CI?
> 
> 1. Could we just create 48 pools on Aurora as well?
> 2. Do we know why we run out of space, or if there is a way to know upfront how many pools could be created?

hmm, it looks like the available storage size differs based on which cluster it gets assigned in CI (I was able to create 48 pools before, but now only 44). Maybe we shouldn't run this in CI?
I talked to the developer and there's no easy way to know upfront how many pools could be created. For each pool, fixed and variable/growing size metadata are generated.

**Comment by daltonbohning** [comment]
> hmm, it looks like the available storage size differs based on which cluster it gets assigned in CI (I was able to create 48 pools before, but now only 44). Maybe we shouldn't run this in CI? I talked to the developer and there's no easy way to know upfront how many pools could be created. For each pool, fixed and variable/growing size metadata are generated.

Let's just keep this as manual for now and revisit if needed

**Pull request closed without merging**
