### PR TITLE
DAOS-8476 test: Remove Highest Aggregation Epoch check from io_aggreg…

### PR DESCRIPTION
**Pull request by shimizukko**
…ation.py

Highest Aggregation Epoch field was removed from daos
container query, so check if the aggregation is triggered
by only looking at the free space.

Skip-unit-tests: true
Test-tag: ioaggregation
Signed-off-by: Makito Kano <makito.kano@intel.com>

### CODE REVIEW

**Review by saurabhtandan — COMMENTED** [review]
@shimizukko , as @kccain mentioned in the email thread, is it not possible we can utilize the snapshot count instead of highest epoch after the snapshot is deleted?

**Comment by shimizukko** [comment]
I manually tested to destroy snapshot and list-snap is empty as expected.
```
[root@wolf-32 ~]# daos container destroy-snap --epc=360370129223811072 mkp1 mkc1
[root@wolf-32 ~]# daos container list-snap mkp1 mkc1
Container's snapshots :
no snapshots
```
I also verified that the size used go down soon after destroying the snapshot.
```
[root@wolf-32 daos]# dmg pool list --verbose
Label UUID                                 SvcReps SCM Size SCM Used SCM Imbalance NVME Size NVME Used NVME Imbalance Disabled
----- ----                                 ------- -------- -------- ------------- --------- --------- -------------- --------
mkp1  e41d27ad-13a4-4cde-a0d0-4bfd83f8ac85 0       10 GB    2.2 GB   87%           0 B       0 B       0%             0/8

[root@wolf-32 daos]# dmg pool list --verbose
Label UUID                                 SvcReps SCM Size SCM Used SCM Imbalance NVME Size NVME Used NVME Imbalance Disabled
----- ----                                 ------- -------- -------- ------------- --------- --------- -------------- --------
mkp1  e41d27ad-13a4-4cde-a0d0-4bfd83f8ac85 0       10 GB    1.1 GB   87%           0 B       0 B       0%             0/8
```
Is this what you mean? Is there any relationship between the aggregation timing and snapshot destroy? e.g., snapshot continues to appear in list-snap until aggregation completes. If not, then not sure why we need to do this other than for testing the list-snap feature.

**Comment by saurabhtandan** [comment]
> I manually tested to destroy snapshot and list-snap is empty as expected.
> 
> ```
> [root@wolf-32 ~]# daos container destroy-snap --epc=360370129223811072 mkp1 mkc1
> [root@wolf-32 ~]# daos container list-snap mkp1 mkc1
> Container's snapshots :
> no snapshots
> ```
> 
> I also verified that the size used go down soon after destroying the snapshot.
> 
> ```
> [root@wolf-32 daos]# dmg pool list --verbose
> Label UUID                                 SvcReps SCM Size SCM Used SCM Imbalance NVME Size NVME Used NVME Imbalance Disabled
> ----- ----                                 ------- -------- -------- ------------- --------- --------- -------------- --------
> mkp1  e41d27ad-13a4-4cde-a0d0-4bfd83f8ac85 0       10 GB    2.2 GB   87%           0 B       0 B       0%             0/8
> 
> [root@wolf-32 daos]# dmg pool list --verbose
> Label UUID                                 SvcReps SCM Size SCM Used SCM Imbalance NVME Size NVME Used NVME Imbalance Disabled
> ----- ----                                 ------- -------- -------- ------------- --------- --------- -------------- --------
> mkp1  e41d27ad-13a4-4cde-a0d0-4bfd83f8ac85 0       10 GB    1.1 GB   87%           0 B       0 B       0%             0/8
> ```
> 
> Is this what you mean? Is there any relationship between the aggregation timing and snapshot destroy? e.g., snapshot continues to appear in list-snap until aggregation completes. If not, then not sure why we need to do this other than for testing the list-snap feature.

Yeah this is what I meant and I am also not sure if it is directly related to aggregation. May be @kccain or @NiuYawei can tell us if snapshot destroy is in anyway related to aggregation and we can use snapshot count to verify if aggregation completed?

**Comment by kccain** [comment]
> use snapshot count to verify if aggregation completed?

The snapshot count reported by container open and container query in the struct daos_cont_info_t.ci_nsnapshots gets updated immediately when the snapshot destroy is processed. I do not believe this snapshot count value can be used to verify that any associated aggregation (that may occur as a result of the snapshot destroy) has completed. Perhaps @NiuYawei can comment on the relationship between snapshot destroy and any subsequent aggregation that may happen.

**Comment by shimizukko** [comment]
I'm not getting any feedback. Can I get approval if there's no issue with the test script?

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Review by dinghwah — APPROVED** [review]
LGTM

**Comment by sylviachanoiyee** [comment]
@shimizukko , could you document this test at
https://daosio.atlassian.net/wiki/spaces/DAOS/pages/11017453618/Aggregation+Test+Plan
?

**Pull request merged**
