### PR TITLE
DAOS-10599 test: Fix bullseye report (#9114)

### PR DESCRIPTION
**Pull request by dinghwah**
Update COVFILE env var for dfuse test to find location of cov file when bullseye is turned on.
Update base.py to exclude test files.

Signed-off-by: Ding Ho ding-hwa.ho@intel.com

### CODE REVIEW

**Review by daltonbohning — APPROVED** [review]
Clean cherry pick?

**Comment by dinghwah** [comment]
3 unit test failures on NLT were not related to this commit.

**Comment by sylviachanoiyee** [comment]
Can we get a rerun with pr and daily testlist to get a report for 2.2?

**Comment by dinghwah** [comment]
1 failure in functional test is due to a known issue DAOS-10739.
Ready to land (cherry-pick from master).

**Comment by phender** [comment]
> 1 failure in functional test is due to a known issue DAOS-10739. Ready to land (cherry-pick from master).

@dinghwah this known failure prevented the Functional HW test stages from running.  Is that required for confirmation of these changes?  If so could you re-run and include the `Allow-unstable-test: true` commit pragma to ensure the HW test stages are run.

**Comment by dinghwah** [comment]
The failures in functional test are irrelated to this PR, and failure in the Jenkins pipeline final stage will be handled by DAOS-11167, which is not related to this cherry-pick.
Ready to merge.

**Pull request merged**
