### PR TITLE
DAOS-9865 test: Increase test timeouts to match pool destroy

### PR DESCRIPTION
**Pull request by phender**
Increase the avocado test timeout and timeout for tearDown to account
for the dmg pool destroy timeout of 3 minutes.  If a test times out
before the dmg pool destroy command returns a status the harness is not
able to take the corrective actions to prevent one test failure from
affecting the next test execution.

Skip-unit-tests: true
Test-tag: pr daily_regression full_regression

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Review by mjean308 — APPROVED** [review]

**Review by shimizukko — APPROVED** [review]
How should we determine the timeout to set in the yaml? I see this at the beginning of the teardown.
`*** TEARDOWN called after test completion: elapsed time: 119.71012711524963 seconds ***`
Should we use this?

**Comment by phender** [comment]
> How should we determine the timeout to set in the yaml? I see this at the beginning of the teardown. `*** TEARDOWN called after test completion: elapsed time: 119.71012711524963 seconds ***` Should we use this?

**Comment by phender** [comment]
Closed accidently

**Comment by phender** [comment]
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5 encountered 20 failures:

- [Functional on CentOS 8 / 3-./rebuild/cascading_failures.py:RbldCascadingFailures.test_cascading_failures](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_rebuild/RbldCascadingFailures/Test___Functional_on_CentOS_8___3___rebuild_cascading_failures_py_RbldCascadingFailures_test_cascading_failures_run_container_hosts_pool_rebuild_server_config_servers_a2e3/)
  - known issue https://daosio.atlassian.net/browse/DAOS-10051
- [Functional Hardware Small / 8-./control/config_generate_output.py:ConfigGenerateOutput.test_net_class](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_control/ConfigGenerateOutput/Test_Hardware___Functional_Hardware_Small___8___control_config_generate_output_py_ConfigGenerateOutput_test_net_class_run_hosts_pool_04a7/)
  - known issue https://daosio.atlassian.net/browse/DAOS-10049
- [Functional Hardware Small / 6-./control/config_generate_run.py:ConfigGenerateRun.test_config_generate_run](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_control/ConfigGenerateRun/Test_Hardware___Functional_Hardware_Small___6___control_config_generate_run_py_ConfigGenerateRun_test_config_generate_run_run_config_generate_params_ethernet_hosts_pool_setup_a47a/)
  - known issue https://daosio.atlassian.net/browse/DAOS-10050
- [Functional Hardware Small / 1-./daos_vol/bigio.py:DaosVol.test_daos_vol_bigio](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_daos_vol/DaosVol/Test_Hardware___Functional_Hardware_Small___1___daos_vol_bigio_py_DaosVol_test_daos_vol_bigio_run_container_daos_vol_tests_dfuse_hosts_pool_server_config_servers_3f53/)
  - https://daosio.atlassian.net/browse/DAOS-6654
- [Functional Hardware Medium /  2-./osa/dmg_negative_test.py:OSADmgNegativeTest.test_osa_dmg_cmd_with_extend](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_osa/OSADmgNegativeTest/Test_Hardware___Functional_Hardware_Medium___2___osa_dmg_negative_test_py_OSADmgNegativeTest_test_osa_dmg_cmd_with_extend_run_container_properties_extra_servers_hosts_pool_server_config_servers_0_1_test_sequence_fd34/)
  - known issue https://daosio.atlassian.net/browse/DAOS-9970
- [Functional Hardware Medium /  5-./osa/offline_drain.py:OSAOfflineDrain.test_osa_offline_drain_multiple_pools](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_osa/OSAOfflineDrain/Test_Hardware___Functional_Hardware_Medium___5___osa_offline_drain_py_OSAOfflineDrain_test_osa_offline_drain_multiple_pools_run_aggregation_akeys_single_checksum_container_dkeys_hosts_ior_clientslots_iorflags_mdtest_client_processes_wr_size_32K_pool_pool_capacity_rebuild_record_1KB_server_config_servers_0_1_server_manager_setup_snapshot_test_obj_class_test_ranks_4a01/)
  - https://daosio.atlassian.net/browse/DAOS-10058
- [Functional Hardware Medium / 05-./osa/offline_reintegration.py:OSAOfflineReintegration.test_osa_offline_reintegration_oclass](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_osa/OSAOfflineReintegration/Test_Hardware___Functional_Hardware_Medium___05___osa_offline_reintegration_py_OSAOfflineReintegration_test_osa_offline_reintegration_oclass_run_agent_config_transport_config_aggregation_blank_node_checksum_container_dmg_hosts_ior_clientslots_iorflags_loop_test_mdtest_client_processes_wr_size_32K_pool_pool_capacity_rebuild_server_config_servers_0_1_setup_snapshot_test_obj_class_test_rf_timeouts_31b3/)
  - known issue https://daosio.atlassian.net/browse/DAOS-9277
- [Functional Hardware Medium / 10-./osa/offline_reintegration.py:OSAOfflineReintegration.test_osa_offline_reintegrate_with_less_pool_space](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_osa/OSAOfflineReintegration/Test_Hardware___Functional_Hardware_Medium___10___osa_offline_reintegration_py_OSAOfflineReintegration_test_osa_offline_reintegrate_with_less_pool_space_run_agent_config_transport_config_aggregation_blank_node_checksum_container_dmg_hosts_ior_clientslots_iorflags_loop_test_mdtest_client_processes_wr_size_32K_pool_pool_capacity_rebuild_server_config_servers_0_1_setup_snapshot_test_obj_class_test_rf_timeouts_31b3/)
  - known issue https://daosio.atlassian.net/browse/DAOS-9788
- [Functional Hardware Medium / 1-./rebuild/no_cap.py:RbldNoCapacity.test_rebuild_no_capacity](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_rebuild/RbldNoCapacity/Test_Hardware___Functional_Hardware_Medium___1___rebuild_no_cap_py_RbldNoCapacity_test_rebuild_no_capacity_run_container_hosts_pool_rebuild_server_config_servers_0_1_c58d/)
  - known issue https://daosio.atlassian.net/browse/DAOS-9524
- [Functional Hardware Large / 1-./deployment/io_sys_admin.py:IoSysAdmin.test_io_sys_admin](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_deployment/IoSysAdmin/Test_Hardware___Functional_Hardware_Large___1___deployment_io_sys_admin_py_IoSysAdmin_test_io_sys_admin_run_container_container_1_container_2_container_3_container_acl_dcp_client_processes_dfuse_dmg_storage_hdf5_vol_hosts_ior_largefilecount_mdtest_pool_pool_1_pool_2_pool_3_server_config_servers_0_1_1252/)
  - known issue https://daosio.atlassian.net/browse/DAOS-9218
- [Functional Hardware Large / 2-./erasurecode/aggregation.py:EcodAggregationOff.test_ec_aggregation_default](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_erasurecode/EcodAggregationOff/Test_Hardware___Functional_Hardware_Large___2___erasurecode_aggregation_py_EcodAggregationOff_test_ec_aggregation_default_run_container_hosts_ior_client_processes_iorflags_objectclass_pool_server_config_servers_0_1_setup_50cf/)
  - known issue https://daosio.atlassian.net/browse/DAOS-9821
- [Functional Hardware Large / 3-./erasurecode/offline_rebuild_aggregation.py:EcodAggregationOffRebuild.test_ec_offline_agg_during_rebuild](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_erasurecode/EcodAggregationOffRebuild/Test_Hardware___Functional_Hardware_Large___3___erasurecode_offline_rebuild_aggregation_py_EcodAggregationOffRebuild_test_ec_offline_agg_during_rebuild_run_container_hosts_ior_client_processes_iorflags_objectclass_pool_server_config_servers_0_1_setup_2f1d/)
  - known issue https://daosio.atlassian.net/browse/DAOS-9821
- [Functional Hardware Large / 2-./erasurecode/restart.py:EcodServerRestart.test_ec_restart_after_agg](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_erasurecode/EcodServerRestart/Test_Hardware___Functional_Hardware_Large___2___erasurecode_restart_py_EcodServerRestart_test_ec_restart_after_agg_run_container_hosts_ior_client_processes_data_percentage_iorflags_objectclass_pool_server_config_servers_0_1_setup_cf1b/)
  - known issue https://daosio.atlassian.net/browse/DAOS-9821
- [Functional Hardware Large / 1-./ior/hard_rebuild.py:EcodIorHardRebuild.test_ec_ior_hard_online_rebuild](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_ior/EcodIorHardRebuild/Test_Hardware___Functional_Hardware_Large___1___ior_hard_rebuild_py_EcodIorHardRebuild_test_ec_ior_hard_online_rebuild_run_container_hosts_servers_6_server_ior_client_processes_iorflags_objectclass_pool_server_config_0_1_setup_abcf/)
  - timeout in teardown; not seen in 
- [Functional Hardware Large / 1-./ior/intercept_multi_client.py:IorInterceptMultiClient.test_ior_intercept_multi_client](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_ior/IorInterceptMultiClient/Test_Hardware___Functional_Hardware_Large___1___ior_intercept_multi_client_py_IorInterceptMultiClient_test_ior_intercept_multi_client_run_container_dfuse_hosts_ior_client_processes_iorflags_ssf_transfersize_blocksize_512B_pool_server_config_servers_d319/)
  - 
- [Functional Hardware Large / 2-./ior/intercept_multi_client.py:IorInterceptMultiClient.test_ior_intercept_multi_client](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_ior/IorInterceptMultiClient/Test_Hardware___Functional_Hardware_Large___2___ior_intercept_multi_client_py_IorInterceptMultiClient_test_ior_intercept_multi_client_run_container_dfuse_hosts_ior_client_processes_iorflags_ssf_transfersize_blocksize_1K_pool_server_config_servers_0ff1/)
  - 
- [Functional Hardware Large / 3-./ior/intercept_multi_client.py:IorInterceptMultiClient.test_ior_intercept_multi_client](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_ior/IorInterceptMultiClient/Test_Hardware___Functional_Hardware_Large___3___ior_intercept_multi_client_py_IorInterceptMultiClient_test_ior_intercept_multi_client_run_container_dfuse_hosts_ior_client_processes_iorflags_ssf_transfersize_blocksize_4K_pool_server_config_servers_54fe/)
  - 
- [Functional Hardware Large / 4-./ior/intercept_multi_client.py:IorInterceptMultiClient.test_ior_intercept_multi_client](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_ior/IorInterceptMultiClient/Test_Hardware___Functional_Hardware_Large___4___ior_intercept_multi_client_py_IorInterceptMultiClient_test_ior_intercept_multi_client_run_container_dfuse_hosts_ior_client_processes_iorflags_ssf_transfersize_blocksize_1M_pool_server_config_servers_6bd4/)
  - new issue https://daosio.atlassian.net/browse/DAOS-10075
- [Functional Hardware Large / 1-./nvme/io.py:NvmeIo.test_nvme_io](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_nvme/NvmeIo/Test_Hardware___Functional_Hardware_Large___1___nvme_io_py_NvmeIo_test_nvme_io_run_hosts_ior_pool_server_config_servers_7f34/)
  - https://daosio.atlassian.net/browse/DAOS-8032
- [Functional Hardware Large / 2-./server/metadata.py:ObjectMetadata.test_metadata_addremove](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-8122/5/testReport/junit/FTEST_server/ObjectMetadata/Test_Hardware___Functional_Hardware_Large___2___server_metadata_py_ObjectMetadata_test_metadata_addremove_run_container_hosts_ior_clientslots_iorreadflags_iorwriteflags_objectclass_pool_server_config_servers_0_1_timeouts_412b/)
  - https://daosio.atlassian.net/browse/DAOS-9078

**Pull request merged**
