### PR TITLE
DAOS-623 build: Improve the preprocessing steps (#9390)

### PR DESCRIPTION
**Pull request by jolivier23**
A couple of things were causing the preprocessing step in cart
to generate _structures_from_macros.h to be slow

1. The Preprocessor builder currently doesn't support building
   multiple items in parallel so it's better to call it one file
   at a time.
2. Use Command builders for intermediate steps so they don't need
   to be repeated
3. Pick to allow W503

Also cherry-picks this patch because it also modified extra.py so it made the other cherry-pick simpler:
DAOS-623 build: Update clang-format settings. (#9007)

Change Alignment to be closer to our established code.
Change spaces to tabs to avoid a clang bug.
Enable clang-format githook if clang-format 14.0.5 or greater is detected

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>
Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

### CODE REVIEW

**Comment by jolivier23** [comment]
The old code takes a long time and makes it painful to switch between branches.

**Review by ashleypittman — DISMISSED** [review]
Not all of this is necessary but I don't think it'd do any harm.

**Comment by ashleypittman** [comment]
Pushed a fix for the build issue.

**Comment by jolivier23** [comment]
> Not all of this is necessary but I don't think it'd do any harm.

yeah, it was more convenient to include it with all of the merge conflicts.   My main goal here is to speed up the build when switching between 2.2. and master

**Review by daltonbohning — COMMENTED** [review]
ftest LGTM

**Review by johannlombardi — APPROVED** [review]

**Pull request merged**
