### PR TITLE
DAOS-12408 cart: Split data_init()

### PR DESCRIPTION
**Pull request by frostedcmos**
- split data_init() into part that can be initialized multiple times and a part that should only be initialized once, such as mutex init

Required-githooks: true

Signed-off-by: Alexander A Oganezov <alexander.a.oganezov@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by soumagne — CHANGES_REQUESTED** [review]
I don't think that's correct to use pthread_once here ? it seems like either that init part should be done somewhere else or you should just be using a constructor/destructor?

**Comment by frostedcmos** [comment]
> I don't think that's correct to use pthread_once here ? it seems like either that init part should be done somewhere else or you should just be using a constructor/destructor?

Why is not not correct to use pthread_once? it's designed for things that have to be initialized only once. we use it in other parts of the stack. I agree we could use library constructor/destructor too, but that seems like a bit of an overkill.

**Comment by soumagne** [comment]
OK well "correct" was maybe not the right terminology but I just feel it's a bit messy :) since all you're doing here is trying to init some global data only once in the middle of other routines that are going be called concurrently... it's probably okay in practice but I feel like it would be much cleaner with a constructor/destructor and I don't see the code here that destroys the R/W lock (which should also be called only once).

**Comment by soumagne** [comment]
actually I see the code now that destroys the R/W lock. I take back what I said, it's probably okay, if you feel like it's good like that I won't oppose to it but I still feel like it's a bit convoluted.

**Review by jgmoore-or — APPROVED** [review]

**Review by soumagne — APPROVED** [review]

**Review by jgmoore-or — APPROVED** [review]

**Pull request merged**
