### PR TITLE
DAOS-9234 bio: cope with zero length IOV

### PR DESCRIPTION
**Pull request by NiuYawei**
To make bio_iod_bulk() supporting zero length IOVs, modified
iterate_biov() to move the IOV length check into callbacks.

Signed-off-by: Niu Yawei <yawei.niu@intel.com>

### CODE REVIEW

**Review by Nasf-Fan — APPROVED** [review]

**Comment by NiuYawei** [comment]
CI hit the known failure DAOS-9179

**Review by liuxuezhao — APPROVED** [review]

**Comment by NiuYawei** [comment]
Should we land it to 2.0? The ticket DAOS-9234 is marked as request_for_2.0.

**Review by jolivier23 — APPROVED** [review]

**Comment by jolivier23** [comment]
@NiuYawei the ticket doesn't have approved to merge field set.  Please re-add when ready.

**Comment by NiuYawei** [comment]
All tests passed one day ago, but not sure why the final report is still in "waiting for status to be reported"

**Comment by ashleypittman** [comment]
> All tests passed one day ago, but not sure why the final report is still in "waiting for status to be reported"

It is waiting for the coverity job which was recently disabled but is apparently still marked as required.

**Pull request merged**
