### PR TITLE
DAOS-623 ci: Parameters are in the params namespace

### PR DESCRIPTION
**Pull request by brianjmurrell**
… Not the env namespace.
Although referencing them in the env namespace seems to sometimes work,
sometimes it seems not to.

Fix some linting issues.

### CODE REVIEW

**Comment by brianjmurrell** [comment]
FWIW, we are getting instances of where the parameter does not seem to be getting propagated such as: https://jenkins-1.wolf.hpdd.intel.com:9090/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pipeline-lib-PR-425-weekly-testing/1/pipeline/79/ where we can see the value is empty (`null`):

image

I'm hopeful that fixing the namespace here helps that.

**Review by daltonbohning — APPROVED** [review]

**Comment by daltonbohning** [comment]
I'm not sure if new/existing, but it's concerning that the commit message uses
```
Test-tag: always_passes
```
But full_regression is running
```
[Functional Hardware Large] Running skipFunctionalTestStage: tags=full_regression,hw,large,
```
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-13941/2/pipeline/76

**Comment by daltonbohning** [comment]
As another datapoint, my PR here correctly ran with always_passes
https://github.com/daos-stack/daos/pull/13942

**Comment by daltonbohning** [comment]
The first run of this PR correctly used `always_passes`. So maybe because the second run was a restart and not a commit push?

**Comment by brianjmurrell** [comment]
> The first run of this PR correctly used `always_passes`. So maybe because the second run was a restart and not a commit push?

This where it's supposed to only run `always_passes` if it's a PR: https://github.com/daos-stack/daos/blob/aa531692f299fc56e4056afefa3df672b801b76a/Jenkinsfile#L274

Is [isPr()](https://github.com/daos-stack/pipeline-lib/blob/master/vars/isPr.groovy)  really returning false on _Restarted from <stage>_ retriggers?  that would be new (to me) behaviour if it is.

That said, are we really getting on the order of [82 failures](https://github.com/daos-stack/pipeline-lib/blob/master/vars/isPr.groovy) from weekly-testing?

**Comment by daltonbohning** [comment]
> Is [isPr()](https://github.com/daos-stack/pipeline-lib/blob/master/vars/isPr.groovy) really returning false on _Restarted from _ retriggers? that would be new (to me) behaviour if it is.

I'm not familiar enough to know, but I suspect the issue is something like that.

> That said, are we really getting on the order of [82 failures](https://github.com/daos-stack/pipeline-lib/blob/master/vars/isPr.groovy) from weekly-testing?

The weekly run on March 2 had 103 failures:
https://daosio.atlassian.net/wiki/spaces/DC/pages/11389534250/Master+Weekly+Test+Results

**Review by JohnMalmberg — APPROVED** [review]

**Comment by brianjmurrell** [comment]
@daos-stack/daos-gatekeeper This requires force-landing because it actually ran the weekly testing instead of skipping it and running only `always_passes` despite the `isPr()` condition for that.

**Pull request merged**
