### PR TITLE
Revert "DAOS-9146 engine: some fixes for daos server (#7490)"

### PR DESCRIPTION
**Pull request by jolivier23**
This reverts commit ccf0027af99ce803c3642787426f00f6d1924d19.

We suspect this is causing the regressions on master branch

https://daosio.atlassian.net/browse/DAOS-9354

### CODE REVIEW

**Review by wangshilong — APPROVED** [review]
I am ok to revert before we figure out root cause.

**Review by wangshilong — CHANGES_REQUESTED** [review]
I tried to revert this patch locally, but i could still reproduce the problem. so i think patch might be not root cause:

[root@daos1 daos]# dmg storage scan -i
ERROR: Errors:
  Hosts     Error
  -----     -----
  localhost spdk: code = 803 description = "SPDK binding failed, rc: 0, "

Hosts     SCM Total       NVMe Total
-----     ---------       ----------
localhost 0 B (0 modules) 0 B (0 controllers)
ERROR: dmg: 1 host had errors

**Comment by jolivier23** [comment]
@wangshilong Here is the last master run for test control (on all platforms)
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/6002/testReport/FTEST_control/

And here is the same set on your PR (centos 8 only)
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7764/5/testReport/FTEST_control/DaosControlConfigTest/

Maybe it's always been failing and something changed that just affects how the test interprets it but we probably need to revert to figure it out.   There are too many failures on master with this patch.

**Review by wangshilong — APPROVED** [review]

**Comment by johannlombardi** [comment]
@wangshilong fixed the errors.

**Pull request closed without merging**
