### PR TITLE
DAOS-5869 rebuild: Support rebuilding more shards than rebuilt targets

### PR DESCRIPTION
**Pull request by byron-marohn**
This patch enables rebuild to handle cases where placement remaps more shards than there are targets currently being rebuilt (occasionally happens during addition).

Implemented in a generic way that leverages stack buffers for performance and will allow rebuild/reint/drain/addition APIs to all return -DER_REC2BIG and be correctly re-tried with a larger buffer.

### CODE REVIEW

**Comment by byron-marohn** [comment]
Note that this patch is stacked on top of #3131 (and thus currently includes those changes until it is landed)

Please only review the last commit here. When 3131 is landed, I will merge master into this and the reclaim changes will disappear

**Review by NiuYawei — APPROVED** [review]

**Comment by rpadma2** [comment]
Please uncomment   @skipForTicket("DAOS-5869") and remove skipForTicket import from src/tests/ftest/osa/osa_online_extend.py and run the test as part of the PR. It will let us know whether the problem is resolved. Thanks. Ravi

**Review by rpadma2 — COMMENTED** [review]
image

> You don't need the skipForTicket in the import section (for osa_online_extend.py).

**Comment by byron-marohn** [comment]
This pull request is ready to re-review / merge. It significantly increases stability of rebuild especially for addition (which frequently hit the assert removed & improved by this patch). There is only one test failure for rebuild 18, which I am reasonably sure is not related to this patch. I am unable to find a ticket for it though.

**Review by NiuYawei — APPROVED** [review]

**Review by ryon-jensen — APPROVED** [review]

**Comment by byron-marohn** [comment]
@daos-stack/daos-gatekeeper This is ready to land. The single test failure is unrelated.

**Review by wangdi1 — APPROVED** [review]

**Pull request merged**
