### PR TITLE
DAOS-7012 bio: Tolerate inconsistent SMD info

### PR DESCRIPTION
**Pull request by NiuYawei**
The SMD pool info could be inconsistent with global pool info when
pool creation/destroy partially succeed or fail. For exmaple: If a
pool destroy happened after a blobstore is torndown for faulty SSD,
the blob and SMD info for the affected pool targets will be left
behind after the pool being destroyed.

SSD faulty reaction should tolerate such kind of inconsistency,
otherwise, state transition for the SSD won't be able to moving
forward. (The problem usually happens in testing where we mark
device as faulty, then destroy pool, then revive the device for
other tests).

In the future, we may need to have some kind of repairing
tool/mechanism to fix such inconsistency manually/automatically.

Signed-off-by: Niu Yawei <yawei.niu@intel.com>

### CODE REVIEW

**Review by liw — DISMISSED** [review]

**Review by liw — APPROVED** [review]

**Comment by NiuYawei** [comment]
All tests passed except a spell error, I'll fix that in the future. @sydneyvanda , @ravalsam Could you review it? Thanks.

**Review by sydneyvanda — APPROVED** [review]
LGTM

**Comment by johannlombardi** [comment]
Please find the spellcheck in a subsequent (doc-only) PR.

Error: ./src/pool/srv_util.c:384: exmaple ==> example

**Comment by johannlombardi** [comment]
Seeing some new failures on master:

https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/master/4609/tests/

Not sure whether this patch is the culprit, but going to try a revert. See https://github.com/daos-stack/daos/pull/5836

**Pull request merged**
