### PR TITLE
DAOS-7084 Test: weekly-test: test_findcmd failing with CommandFailure

### PR DESCRIPTION
**Pull request by omar-ocampo**
Use python3 instead of "python" which may be linked to python2.

Test-tag-hw-medium: pr,hw,medium,ib2 findcmd
Signed-off-by: Omar Ocampo <omar.ocampo.coronado@intel.com>

### CODE REVIEW

**Comment by omar-ocampo** [comment]
Test passed: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5438/1/artifact/Functional%20Hardware%20Medium/io/dfuse_find_cmd.py/results.json

**Comment by omar-ocampo** [comment]
This change should also be merged in 1.2

**Review by shimizukko — APPROVED** [review]

**Comment by omar-ocampo** [comment]
Funct HW medium failed due to: https://jira.hpdd.intel.com/browse/DAOS-7245

**Review by mjean308 — APPROVED** [review]

**Comment by omar-ocampo** [comment]
@sylviachanoiyee, can we merge this?

**Comment by rpadma2** [comment]
> @sylviachanoiyee, can we merge this?

@omar-ocampo : Hardware testing not completed/or failed. The PR is not ready for merge without hardware testing.. Normally, it is better to get "All passed" condition. I believe you are not using any Skip tags.

**Comment by sylviachanoiyee** [comment]
Test stage failed. Need to rebase and rerun

**Comment by omar-ocampo** [comment]
> Test stage failed. Need to rebase and rerun
Merged from master and pushed changes, waiting for CI results

**Comment by omar-ocampo** [comment]
@sylviachanoiyee , please merge

**Pull request merged**
