### PR TITLE
DAOS-9121 build: fix socketid in spdk scan with vmd

### PR DESCRIPTION
**Pull request by tanabarr**
Fix SPDK bug where incorrect socket-ID is reported in NVMe controller
details when running daos_server storage scan or dmg storage scan -v.

Fix is to apply SPDK patch #10373 in build.config for source builds,
another PR will update SPDK RPM repo to apply the same patch.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### CODE REVIEW

**Comment by tanabarr** [comment]
build counterpart to https://github.com/daos-stack/spdk/pull/34 which applies the patch to SPDK RPM

**Review by NiuYawei — APPROVED** [review]

**Comment by tanabarr** [comment]
Output now correctly reflects VMD backing devices socket-ID:
```
tanabarr@wolf-157:~/projects/daos_m> install-leap15/bin/dmg storage scan -i -v
---------
localhost
---------
SCM Namespace Socket ID Capacity
------------- --------- --------
pmem0         0         3.2 TB
pmem1         1         3.2 TB

NVMe PCI       Model               FW Revision Socket ID Capacity
--------       -----               ----------- --------- --------
5d0505:01:00.0 INTEL SSDPE2KE016T8 VDV10170    0         1.6 TB
5d0505:03:00.0 INTEL SSDPE2KE016T8 VDV10170    0         1.6 TB
850505:07:00.0 INTEL SSDPE2KE016T8 VDV10170    1         1.6 TB
850505:09:00.0 INTEL SSDPE2KE016T8 VDV10170    1         1.6 TB
850505:0b:00.0 INTEL SSDPE2KE016T8 VDV10170    1         1.6 TB
850505:0d:00.0 INTEL SSDPE2KE016T8 VDV10170    1         1.6 TB
850505:0f:00.0 INTEL SSDPE2KE016T8 VDV10170    1         1.6 TB
850505:11:00.0 INTEL SSDPE2KE016T8 VDV10170    1         1.6 TB
850505:14:00.0 INTEL SSDPED1K750GA E2010475    1         750 GB
```

**Comment by tanabarr** [comment]
Config generate now works correctly with backing devices selected matching socket/NUMA code:
```
tanabarr@wolf-157:~/projects/daos_m> install-leap15/bin/dmg config generate -i -a wolf-157 -e 1
port: 10001
transport_config:
  allow_insecure: false
  client_cert_dir: /etc/daos/certs/clients
  ca_cert: /etc/daos/certs/daosCA.crt
  cert: /etc/daos/certs/server.crt
  key: /etc/daos/certs/server.key
engines:
- targets: 22
  nr_xs_helpers: 1
  first_core: 0
  log_file: /tmp/daos_engine.0.log
  storage:
  - class: dcpm
    scm_mount: /mnt/daos0
    scm_list:
    - /dev/pmem0
  - class: nvme
    bdev_list:
    - 5d0505:01:00.0
    - 5d0505:03:00.0
  provider: ofi+sockets
  fabric_iface: eth0
  fabric_iface_port: 31416
  pinned_numa_node: 0
disable_vfio: false
enable_vmd: false
enable_hotplug: false
nr_hugepages: 11264
control_log_mask: INFO
control_log_file: /tmp/daos_server.log
helper_log_file: ""
firmware_helper_log_file: ""
fault_path: ""
name: daos_server
socket_dir: /var/run/daos_server
provider: ofi+sockets
access_points:
- wolf-157:10001
fault_cb: ""
hyperthreads: false
```

**Review by ashleypittman — APPROVED** [review]
I wonder at what point we consider changing to quilt or similar for managing these.

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
