### PR TITLE
DAOS-12112 rebuild:rebuild patches port from 2.4

### PR DESCRIPTION
**Pull request by wangdi1**
Several rebuild patches sync with master

DAOS-11444 pool: return rc for ds_pool_lookup (#10551)
DAOS-11952 rebuild: increase stack size for rebuild ULT (#10683)
DAOS-11064 rebuild: search the right targets to merge (#10776)
DAOS-12112 rebuild: keep reclaim op unchanged (#10973)
DAOS-10836 pool: add master term to IV namespace (#11024)
DAOS-12198 rebuild: remove invalid assertion. (#11070)
DAOS-10681 rebuild: check the global pool map version before rebuild (#11140)
DAOS-10681 object: misc fixes for layout upgrade and rebuild (#11129)

Test-tag: pr rebuild ec
Signed-off-by: Di Wang <di.wang@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by wangdi1** [comment]
ping, these are needed rebuild patches for 2.2

**Comment by wangdi1** [comment]
all tests passed with test-tag: pr rebuild ec   ping reviewer

**Comment by wangdi1** [comment]
ping

**Review by jolivier23 — APPROVED** [review]
Do you have a list of patches that this is drawing from?

**Comment by wangdi1** [comment]
> Do you have a list of patches that this is drawing from?

Yes, this PR include several patches from patches, actually 8 commit. Can this be landed as 8 commit? or only 1 commit? Here are lists.

pick 378fe22dba DAOS-11444 pool: return rc for ds_pool_lookup (#10551)
pick 353c0f0996 DAOS-11952 rebuild: increase stack size for rebuild ULT (#10683)
pick 7b5403ac75 DAOS-11064 rebuild: search the right targets to merge (#10776)
pick cdd931310e DAOS-12112 rebuild: keep reclaim op unchanged (#10973)
pick 82e35d24c0 DAOS-10836 pool: add master term to IV namespace (#11024)
pick a398950252 DAOS-12198 rebuild: remove invalid assertion. (#11070)
pick afe0753d63 DAOS-10681 rebuild: check the global pool map version before rebuild (#11140)
pick 12bdd1286a DAOS-10681 object: misc fixes for layout upgrade and rebuild (#11129)

**Pull request merged**
