### PR TITLE
DAOS-6903 Test: Fix regression in NVMe health test code. (#4832)

### PR DESCRIPTION
**Pull request by ravalsam**
Quick-Functional: true
Test-tag: csum_error_log nvme_health der_enospace

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
Ci Test result can be found from https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5240/1/artifact/Functional_Hardware_Medium/nvme/

**Review by mjean308 — APPROVED** [review]
lgtm

**Review by saurabhtandan — DISMISSED** [review]
LGTM

**Comment by sylviachanoiyee** [comment]
@ravalsam , can we run all func tests? you can skip unit testing
I don't see result for nvme_io and there is change in the general utils.

**Comment by ravalsam** [comment]
> @ravalsam , can we run all func tests? you can skip unit testing
> I don't see result for nvme_io and there is change in the general utils.

I was mention not to run all tests when we Cherry-pick instead only which impacts the tests. is that changed now? 

NVMe IO has been worked out in another PR because of getting issue in the DAOS side and that was the reason I did not ran part of Ci in this PR.

**Review by dinghwah — APPROVED** [review]
LGTM.

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Pull request merged**
