### PR TITLE
DAOS-3793 tests: Update pool eviction tests to test automatic eviction

### PR DESCRIPTION
**Pull request by phender**
Replacing DAOS API pool exclude call in pool/bad_exclude.py test with a
'dmg pool exclude' call.

Quick-build: true
Skip-unit-tests: true
Skip-func-hw-test: true
Test-tag-vm: badexclude

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Review by dinghwah — APPROVED** [review]

**Comment by phender** [comment]
This PR is just removing a test.  There was one test failure:

Test / Functional_Hardware_Large / FTEST_mdtest.MdtestSmall.1-./mdtest/mdtest_small.py:MdtestSmall.test_mdtest_small;transport_config-container-dfuse-transport_config-hosts-np_8-pool-transport_config-a3bd

but this should not be a result of removing the src/tests/ftest/pool/bad_exclude.py test.

**Comment by phender** [comment]
@daos-stack/daos-gatekeeper please hold off from landing while we confirm if the loss of test coverage is ok.

**Comment by phender** [comment]
Per https://jira.hpdd.intel.com/browse/DAOS-3793?focusedCommentId=257695&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-257695 it has been confirmed that this patch can land.

**Pull request merged**
