### PR TITLE
DAOS-4903 tests: Fix installing packages for core file processing

### PR DESCRIPTION
**Pull request by phender**
Resolving a 'UnboundLocalError: local variable 'cmd' referenced before
assignment' that can occur in launch.py when installing packages for
processing core files possibly generated by test execution.

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by phender** [comment]
There are 4 failures in [Build 2](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-2744/2/).  Three of which are known issues:
- io/ior_small.py: [DAOS-4919](https://jira.hpdd.intel.com/browse/DAOS-4919)
- io/mdtest_small.py: [DAOS-4930](https://jira.hpdd.intel.com/browse/DAOS-4930)
- daos_test/daos_core_test-rebuild.py - test_r_1-10:  I believe this is [DAOS-4740](https://jira.hpdd.intel.com/browse/DAOS-4740) which appears to be fixed in the master branch, but does not have a cherry-pick into release/0.9

The fourth issue occurred in the Test CentOS 7 RPMs step, where the DAOS Management Tests failed here:
destroying pool synchronously ... [  FAILED  ] MGMT5: retry MGMT_POOL_{CREATE,DESETROY} upon errors

**Comment by phender** [comment]
I opened https://jira.hpdd.intel.com/browse/DAOS-4948 for the  "Test CentOS 7 RPMs" failure

**Comment by phender** [comment]
@daos-stack/daos-gatekeeper is there anything holding this up?

**Comment by jolivier23** [comment]
> @daos-stack/daos-gatekeeper is there anything holding this up?

Just held up by approval to land anything to this branch

**Comment by jolivier23** [comment]
1.0 is released now, should we abandon this patch?

**Comment by brianjmurrell** [comment]
Isn't this something that should land in case/anticipation of a 1.x.x?  It's usually a lot easier to just land stuff preemptively as they are identified than it is to one day decide we are going to do another 1.x.x release and then have to go hunting and scrambling and stabilising for things that should be in it.

**Pull request closed without merging**
