### PR TITLE
DAOS-13223 cq: Fail Doxygen build on warnings.

### PR DESCRIPTION
**Pull request by ashleypittman**
Required-githooks: true

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
This new option doesn't work on el8 but does in GitHub Actions.

**Comment by ashleypittman** [comment]
Fix for the header is already on master, for the purposes of this PR I branched from a point in history.

**Review by JohnMalmberg — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by jolivier23** [comment]
Probably should merge latest master to make sure it works when there isn't an issue

**Comment by ashleypittman** [comment]
> Probably should merge latest master to make sure it works when there isn't an issue

Done, and Doxygen test passed.

**Pull request merged**
