### PR TITLE
DAOS-5764 tests: Increasing timeout for server storage format

### PR DESCRIPTION
**Pull request by phender**
Temporarily increasing the 'dmg storage format' timeout to avoid failing
the fio_small.py test.

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by phender** [comment]
In https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3613/2/artifact/Functional/job-2020-10-08T20.15-e248aba-io-fio_small/job.log, fio_small.py passed all 4 variants on wolf-[126-127] with the following `dmg storage format` times:
```
2020-10-08 20:16:33,869 process          L0499 INFO | Command '/usr/bin/dmg -o /mnt/share/tmp.iIXCEIBqzQ/fio_small.py-1__daos_server_dmg.yaml storage format' finished with 0 after 32.3618059158s
2020-10-08 20:18:16,743 process          L0499 INFO | Command '/usr/bin/dmg -o /mnt/share/tmp.iIXCEIBqzQ/fio_small.py-2__daos_server_dmg.yaml storage format' finished with 0 after 32.3826398849s
2020-10-08 20:20:00,401 process          L0499 INFO | Command '/usr/bin/dmg -o /mnt/share/tmp.iIXCEIBqzQ/fio_small.py-3__daos_server_dmg.yaml storage format' finished with 0 after 32.369453907s
2020-10-08 20:21:36,575 process          L0499 INFO | Command '/usr/bin/dmg -o /mnt/share/tmp.iIXCEIBqzQ/fio_small.py-4__daos_server_dmg.yaml storage format' finished with 0 after 32.4294450283s
```

**Comment by phender** [comment]
The https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-3613/2 included only e failures, unrelated to the change in this PR:
- daos_test/daos_core_test-rebuild: r0-10: https://jira.hpdd.intel.com/browse/DAOS-5810
- checksum/csum_error_logging.py: https://jira.hpdd.intel.com/browse/DAOS-5745

**Review by dinghwah — APPROVED** [review]
LGTM

**Review by shimizukko — APPROVED** [review]
LGTM

**Pull request merged**
