### PR TITLE
DAOS-12679 object: refresh DTX ID for DER_EP_OLD

### PR DESCRIPTION
**Pull request by Nasf-Fan**
master-commit: 1d42b485d49d9aec03bc7318916aa9871b9f6fe8

If the resent RPC is too old as to exceed server DTX aggregation time threshold, then related DTX entry on server may be removed by DTX aggregation, and then the resent logic will have no way to know whether related modification has ever been executed on the engine or not. Under such case, client will get -DER_EP_OLD failure. For non-conditional modifcation, that is not fatal, the client logic can re-generate newer DTX ID and retry the RPC. If its former RPC has ever been executed, it just re-executes the modification with some redundant data (that can be handled via VOS aggregation sometime later), but it will not cause semantics issues.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by Nasf-Fan** [comment]
Hit DAOS_Rebuild_EC.REBUILD4 failure for DAOS-12631.

**Review by liuxuezhao — APPROVED** [review]

**Comment by Nasf-Fan** [comment]
@gnailzenh , please help to review the patch for b22 back-porting. Thanks!

**Comment by Nasf-Fan** [comment]
@gnailzenh @jolivier23 , please help to review the 2.2 back-ported patch? Thanks!

**Comment by Nasf-Fan** [comment]
@wangdi1 @jolivier23 @gnailzenh , please help to review the patch which is required for release/2.2, thanks!

**Review by wangdi1 — APPROVED** [review]

**Comment by Nasf-Fan** [comment]
@daos-stack/daos-gatekeeper , would you please to consider landing the patch to release/2.2?

**Comment by Nasf-Fan** [comment]
@daos-stack/daos-gatekeeper , it is approved for "2.2.1 Community Release". Would you please to land the patch to release/2.2? Thanks!

**Pull request merged**
