### PR TITLE
DAOS-13878 test: Install golang >= 1.18 as a daos-tests dep

### PR DESCRIPTION
**Pull request by mjmac**
Needed for the dfuse/daos_build.py tests. Also disables
module filtering for the daos-stack-deps repository
in order to allow installation of newer golang RPMs.

Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
Isn't this going to require that we start to ship our go runtime also then, so that production systems will be running in the same way that we are testing?

I thought the only problem we were having was with developers getting our own go RPMs on their development systems.

**Comment by mjmac** [comment]
Ok, verified that this fixes the dfuse test:
`2023-06-29 22:59:28,328 run_utils        L0184 DEBUG|     Checking /bin/go version... 1.20.3`

**Review by jolivier23 — APPROVED** [review]
need debian/changelog entry?

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
You need to make the corresponding `debian/` updates.

**Review by brianjmurrell — APPROVED** [review]

**Review by ashleypittman — APPROVED** [review]

**Pull request merged**
