### PR TITLE
DAOS-623 utils: daos fs copy: don't try to create root

### PR DESCRIPTION
**Pull request by daltonbohning**
Test-tag: daos_fs_copy

Don't try to create the root - assume it always exists.

Required-githooks: true

Signed-off-by: Dalton Bohning <dalton.bohning@intel.com>

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficent testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by wangshilong — APPROVED** [review]

**Comment by jolivier23** [comment]
Is this the only test that uses daos_hdlr ?

**Comment by daltonbohning** [comment]
> Is this the only test that uses daos_hdlr ?

@jolivier23 Not the only test that uses daos_hdlr, but the changes are contained to the function fs_copy_dir, which is only used by NLT (which ran) and functional tests tagged with `daos_fs_copy`

**Comment by ashleypittman** [comment]
> > Is this the only test that uses daos_hdlr ?
> 
> @jolivier23 Not the only test that uses daos_hdlr, but the changes are contained to the function fs_copy_dir, which is only used by NLT (which ran) and functional tests tagged with `daos_fs_copy`

if this was run under NLT before then I'd expect it to fail as it would have logged an error?

**Comment by daltonbohning** [comment]
> if this was run under NLT before then I'd expect it to fail as it would have logged an error?

This is an edge case when copying to the root. It might be that NLT doesn't have a specific case for it

**Pull request merged**
