### PR TITLE
DAOS-13167 test: Enable bullseye build.

### PR DESCRIPTION
**Pull request by ashleypittman**
Skip-fnbullseye: false
Skip-bullseye: false

Required-githooks: true

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Review by jolivier23 — DISMISSED** [review]
so then there probably was no change, just a difference in the base image?

**Comment by ashleypittman** [comment]
There are still Java errors even with this PR but this is a step forwards.

**Review by brianjmurrell — APPROVED** [review]

**Review by dinghwah — APPROVED** [review]

**Comment by ashleypittman** [comment]
Jenkins hit networking problems after the build but this PR only changes dockerfiles which was covered by the testing.

**Comment by daltonbohning** [comment]
> Jenkins hit networking problems after the build but this PR only changes dockerfiles which was covered by the testing.

Don't we need to verify the "Bullseye Report on EL 8" stage in Jenkins?
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12379/2/pipeline

**Comment by ashleypittman** [comment]
> > Jenkins hit networking problems after the build but this PR only changes dockerfiles which was covered by the testing.
> 
> Don't we need to verify the "Bullseye Report on EL 8" stage in Jenkins? https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12379/2/pipeline

I assume @dinghwah is looking at that and it's covered by the same ticket but it's a different problem.

**Comment by daltonbohning** [comment]
> > > Jenkins hit networking problems after the build but this PR only changes dockerfiles which was covered by the testing.
> > 
> > 
> > Don't we need to verify the "Bullseye Report on EL 8" stage in Jenkins? https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-12379/2/pipeline
> 
> I assume @dinghwah is looking at that and it's covered by the same ticket but it's a different problem.

@dinghwah Will you please confirm that the Bullseye Report on EL 8" stage is still expected to fail?

**Pull request merged**
