### PR TITLE
DAOS-3623 tests: Moving DAOS_SINGLETON_CLI setting to launch.py

### PR DESCRIPTION
**Pull request by phender**
A number of test files set DAOS_SINGLETON_CLI. Moving the setting of
the evironment variable to a single location that is easy to modify.
Other test files that export the variable setting will no source the
value from the environment.

Test-tag-hw: pr,hw, daosperfsmall

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
Title says **Moving DAOS_SINGLETON_CLI setting to launch.py** but I don't see where it actually moves to `launch.py`.  Did a change get forgotten?

Also, it's the intention of the patch to invert the value of DAOS_SINGLETON_CLI in all of the changed locations?

**Comment by phender** [comment]
> Title says **Moving DAOS_SINGLETON_CLI setting to launch.py** but I don't see where it actually moves to `launch.py`. Did a change get forgotten?

No, I guess the wording could be slightly clearer - my apologies for the confusion.  The change reduces the locations in which DAOS_SINGLETON_CLI is set to just launch.py (which does not require a change).  The other files now obtain the DOAS_SINGLETON_CLI setting from the environment variable set by launch.py (or the launch node environment if not utilizing launch.py).

> Also, it's the intention of the patch to invert the value of DAOS_SINGLETON_CLI in all of the changed locations?

That is a bit of an open question.  I purposely used a inverse default value (`0`) to verify that launch.py's setting of `DAOS_SINGLETON_CLI=1` propagated correctly.  When we support PMIx-less bootstrapping I think this default makes sense.

**Comment by brianjmurrell** [comment]
@phender Fair enough.  Are you ready for reviews?  Scott pointed me at this but I didn't see any reviewer flags set so wasn't sure if I should add a review or if you wanted to reserve the ability to force-push still.

**Comment by shimizukko** [comment]
It looks good to me.

**Comment by phender** [comment]
> @phender Fair enough. Are you ready for reviews? Scott pointed me at this but I didn't see any reviewer flags set so wasn't sure if I should add a review or if you wanted to reserve the ability to force-push still.

I wanted to verify that the code had been properly tested through CI before I requested reviews.  As it turns out none of the modified code was tested through CI as a result of three tests (`io/romio.py`, `pool/rebuild_no_cap.py`, and `pool/rebuild_with_ior`) being skipped due to bugs and there being no Functional HW testing for these tests:
- io/daos_perf.py
- io/mdtest_small.py
- io/ior_small.py

**Comment by phender** [comment]
This change is no longer needed.

**Pull request closed without merging**
