### PR TITLE
DAOS-14302 test: Skip DAOS_Drain_Simple w/o fault injection

### PR DESCRIPTION
**Pull request by phender**
Do not run the DAOS_Drain_Simple test when DAOS is built without fault injection.

Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: test_daos_drain_simple

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by daltonbohning — APPROVED** [review]

**Review by wangshilong — APPROVED** [review]

**Comment by phender** [comment]
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13039/4/testReport/FTEST_daos_test/ had two failures related to the `1-./daos_test/suite.py:DaosCoreTest.test_daos_ec_obj` test where the daos_test command completing after the test timeout.  The test did pass, just 36 seconds after the test timeout:
```
2023-09-12 19:15:00,870 process          L0416 DEBUG| [stdout] [1,0]<stdout>:
2023-09-12 19:15:00,870 process          L0416 DEBUG| [stdout] [1,0]<stdout>:============ Summary src/tests/suite/daos_test.c
2023-09-12 19:15:00,870 process          L0416 DEBUG| [stdout] [1,0]<stdout>:OK - NO TEST FAILURES
``` 
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13039/4/artifact/Functional%20Hardware%20Medium%20Verbs%20Provider/daos_test/suite.py/job.log
The missing cmocka result failure was a result of this timeout.

**Comment by phender** [comment]
Running https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13039/5/ with the `2.4.0-1` RPMs to verify the tests get skipped.

**Comment by phender** [comment]
Skipping tests was only successful for the DAOS_EC tests in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13039/5/testReport/FTEST_daos_test/

**Comment by phender** [comment]
Running https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13039/6/ with a release build to verify tests are skipped.

**Comment by phender** [comment]
All expected tests were skipped in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13039/6/testReport/FTEST_daos_test/, but because DAOS_Drain_Simple consists of just one cmocka test case we get this `missing cmocka test results` error: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13039/6/testReport/FTEST_daos_test/DAOS_Drain_Simple/2___daos_test_suite_py_DaosCoreTest_test_daos_drain_simple_run_agent_config_transport_config_daos_tests_args_daos_test_num_clients_pools_created_scalable_endpoint_stopped_ranks_test_name_dmg_hosts_pool_server_config_engines_0_storage_0_1_timeouts_b7f7/

It seems like cmocka should still produce a test result if the test is skipped, but if needed we could work around it with a `faults` tag on the functional test.

**Pull request merged**
