### PR TITLE
DAOS-10894 pool: reject pool connection from old clients (#9488)

### PR DESCRIPTION
**Pull request by wangshilong**
If pool upgrade succeed for EC rotation, old client(2.2) should
be not allowed to access upgraded pools any more unless clients
are upgraded to 2.4 as well.

Modify pool connection rpc to take max pool version that client
could be supported to server side, server will reject if pool's
version is larger than client max supported version.

Signed-off-by: Wang Shilong <shilong.wang@intel.com>

### CODE REVIEW

**Comment by wangshilong** [comment]
> Is this PR ready for review? I see that the destination branch is not release/2.2
> 
> It looks like the cherry-pick conflicts in pool/srv_pool.c when picking master commit [bddb678](https://github.com/daos-stack/daos/commit/bddb67849558d520db8b6de9d76eecf82719b642) are a little tricky. There are different master commits affecting the same areas of the code e.g., ds_pool_mark_upgrade_completed() and read_db_for_stepping_up()) - and they haven't been picked to release/2.2 yet.

Yup, this PR is based on another PR that has not been merged to release/2.2, there are some dependency there.

**Comment by wangshilong** [comment]
> > Is this PR ready for review? I see that the destination branch is not release/2.2
> > It looks like the cherry-pick conflicts in pool/srv_pool.c when picking master commit [bddb678](https://github.com/daos-stack/daos/commit/bddb67849558d520db8b6de9d76eecf82719b642) are a little tricky. There are different master commits affecting the same areas of the code e.g., ds_pool_mark_upgrade_completed() and read_db_for_stepping_up()) - and they haven't been picked to release/2.2 yet.
> 
> Yup, this PR is based on another PR that has not been merged to release/2.2, there are some dependency there.

PR should be ready for landing now, base PR has been landed to 2.2

**Comment by wangshilong** [comment]
> > Is this PR ready for review? I see that the destination branch is not release/2.2
> > It looks like the cherry-pick conflicts in pool/srv_pool.c when picking master commit [bddb678](https://github.com/daos-stack/daos/commit/bddb67849558d520db8b6de9d76eecf82719b642) are a little tricky. There are different master commits affecting the same areas of the code e.g., ds_pool_mark_upgrade_completed() and read_db_for_stepping_up()) - and they haven't been picked to release/2.2 yet.
> 
> Yup, this PR is based on another PR that has not been merged to release/2.2, there are some dependency there.

sorry, i mean ready for review.

**Comment by kccain** [comment]
> > > Is this PR ready for review? I see that the destination branch is not release/2.2
> > > It looks like the cherry-pick conflicts in pool/srv_pool.c when picking master commit [bddb678](https://github.com/daos-stack/daos/commit/bddb67849558d520db8b6de9d76eecf82719b642) are a little tricky. There are different master commits affecting the same areas of the code e.g., ds_pool_mark_upgrade_completed() and read_db_for_stepping_up()) - and they haven't been picked to release/2.2 yet.
> > 
> > 
> > Yup, this PR is based on another PR that has not been merged to release/2.2, there are some dependency there.
> 
> sorry, i mean ready for review.

This was the patch I was looking at when writing this comment. https://github.com/daos-stack/daos/pull/9840
Does this PR need to wait for that one to land first?

**Comment by wangshilong** [comment]
> > > > Is this PR ready for review? I see that the destination branch is not release/2.2
> > > > It looks like the cherry-pick conflicts in pool/srv_pool.c when picking master commit [bddb678](https://github.com/daos-stack/daos/commit/bddb67849558d520db8b6de9d76eecf82719b642) are a little tricky. There are different master commits affecting the same areas of the code e.g., ds_pool_mark_upgrade_completed() and read_db_for_stepping_up()) - and they haven't been picked to release/2.2 yet.
> > > 
> > > 
> > > Yup, this PR is based on another PR that has not been merged to release/2.2, there are some dependency there.
> > 
> > 
> > sorry, i mean ready for review.
> 
> This was the patch I was looking at when writing this comment. #9840 Does this PR need to wait for that one to land first?

Yup, that is good idea.

**Review by kccain — APPROVED** [review]

**Review by johannlombardi — APPROVED** [review]

**Pull request merged**
