### PR TITLE
DAOS-4248 container: do not use tse_set_priv in cont open.

### PR DESCRIPTION
**Pull request by mchaarawi**
a user can use tse_set_priv() and overwrite any internal data that
DAOS sets so we should not be using it internally. change container
open to do the dc_cont allocation in the completion CB.

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Comment by liw** [comment]
We use task priv in libdaos for keeping state across task reinitializations in many places. Search also for daos_task_set_priv.

**Comment by fortnern** [comment]
We've been using tse/daos tasks to manage async HDF5. There isn't any other way I can find to attach data to a task, so we need to be able to set private data on DAOS tasks so the callbacks can function. Maybe there should be a separate internal private data pointer, or a separate pointer specified for each callback (as well as the main task function).

**Comment by liw** [comment]
@mchaarawi, any thoughts?

**Comment by johannlombardi** [comment]
@mchaarawi is on vacation. @liuxuezhao is looking into refreshing the patch based on inspection feedback.

**Comment by liuxuezhao** [comment]
@liw @johannlombardi @mchaarawi 
Now there are two ways to attach data to a task - 1) tse_task_set_priv/_get_priv, 2) tse_task_stack_push/_pop, and currently both are public exported.

Since user want to use tse_task_set_priv (it is simpler to use), probably we can export that API to user, and don't export tse_task_stack_push/_pop() to user.
So for DAOS internal usage, it need to use tse_task_stack_push/_pop, that need to be carful because push/pop must be in pair. I need to check if it is practical for all DAOS internal usage.

Another option is we keep two task priv pointers, one for daos internal usage,  another for daos' user usage.

**Comment by liuxuezhao** [comment]
https://github.com/daos-stack/daos/pull/2047  is a small patch to provide a quick fix for user, we may revisit is later when needed. thanks.

**Comment by johannlombardi** [comment]
Thanks Xuezhao. This patch should unblock the HDF group until Mohamad is back.

**Pull request closed without merging**
