### PR TITLE
Fixed an error on line 202

### PR DESCRIPTION
**Pull request by TheOtherDave**
Changed "$ scons PREFIX=$(daos_prefix_path}" to "$ scons PREFIX=${daos_prefix_path}"
Note the "(" vs "{" preceding "daos_prefix_path"

### CODE REVIEW

**Comment by TheOtherDave** [comment]
Line 202 of https://github.com/daos-stack/daos/blob/master/doc/quickstart.md, that is.

**Comment by johannlombardi** [comment]
Good catch. If you don't mind, I am just going to reformat the commit message to match our standard.
Could you please also share with me your signed-off-by?
Thanks for your contribution.

**Comment by TheOtherDave** [comment]
Yeah, sure. Sorry, I didn't think to look for commit message formatting guidelines first.

I don't know what a "signed-off-by" is. My real-life name is Dave Sweeris, if that's what you mean.

**Comment by johannlombardi** [comment]
np. As for the Signed-off-by, please see https://wiki.hpdd.intel.com/display/DC/Signed-off-by

**Comment by TheOtherDave** [comment]
Ah, ok. "Signed-off-by: Dave Sweeris <davesweeris@mac.com>"

**Comment by brianjmurrell** [comment]
Given that this has been fixed in the existing master, I'm going to close this.  Thanks for bringing it to our attention.

**Pull request closed without merging**
