### PR TITLE
DAOS-5903: Fix daos_io_run_conf to pass dmg yaml file for pool creation.

### PR DESCRIPTION
**Pull request by ravalsam**
Test was updated to pass the dmg yaml file to avoide the certification
issue while pool create.
Added additional check to validate expected success message for Avocado test.

Test-tag-hw-large: unaligned_io

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Comment by mjmac** [comment]
@ravalsam: Please check the test failures and associate them with a ticket if they are known issues unrelated to this PR.

**Comment by ravalsam** [comment]
> @ravalsam: Please check the test failures and associate them with a ticket if they are known issues unrelated to this PR.

Test failure is not related to the change I made with current PR.

**Comment by ravalsam** [comment]
Created new defect DAOS-5934 for test failure

**Pull request merged**
