### PR TITLE
DAOS-6040 tests: Clearly identifying timeouts in test harness

### PR DESCRIPTION
**Pull request by phender**
Improving the notification of command and test timeouts by reporting
which timeouts have been exceeded and under what conditions the
test tearDown() method has been called.

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Review by mjmac — COMMENTED** [review]
What does it look like when a test times out e.g. because the servers didn't start in time? I think this is definitely an improvement, but I'm concerned that it's still not going to be clear which of the several timeouts that come into play during test setup and execution have been tripped.

**Comment by phender** [comment]
> What does it look like when a test times out e.g. because the servers didn't start in time? I think this is definitely an improvement, but I'm concerned that it's still not going to be clear which of the several timeouts that come into play during test setup and execution have been tripped.

As the `daos_server start` and `daos_agent` commands are currently ran as sub processes the timeouts are related to timeout in string detection.  The current message does include the timeout value (here it's 3 seconds), but admittedly it is not very clear:
```
2020-12-07 22:20:31,412 command_utils    L0641 INFO | Time out detected - 0/1 '(SCM format required)(?!;)' messages detected in 3.00001192093/3 seconds
```
More importantly it does not indicate how/where this can be adjusted.

Would this change satisfy the request:

- String detected within the timeout:
```
2020-12-07 22:59:08,969 command_utils    L0662 INFO | daos_agent subprocess startup detected - 2/2 'Listening on ' messages detected in 1.27509689331
```

- String no detected within the timeout
```
2020-12-07 22:59:26,181 command_utils    L0649 INFO | TIMEOUT after 3 seconds - '0/1 '(SCM format required)(?!;)' messages detected in 3.00000691414'
2020-12-07 22:59:26,181 command_utils    L0654 DEBUG| If needed the 3 second timeout can be adjusted via the 'pattern_timeout' test yaml parameter under /run/daos_server/*
```

**Comment by phender** [comment]
An example of the new command timeout reporting - in this case for an `orterun` command:
```
2020-12-07 22:17:25,910 process          L0479 DEBUG| [stdout]  All ranks reading chu[1,5]<stdout>:    data verification failed for chunk 9
2020-12-07 22:29:05,161 process          L0499 INFO | Command '/usr/lib64/openmpi3/bin/orterun --enable-recovery -x DAOS_POOL=AA88F28C-79F3-45E0-9FD5-BF3572E40F66 -x DAOS_CONT=B7578261-C149-4DAD-A4D7-02A99F128620 -x HDF5_VOL_CONNECTOR=daos -x HDF5_PLUGIN_PATH=/usr/lib64/openmpi3/lib -x DAOS_SVCL=0 --hostfile /tmp/hostfile61932 --map-by node --mca pml "ob1" --mca btl_openib_warn_default_gid_prefix "0" --mca btl_tcp_if_include "eth0" --mca oob "tcp" --mca btl "tcp,self" --np 6 --tag-output -wdir /tmp/daos_dfuse /usr/lib64/hdf5_vol_daos/openmpi3/tests/h5vl_test_parallel' finished with 1 after 702.011212111s
2020-12-07 22:29:05,161 output           L0655 DEBUG| Timeout detected running '/usr/lib64/openmpi3/bin/orterun --enable-recovery -x DAOS_POOL=AA88F28C-79F3-45E0-9FD5-BF3572E40F66 -x DAOS_CONT=B7578261-C149-4DAD-A4D7-02A99F128620 -x HDF5_VOL_CONNECTOR=daos -x HDF5_PLUGIN_PATH=/usr/lib64/openmpi3/lib -x DAOS_SVCL=0 --hostfile /tmp/hostfile61932 --map-by node --mca pml "ob1" --mca btl_openib_warn_default_gid_prefix "0" --mca btl_tcp_if_include "eth0" --mca oob "tcp" --mca btl "tcp,self" --np 6 --tag-output -wdir /tmp/daos_dfuse /usr/lib64/hdf5_vol_daos/openmpi3/tests/h5vl_test_parallel' with a 700s timeout
2020-12-07 22:29:05,161 stacktrace       L0039 ERROR| 
2020-12-07 22:29:05,161 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:596
2020-12-07 22:29:05,162 stacktrace       L0045 ERROR| Traceback (most recent call last):
2020-12-07 22:29:05,162 stacktrace       L0045 ERROR|   File "/usr/lib/daos/TESTING/ftest/io/daos_vol.py", line 68, in test_daos_vol
2020-12-07 22:29:05,162 stacktrace       L0045 ERROR|     self.run_test()
2020-12-07 22:29:05,162 stacktrace       L0045 ERROR|   File "/usr/lib/daos/TESTING/ftest/util/vol_test_base.py", line 82, in run_test
2020-12-07 22:29:05,162 stacktrace       L0045 ERROR|     self.job_manager.job, str(_error)))
2020-12-07 22:29:05,162 stacktrace       L0045 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 762, in fail
2020-12-07 22:29:05,162 stacktrace       L0045 ERROR|     raise exceptions.TestFail(message)
2020-12-07 22:29:05,162 stacktrace       L0045 ERROR| TestFail: /usr/lib64/hdf5_vol_daos/openmpi3/tests/h5vl_test_parallel FAILED> 
2020-12-07 22:29:05,163 stacktrace       L0045 ERROR| Exception occurred: Timeout detected running '/usr/lib64/openmpi3/bin/orterun --enable-recovery -x DAOS_POOL=AA88F28C-79F3-45E0-9FD5-BF3572E40F66 -x DAOS_CONT=B7578261-C149-4DAD-A4D7-02A99F128620 -x HDF5_VOL_CONNECTOR=daos -x HDF5_PLUGIN_PATH=/usr/lib64/openmpi3/lib -x DAOS_SVCL=0 --hostfile /tmp/hostfile61932 --map-by node --mca pml "ob1" --mca btl_openib_warn_default_gid_prefix "0" --mca btl_tcp_if_include "eth0" --mca oob "tcp" --mca btl "tcp,self" --np 6 --tag-output -wdir /tmp/daos_dfuse /usr/lib64/hdf5_vol_daos/openmpi3/tests/h5vl_test_parallel' with a 700s timeout
2020-12-07 22:29:05,163 stacktrace       L0046 ERROR| 
2020-12-07 22:29:05,163 test             L0601 DEBUG| Local variables:
2020-12-07 22:29:05,182 test             L0604 DEBUG|  -> self <class 'daos_vol.DaosVol'>: 11-./io/daos_vol.py:DaosVol.test_daos_vol;container-test2-dfuse-hosts-openmpi-pool-servers-7436
2020-12-07 22:29:05,182 test             L0186 INFO | *** TEARDOWN called after test completion: elapsed time: 759.97684598 seconds ***
2020-12-07 22:29:05,182 test             L0189 INFO | Amount of time left in test timeout: 70.0231540203 seconds 
```

**Comment by phender** [comment]
Test failures in https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-4020/8:
- Functional_Hardware_Small / DaosVol.11-./io/daos_vol.py:DaosVol.test_daos_vol: https://jira.hpdd.intel.com/browse/DAOS-5647
- Functional_Hardware_Medium / DaosCoreTest.02-./daos_test/daos_core_test.py:DaosCoreTest.test_subtest: test_m: https://jira.hpdd.intel.com/browse/DAOS-6245

**Review by sylviachanoiyee — APPROVED** [review]

**Comment by mjmac** [comment]
> ```
> 2020-12-07 22:59:26,181 command_utils    L0649 INFO | TIMEOUT after 3 seconds - '0/1 '(SCM format required)(?!;)' messages detected in 3.00000691414'
> 2020-12-07 22:59:26,181 command_utils    L0654 DEBUG| If needed the 3 second timeout can be adjusted via the 'pattern_timeout' test yaml parameter under /run/daos_server/*
> ```
If you can get to this level of detail for providing hints to the developer/triager, it would be great.

There are two goals here:
  1) Make it clearer to a developer running these tests locally or in CI that the failure was due to a timeout, clearly indicate which timeout was hit, and ideally provide some guidance on how to adjust the timeout if necessary
  2) Make it very clear to someone who may be unfamiliar with the details of the test and/or area of code under test that the failure occurred due to a timeout, and provide some clue as to who might be best to do additional digging into why the timeout occurred

The first use case is important for a developer looking at the results of their PR run. Assuming that the failure is due to something in their PR, they should be able to quickly figure out that the timeout was due to a regression (something hung, or got slower than it should have) or because the timeout is too aggressive and needs to be adjusted (the slowdown is expected because things got more complicated or whatever).

The second case is particularly important for the triage use case, where folks are periodically looking at a large number of test failures in one go and making priority/assignment decisions. They may or may not be particularly knowledgeable about the specific test or tested area of code, and are primarily concerned with figuring out who the right person is to do deeper analysis of the failure.

**Comment by phender** [comment]
I added changes to src/tests/ftest/util/command_utils.py to update the reporting of timeouts when detecting strings in sub process command output as previous described.  All tests passed in https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-4020/10/pipeline/

**Review by mjmac — APPROVED** [review]
LGTM, thanks for working on this. Should make life easier for a lot of people.

**Review by sylviachanoiyee — APPROVED** [review]

**Pull request merged**
