### PR TITLE
DAOS-7088 Test: Fix NVMe util for calculating IOR block size.

### PR DESCRIPTION
**Pull request by ravalsam**
Blocksize variable need to be int type to get the IOR blocksize
multiple of Transfer size.

Quick-Functional: true
Test-tag: nvme_fault

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
NVMe fault test passed https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5136/3/artifact/Functional_Hardware_Medium/nvme/nvme_fault.py/job.log

**Review by saurabhtandan — APPROVED** [review]
LGTM, but my only concern is, this involves change in nvme_util file. I hope it doesn't impact other nvme tests which mostly run on weekly runs and we won't find it out until weekly is run. Would have been nice if we could run with `nvme` tag.

**Comment by ravalsam** [comment]
> LGTM, but my only concern is, this involves change in nvme_util file. I hope it doesn't impact other nvme tests which mostly run on weekly runs and we won't find it out until weekly is run. Would have been nice if we could run with `nvme` tag.

Well in some cases we have to test the part which is impacted no matter which test case it uses. It breaks all the tests which use the size calculation function so verifying the single one should be sufficient. Another challenge is the HW as we do not want to use the Ci HW for all tests in the PR.

**Review by dinghwah — APPROVED** [review]
LGTM

**Pull request merged**
