### PR TITLE
DAOS-4467 tests: Support container properties in DaosCommand

### PR DESCRIPTION
**Pull request by phender**
Adding support for the '--properties' command line argument for the daos
container create command.  Tests will be able to pass options for the
'--properties' comamnd line argument in their test yaml file or by
passing the argument to the DaosCommand.container_create() method.

Signed-off-by: Phillip Henderson <phillip.henderson@intel.com>

### CODE REVIEW

**Comment by rpadma2** [comment]
Can we update ior_test_base.py and ior_small.yaml files as part of this PR. Without those changes, I am not sure how we are validating the changes in daos_utils.py. If required, I can do it in a different PR.
What is the format we have to adopt in the test.yaml file for setting the properties?

**Comment by ashleypittman** [comment]
This hit some kind of issue in CI overnight so I've hit restart.

**Comment by phender** [comment]
The 3 Build 8 failures are known issues:

pool/evict_test.py: DAOS-4410
io/ior_small.py: DAOS-4466
daos_test/daos_core_test-rebuild.py: DAOS-4491

**Comment by phender** [comment]
The 3 Build 9 failures are known issues:
- pool/destroy_tests.py: DAOS-3945
- pool/evict_test.py: DAOS-4410
- server/daos_server_config.py: DAOS-3945

Functional HW Large failed to run due to server issues - restarting the test phase

**Comment by phender** [comment]
The one Build 11 failure is a known issues:

pool/evict_test.py: DAOS-4410

**Comment by phender** [comment]
> I'm still learning avocado but this test looks like it could be changed to use the !mux feature to invoke the test multiple times with different params rather than having a loop in the test itself, and the file-per-process part split out into a different test entirely. That's outside the scope of this though.

Yes, the `!mux` feature could be used to iterate through different ior commands - in fact that is how the test used to operate.  It was updated to not use `!mux` as part of https://github.com/daos-stack/daos/pull/1649 to reduce the test time by eliminating starting/stopping the servers before/after each ior command.

**Pull request merged**
