### PR TITLE
DAOS-7804 object: check resent CPD RPC on non-leader

### PR DESCRIPTION
**Pull request by Nasf-Fan**
For resent CPD RPC, if related DTX entry exists but with different
(old) epoch, then we need to abort it firstly, and then re-execute
related modification with new epoch.

In such process, the vos_dtx_abort() will return positive value to
indicate how many DTX entries have been aborted. That is NOT error.

Signed-off-by: Fan Yong <fan.yong@intel.com>

### CODE REVIEW

**Comment by Nasf-Fan** [comment]
DAOS_Aggregate_EC failed for DAOS-7204, to be retested.

**Comment by johannlombardi** [comment]
Please review.

**Review by jolivier23 — APPROVED** [review]

**Review by wangdi1 — APPROVED** [review]

**Comment by liuxuezhao** [comment]
Just FYI, for the EC aggregation testing failure, looks like should be able to be fixed by PR5864 (landed at Jun-11).
can test to rebase to latest master to see if the failures still occures.

**Comment by jolivier23** [comment]
One question I have on this is what does the patch have to do with the description?

As far as I can tell (with @wangdi1 's help), the only change is preserving rc1 if none of the conditions hold by setting rc = rc1 (e.g. rc1 != DER_MISMATCH, DER_NONEXIST or 0).  But I can't find the correlation between that and the commit message

**Comment by jolivier23** [comment]
> One question I have on this is what does the patch have to do with the description?
> 
> As far as I can tell (with @wangdi1 's help), the only change is preserving rc1 if none of the conditions hold by setting rc = rc1 (e.g. rc1 != DER_MISMATCH, DER_NONEXIST or 0). But I can't find the correlation between that and the commit message

Ah, I think I figured it out.   The issue is that rc1 is still set to -DER_MISMATCH so the old code will abort the function early and return 1.

**Pull request merged**
