### PR TITLE
DAOS-7777 dfs: dfs_punch() should not set size if offset > file size

### PR DESCRIPTION
**Pull request by mchaarawi**
- also fix typo in punch to just punch len bytes

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Review by wangdi1 — APPROVED** [review]

**Review by daltonbohning — DISMISSED** [review]
I'm curious what the motivation is for NOT extending the file?
FWIW, posix truncate DOES extend: https://man7.org/linux/man-pages/man2/ftruncate.2.html

**Comment by mchaarawi** [comment]
> I'm curious what the motivation is for NOT extending the file?
> FWIW, posix truncate DOES extend: https://man7.org/linux/man-pages/man2/ftruncate.2.html

after discussion with wangdi, we thought it was probably clearer if we emulate truncate when len=DFS_MAX_FSIZE
otherwise we treat this as a punch that does not extend the file. what do you think?

**Comment by daltonbohning** [comment]
> > I'm curious what the motivation is for NOT extending the file?
> > FWIW, posix truncate DOES extend: https://man7.org/linux/man-pages/man2/ftruncate.2.html
> 
> after discussion with wangdi, we thought it was probably clearer if we emulate truncate when len=DFS_MAX_FSIZE
> otherwise we treat this as a punch that does not extend the file. what do you think?

After playing with this some, it seems punch can do anything that posix truncate can do, so I think this is okay. We maybe just need to update the documentation for this PR's change: https://github.com/daos-stack/daos/blob/master/src/include/daos_fs.h#L394-L397

However, I did run into a separate but related bug where there isn't overflow protection for offset+len.
Consider:
```
// Set size to 10
rc = dfs_punch(dfs_mt, obj, 10, DFS_MAX_FSIZE);

// offset + len = DFS_MAX_FSIZE-1 + 9 = 7 (overflow)
// Tries to punch the range (9,7) and the unit test at least appears to hang
rc = dfs_punch(dfs_mt, obj, 9, DFS_MAX_FSIZE-1);
```

**Comment by mchaarawi** [comment]
> > > I'm curious what the motivation is for NOT extending the file?
> > > FWIW, posix truncate DOES extend: https://man7.org/linux/man-pages/man2/ftruncate.2.html
> > 
> > 
> > after discussion with wangdi, we thought it was probably clearer if we emulate truncate when len=DFS_MAX_FSIZE
> > otherwise we treat this as a punch that does not extend the file. what do you think?
> 
> After playing with this some, it seems punch can do anything that posix truncate can do, so I think this is okay. We maybe just need to update the documentation for this PR's change: https://github.com/daos-stack/daos/blob/master/src/include/daos_fs.h#L394-L397
> 
> However, I did run into a separate but related bug where there isn't overflow protection for offset+len.
> Consider:
> 
> ```
> // Set size to 10
> rc = dfs_punch(dfs_mt, obj, 10, DFS_MAX_FSIZE);
> 
> // offset + len = DFS_MAX_FSIZE-1 + 9 = 7 (overflow)
> // Tries to punch the range (9,7) and the unit test at least appears to hang
> rc = dfs_punch(dfs_mt, obj, 9, DFS_MAX_FSIZE-1);
> ```

good catch, i will push a fix + test

**Comment by mchaarawi** [comment]
> > > I'm curious what the motivation is for NOT extending the file?
> > > FWIW, posix truncate DOES extend: https://man7.org/linux/man-pages/man2/ftruncate.2.html
> > 
> > 
> > after discussion with wangdi, we thought it was probably clearer if we emulate truncate when len=DFS_MAX_FSIZE
> > otherwise we treat this as a punch that does not extend the file. what do you think?
> 
> After playing with this some, it seems punch can do anything that posix truncate can do, so I think this is okay. We maybe just need to update the documentation for this PR's change: https://github.com/daos-stack/daos/blob/master/src/include/daos_fs.h#L394-L397
> 
> However, I did run into a separate but related bug where there isn't overflow protection for offset+len.
> Consider:
> 
> ```
> // Set size to 10
> rc = dfs_punch(dfs_mt, obj, 10, DFS_MAX_FSIZE);
> 
> // offset + len = DFS_MAX_FSIZE-1 + 9 = 7 (overflow)
> // Tries to punch the range (9,7) and the unit test at least appears to hang
> rc = dfs_punch(dfs_mt, obj, 9, DFS_MAX_FSIZE-1);
> ```

btw the hang can still occur in the situation where say you set file size = MAX;
and then punch everything up to MAX-1. it's not a hang really, but probably an assertion caused by a bug.. i will investigate this in a different ticket / PR

**Review by daltonbohning — APPROVED** [review]

**Review by wangdi1 — APPROVED** [review]

**Review by liuxuezhao — APPROVED** [review]

**Pull request merged**
