### PR TITLE
DAOS-10500 test: nvme/health.py: increase pool capacity (#9066)

### PR DESCRIPTION
**Pull request by daltonbohning**
Test-tag: nvme_health
Skip-unit-tests: true
Skip-fault-injection-test: true

nvme/health.py
- Increase total space usage from 75% to 90%

Signed-off-by: Dalton Bohning <dalton.bohning@intel.com>

### CODE REVIEW

**Comment by daltonbohning** [comment]
The single modified test passed: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9245/4/artifact/Functional%20Hardware%20Medium/nvme/health.py/results.html

But `pr,hw,medium` were also ran due to the python2/3 compatibility issue. Some of these tests failed, but are unrelated to this PR: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9245/4/tests/

**Review by shimizukko — APPROVED** [review]

**Review by jolivier23 — CHANGES_REQUESTED** [review]
Too late for 2.0.3, please add request_for_2.0.4 to ticket if you want to try to land.

**Comment by daltonbohning** [comment]
@jolivier23 Approved for 2.0.4: https://daosio.atlassian.net/browse/DAOS-10500

**Comment by sylviachanoiyee** [comment]
Build #4 has a lot of daos test rebuild ec failures. Probably unrelated to the changes in this PR since the changes restricted to health py/yml.
@daltonbohning , could you take a look at the failures anyway and see if it needs a ticket, segmentation fault looks pretty serious.
In the meantime, can you also retrigger test to see if it is reproducible? Thanks!

**Comment by daltonbohning** [comment]
@sylviachanoiyee All failures appear to be existing and since RESOLVED
- 3 DaosCoreTest failures due to pmem issue on wolf-122
  - configured SCM device /dev/pmem0 does not exist
  - Looking through DCO, some other nodes also had this, and the issue appears to have been resolved.
- DAOS_Rebuild_EC with segmentation fault
  - https://daosio.atlassian.net/browse/DAOS-10415
- DAOS_IO and DAOS_IO_EC
  - https://daosio.atlassian.net/browse/DAOS-10891

**Comment by rpadma2** [comment]
> @sylviachanoiyee All failures appear to be existing and since RESOLVED
> 
> * 3 DaosCoreTest failures due to pmem issue on wolf-122
>   
>   * configured SCM device /dev/pmem0 does not exist
>   * Looking through DCO, some other nodes also had this, and the issue appears to have been resolved.
>   * https://daosio.atlassian.net/browse/DAOS-10286
> * DAOS_Rebuild_EC with segmentation fault
>   
>   * https://daosio.atlassian.net/browse/DAOS-10415
> * DAOS_IO and DAOS_IO_EC
>   
>   * https://daosio.atlassian.net/browse/DAOS-10891

I would re-open those tickets and provide the test results from this PR.

**Comment by rpadma2** [comment]
(or) maybe the fixes are only under master and is not cherry picked to 2.0. Unless the changes not required for branches (2.0, 2.2).

**Comment by daltonbohning** [comment]
> (or) maybe the fixes are only under master and is not cherry picked to 2.0. Unless the changes not required for branches (2.0, 2.2).

Yes, very likely. I'll at least comment on the tickets to clarify whether they are/should be backported. Thanks!

**Pull request merged**
