### PR TITLE
DAOS-10880 control: Don't use multirail with UCX

### PR DESCRIPTION
**Pull request by kjacque**
Previously we were returning multirail network device names. This
patch returns to using a single device name.

Signed-off-by: Kris Jacque <kristin.jacque@intel.com>

### CODE REVIEW

**Review by Michael-Hennecke — CHANGES_REQUESTED** [review]
could this be merged into the tagged 2.2.0-rc1 ? many thanks...

**Comment by kjacque** [comment]
> could this be merged into the tagged 2.2.0-rc1 ? many thanks...

I've merged in the release/2.2 branch, so this should be up to date now.

**Review by mjmac — APPROVED** [review]

**Comment by kjacque** [comment]
The only test failure was this ticket, a fix for which was just landed today: https://daosio.atlassian.net/browse/DAOS-11872

**Review by jgmoore-or — APPROVED** [review]

**Review by jgmoore-or — CHANGES_REQUESTED** [review]
Sorry, but I need to update some mercury stuff before this can be landed.  Sorry for the delay.

**Review by knard-intel — APPROVED** [review]
Seems OK for what I understand.

**Review by jgmoore-or — APPROVED** [review]

**Comment by kjacque** [comment]
> The only test failure was this ticket, a fix for which was just landed today: https://daosio.atlassian.net/browse/DAOS-11872

Should be good to land now. This failure was the only one in CI. Haven't made any changes since.

**Pull request merged**
