### PR TITLE
DAOS-9085 test: Fix pool/list_verbose.py in weekly

### PR DESCRIPTION
**Pull request by shimizukko**
The test failed because the actual SCM size allocated to the pool
is slightly higher than what the user requested during the create.
Apply threshold to validate rather than the direct comparison.

Skip-build: true
Skip-unit-tests: true
Test-tag: list_verbose_basic
Signed-off-by: Makito Kano <makito.kano@intel.com>

### CODE REVIEW

**Review by dinghwah — APPROVED** [review]
LGTM

**Review by daltonbohning — COMMENTED** [review]
Is this maybe related to https://github.com/daos-stack/daos/pull/7374?

**Comment by shimizukko** [comment]
Yes, it's the same issue. They mention that it's rounded up by at most number_of_targets * (4K - 1) in [DAOS-9030](https://daosio.atlassian.net/browse/DAOS-9030) so I use this value to calculate the threshold. The exact value matching is probably not a good idea in this test because we call ilst pool --verbose a bunch of times and we would need to figure out the exact value for all of those calls.

**Comment by daltonbohning** [comment]
> Yes, it's the same issue. They mention that it's rounded up by at most number_of_targets * (4K - 1) in [DAOS-9030](https://daosio.atlassian.net/browse/DAOS-9030) so I use this value to calculate the threshold. The exact value matching is probably not a good idea in this test because we call ilst pool --verbose a bunch of times and we would need to figure out the exact value for all of those calls.

Ah, I see. Thanks for the explanation!

**Review by daltonbohning — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
These tests are currently failing in 2.0 weekly as well. Please backport to 2.0. Thanks.

**Pull request merged**
