### PR TITLE
DAOS-9922: Fix invalid readlink usage

### PR DESCRIPTION
**Pull request by knard-intel**
Fix invalid type of the len variable => fix always true condition of line 1675.

Signed-off-by: Cedric Koch-Hofer <cedric.koch-hofer@intel.com>

### CODE REVIEW

**Review by wiliamhuang — DISMISSED** [review]

**Review by bfaccini — DISMISSED** [review]

**Review by wiliamhuang — APPROVED** [review]

**Comment by wiliamhuang** [comment]
Still has compiling error to resolve.

**Review by bfaccini — APPROVED** [review]

**Review by wiliamhuang — APPROVED** [review]

**Review by wiliamhuang — APPROVED** [review]

**Review by bfaccini — APPROVED** [review]

**Comment by ashleypittman** [comment]
@daltonbohning is this the same as https://github.com/daos-stack/daos/pull/8183

**Comment by daltonbohning** [comment]
> @daltonbohning is this the same as #8183

@ashleypittman Yes. I originally avoided doing it this way to avoid potential overflow of the `ssize_t`, but I think it's realistically okay since `DFS_MAX_PATH` would not overflow `ssize_t`. So this is a simpler fix.

**Comment by jolivier23** [comment]
Landed #8183 which also addressed the issue

**Pull request closed without merging**
