### PR TITLE
DAOS-13833 dfuse: Fix an issue in readdir with seek to start. (#12593)

### PR DESCRIPTION
**Pull request by ashleypittman**
When seeking to the start of a directory do not try in
increase the anchor.

Add a test covering this case.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>
# ------------------------ >8 ------------------------
Skip-func-hw-test: true
Skip-func-test: true
Quick-Functional: true
Test-tag: dfuse

### CODE REVIEW

**Review by daltonbohning — APPROVED** [review]
Clean cherry-pick  so this just needs gatekeeper, right?

**Comment by mchaarawi** [comment]
sorry can't land this PR with no testing being done.

**Comment by ashleypittman** [comment]
Merged with the release branch. I think it still qualifies as a clean-cherry-pick.  I've also updated my commit hook to not apply test-tags on cherry-pick which was the problem before.

**Comment by mchaarawi** [comment]
> Merged with the release branch. I think it still qualifies as a clean-cherry-pick. I've also updated my commit hook to not apply test-tags on cherry-pick which was the problem before.

yea clean cherry-pick just gets you the option to not require reviews again. but we still want the tests to run on backports

**Pull request merged**
