### PR TITLE
DAOS-5460 vos: fail DTX commit when server out of space

### PR DESCRIPTION
**Pull request by Nasf-Fan**
When batched commit DTX entries, it is possible that the server
runs out of space. Under such case, related PMDK TX handle will
be aborted automatically. Then we cannot use related PMDK TX to
commit former processed DTX entries that will trigger assertion
in PMDK logic, instead the DTX batched commit should be aborted
with -DER_NOSPACE.

Signed-off-by: Fan Yong <fan.yong@intel.com>

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]
can you even abort if there is no space?

**Review by NiuYawei — APPROVED** [review]

**Comment by Nasf-Fan** [comment]
> can you even abort if there is no space?

The abort is PMDK TX abort, not DAOS transaction abort. My understand is that the PMDK TX abort only needs to discard former temporary modifications without additional space.

**Review by johannlombardi — APPROVED** [review]

**Comment by Nasf-Fan** [comment]
Rebuild r_0_10 failed for DAOS-5708.
Checksum test failed for DAOS-5745.
OSA_offline_drain timeout for DAOS-5538.

**Comment by Nasf-Fan** [comment]
@daos-stack/daos-gatekeeper , would you please to help force land this patch? Thanks!

**Pull request merged**
