### PR TITLE
DAOS-10472 bio: Use hugepages from any NUMA in legacy mode

### PR DESCRIPTION
**Pull request by tanabarr**
Use memory from any NUMA node when allocating DMA buffer when the
engine is using the legacy core allocation algorithm. Enable legacy
mode whenever a non-zero first_core value is specified in the server
config file or if a single engine on NUMA-0 is unpinned.

Required-githooks: true

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by NiuYawei — APPROVED** [review]

**Review by wangshilong — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]
Mostly OK for me.
Maybe we could emphasize in the _utils/config/daos_server.yml_ file that _first_core_ parameter deprecated in favor of _pinned_numa_node_, and this first parameter should be really used cautiously.

**Comment by tanabarr** [comment]
> Mostly OK for me. Maybe we could emphasize in the _utils/config/daos_server.yml_ file that _first_core_ parameter deprecated in favor of _pinned_numa_node_, and this first parameter should be really used cautiously.

yes I agree, I will apply the doc change either if I have to re-push or as part of a follow-up/future PR

**Review by mjmac — APPROVED** [review]
Code looks fine. I wonder if we should add a NOTICE-level log message that `first_core` is deprecated so that we can remove it in 2.6, though. Maybe we can even get away with removing it now? I'm not sure how widely-used the option is.

**Comment by tanabarr** [comment]
> Code looks fine. I wonder if we should add a NOTICE-level log message that `first_core` is deprecated so that we can remove it in 2.6, though. Maybe we can even get away with removing it now? I'm not sure how widely-used the option is.

I don't think @NiuYawei is in favour of removing it, it seems like it is still used in development and testing, hence the reason for this PR.

**Pull request merged**
