### PR TITLE
DAOS-9908 build: Build with go >= 1.17

### PR DESCRIPTION
**Pull request by mjmac**
Ensure that we are building RPMs with the latest release
available in our internal package repositories.

Signed-off-by: Michael MacDonald <mjmac.macdonald@intel.com>

### CODE REVIEW

**Review by tanabarr — APPROVED** [review]

**Review by tanabarr — APPROVED** [review]

**Review by brianjmurrell — COMMENTED** [review]
Does this specfile still build an RPM on all distros *without* out specially built go RPMs?  I.e. using the vendor supplied go packages.

**Comment by mjmac** [comment]
> Does this specfile still build an RPM on all distros _without_ out specially built go RPMs? I.e. using the vendor supplied go packages.

Yes. The el(7|8) and leap15 vendor packages `Provide: go` in addition to the per-distro package names, so they'll satisfy this requirement.

**Review by brianjmurrell — APPROVED** [review]
It would have been good to be able to test this change in absence of our own go toolchain, say, by keeping the toolchain update in a PR until a with/without (i.e. using `PR-repos:` for the with test) test could be done on daos.

In any case, I will trust that you have done enough testing to be confident that this still works in the wild, without our custom go toolchain.

**Comment by mjmac** [comment]
For the record:
```
[root@wolf-61 ~]# yum --disablerepo repo.dc.hpdd.intel.com_repository_daos-stack-el-7-x86_64-stable-local_ install 'go >= 1.14'
...
Resolving Dependencies                                                                                                                                                                              --> Running transaction check                                                                                                                                                                       ---> Package golang.x86_64 0:1.16.13-2.el7 will be installed                                                                                                                                        --> Processing Dependency: golang-bin = 1.16.13-2.el7 for package: golang-1.16.13-2.el7.x86_64                                                                                                      --> Processing Dependency: golang-src = 1.16.13-2.el7 for package: golang-1.16.13-2.el7.x86_64                                                                                                      --> Running transaction check                                                                                                                                                                       ---> Package golang-bin.x86_64 0:1.16.13-2.el7 will be installed                                                                                                                                    ---> Package golang-src.noarch 0:1.16.13-2.el7 will be installed                                                                                                                                    --> Finished Dependency Resolution                                                                                                                                                                                                                                                                                                                                                                      Dependencies Resolved                                                                                                                                                                                                                                                                                                                                                                                   ======================================================================================================================== Package                       Arch                      Version                          Repository               Size                                                                                                                                                         ========================================================================================================================Installing:                                                                  golang                        x86_64                    1.16.13-2.el7                    epel                    678 k                                                                             Installing for dependencies:                                                                                                                                                                         golang-bin                    x86_64                    1.16.13-2.el7                    epel                     90 M                                                                              golang-src                    noarch                    1.16.13-2.el7                    epel                    8.2 M                                                                                                                                                                                                                                                                                 Transaction Summary                                                                                                                                                                                 ========================================================================================================================Install  1 Package (+2 Dependent packages) 
```

```
wolf-37:~ # zypper mr -d 1
Repository 'daos-stack-opensuse-15-x86_64-stable-group' has been successfully disabled.
wolf-37:~ # zypper install 'go >= 1.14'
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 2 recommended packages were automatically selected:
  go-doc go1.17-doc

The following 6 NEW packages are going to be installed:
  go go-doc go-race go1.17 go1.17-doc go1.17-race

6 new packages to install.
Overall download size: 134.9 MiB. Already cached: 0 B. After the operation, additional 631.7 MiB will be used.
Continue? [y/n/v/...? shows all options] (y):
```

**Pull request merged**
