### PR TITLE
DAOS-9934 test: Add suppression from master branch

### PR DESCRIPTION
**Pull request by jolivier23**
The exact PR is tricky but this suppression is in master branch
and will cover the ofi leak in the ticket.

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
We haven't got master branch stable yet, it's too early to be cherry-picking partial fixes to 2.0.  If you want to start somewhere I'd copy the entire file from https://github.com/daos-stack/daos/pull/7953

**Comment by jolivier23** [comment]
This suppresses a recurrent failure on 2.0 though.  I'm not sure why we wouldn't want it?

**Comment by ashleypittman** [comment]
I think the PR I linked above modifies the suppression you're adding in order to make it more generic so you probably want to copy the modified one rather than the unmodified one.  I'm not saying this PR is wrong, but we're going to have to immediately update the branch again, even if we do land this.

**Comment by jolivier23** [comment]
Ashley has one from master that should also work

**Pull request closed without merging**
