### PR TITLE
CART-986: Re-enable ghost rank test

### PR DESCRIPTION
**Pull request by mallove79**

### CODE REVIEW

**Comment by mallove79** [comment]
[CI tests pass](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-7664/2/pipeline), except for one which _might_ be related to [DAOS-8980](https://daosio.atlassian.net/browse/DAOS-8980) (`Failed to start servers after format`).

**Comment by sylviachanoiyee** [comment]
@mallove79 , you need to run this test on centos7, centos8 and leap15.

**Comment by mallove79** [comment]
> @mallove79 , you need to run this test on centos7, centos8 and leap15.

https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7664/4/

**Comment by mallove79** [comment]
CI [tests pass](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-7664/4/pipeline).  [OSAOfflineReintegration failure](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-7664/4/testReport/junit/FTEST_osa/OSAOfflineReintegration/Test_Hardware___Functional_Hardware_Medium___2___osa_offline_reintegration_py_OSAOfflineReintegration_test_osa_offline_reintegration_server_stop_run_agent_config_transport_config_aggregation_blank_node_checksum_container_dmg_hosts_ior_clientslots_iorflags_loop_test_mdtest_client_processes_wr_size_32K_pool_pool_capacity_rebuild_server_config_servers_0_1_setup_snapshot_test_obj_class_test_rf_timeouts_3f75/) is known ([DAOS-9313](https://daosio.atlassian.net/browse/DAOS-9313)).

**Review by frostedcmos — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
Rerunning the GHA that failed

**Review by jgmoore-or — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
The test is passing on all 3 vm platform and test failures are unrelated. Landing.

**Pull request merged**
