### PR TITLE
DAOS-7849 build: Remove psm2 from the default build

### PR DESCRIPTION
**Pull request by rogue-developer**
This patch removes the psm2 and psm3 providers from the default DAOS build. The
providers can be enabled on demand by using the `INCLUDE` option.
For instance, to enable the psm2 provider:

`scons --build-deps=yes --config=force BUILD_TYPE=release INCLUDE=psm2 install`

The list of all the optional components can be retrieved by running the scons
help command.

`scons -h`

                    ¯\_(ツ)_/¯

Signed-off-by: Galen Erso <rogue.developer@outlook.com>

### CODE REVIEW

**Comment by rogue-developer** [comment]
The following commands are now supported:

Help
`$ scons -h`
`INCLUDE: Optional components to build`
`    (all|none|comma-separated list of names)`
`    allowed names: psm2 psm3`
`    default: none`
`    actual:`

Default option, does not build psm2 or psm3 proviers
`$ scons --build-deps=yes --config=force BUILD_TYPE=release install`

Enable psm2 provider
`$ scons --build-deps=yes --config=force BUILD_TYPE=release INCLUDE=psm2 install`

And so on...
`$ scons --build-deps=yes --config=force BUILD_TYPE=release INCLUDE=psm3 install`
`$ scons --build-deps=yes --config=force BUILD_TYPE=release INCLUDE=psm2,psm3 install`
`$ scons --build-deps=yes --config=force BUILD_TYPE=release INCLUDE=all install`
`$ scons --build-deps=yes --config=force BUILD_TYPE=release INCLUDE=none install`

**Comment by ashleypittman** [comment]
I wonder if we should change cart_init() to emit a D_WARN if psm2 is used?

My only other concern is there's still a version number in utils/build.config which is the version we're currently running.  We could leave that unchanged (forever?) or remove it, in which case the most recent commit would be used, neither of which is ideal.  It doesn't seem unreasonable that if psm2 is being built that somebody should have to put in their own version number/tag however.

**Comment by rogue-developer** [comment]
@ashleypittman I added the requested `D_WARN` message to `crt_init()`. I think that we can leave the current `psm2` version as is. My guess is that the current `psm2` version number in [utils/build.config](https://github.com/daos-stack/daos/blob/master/utils/build.config) is already supported by DAOS. So, to (hopefully) address your concern. I updated the documentation to inform the users about how they can enable `psm2` at build time and how they can put in their own version number.

**Review by jolivier23 — APPROVED** [review]

**Comment by jolivier23** [comment]
I've taken this and pushed it as a new pr #5998 so it will actually go through our full testing.  You are still listed as the PR creator.  I suspect you're not the real Galen Erso :)

**Pull request closed without merging**
