### PR TITLE
DAOS-4682 test: Adding capability for different timeout

### PR DESCRIPTION
**Pull request by saurabhtandan**
Adding capability to provide different timeout
for different tests under same test class for functional
test

Implementing the same for io/nvme_object.py

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

### CODE REVIEW

**Comment by saurabhtandan** [comment]
> Nice.
> 
> Verified it's working even. :-)
> 
> ```
> 2020-04-28 04:59:54,300 varianter        L0112 DEBUG| PARAMS (key=test_nvme_object_single_pool, path=/run/timeouts/*, default=None) => 900
> 2020-04-28 04:59:54,300 test             L0120 INFO | self.timeout: 900
> ```
> 
> Is even 900s overkill still though?
> 
> ```
> [2020-04-28T05:04:16.765Z]  (1/1) ./io/nvme_object.py:NvmeObject.test_nvme_object_single_pool;container-hosts-createmode-createset-createsize-createsvc-servers-server_manager-timeouts-7c68:  PASS (226.05 s)
> ```
> 
> Seems it's about 4x the actual test time.
> 
> Not really a suggestion for this PR but it might be interesting to have tests flagged/failed when their timeout is grossly overestimated.

I went by the last few results where it was taking about 10 mints so I thought of making timeout to be 15 mints. But seems like some patch landed recently might have improved the performance by some folds. I can resubmit with lower timeout.

**Comment by brianjmurrell** [comment]
> I went by the last few results where it was taking about 10 mints so I thought of making timeout to be 15 mints.

FWIW, a 15 min. timeout for a 10 minute test is perfect, IMHO.  I'm more a fan of 1.5x than 2x, personally.

> But seems like some patch landed recently might have improved the performance by some folds.

That is great news, that should be celebrated.

An interesting side effect of cause a test with an overestimated timeout to fail is that if a patch does have some kind of significant impact on performance, failing it's test it because the timeout is now too high will prompt the developer to lower the timeout.  Having that kind of change in the commit history could be immensely archaeologically useful to be able go back in time and identify patches that produced a significant performance benefit.

**Comment by brianjmurrell** [comment]
> Test stage Test CentOS 7 RPMs completed with status FAILURE. https://build.hpdd.intel.com//job/daos-stack/job/daos/view/change-requests/job/PR-2549/2/execution/node/537/log

This is fixed on master now.

**Comment by saurabhtandan** [comment]
CI test failures are not related to this PR
connect_test.py - DAOS-4687
multiple_creates_test.py - DAOS-4687
ior_small.py - DAOS-4510

**Pull request merged**
