### PR TITLE
DAOS-5947 tools: remove obj_ctl from daos(8)

### PR DESCRIPTION
**Pull request by berserk-fury**
On DAOS-5497 the obj_ctl utility was integrated into
the daos(8) utility. As a drawback an MPI dependency
was inherited. This patch splits the obj_ctl
functionality into a separated tool until a refactor
or redesigned effectively removes the MPI dependencies.

Signed-off-by: Jonathan Martinez Montes <jonathan.martinez.montes@intel.com>

### CODE REVIEW

**Comment by jolivier23** [comment]
[2020-10-29T22:17:36.692Z] error: Installed (but unpackaged) file(s) found:
[2020-10-29T22:17:36.692Z]    /usr/bin/obj_ctl
[2020-10-29T22:17:36.692Z]     File listed twice: /etc/daos/certs
[2020-10-29T22:17:36.692Z]     File listed twice: /etc/daos/certs/clients
[2020-10-29T22:17:36.692Z]     File listed twice: /etc/daos/certs/clients
[2020-10-29T22:17:36.692Z]     File listed twice: /etc/daos/daos_server.yml
[2020-10-29T22:17:36.692Z]     Installed (but unpackaged) file(s) found:
[2020-10-29T22:17:36.692Z]    /usr/bin/obj_ctl
[2020-10-29T22:17:36.692Z] RPM build errors:

I think you need a new version of daos.spec to revert the changes you made previously

**Comment by jolivier23** [comment]
You may also need changes to something for debian...that's new stuff

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
You need to update [debian/changelog](https://github.com/daos-stack/daos/blob/d0217a5cdad9a2a38b2f9a1e5734714b792d19b8/debian/changelog) also.

**Comment by berserk-fury** [comment]
> You need to update [debian/changelog](https://github.com/daos-stack/daos/blob/d0217a5cdad9a2a38b2f9a1e5734714b792d19b8/debian/changelog) also.

Right, I updated the changelog by using this command:

`dch -c debian/changelog -i`

**Review by jolivier23 — APPROVED** [review]

**Review by mchaarawi — APPROVED** [review]

**Review by brianjmurrell — APPROVED** [review]

**Pull request merged**
