### PR TITLE
DAOS-8103 cont: add new container types

### PR DESCRIPTION
**Pull request by johannlombardi**
Add container types for new I/O middleware developped over DAOS.
Fix typo in DAOS_PROP_CO_LAYOUT_UNK(N)OWN.

Signed-off-by: Johann Lombardi <johann.lombardi@intel.com>

### CODE REVIEW

**Comment by johannlombardi** [comment]
@zjf2012 it sounds like you have a lot of the defines are duplicated in the java code (HDF5, POSIX container type...). Not sure what is the purpose of this and whether we should update those definition. I leave it to you.
I was also wondering whether we should add a new container type for temporary spark data so that it can use the UNS too. Let me know what you think.

**Review by mchaarawi — DISMISSED** [review]

**Comment by zjf2012** [comment]
> @zjf2012 it sounds like a lot of the defines are duplicated in the java code (HDF5, POSIX container type...). Not sure what is the purpose of this and whether we should update those definition. I leave it to you.
> I was also wondering whether we should add a new container type for temporary spark data so that it can use the UNS too. Let me know what you think.

@johannlombardi , the related Java code was originally for creating a UNS path from Java command line so that user doesn't touch DAOS. But later we think that approach may not appropriate. We may need to remove related code.

**Comment by johannlombardi** [comment]
@zjf2012 ok, i will let you push a follow-up patch to remove this code then. What about my 2nd question? Do we need to add a container type for the shuffle data? If so, any name suggestion>

**Comment by zjf2012** [comment]
> @zjf2012 ok, i will let you push a follow-up patch to remove this code then. What about my 2nd question? Do we need to add a container type for the shuffle data? If so, any name suggestion?

For Spark, it uses two container types, one is posix for data input and output. The other is object container for shuffling data. So I assume you are only talking about the second one, object container.  We only use dkey/akey with value type of array to write/read data. For now, I see two benefits if shuffle has a dedicated container type. One is for container management. And the other is for convenience, such as mandatory container label so that we can have a simple DAOS URI. Do you see more? 
If you think there is enough reason to create a new container type, I would suggest type name of "spark-shuffle".

It would be great if we can later have more features for "spark-shuffle" container, like renaming akey or akey alias (mimic file renaming), daos server procedure to clean up temp shuffle data.

**Comment by johannlombardi** [comment]
Correct, i was referring to the 2nd one. I add a spark type (shuffle did not fit). I will land this patch and let you change the java code to use this container type going forward. Thanks!

**Review by mchaarawi — APPROVED** [review]

**Comment by zjf2012** [comment]
> Correct, i was referring to the 2nd one. I add a spark type (shuffle did not fit). I will land this patch and let you change the java code to use this container type going forward. Thanks!

cool, thanks.

**Pull request merged**
