### PR TITLE
DAOS-6319 rsvc: Optimize bootstrapping latencies

### PR DESCRIPTION
**Pull request by liw**
To optimize pool create latencies, when creating and bootstrapping an
rsvc with an initial membership, this patch lets one replica to start
campaigning without waiting for the election timeout. Also, the patch
replaces the 1 s constant backoff in ds_pool_svc_create with an
exponential one starting from a few milliseconds. The greatest factor of
the latency of a pool create operation will more likely be the creation
of the PMDK pools, as a result.

Signed-off-by: Li Wei <wei.g.li@intel.com>

### CODE REVIEW

**Comment by liw** [comment]
Preliminary reviews, please.

**Comment by liw** [comment]
The last CI session had what seemed to be a network problem in F_H_L; refreshed with the latest master to retrigger CI.

**Review by kccain — APPROVED** [review]

**Comment by liw** [comment]
Fixed a replicas pointer NULL dereference and merged with the latest master.

**Review by NiuYawei — APPROVED** [review]

**Comment by liw** [comment]
The last CI session had trouble cloning some Git repository; merged with the latest master to retry CI.

**Review by kccain — APPROVED** [review]

**Comment by liw** [comment]
CI testing can't pass until DAOS-7014 is resolved.

**Comment by berserk-fury** [comment]
@liw I just want to let you know that I tested this PR on [DAOS-4902](https://jira.hpdd.intel.com/browse/DAOS-4902) by creating 200 pools. Your patch reduces the time need from  37:56 min to 5:43 min

**Comment by liw** [comment]
> @liw I just want to let you know that I tested this PR on [DAOS-4902](https://jira.hpdd.intel.com/browse/DAOS-4902) by creating 200 pools. Your patch reduces the time need from 37:56 min to 5:43 min

@berserk-fury, thank you. Glad to hear that.

**Pull request merged**
