### PR TITLE
[DO NOT MERGE] DAOS-7134 tests: Add pool_map_ver check to rebuild_tests.py

### PR DESCRIPTION
**Pull request by saurabhtandan**
Adding pool_map_ver check to rebuild_tests.py.
Also remove unneccesary pool exclude and pool query
for rebuild check from the test.

Quick-Functional: true
Test-tag: rebuild_tests

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]

**Comment by saurabhtandan** [comment]
> Script looks good.
> There still lots of failures on single and multiple pools rebuild tests, might need to relaunch the tests after the intermittent failures resolved.

Yeah most seem like DAOS-7169, DAOS-7178. Regardless I need to discuss them with Di. The first run ran better than this. Had only 5 failures which were all DAOS-7169. Wanted to try once more, and that resulted it in many other failures.

**Comment by kprantis** [comment]
There were a lot of fixes to issues on master today - perhaps one more retry?

**Comment by saurabhtandan** [comment]
> There were a lot of fixes to issues on master today - perhaps one more retry?

Thanks, just re-pushed after rebase.

**Comment by kprantis** [comment]
The last master run only had one leap-15 error. Is it possible this patch is in some way inflaming other issues into more frequency?

**Comment by saurabhtandan** [comment]
> The last master run only had one leap-15 error. Is it possible this patch is in some way inflaming other issues into more frequency?

Was just talking to Mj Mac regarding DAOS-7169 and he thinks it is still resolved and the same error in my last run could be actually due to overloading of vm running the tests. So increasing the timeout value for server start slightly should be fine.
This PR is enabling more tests with multiple pools vs already enabled tests run single pool, so surely it seems like this PR is aggravating those issues above.
As far as last master run goes, I won't be surprised if it hits DAOS-7178 intermittently. Last couple of runs have been free of that.

**Comment by sylviachanoiyee** [comment]
Looking at the logs, I think there are failures I have not seen on master before:
centos7 rebuildtest 15 - I think Mjmac mentioned it might have been a corner case and he has a PR to fix it
leap15 rebuildtest 28, 32, 58, 62 - these are DAOS-7178 and yes, we might see it until it is fixed
leap15 rebuildtest 24, 25, 26, 49, 50 - I have not seen rebuildtest failed like this in master recently. Could you look at the failure and file a ticket if necessary? These are not caused by DAOS-7178, signature looks different.

**Comment by kprantis** [comment]
14 failures in test_multipool_rebuild

**Comment by sylviachanoiyee** [comment]
The latest build #6 has dmg cmd failure I have not seen on master recently.
And the PR also needs another approval.

**Comment by saurabhtandan** [comment]
> The latest build #6 has dmg cmd failure I have not seen on master recently.
> And the PR also needs another approval.

Please wait on this PR. Do Not Merge.
As per Rebuild working group discussions we are working on couple of issues associated with the current failures happening as part of this PR. Let's not introduce new failures to master.
I will add DO NOT MERGE to the title of the PR until it is ready to merge and we already don't have any gatekeeper attached to it which is good.

**Pull request closed without merging**
