### PR TITLE
DAOS-6713 Agent: ofi+verbs;ofi_rxm unavailable with systemd

### PR DESCRIPTION
**Pull request by jbrosenz**
The verbs provider was no longer available when running
    the daos_agent via systemd.  The daos_server was capable
    of finding and using the verbs provider, but the agent
    was not.  This mismatch caused the agent to provide the
    default connection information to the client, which was
    not suitable for a valid verbs connection.

    The root cause of the failure was a lack of memory
    resources available to the daos_agent service.
    libfabric could not initialize the queue pairs with the
    default memory limits.

    Removing the memory limitation for the daos_agent service
    addresses the problem.

Signed-off-by: Joel Rosenzweig <joel.b.rosenzweig@intel.com>

### CODE REVIEW

**Review by johannlombardi — DISMISSED** [review]
Just curious why we are initializing queue pairs in the agent? I thought that we were just scanning interfaces and providers...
In the future, we might always want to limit the agent to core 0 to limit noise for application. Not sure whether we can do that easily with systemd.

**Review by dpquigl — DISMISSED** [review]
LGTM

**Comment by jbrosenz** [comment]
> Just curious why we are initializing queue pairs in the agent? I thought that we were just scanning interfaces and providers...
> In the future, we might always want to limit the agent to core 0 to limit noise for application. Not sure whether we can do that easily with systemd.

@johannlombardi That's an artifact of libfabric performing some initialization upon performing a fabric scan on behalf of the agent.  The bread crumbs it left behind in its debug log suggested a memory allocation failure relating to queue pairs.  I didn't take it deeper than that, other than to determine that it was failing because it didn't have enough memory resources to do what it needed to do.

**Review by mjean308 — APPROVED** [review]
lgtm

**Comment by jbrosenz** [comment]
I'm looking at the logs to understand the failure.  I don't understand what is happening yet.

**Comment by jbrosenz** [comment]
Same solution as the original commit.  This time, the CI run is all green.  I had to try a few debug runs to get more data on the earlier failures.

**Review by mjmac — APPROVED** [review]

**Review by tanabarr — APPROVED** [review]

**Pull request merged**
