### PR TITLE
DAOS-5807 test: update log_mask

### PR DESCRIPTION
**Pull request by rpadma2**
Quick-build: true
Skip-unit-tests: true
Skip-func-hw-test-small: true
Skip-func-hw-test-medium: true

Summary: Update the log_mask for debugging

Signed-off-by: Padmanabhan <ravindran.padmanabhan@intel.com>

### CODE REVIEW

**Review by wangdi1 — APPROVED** [review]
thanks.

**Review by sylviachanoiyee — APPROVED** [review]

**Comment by sylviachanoiyee** [comment]
@rpadma2 , can you check why fn hw large stage failed? I don't see any test failure though.

**Comment by rpadma2** [comment]
Posted the information on ESAD channel. I don't see any issues with the changes. The Large test results are fine. Also, the online reintegration test passed which is the YAML file modified by this PR. I think it can be force landed by the gatekeeper.

**Comment by sylviachanoiyee** [comment]
Looks like it failed archiving related to known issue
https://jira.hpdd.intel.com/browse/DAOS-5975

**Pull request merged**
