### PR TITLE
DAOS-6726 rsvc: Add logging to rsvc reference counting.

### PR DESCRIPTION
**Pull request by ashleypittman**
There appears to be an intermittent reference leak with
this structure, so improve and add logging to the ref
counting code.

Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

### CODE REVIEW

**Comment by ashleypittman** [comment]
This was intended as a reproducer for something that happens on master ~5-10% of the time, but after running 20 iterations it hasn't reproduced it, but I'm wondering if this code is worth landing anyway.

**Comment by dmiter** [comment]
Does https://github.com/daos-stack/daos/pull/6308 resolve the reference leak? For performance reason I would like to avoid any logging inside reference counting. In other case make it conditional compiled in by demand.

**Comment by ashleypittman** [comment]
> Does #6308 resolve the reference leak? For performance reason I would like to avoid any logging inside reference counting. In other case make it conditional compiled in by demand.

No, it doesn't resolve the issue.  I'm just trying to get logs of what is happening.

**Review by jolivier23 — APPROVED** [review]

**Review by liw — CHANGES_REQUESTED** [review]
I prefer not to land this patch if possible. Can we focus on #6308 (by the way, @ashleypittman, why asserting that #6308 doesn't fix the leak?) first and see if it fixes the leak, please?

**Comment by ashleypittman** [comment]
> I prefer not to land this patch if possible. Can we focus on #6308 (by the way, @ashleypittman, why asserting that #6308 doesn't fix the leak?) first and see if it fixes the leak, please?

Fine with me.  I wasn't asserting that #6308 doesn't fix the leak, just thinking about what you said on Skype that you hadn't been able to verify it.  I'd like to keep this PR open however in case we do need more debugging later on.

**Comment by liw** [comment]
> Fine with me. I wasn't asserting that #6308 doesn't fix the leak, just thinking about what you said on Skype that you hadn't been able to verify it. I'd like to keep this PR open however in case we do need more debugging later on.

Sure. Let's keep this around just in case.

**Pull request closed without merging**
