### PR TITLE
DAOS-11182 test: Increase timeout for pool/create_all_hw.py

### PR DESCRIPTION
**Pull request by knard-intel**
# Description

Increase the timeout of functional test pool/create_all_hw.py.

Required-githooks: true

### CODE REVIEW

**Comment by knard-intel** [comment]
Modification of the tests have been validated with running it 10 times:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9815/1/testReport/FTEST_pool/PoolCreateAllHwTests/

**Review by shimizukko — APPROVED** [review]

**Review by daltonbohning — APPROVED** [review]
FYI - When modifying _**only a single test case**_ it's better to use these pragmas so only the corresponding stages are ran:
```
Test-tag: pool_create_all
Test-repeat: 20
```
Which would run only HW Large, and only this test case. Whereas with the other tags, VM and HW Small, Medium, Large were ran: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9815/1/pipeline/
Not a requirement - just resource conservation

**Comment by knard-intel** [comment]
> FYI - When modifying _**only a single test case**_ it's better to use these pragmas so only the corresponding stages are ran:
> 
> ```
> Test-tag: pool_create_all
> Test-repeat: 20
> ```
> 
> Which would run only HW Large, and only this test case. Whereas with the other tags, VM and HW Small, Medium, Large were ran: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9815/1/pipeline/ Not a requirement - just resource conservation

Yes, I have seen this in the Jenkins Pipeline :'(
Every time I need this kind of pragma, I go to the confluence page on pragmas and I miss-understand it => At this point of memory loss, I am going to pin point a stickers on my screen to try to not forget it next time ;)
Thanks for the reminder.

**Comment by daltonbohning** [comment]
> Yes, I have seen this in the Jenkins Pipeline :'( Every time I need this kind of pragma, I go to the confluence page on pragmas and I miss-understand it => At this point of memory loss, I am going to pin point a stickers on my screen to try to not forget it next time ;) Thanks for the reminder.

What is missing in the documentation that would make this easier to understand?

**Pull request merged**
