### PR TITLE
DAOS-14126 pool: Debug fetch_hdls (#12889)

### PR DESCRIPTION
**Pull request by liw**
Because I couldn't reproduce the hang in pool_fetch_hdls_ult_abort even after a considerable effort both manually and through CI, I have to propose landing these extra logging.

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by daltonbohning** [comment]
Still awaiting merge approval for 2.4.2

**Comment by daltonbohning** [comment]
Merge approval granted, but last commit was 5 weeks ago. Will you please merge latest 2.4 and re-add gatekeeper when ready?

**Comment by liw** [comment]
@daos-stack/daos-gatekeeper, this backport debug PR has waited almost 3 months. Could you let me know what it takes to get it landed, please?

**Comment by mchaarawi** [comment]
> @daos-stack/daos-gatekeeper, this backport debug PR has waited almost 3 months. Could you let me know what it takes to get it landed, please?

this is approved to merge to 2.4.3 and not 2.4.2.
so it cannot be merged by gatekeepers until 2.4.2 is officially released.

**Comment by liw** [comment]
> > @daos-stack/daos-gatekeeper, this backport debug PR has waited almost 3 months. Could you let me know what it takes to get it landed, please?
> 
> this is approved to merge to 2.4.3 and not 2.4.2. so it cannot be merged by gatekeepers until 2.4.2 is officially released.

Hmm, I see. :( Thanks, @mchaarawi.

**Review by kccain — APPROVED** [review]

**Comment by liw** [comment]
Cherry-picked into #14019.

**Pull request closed without merging**
