### PR TITLE
DAOS-7930 dtx: pool based DTX aggregation threshold

### PR DESCRIPTION
**Pull request by Nasf-Fan**
Currently, the committed DTX table in DRAM in container based. For
the committed DTX table, the count threshold of DTX aggregation is
about 1^20 entries. If there are multiple (assume 'N') containers
maintained by the same engine, then there maybe at most 1^ 20 * N
committed DTX entries. If "N" is too large, then may cause server
out of memory.

This patch changes the container based DTX aggregation threshold
as pool based. Then the total committed DTX entries in DRAM will
be much reduced for multiple containers case.

The DTX aggregation thresholds are also adjusted:

1. Count threshold: 1^20 => 1^20 * 3
2. Time threshold: 90 sec => 180 sec

The in-DRAM committed DTX entry size is reduced to 36 bytes per entry.

Signed-off-by: Fan Yong <fan.yong@intel.com>

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]
Is the memory leak reported by NLT related to the patch?

**Comment by Nasf-Fan** [comment]
> Is the memory leak reported by NLT related to the patch?
Which memory leak you mean? It is true that the old version miss to set some value as to leak some DRAM, related issue has been fixed in the latest version (set 4).

**Comment by Nasf-Fan** [comment]
Resolve merge conflict.

**Comment by Nasf-Fan** [comment]
@jolivier23 , @niu , @liang , would you please to help review the patch, it needs to be landed before 2.0 feature frozen. Thanks!

**Review by NiuYawei — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by ashleypittman** [comment]
FYI - this PR appears to have introduced a memory leak, there's a new leak in master builds starting with this PR and I've checked the PR build and that also shows the regression.

**Pull request merged**
