### PR TITLE
DAOS-5602 object: Fix CPD epoch uncertainty

### PR DESCRIPTION
**Pull request by liw**
ds_obj_dtx_leader_ult drops the UNCERTAINTY flags for _all_ writes when
the epoch is chosen locally. This, however, is safe only for writes to
_local_ RDGs (i.e., RDGs that include the local rank). This patch
removes the incorrect optimization and leaves a correct version to
future work.

Signed-off-by: Li Wei <wei.g.li@intel.com>

### CODE REVIEW

**Review by jolivier23 — APPROVED** [review]

**Comment by liw** [comment]
ior_small: DAOS-5610
nvme_object: DAOS-4943
macsio: DAOS-5587
mdtest: DAOS-5610
osa tests: DAOS-5610
io_consistency: DAOS-5610
server_restart: DAOS-4943
aggregation_basic: DAOS-5610

**Comment by mchaarawi** [comment]
> ior_small: DAOS-5610
> nvme_object: DAOS-4943
> macsio: DAOS-5587
> mdtest: DAOS-5610
> osa tests: DAOS-5610
> io_consistency: DAOS-5610
> server_restart: DAOS-4943
> aggregation_basic: DAOS-5610

This isn't anything against your patch, but given the amount of failing tests there, it really is worrisome to land patches.

**Review by mchaarawi — APPROVED** [review]

**Review by Nasf-Fan — APPROVED** [review]

**Comment by liw** [comment]
> This isn't anything against your patch, but given the amount of failing tests there, it really is worrisome to land patches.

No problem. Let's retest it...

**Comment by liw** [comment]
evict_test: DAOS-5610
ior_small: DAOS-4989
macsio: DAOS-5591

**Pull request merged**
