### PR TITLE
DAOS-7204 Test: Enabled EC Aggregation tests in ci.

### PR DESCRIPTION
**Pull request by ravalsam**
Quick-Functional: true
Test-tag-hw-large: ec_aggregation

Signed-off-by: Samir Raval <samir.raval@intel.com>

### CODE REVIEW

**Comment by ravalsam** [comment]
Test ran in Ci and result can be found from https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6190/2/artifact/Functional%20Hardware%20Large/erasurecode/ec_aggregation.py/

**Comment by ravalsam** [comment]
All EC aggregation tests got passed in Ci https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-6190/4/artifact/Functional%20Hardware%20Large/erasurecode/ec_aggregation.py/

I will restart the default Ci tests

**Review by rpadma2 — APPROVED** [review]
LGTM.

**Review by saurabhtandan — APPROVED** [review]
LGTM

**Pull request merged**
