### PR TITLE
DAOS-9820 test: simplify datamover test base

### PR DESCRIPTION
**Pull request by daltonbohning**
Skip-unit-tests: true
Skip-fault-injection-test: true

Test-tag: datamover

Simplify the data mover test base to make it easier to add tests.

- Enhance and move `format_daos_path` to `duns_utils.uns_path`
- New `set_dm_params` that takes a simplified set of params.
  - Deprecate, but still support, `set_datamover_params`
- Rename `self.parent` to `self.posix_root`

Signed-off-by: Dalton Bohning <dalton.bohning@intel.com>

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]

**Comment by daltonbohning** [comment]
Ping reviewers

**Comment by daltonbohning** [comment]
One existing test failure: https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-8109/15/tests
Ticket: https://daosio.atlassian.net/browse/DAOS-10258

**Comment by daltonbohning** [comment]
Ping reviewers

**Review by dinghwah — APPROVED** [review]
Scripts are look good.
We might want to include more tests for the utils files change.

**Comment by daltonbohning** [comment]
> Scripts are look good. We might want to include more tests for the utils files change.

I did run with `Test-tag: datamover,-iosysadmin`, which will run every test using the test base, except a known failure. And the new function `set_dm_params` is called by the old function `set_datamover_params` for backwards compatibility, so the changes are tested.

**Pull request merged**
