### PR TITLE
DAOS-7130 metrics: Add ephemeral metrics support

### PR DESCRIPTION
**Pull request by kjacque**
- Add functions for managing ephemeral metrics in shared
  memory segments. Outside of these functions, the ephemeral
  nature of these directories should be invisible to
  users/callers.
- Add infrastructure for per-pool metrics and example.
- Format per-pool metrics nicely in Prometheus exporter.
- Add convenience functions for common tree traversal
  operations for clients.
- Add clean shutdown for Prometheus exporter HTTP server.
- Refactor utility functions for managing shmem.
- Update d_tm_conv_ptr function to specifically deal with
  context for the node. This allows us to find the correct
  shmem region to convert with via the context.

Signed-off-by: Kris Jacque <kristin.jacque@intel.com>

### CODE REVIEW

**Review by mjmac — COMMENTED** [review]
Looks good so far, @kjacque. Out of curiosity, have you been able to test the new stuff with the Prometheus exporter? It would be nice to figure out how we can create a test tree of metrics and verify that the `telemetry.CollectMetrics()` code works properly.

**Comment by kjacque** [comment]
> Looks good so far, @kjacque. Out of curiosity, have you been able to test the new stuff with the Prometheus exporter? It would be nice to figure out how we can create a test tree of metrics and verify that the `telemetry.CollectMetrics()` code works properly.

I did a manual sanity check but the new stuff isn't being picked up yet. We're only collecting gauges and counters, and the sample property I added to pools is a timestamp. That's a good idea, though, verifying what it looks like in the Prometheus exporter. I think integration testing at that level is plausible, but I'd rather add that in a separate PR if that's all right.

**Comment by kjacque** [comment]
With the latest commit, the Prometheus exporter is traversing the tree and picking up the per-pool metric that I added (I changed the name in this round because it felt unclear in the dmg output). For the time being, I'm serving timestamps as gauges with value == Unix time in seconds.

Here's example output on my dev VM with two pools:
```
kris@dragon:~$ dmg -o ~/dmg.yml telemetry metrics query -m engine_pool_started_at
connecting to localhost:9191...
- Metric Set: engine_pool_started_at (Type: Gauge)
  Last time the pool started
    Metric Labels                                              Value           
    ------ ------                                              -----           
    Gauge  (pool=6cc659de-006f-4090-861b-7a945d03c9a5, rank=0) 1.62102982e+09  
    Gauge  (pool=88b21011-2fdb-42bf-9737-56c9ebd8ba08, rank=0) 1.621029711e+09 

kris@dragon:~$ 
```

**Review by mjmac — APPROVED** [review]
Ah, this looks even better! The new traversal helpers are much nicer to read/use.

**Comment by kjacque** [comment]
Some open questions I'd like to address in a follow-on: How often should the client check if an ephemeral branch has been destroyed? Should the client be able to decide when to close specific branches, or should it periodically call a cleanup method to check all open shmem regions and close those that have been deleted?

In practice the metrics producer clears the link to the ephemeral dir in the tree when it deletes the ephemeral dir, so the client can't run into it again organically while traversing the tree, unless the producer creates a new shmem region with the same key. This is possible but unlikely.

This cleanup issue only affects the client side of telemetry operations, so I don't think it's necessarily bad to clean up its own list of open shmem links every now and then. The question is how often, and should it be called automatic under the covers, or something we expect client applications to do on their own? Or both?

**Comment by jbrosenz** [comment]
> Some open questions I'd like to address in a follow-on: How often should the client check if an ephemeral branch has been destroyed? Should the client be able to decide when to close specific branches, or should it periodically call a cleanup method to check all open shmem regions and close those that have been deleted?
> 
> In practice the metrics producer clears the link to the ephemeral dir in the tree when it deletes the ephemeral dir, so the client can't run into it again organically while traversing the tree, unless the producer creates a new shmem region with the same key. This is possible but unlikely.
> 
> This cleanup issue only affects the client side of telemetry operations, so I don't think it's necessarily bad to clean up its own list of open shmem links every now and then. The question is how often, and should it be called automatic under the covers, or something we expect client applications to do on their own? Or both?

Perhaps it's worthwhile to poll the status of a region to see if it has been marked for deletion, once it reaches a certain age.  If it has expired, then do the client side cleanup.  Otherwise, check it at periodic intervals until it expires.  It should be fairly lightweight to maintain the client data with timers that trigger a cleanup event at the appropriate time.  You could also look at producing an event that originates from the telemetry producer, that occurs at some watermark when resources are running low.  That event would be used to signal the control plane consumer to cleanup, or whatever you now need it to do in response.

**Comment by kjacque** [comment]
> Perhaps it's worthwhile to poll the status of a region to see if it has been marked for deletion, once it reaches a certain age. If it has expired, then do the client side cleanup. Otherwise, check it at periodic intervals until it expires. It should be fairly lightweight to maintain the client data with timers that trigger a cleanup event at the appropriate time. You could also look at producing an event that originates from the telemetry producer, that occurs at some watermark when resources are running low. That event would be used to signal the control plane consumer to cleanup, or whatever you now need it to do in response.

The polling solution is along the lines of what I was thinking, for simplicity's sake. Events are a good idea but I'm not sure if it's worthwhile to put that much infrastructure in yet, when the control plane is really the main consumer. During standup this morning @mjmac made a good point, that we are really setting the standard for what telemetry consumers look like. So it may be reasonable to say clients should poll periodically to clean up deleted resources held.

**Review by tanabarr — APPROVED** [review]
struggled to follow at some points, great work

**Pull request merged**
