### PR TITLE
DAOS-4622 duns: special path format for direct access

### PR DESCRIPTION
**Pull request by mchaarawi**
Allow users to pass a special path to duns_resolve_path() with a pool and container uuid for direct access instead of looking in extended attributes. The format of the path has to be:
`daos://pool_uuid/container_uuid/...`
or without the prefix `daos:` by setting the da_no_prefix field in the attr struct and passing the pool and container in the path:
`/pool_uuid/container_uuid/...`

Signed-off-by: Mohamad Chaarawi <mohamad.chaarawi@intel.com>

### CODE REVIEW

**Comment by johannlombardi** [comment]
Patch looks good, but i tend to use a standard instead (e.g. a URI like daos://pooluuid/containeruuid). Is there any library we could use for the parsing?

**Comment by mchaarawi** [comment]
> Patch looks good, but i tend to use a standard instead (e.g. a URI like daos://pooluuid/containeruuid). Is there any library we could use for the parsing?

The problem is that this would look ugly for MPIIO. user would need to pass something like:
daos:daos://pooluuid/containeruuid. very easy to make a mistake and eliminate the first one.

**Review by johannlombardi — APPROVED** [review]

**Review by zjf2012 — APPROVED** [review]
looks good. I'll update the Java wrapper and Hadoop DAOS accordingly.

**Review by bfaccini — APPROVED** [review]

**Comment by mchaarawi** [comment]
1 unrelated rebuild test failure

**Comment by zjf2012** [comment]
@mchaarawi Besides UUIDs, some additional info is needed to connect to pool, like grp and svc, according to the API. I put these info as extended attributes of the UNS path by myself for now. Do you have better solution? like providing API in UNS to store customized attributes?

int
daos_pool_connect(const uuid_t uuid, **const char *grp**,
		  **const d_rank_list_t *svc**, unsigned int flags,
		  daos_handle_t *poh, daos_pool_info_t *info, daos_event_t *ev);

thanks.

**Comment by mchaarawi** [comment]
> @mchaarawi Besides UUIDs, some additional info is needed to connect to pool, like grp and svc, according to the API. I put these info as extended attributes of the UNS path by myself for now. Do you have better solution? like providing API in UNS to store customized attributes?
> 
> int
> daos_pool_connect(const uuid_t uuid, *_const char _grp__,
> *_const d_rank_list_t _svc__, unsigned int flags,
> daos_handle_t *poh, daos_pool_info_t *info, daos_event_t *ev);
> 
> thanks.

right, so it wouldn't be right to put those in there, because we are going to make that automatic through the agent in the near future. for now you should be able to use like an env variable?

**Comment by zjf2012** [comment]
> > @mchaarawi Besides UUIDs, some additional info is needed to connect to pool, like grp and svc, according to the API. I put these info as extended attributes of the UNS path by myself for now. Do you have better solution? like providing API in UNS to store customized attributes?
> > int
> > daos_pool_connect(const uuid_t uuid, *_const char _grp__,
> > *_const d_rank_list_t _svc__, unsigned int flags,
> > daos_handle_t *poh, daos_pool_info_t *info, daos_event_t *ev);
> > thanks.
> 
> right, so it wouldn't be right to put those in there, because we are going to make that automatic through the agent in the near future. for now you should be able to use like an env variable?

sounds good. thanks

**Comment by zjf2012** [comment]
> > @mchaarawi Besides UUIDs, some additional info is needed to connect to pool, like grp and svc, according to the API. I put these info as extended attributes of the UNS path by myself for now. Do you have better solution? like providing API in UNS to store customized attributes?
> > int
> > daos_pool_connect(const uuid_t uuid, *_const char _grp__,
> > *_const d_rank_list_t _svc__, unsigned int flags,
> > daos_handle_t *poh, daos_pool_info_t *info, daos_event_t *ev);
> > thanks.
> 
> right, so it wouldn't be right to put those in there, because we are going to make that automatic through the agent in the near future. for now you should be able to use like an env variable?

@mchaarawi , have you put those into the agent? or any ticket to track?

**Pull request merged**
