### PR TITLE
DAOS-6869 tests: Fix large_file_count.py in weekly run

### PR DESCRIPTION
**Pull request by saurabhtandan**
Fix large_file_count.py in weekly run

Test-tag-hw-large: pr,hw,large largefilecount

Signed-off-by: Saurabh Tandan <saurabh.tandan@intel.com>

### CODE REVIEW

**Review by shimizukko — APPROVED** [review]
LGTM

**Review by dinghwah — APPROVED** [review]
LGTM

**Comment by saurabhtandan** [comment]
nlt test seem to be failing due to DAOS-6726

**Comment by ashleypittman** [comment]
> nlt test seem to be failing due to DAOS-6726

It's DAOS-6572 and https://github.com/daos-stack/daos/pull/4771 is in review to resolve the issue

**Pull request merged**
