### PR TITLE
DAOS-14573 bio: Skip role assignment for hotplugged bdev (#13280)

### PR DESCRIPTION
**Pull request by tanabarr**
In VMD mode with PMem SCM, hotplug add event (triggered through SPDK
rpc in engine) was not resulting in bdev being reinstated in DAOS. The
cause was a regression related to MD-on-SSD code changes where role
could not be decoded from bdev_name. In the case where SPDK is being
initialised through daos_nvme.conf, role info is encoded into the name
whereas during hotplug scanning, the name is generic and doesn't
include the role info.

Fix by passing roles into create_bio_bdev and decode as before for
init case but use a default value for scan/hotplug case (as the
bdev_name doesn't have role info). In the latter scenario make default
role assignment consistent with operating mode (unset for PMem and
DATA for MD-on-SSD).

Also fix LED reporting by performing pci address match before checking
type.

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by NiuYawei — APPROVED** [review]

**Comment by tanabarr** [comment]
CI failures attributable to:
- log file processing error
- DAOS-14593

**Comment by tanabarr** [comment]
clang format failures seem valid, fixing and re-pushing

**Review by NiuYawei — APPROVED** [review]

**Comment by tanabarr** [comment]
single known CI failure DAOS-14593

**Comment by NiuYawei** [comment]
> single known CI failure DAOS-14593

Hi, @tanabarr , FYI, I can't land PR with test failures since I don't have the "force landing" permission. You could ask other gatekeepers (like @gnailzenh or @jolivier23 ) with "force landing" permission or try to re-trigger the test.

**Review by gnailzenh — APPROVED** [review]

**Pull request merged**
