### PR TITLE
DAOS-14225 control: Prevent duplicate call to SetRank

### PR DESCRIPTION
**Pull request by tanabarr**
Remove legacy workaround where SetRank is called directly as a special
case when rank 0 is bootstrapping the DAOS system as this creates a
window where SetRank can be called a second time. The localJoin flag
is removed from JoinResp and SetRank will return immediately if rank
has already been set as ready.

Features: control
Required-githooks: true

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by tanabarr** [comment]
to verify this fix, https://github.com/daos-stack/daos/pull/13060 is running with the following pragmas:
```    Test-nvme: auto_md_on_ssd
    Test-tag: test_create_pool_quantity
    Test-repeat: 10```

**Comment by tanabarr** [comment]
All 10 repetitions of affected test completed successfully, this fix looks good:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13060/3/testReport/FTEST_pool/PoolCreateCapacityTests/

**Review by kjacque — APPROVED** [review]
Nice work. Thanks for cleaning this up!

**Review by knard-intel — APPROVED** [review]
Seems OK for what I understand.

**Comment by tanabarr** [comment]
@daos-stack/daos-gatekeeper can this please be landed

**Review by gnailzenh — APPROVED** [review]

**Pull request merged**
