### PR TITLE
DAOS-15930 test: extend_simple add FI required macro call

### PR DESCRIPTION
**Pull request by kccain**
In release 2.6 RC1 testing certain daos_test -B (extend_simple)
cases failed (EXTEND6, EXTEND8, EXTEND14). It was found that, although
some extend tests use fault injection via dfs_extend_internal(), they
did not invoke FAULT_INJECTION_REQUIRED(). Tthis can result in
unpredictable execution (e.g., hangs) when running with a daos build
whose BUILD_TYPE=release.

This change adds the FAULT_INJECTION_REQUIRED() macro call,
and makes some minor changes to the test code to make the output
reflect what steps the test executes - to facilitate debugging.

Skip-unit-tests: true
Skip-fault-injection-test: true
Test-tag: test_daos_extend_simple
faults-enabled: false

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by kccain** [comment]
This is a cherry-pick of master PR https://github.com/daos-stack/daos/pull/14667

Jenkins build https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14668/2/ in progress at priority 2 as discussed with @sbpeirce .

**Comment by kccain** [comment]
tests passed in all 3 environments (ucx, verbs, verbs MD on SSD) https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-14668/2/testReport/FTEST_daos_test/DaosCoreTest/

Awaiting review and landing of the master PR first (PR #[14667](https://github.com/daos-stack/daos/pull/14667)

**Comment by kccain** [comment]
master PR landed, commit [f3f959a](https://github.com/daos-stack/daos/commit/f3f959ab86f3d72b1a24ee3b535131b60a9f8276)

awaiting approval to merge this backport PR to release/2.6 branch

**Comment by kccain** [comment]
This PR is still ready (no merge conflicts, and successful CI testing in Jenkins build 2), so once approval to merge is given I'll request review from daos-gatekeeper.

**Review by daltonbohning — APPROVED** [review]

**Pull request merged**
