### PR TITLE
DAOS-5412 test: checksum tests use dmg (pool mgmt)

### PR DESCRIPTION
**Pull request by rpadma2**
Summary:
 Update the basic_checksum.py script to use dmg for pool creation.

Signed-off-by: Padmanabhan <ravindran.padmanabhan@intel.com>

### CODE REVIEW

**Review by mjmac — COMMENTED** [review]
Looks fine to me. The docstring for the test class still has the following comment, though:

```
This test case doesn't use TestPool/
TestContainer for now. TestPool/TestContainer
needs changes to support checksum.
```

Is that not correct? If so, then the comment should be removed...

**Review by shimizukko — DISMISSED** [review]
Looks good to me

**Comment by rpadma2** [comment]
> Looks fine to me. The docstring for the test class still has the following comment, though:
> 
> ```
> This test case doesn't use TestPool/
> TestContainer for now. TestPool/TestContainer
> needs changes to support checksum.
> ```
> 
> Is that not correct? If so, then the comment should be removed...

Agree.. The docstring is incorrect. add_pool uses internally TestPool. Removed the references to TestPool/TestContainer in docsttring and pushed the patch,.

**Review by shimizukko — APPROVED** [review]
Looks good to me

**Review by mjmac — APPROVED** [review]

**Comment by rpadma2** [comment]
iorsmall failure known issue : https://jira.hpdd.intel.com/browse/DAOS-4989

**Comment by rpadma2** [comment]
Hi Gatekeeper, This PR is ready to be landed. One failure is a known issue.

**Comment by rpadma2** [comment]
Sylvia is on vacation this week. Can any other gatekeeper merge this change? Thanks.

**Comment by mjmac** [comment]
> 
> 
> Sylvia is on vacation this week. Can any other gatekeeper merge this change? Thanks.

I'll land it after the fix for DAOS-5622 has landed to master. Shouldn't have any conflicts with this PR.

**Comment by rpadma2** [comment]
> > Sylvia is on vacation this week. Can any other gatekeeper merge this change? Thanks.
> 
> I'll land it after the fix for DAOS-5622 has landed to master. Shouldn't have any conflicts with this PR.

Ok. Thanks Mike.

**Pull request merged**
