### PR TITLE
DAOS-14718 test: Fix reading of DAOS_TEST_INSECURE_MODE envar

### PR DESCRIPTION
**Pull request by tanabarr**
The ConfigGenerateRun tests fail to use certs because insecure mode is
enabled when trying to access non-existent DAOS_INSECURE_MODE env.
Update env keyname to DAOS_TEST_INSECURE_MODE and explicitly set
allow_insecure mode to true in ConfigGenerateRun tests.

Test-tag: control,dmg_config_generate
Required-githooks: true

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by daltonbohning — COMMENTED** [review]
Code LGTM, but since this touches a utility file it should run more tests. Thoughts @phender? Maybe just one more test that uses `allow_insecure: True`?
FWIW, this is a VM test that does: `test_daos_control_config_basic`

**Review by daltonbohning — DISMISSED** [review]

**Review by phender — DISMISSED** [review]

**Comment by phender** [comment]
> Code LGTM, but since this touches a utility file it should run more tests. Thoughts @phender? Maybe just one more test that uses `allow_insecure: True`? FWIW, this is a VM test that does: `test_daos_control_config_basic`

Since the removal of setting DAOS_INSECURE_MODE the control/config_generate_run.py is the only test that has failed.  As this env was used to set the default value when the test neglected to set a value in its yaml file, I think the tag selection is sufficient.

**Review by phender — DISMISSED** [review]

**Comment by ashleypittman** [comment]
The linting issues in this PR are as a result of being behind master, this is something we're getting better at but the checks should run if you merge with master.  The failures are because the checks aren't running properly so I can't say if they'll pass or not but looking at the PR they should.

**Comment by tanabarr** [comment]
Merged master and repushed with `Features: control` to both resolve linting issues fixed on master and check we can get a clean feature run for control.

**Review by knard-intel — APPROVED** [review]
LGTM

**Review by daltonbohning — APPROVED** [review]

**Pull request merged**
