### PR TITLE
DAOS-GCP147 object: use dkey hash to get RP leader

### PR DESCRIPTION
**Pull request by wangdi1**
Let's use dkey hash to get replication object leader
to avoid always using the same shard as the DTX leader.
    
Required-githooks: true
Signed-off-by: Di Wang <di.wang@intel.com>### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by wangdi1** [comment]
@Nasf-Fan  I thought DTX on the server side will get the dtx leader independently, i.e. not depend on the object anymore, so it should not cause incompatible issue?  This patch will help improve RP directory open/create performance.

**Review by johannlombardi — COMMENTED** [review]
hm, does it introduce a runtime incompatibility?

**Comment by wangdi1** [comment]
> hm, does it introduce a runtime incompatibility?

It should not, since it is the client who decide which is the dtx leader,  then server will get the leader from dtx itself, instead of OID or dkey_hash.

So even the new client decide to change the leader, the old server will use the new leader anyway.

**Comment by wangdi1** [comment]
failure due to DAOS-12419

**Review by Nasf-Fan — DISMISSED** [review]
It looks fine for me. It is not problem if the two clients update the same dkey but with different leaders. Even if without this patch, such case still exists for distributed transaction.

**Review by johannlombardi — APPROVED** [review]

**Comment by wangdi1** [comment]
fail with DAOS-13127.  @johannlombardi  @Nasf-Fan  please review thanks

**Review by Nasf-Fan — APPROVED** [review]
It potentially affect DTX batched commit. We can consider to optimize that in next step.

**Pull request merged**
