### PR TITLE
SRE-2171 ci: Big refactor of GHA workflows (#15556)

### PR DESCRIPTION
**Pull request by brianjmurrell**
Add the use of reusable workflows and actions to reduce the amount of
duplicated code in this repository as well as dependency repositories.

Run Bullseye workflow on schedule (#15574)
Saturdays at midnight, UTC.

Accept and propagate a run-gha variable (#15576)
For the case where daos is being used as a downstream test.
    
Fixes: SRE-2570 DAOS-16262

Run-GHA: true
Skip-PR-comments: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by ryon-jensen — APPROVED** [review]

**Comment by daltonbohning** [comment]
FYI Ubuntu-related build failures will need #15563, #15255, #15607. I'm not sure whether this PR is safe to ignore those or not.

**Review by daltonbohning — APPROVED** [review]

**Comment by brianjmurrell** [comment]
> FYI Ubuntu-related build failures will need #15563, #15255, #15607. I'm not sure whether this PR is safe to ignore those or not.

Yes, this PR should be unaffected by those -- other than their stages in CI fail, but that has no impact on the stages this PR adds.  This PR does nothing with or about Ubuntu.

**Comment by brianjmurrell** [comment]
Adding @daos-stack/daos-gatekeeper should this get approved for `release/2.6`.  The main benefit of landing there is so that dependency build+test in GHA can validate against `release/2.6` to ensure that landing a dependency update will not cause a regression on that branch -- exactly like we do in Jenkins.

**Comment by daltonbohning** [comment]
> Adding @daos-stack/daos-gatekeeper should this get approved for `release/2.6`. The main benefit of landing there is so that dependency build+test in GHA can validate against `release/2.6` to ensure that landing a dependency update will not cause a regression on that branch -- exactly like we do in Jenkins.

Normally we should get merge approval before requesting gatekeeper. I requested approval on the ticket, which I expect to be approved

**Pull request merged**
