### PR TITLE
DAOS-15128 object: avoid double recx conversion

### PR DESCRIPTION
**Pull request by wangdi1**
During collective size query process, let's add flag to avoid double recx conversion.

Required-githooks: true

### Before requesting gatekeeper:

* [ ] Two review approvals and any prior change requests have been resolved.
* [ ] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [ ] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [ ] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [ ] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate owners.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Review by jolivier23 — DISMISSED** [review]

**Review by Nasf-Fan — APPROVED** [review]

**Review by jolivier23 — APPROVED** [review]

**Comment by wangdi1** [comment]
add features: rebuild ec

**Comment by jolivier23** [comment]
Interesting that this hit an NLT issue whereas my patch that is based on it did not.  See #13779 

Do we have an intermittent NLT issue?

**Comment by wangdi1** [comment]
> Interesting that this hit an NLT issue whereas my patch that is based on it did not. See #13779
> 
> Do we have an intermittent NLT issue?

I was told the failure is due to some kernel issue. just retrigger the test for now.

**Comment by wangdi1** [comment]
the failure caused by DAOS-15007, 15208 14673 15135 and 14780.   Any of it should not caused by Coll size query patch, though I am not so sure about 15135, will check.

anyway, I think this PR fix 15127 and 15128, should be safe to land. @daos-stack/daos-gatekeeper 

ping

**Comment by jolivier23** [comment]
@wangdi1 As an extra bit of information on this, how many failures are there on my patch that is based on this one?  It looks like less failures from the outside.

https://github.com/daos-stack/daos/pull/13779

**Comment by mchaarawi** [comment]
> the failure caused by DAOS-15007, 15208 14673 15135 and 14780. Any of it should not caused by Coll size query patch, though I am not so sure about 15135, will check.
> 
> anyway, I think this PR fix 15127 and 15128, should be safe to land. @daos-stack/daos-gatekeeper
> 
> ping

this still looks much more failures than the revert of the coll query PR.. so not sure we have fixed the issue introduced with that pr yet ..

**Comment by wangdi1** [comment]
> @wangdi1 As an extra bit of information on this, how many failures are there on my patch that is based on this one? It looks like less failures from the outside.
> 
> #13779

@jolivier23  does your PR include @Nasf-Fan 's update [ ](https://github.com/daos-stack/daos/pull/13775/commits/83b1a0e59cf35733b8e7eb2450ba8088df423a7f) ?

**Comment by wangdi1** [comment]
> > the failure caused by DAOS-15007, 15208 14673 15135 and 14780. Any of it should not caused by Coll size query patch, though I am not so sure about 15135, will check.
> > anyway, I think this PR fix 15127 and 15128, should be safe to land. @daos-stack/daos-gatekeeper
> > ping
> 
> this still looks much more failures than the revert of the coll query PR.. so not sure we have fixed the issue introduced with that pr yet ..

Oh, I think these failures exist in master before Coll size patch landing.  Though I need check 15135

**Comment by jolivier23** [comment]
> > @wangdi1 As an extra bit of information on this, how many failures are there on my patch that is based on this one? It looks like less failures from the outside.
> > #13779
> 
> @jolivier23 does your PR include @Nasf-Fan 's update [ ](https://github.com/daos-stack/daos/pull/13775/commits/83b1a0e59cf35733b8e7eb2450ba8088df423a7f) ?

Ah, no, it doesn't

**Comment by mchaarawi** [comment]
> > > the failure caused by DAOS-15007, 15208 14673 15135 and 14780. Any of it should not caused by Coll size query patch, though I am not so sure about 15135, will check.
> > > anyway, I think this PR fix 15127 and 15128, should be safe to land. @daos-stack/daos-gatekeeper
> > > ping
> > 
> > 
> > this still looks much more failures than the revert of the coll query PR.. so not sure we have fixed the issue introduced with that pr yet ..
> 
> Oh, I think these failures exist in master before Coll size patch landing. Though I need check 15135

if Jeff's branch is based on yours, 15127 is intermittent and is not fixed?

**Comment by wangdi1** [comment]
> > > the failure caused by DAOS-15007, 15208 14673 15135 and 14780. Any of it should not caused by Coll size query patch, though I am not so sure about 15135, will check.
> > > anyway, I think this PR fix 15127 and 15128, should be safe to land. @daos-stack/daos-gatekeeper
> > > ping
> > 
> > 
> > this still looks much more failures than the revert of the coll query PR.. so not sure we have fixed the issue introduced with that pr yet ..
> 
> Oh, I think these failures exist in master before Coll size patch landing. Though I need check 15135

Unfortunately, 15135 dose caused by Coll size query patch. Just updated that ticket.

**Pull request merged**
