### PR TITLE
DAOS-10835 test: enable D_LOG_FILE_APPEND_PID in the client

### PR DESCRIPTION
**Pull request by wangshilong**
So rpc logs won't be messed up to make cart_logparse work.

Test-tag: pr rebuild_widely_striped
Signed-off-by: Wang Shilong <shilong.wang@intel.com>

Required-githooks: true

### CODE REVIEW

**Review by wiliamhuang — DISMISSED** [review]

**Comment by wiliamhuang** [comment]
There are failures in both build 1 and 2. Are they known issues?

**Review by tanabarr — CHANGES_REQUESTED** [review]
looks like one of the test failures was on the RebuildWidelyStriped test so that should probably be investigated

**Comment by wangshilong** [comment]
> Looks like one of the test failures was on the RbldWidelyStriped test so that should probably be investigated https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9399/2/tests as we don't want to introduce intermittent failures.
> 
> The change does look trivial however so probably we just need to verify that the same failure is being seen elsewhere, when does that test get run, if it's on weekly or daily can you see the same failure on the respective test runs? if so then I think it's okay to land.

See logs here:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9399/2/artifact/Functional%20Hardware%20Large/rebuild/widely_striped.py/daos_logs/test_rebuild_widely_striped_daos_server.wolf-142.log.272056/*view*/

I looked through logs, it looks this is because cart problems in the server side, somehow pool query request could not be sent to engine 0, so i think failure is not related to this PR.

Let me open separate ticket for this issue.

**Comment by wangshilong** [comment]
> > Looks like one of the test failures was on the RbldWidelyStriped test so that should probably be investigated https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-9399/2/tests as we don't want to introduce intermittent failures.
> > The change does look trivial however so probably we just need to verify that the same failure is being seen elsewhere, when does that test get run, if it's on weekly or daily can you see the same failure on the respective test runs? if so then I think it's okay to land.
> 
> See logs here: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9399/2/artifact/Functional%20Hardware%20Large/rebuild/widely_striped.py/daos_logs/test_rebuild_widely_striped_daos_server.wolf-142.log.272056/*view*/
> 
> I looked through logs, it looks this is because cart problems in the server side, somehow pool query request could not be sent to engine 0, so i think failure is not related to this PR.
> 
> Let me open separate ticket for this issue.

Opened  DAOS-10887 for this

**Review by tanabarr — APPROVED** [review]
I'm fine to land as long as the same failure is not found in the next CI run.

**Comment by ipoddubn** [comment]
This PR is blocked by #9528 (which, in its turn, has some merging conflicts)

**Comment by johannlombardi** [comment]
Could you please have a look at the failure?

**Comment by wangshilong** [comment]
> Could you please have a look at the failure?

The only failure is a EC test which timeout because CommandFailure("ERROR: Copying yaml configuration file to wolf-[142-146]: Timeout detected running 'clush -S -v -w wolf-[142-146] /usr/bin/mkdir -p /etc/daos' with a 15s timeout",)

I think this should be not related to this PR, anyway, i could retrigger test.

**Review by wiliamhuang — DISMISSED** [review]

**Review by knard-intel — DISMISSED** [review]

**Review by bfaccini — APPROVED** [review]

**Review by jolivier23 — COMMENTED** [review]
Can't  be landed due to a merge conflict

**Review by wiliamhuang — APPROVED** [review]

**Review by knard-intel — APPROVED** [review]

**Comment by ashleypittman** [comment]
Somewhat unrelated to this patch but Jenkins handles files differently based on extension so daos.<pid>.log will be viewable online but daos.log.<pid> will download by default.

**Pull request merged**
