### PR TITLE
DAOS-14793 control: Fail if VMD has no backing storage (#13503)

### PR DESCRIPTION
**Pull request by tanabarr**
Report the specific case where VMD address has no backing devices. A
bdev scan of PCI address specified in server config file bdev_list
should report an error indicating if any of the addresses are for a
VMD which has no backing storage (backing NVMe SSDs).

Features: control
Required-githooks: true

### Before requesting gatekeeper:

* [x] Two review approvals and any prior change requests have been resolved.
* [x] Testing is complete and all tests passed or there is a reason documented in the PR why it should be force landed and forced-landing tag is set.
* [x] `Features:` (or `Test-tag*`) commit pragma was used or there is a reason documented that there are no appropriate tags for this PR.
* [x] Commit messages follows the guidelines outlined [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments).
* [x] Any tests skipped by the ticket being addressed have been run and passed in the PR.

### Gatekeeper:

* [ ] You are the appropriate gatekeeper to be landing the patch.
* [ ] The PR has 2 reviews by people familiar with the code, including appropriate watchers.
* [ ] Githooks were used. If not, request that user install them and check copyright dates.
* [ ] Checkpatch issues are resolved.  Pay particular attention to ones that will show up on future PRs.
* [ ] All builds have passed.  Check non-required builds for any new compiler warnings.
* [ ] Sufficient testing is done. Check feature pragmas and test tags and that tests skipped for the ticket are run and now pass with the changes.
* [ ] If applicable, the PR has addressed any potential version compatibility issues.
* [ ] Check the target branch.   If it is master branch, should the PR go to a feature branch?  If it is a release branch, does it have merge approval in the JIRA ticket.
* [ ] Extra checks if forced landing is requested
  * [ ] Review comments are sufficiently resolved, particularly by prior reviewers that requested changes.
  * [ ] No new NLT or valgrind warnings.  Check the classic view.
  * [ ] Quick-build or Quick-functional is not used.
* [ ] Fix the commit message upon landing. Check the standard [here](https://daosio.atlassian.net/wiki/spaces/DC/pages/11133911069/Commit+Comments). Edit it to create a single commit. If necessary, ask submitter for a new summary.

### CODE REVIEW

**Comment by tanabarr** [comment]
CI failures with `Features: control` all due to DAOS-14718

**Comment by knard-intel** [comment]
CI failures seems to not be related to this PR as they are also happening in the PR https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-13490/5/testReport/ from @kjacque .

**Review by knard-intel — APPROVED** [review]
LGTM

**Comment by daltonbohning** [comment]
Still awaiting merge approval for 2.4.2

**Review by kjacque — APPROVED** [review]

**Comment by tanabarr** [comment]
CI run nr. 2 (https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-13546/2/tests/) failed with the following known issue:
- https://daosio.atlassian.net/browse/DAOS-14594
Request forced landing

**Comment by mchaarawi** [comment]
> CI run nr. 2 (https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-13546/2/tests/) failed with the following known issue:
> 
> * https://daosio.atlassian.net/browse/DAOS-14594
>   Request forced landing

DAOS-14793 has not gone through merge approvals yet. please request gatekeeper when it's approved to merge.

**Comment by tanabarr** [comment]
> > CI run nr. 2 (https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-13546/2/tests/) failed with the following known issue:
> > 
> > * https://daosio.atlassian.net/browse/DAOS-14594
> >   Request forced landing
> 
> DAOS-14793 has not gone through merge approvals yet. please request gatekeeper when it's approved to merge.

yes apologies I removed the gatekeeper a couple of minutes ago when I realised

**Comment by tanabarr** [comment]
merge approval has been given

**Pull request merged**
