### PR TITLE
DAOS-7824 daos_test: Changed mismatched options in daos_test

### PR DESCRIPTION
**Pull request by chrisphoffman**
Changed a number of mismatched options in daos_test. The defined options in print_message and struct long_options had a mismatch. The options in print_message was changed to match long_options

Test-tag: pr daily_regression

Signed-off-by: Christopher Hoffman <christopherx.hoffman@intel.com>

### CODE REVIEW

**Review by dmiter — APPROVED** [review]

**Review by bfaccini — APPROVED** [review]

**Comment by ashleypittman** [comment]
This look to have failed in CI due to https://jira.hpdd.intel.com/browse/DAOS-7623 but it should pass if retriggered.

**Comment by sylviachanoiyee** [comment]
@chrisphoffman , I don't think you need to run the daily_regression list with changes just on daos_test.
The failure on RbldBasic seems unrelated to changes in this PR but it is preventing daos_tests from executing on the hw stages.
You can remove the Test-tag in your commit message and repush.

**Review by jolivier23 — CHANGES_REQUESTED** [review]
You'll need to refresh.  daos_test didn't run. You could try with Allow-unstable-test: True

**Review by jolivier23 — APPROVED** [review]
And like @sylviachanoiyee, no need to run daily-regression..just need to make sure relevant tests run

**Comment by sylviachanoiyee** [comment]
In additional to restarting the test, I think it's worth to either file a new or re-open a JIRA ticket (if one exist)  on the server start after format issue. I have not seen this issue for a long time on master.

**Comment by chrisphoffman** [comment]
Restarted with Allow-unstable-test: true. Thank you @sylviachanoiyee and @jolivier23 for your guidance.

**Pull request merged**
