### PR TITLE
DAOS-10828 mercury: Restrict mercury version to less than 2.2

### PR DESCRIPTION
**Pull request by soumagne**

### CODE REVIEW

**Review by johannlombardi — APPROVED** [review]

**Comment by jolivier23** [comment]
> @jolivier23 I have added the git hash fix for the mercury patch as part of this PR.



> @jolivier23 I have added the git hash fix for the mercury patch as part of this PR.

This is fine but I think this needs to land everywhere before we land your mercury PR that removes them.

**Review by johannlombardi — APPROVED** [review]

**Comment by johannlombardi** [comment]
Any idea why NLT failed?

**Review by jolivier23 — APPROVED** [review]

**Comment by jolivier23** [comment]
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-9568/5/VM_test/new/source.c10bd041-bb47-40ae-bc8a-57e2407f5a65/#417

**Comment by brianjmurrell** [comment]
> The new mercury version is about to land and we don't want to pick it in 2.0 since it introduces some runtime incompatibilities.

What kind of incompatibilities?  Is it breaking the ABI without updating the SOVERSION?

**Comment by soumagne** [comment]
mercury is composed of 3 libraries, libmercury, libmercury_util, libna. libna and libmercury_util SOVERSION number was bumped to 3 but DAOS was linking against those too whereas it should have only be linking against libmercury.

**Pull request merged**
