### PR TITLE
DAOS-4762: Use proper mercury version

### PR DESCRIPTION
**Pull request by brianjmurrell**
Using the one properly tagged as a pre-release RPM version.

PR-repos: mercury@PR-44
SKip-func-hw-test: true
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/PR-2677/5/pipeline is the build targeted at release/0.9 to prove the mercury and cart updates.

**Comment by brianjmurrell** [comment]
Failures are known: https://jira.hpdd.intel.com/browse/DAOS-4740, https://jira.hpdd.intel.com/browse/DAOS-4700

**Comment by jolivier23** [comment]
What does that PR-repos: mercury@PR-44 do?   Does it need to be removed?

**Comment by brianjmurrell** [comment]
> What does that PR-repos: mercury@PR-44 do? Does it need to be removed?

Ahh.  Thanks for asking @jolivier23, because it does want to be removed when landed.

It tells the/this PR build to use mercury from PR-44 when it builds and tests.  This is the new way (the old way was to modify the `Makefile` and `Jenkinsfile`, which then required another patch to revert that before it could be landed to the branch) to test a component before landing it.

The idea is you create a component RPM PR, then create a daos PR referring to it.  Run the daos PR which confirms the component PR.  Then the component PR can be landed and then land the daos PR.  All without having to muck with the `Jenkinsfile` and `Makefile` in the daos PR and not have to resubmit it after the component PR has landed with the mucking undone.

**Pull request merged**
