### PR TITLE
DAOS-6344 build: create daos_daemons secondary group (#8331)

### PR DESCRIPTION
**Pull request by Michael-Hennecke**
Create daos_daemons secondary group for daos_server and daos_agent,
to enable both daemons to write their logfiles into the same
non-world-writeable logfile directory (being writeable by the
daos_daemons group will be sufficient).

Signed-off-by: Michael Hennecke <michael.hennecke@intel.com>

### CODE REVIEW

**Review by brianjmurrell — APPROVED** [review]

**Review by mjmac — APPROVED** [review]
Seems reasonable to me. I wonder if we should be testing this somehow, though, e.g. with the "Test * RPMs" stages in Jenkins?

**Review by brianjmurrell — APPROVED** [review]
While it LGTM, I would agree with @mjmac that some even minor testing that the result achieves the goal would be good.  Also agree that the RPM test stage might be a good place for this.

**Comment by Michael-Hennecke** [comment]
the force-push only updated the Signed-off-by line, which was corrupted in the original commit. is there a way this can be fixed without a force-push?

**Comment by brianjmurrell** [comment]
> the force-push only updated the Signed-off-by line, which was corrupted in the original commit. is there a way this can be fixed without a force-push?

I would say you just leave a defective SoB alone.  It will get squashed out from a subsequent commit in the landing.  If there is only one commit in the PR and it's got a corrupt SoB, you could `git commit --allow-empty` and push another (empty) commit fixing the SoB, which again, would get squashed out by the landing.

**Pull request merged**
