### PR TITLE
DAOS-6132 rebuild: add rebuild overflow handling

### PR DESCRIPTION
**Pull request by wangdi1**
Add rebuild overflow handling.

Signed-off-by: Di Wang <di.wang@intel.com>

### CODE REVIEW

**Review by NiuYawei — COMMENTED** [review]
Could you provide some commit comments to explain the problem and how is the problem solved?

**Review by liuxuezhao — APPROVED** [review]

**Review by NiuYawei — CHANGES_REQUESTED** [review]
I think first we need to figure out why BIO returns -DER_OVERFLOW, if it because hugepages are not enough, I think we should configure more hugepages to make sure each xstream can have at least 1GB (hardcoded limit) hugepages.

When there are enough hugepages configured, BIO will not return -DER_OVERFLOW, but the 1GB per-xsteam DMA buffer could still be exhausted by high io workload, in that case, later IO has to wait for prior IO releasing DMA buffer and performance will be impacted.

Then I think we'd scrutinize the whole rebuild IO stack (and IO workload in tests) to see if exhausting 1GB DMA buffer is expected, if it's not expected, we'd figure out the reason, if it's expected, I think we should increase the hardcoded DMA buffer limit (currently 1GB) to satisfy the common rebuild cases.

**Comment by johannlombardi** [comment]
@wangdi1 could you please advise what we should do with this patch?

**Comment by wangdi1** [comment]
@wangdi1 could you please advise what we should do with this patch?

Oh, I will probably use this PR to investigate that "DMA buffer not enough issue" in Jean's soak tests. I will work on that once I cleanup all my 1.1.3 tickets.

**Comment by wangdi1** [comment]
We have land rebuild inflight control patch by another patch, so close this one.

**Pull request closed without merging**
