### PR TITLE
DAOS-6446

### PR DESCRIPTION
**Pull request by omar-ocampo**
Added "all" tags to test cases missing the tag.
    Added "full_regression" or "daily_regression" to tests which
    were not part of those tags.
Signed-off-by: Omar Ocampo <omar.ocampo.coronado@intel.com>

### CODE REVIEW

**Review by brianjmurrell — APPROVED** [review]
Looks good.  Any thoughts on how do we prevent regressions of this sort in the future?

We can use `avocado list` (and the launch.py wrapper around it) to list test files.

It seems to me that we could do some tests to determine if a test doesn't have the minimum set of tags.  Do a list with no filter to get a list of all test files, then do lists with filters to ensure that all of the files from the first list end up in one of the other lists.

The problem is, I don't think this would catch a test being added to a file that already has valid tags since the list lists files, not tests.

Anyway, just something to consider.

**Comment by omar-ocampo** [comment]
Test failed due to src/tests/ftest/cart/test_rpc_to_ghost_rank.c, which was enabled in this change. A new ticket was opened to track the solution of the failure.

**Comment by omar-ocampo** [comment]
Resolved merge conflict

**Review by brianjmurrell — APPROVED** [review]

**Review by rpadma2 — DISMISSED** [review]
LGTM.

**Comment by sylviachanoiyee** [comment]
Can you retrigger a build and include all the tests you are enabling either daily_regression and full_regression?
You can use pragmas to include those tests in your PR testing.
We need to make sure they are passing before enabling them.

**Comment by omar-ocampo** [comment]
> Can you retrigger a build and include all the tests you are enabling either daily_regression and full_regression?
> You can use pragmas to include those tests in your PR testing.
> We need to make sure they are passing before enabling them.

Tests are running and one ticket was opened due a failure, do you see a specific test that requires to run?

**Review by sylviachanoiyee — CHANGES_REQUESTED** [review]
A number if tests getting enabled in this PR are not run in testing.
Need to make sure they pass before enabling.

**Comment by sylviachanoiyee** [comment]
> > Can you retrigger a build and include all the tests you are enabling either daily_regression and full_regression?
> > You can use pragmas to include those tests in your PR testing.
> > We need to make sure they are passing before enabling them.
> 
> Tests are running and one ticket was opened due a failure, do you see a specific test that requires to run?

Yea, I see  bunch of tests you are enabling for full_regression or daily_regression.  large_file_count and seg_count are 2 examples. I don't see them in the test result of this pr.

**Comment by omar-ocampo** [comment]
> > > Can you retrigger a build and include all the tests you are enabling either daily_regression and full_regression?
> > > You can use pragmas to include those tests in your PR testing.
> > > We need to make sure they are passing before enabling them.
> > 
> > 
> > Tests are running and one ticket was opened due a failure, do you see a specific test that requires to run?
> 
> Yea, I see bunch of tests you are enabling for full_regression or daily_regression. large_file_count and seg_count are 2 examples. I don't see them in the test result of this pr.



> > > Can you retrigger a build and include all the tests you are enabling either daily_regression and full_regression?
> > > You can use pragmas to include those tests in your PR testing.
> > > We need to make sure they are passing before enabling them.
> > 
> > 
> > Tests are running and one ticket was opened due a failure, do you see a specific test that requires to run?
> 
> Yea, I see bunch of tests you are enabling for full_regression or daily_regression. large_file_count and seg_count are 2 examples. I don't see them in the test result of this pr.

Latest commit should include "Features" should include all tests affected by this PR, waiting for results

**Comment by sylviachanoiyee** [comment]
> > > > Can you retrigger a build and include all the tests you are enabling either daily_regression and full_regression?
> > > > You can use pragmas to include those tests in your PR testing.
> > > > We need to make sure they are passing before enabling them.
> > > 
> > > 
> > > Tests are running and one ticket was opened due a failure, do you see a specific test that requires to run?
> > 
> > 
> > Yea, I see bunch of tests you are enabling for full_regression or daily_regression. large_file_count and seg_count are 2 examples. I don't see them in the test result of this pr.
> 
> > > > Can you retrigger a build and include all the tests you are enabling either daily_regression and full_regression?
> > > > You can use pragmas to include those tests in your PR testing.
> > > > We need to make sure they are passing before enabling them.
> > > 
> > > 
> > > Tests are running and one ticket was opened due a failure, do you see a specific test that requires to run?
> > 
> > 
> > Yea, I see bunch of tests you are enabling for full_regression or daily_regression. large_file_count and seg_count are 2 examples. I don't see them in the test result of this pr.
> 
> Latest commit should include "Features" should include all tests affected by this PR, waiting for results

Thanks, but let's cancel the PR run for this job as we discussed over IM. Let's verify whether the large io jobs are meant to run over CI with owners first.

**Comment by omar-ocampo** [comment]
> Thanks, but let's cancel the PR run for this job as we discussed over IM. Let's verify whether the large io jobs are meant to run over CI with owners first.

Restarted job as mentioned in IM however, I do not see any of the related features run within the jenkins builds, why? https://build.hpdd.intel.com/job/daos-stack/job/daos/job/PR-5077/6/artifact/

**Review by brianjmurrell — CHANGES_REQUESTED** [review]
The format of the tags in these tests does not seem to follow the recently established formatting guidelines.  I don't recall specifically the details, but somebody on the test team must know what was established.  Generally speaking it is a multiline format,

**Comment by rpadma2** [comment]
Omar, I have pinged via skype... We can discuss what you are trying to accomplish here.
You have to something like:
Test-tag-hw-medium: pr,hw,medium,ib2 offline_reintegration_daily (This will runs offline_reintegration_daily tag tests apart from the PR tests)...

**Comment by brianjmurrell** [comment]
`Features: ` is a space separated list ([as described](https://wiki.hpdd.intel.com/display/CI/Commit+Pragmas#CommitPragmas-Features)) and does not need to include `daily_regression` in it as that is automatically collated into each of the space separated items in the `Features:` list.

**Comment by sylviachanoiyee** [comment]
@omar-ocampo , could you fix teh title of this pr and retrigger the build?

**Comment by sylviachanoiyee** [comment]
@omar-ocampo , please merge with master as well, looks like you are pretty behind, still using the old pipeline.
please fix the title of the pr, thanks.

**Comment by omar-ocampo** [comment]
> @omar-ocampo , please merge with master as well, looks like you are pretty behind, still using the old pipeline.
> please fix the title of the pr, thanks.

Master was rebased a week ago, rebased again. Title fixed.

**Comment by omar-ocampo** [comment]
Going to split this review into 2-3 separate PRs

**Pull request closed without merging**
