### PR TITLE
DAOS-5279 bio: change dma chunk size to 2MB

### PR DESCRIPTION
**Pull request by NiuYawei**
Change DMA chunk size from 32MB to 2MB.

Signed-off-by: Niu Yawei <yawei.niu@intel.com>

### CODE REVIEW

**Review by johannlombardi — APPROVED** [review]

**Comment by jolivier23** [comment]
Merged with latest master because you are way back in the queue anyway and to get the provisioning performance fix.

**Comment by kprantis** [comment]
Looks like this passed test - is it just waiting for reviews now at this point?

**Comment by johannlombardi** [comment]
Successfully tested by Maureen with Soak tests.

**Comment by johannlombardi** [comment]
@NiuYawei  Please port to release/1.2

**Pull request merged**
