### PR TITLE
DAOS-8918 container: Fix key conflict with pool MD

### PR DESCRIPTION
**Pull request by liw**
The ds_cont_prop_version key conflicts with ds_pool_prop_version. The
two keys refer to the same value in the root RDB KVS. This patch removes
ds_cont_prop_version to avoid future confusions, for using separate
versions for pool and container metadata would be an overkill currently.

The patch also includes some layout-related fixes and improvements:

  - Fix the value type comments for ds_cont_prop_ec_pda and
    ds-cont_prop_rp_pda.

  - Improve the consistency of value type comments.

How to add layout-version-dependent code to src/container is left to
further discussions (e.g., by exporting and using ds_pool_prop_version
and/or ds_pool_prop_global_version?).

Signed-off-by: Li Wei <wei.g.li@intel.com>

### CODE REVIEW

**Comment by wangshilong** [comment]
> The ds_cont_prop_version key conflicts with ds_pool_prop_version. The two keys refer to the same value in the root RDB KVS. This patch removes ds_cont_prop_version to avoid future confusions, for using separate versions for pool and container metadata would be an overkill currently.
> 
> The patch also includes some layout-related fixes and improvements:
> 
> * Remove ds_cont_prop_ghce and ds_cont_prop_ghpce, for these were
>   deprecated long ago and have not been read since.
> * Fix the value type comments for ds_cont_prop_ec_pda and
>   ds-cont_prop_rp_pda.
> * Improve the consistency of value type comments.
> 
> How to add layout-version-dependent code to src/container is left to further discussions (e.g., by exporting and using ds_pool_prop_version and/or ds_pool_prop_global_version?).

I discussed this with Johann, he is fine to remove ds_pool_prop_version, and let's keep one ds_pool_prop_global_version, are you ok to remove it together in this PR or i could push a seperate PR to do this?

> 
> Signed-off-by: Li Wei [wei.g.li@intel.com](mailto:wei.g.li@intel.com)

**Comment by liw** [comment]
> I discussed this with Johann, he is fine to remove ds_pool_prop_version, and let's keep one ds_pool_prop_global_version, are you ok to remove it together in this PR or i could push a seperate PR to do this?

@wangshilong, let's separate the two things, for I don't know if removing ds_pool_prop_version will turn out to work well or not.

**Review by kccain — APPROVED** [review]
Is there any case to update DAOS_POOL_MD_VERSION with this change? Probably not, but let me consider something here: If a pool (with container[s]) is created in newer daos versions (i.e., with this patch)  does not write prop_ghce, but older software uses the pool/containers. I realize that older software does not read ghce so maybe no harm. But if in another scenario, older software creates a pool (with container[s]) and writes prop_ghce it would be weird for the older software to claim that it has the same DAOS_POOL_MD_VERSION as pools created with the newer software.

And as for forward compatibility, old layout pools/containers created with prop_ghce should be harmless when loaded by new daos software because while the key/value is there, the software won't be looking for it anyway?

**Comment by liw** [comment]
> Is there any case to update DAOS_POOL_MD_VERSION with this change? Probably not, but let me consider something here: If a pool (with container[s]) is created in newer daos versions (i.e., with this patch) does not write prop_ghce, but older software uses the pool/containers. I realize that older software does not read ghce so maybe no harm. But if in another scenario, older software creates a pool (with container[s]) and writes prop_ghce it would be weird for the older software to claim that it has the same DAOS_POOL_MD_VERSION as pools created with the newer software.
> 
> And as for forward compatibility, old layout pools/containers created with prop_ghce should be harmless when loaded by new daos software because while the key/value is there, the software won't be looking for it anyway?

Hmm, I'm not sure what the official way is for this kind of layout changes. To keep focused, I've restored the ghce property.

**Review by wangshilong — APPROVED** [review]

**Review by kccain — APPROVED** [review]

**Review by wangshilong — APPROVED** [review]

**Pull request merged**
